<?php
/** 
  * Store/ReportController/stockreportAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('store/report/partial.phtml', array('active' => 'stockreport')); ?> <br/>
<style>
	tr.group,
	tr.group:hover {
		background-color: #red !important;
		font: 15px "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<form id="#form" method="post" action="<?php echo $this->url('inreport', array('action' => 'stockreport')); ?>"  enctype="multipart/form-data" >    
			<div class="row">
				<div class="form-group col-lg-2">
					<label class="control-label" for="location">Location</label>
					<select class="form-control" name="location" id="location" data-placeholder="select" >
						<option value="-1">All</option>
						<?php foreach($regions as $region):?>
							<optgroup label="<?php echo $region['region'];?>">
							<?php  
								$locations = $locationObj->get(array('l.region'=>$region['id'],'l.location_type'=>array(1,2,4,7,8)));
								foreach ($locations as $location):
									$selected_loc = ($location['id']==$data['location'])?"selected":"";
							?>
								<option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
									<?php echo $location['location']; ?>
								</option>
							<?php endforeach;?>
							</optgroup>
						<?php endforeach;  ?>									
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="item_group">Item Group</label>
					<select class="form-control" name="item_group" id="item_group" data-placeholder="select" >
						<option value=""></option>
						<?php 
							$groups = $this->groupObj->getAll();
							foreach($groups as $group):
							$selected_group = ($group['id']==$data['item_group'])?"selected":"";
						?>
							<option value="<?php echo $group['id'];?>" <?php echo $selected_group;?>>
								<?php echo $group['name'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="item_sub_group">Item Sub Group</label>
					<select class="form-control" name="item_sub_group" id="item_sub_group" data-placeholder="select" >
						<option value="-1" <?php echo ($data['item_sub_group'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($this->subgroupdtls as $sub_group):
							$selected_sub_group = ($sub_group['id'] == $data['item_sub_group'])?'selected':'';
						?>
							<option value="<?php echo $sub_group['id'];?>" <?php echo $selected_sub_group;?> >
								<?php echo $sub_group['code'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="start_date">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="end_date">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="item">Store Item</label>
					<select class="form-control" name="item" id="item" data-placeholder="select" >
						<option value="-1" <?php echo ($data['item'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($item_details as $item_detail):
							$selected_item = ($item_detail['item_id'] == $data['item'])?'selected':'';
						?>
							<option value="<?php echo $item_detail['item_id'];?>" <?php echo $selected_item;?> >
								<?php echo $item_detail['code'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="col-lg-2">
					<div class="space-8"></div>
					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>Refresh</button>
				</div>
			</div>
		</form>
		<div class="hr hr-dotted"></div>
		<div class="space-4"></div>
		<div>
			<table class="table table-striped table-condensed table-bordered table-hover" id="example">
				<thead>
					<tr>
						<th>Item</th>
						<?php if($data['item_group'] == '2'): ?>
						<th>Stores and Spares</th>
						<th>Item Group</th>
						<?php elseif($data['item_group'] == '1'):?>
						<th>Asset No. </th>
						<th>Item Group</th>
						<?php endif;?>
						<th>Opening</th>
						<?php if($data['item_group'] == '2'):?>
						<th>Rate</th>
						<th>Amount</th>
						<?php endif;?>
						<th>Purchase</th>
						<?php if($data['item_group'] == '2'):?>
						<th>Rate </th>
						<th>Amount </th>
						<?php endif;?>
						<th>Dispatch</th>
						<?php if($data['item_group'] == '2'):?>
						<th>Rate</th>
						<th>Amount</th>
						<?php endif;?>
						<th>Auctioned</th>
						<th>Closing</th>
						<?php if($data['item_group'] == '2'):?>
						<th>Quantity</th>
						<?php endif;?>
						<th>Rate</th>
						<th>Amount</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					$amount_sum = 0;
					$closing_sum = 0;
					if($data['item_group'] == 1):
						$lists = $this->assetObj->filterSRAsset($data['location'],array('i.item_group'=>$data['item_group'], 'a.status' => 3),'ad.location',$data['item_sub_group'],$data['item']);
						//echo "From asset=".sizeof($lists)."<br>"; exit;
						$array = array();
						foreach($lists as $list):
							array_push($array, $list['id']);
						endforeach;
						
				     	$opening_list = $this->openingassetObj->filterSRAsset($data['start_date'],$data['location'],array('i.item_group'=>$data['item_group']),'o.opening_date','od.location',$array,$data['item_sub_group'],$data['item']);
						$pur_list = $this->pur_receiptObj->filterSRAsset($data['end_date'],$data['location'],array('p.status'=>3,'p.item_group'=>$data['item_group']),'p.purchase_receipt_date','p.location',$array,$data['item_sub_group'],$data['item']);
						//echo "Purchase=".sizeof($pur_list)."<br>";exit;
						$disp_list = $this->issueObj->filterSRAsset($data['start_date'],$data['end_date'],$data['location'],array('d.status'=>array(2,10,3),'d.item_group'=>$data['item_group']),'d.issue_date','d.from_location',$array,$data['item_sub_group'],$data['item']);
						//echo "dispatch=".sizeof($disp_list)."<br>"; //exit;
						$row_list = array_merge($lists,$opening_list,$pur_list,$disp_list);
						//echo "Merge = ".sizeof($row_list)."<br>"; //exit;
						$row_unique = array_unique($row_list, SORT_REGULAR);
						//echo "Unique = ".sizeof($row_unique)."<br>" ;exit;
						foreach($row_unique as $list): 
						    if($list['id'] > 0):
							$assets = $this->assetObj->fetchSRAssetDetails($list['id']);
							foreach($assets as $asset);
							
							//Opening Stock Table
							$op_asset_openings = $this->openingassetObj->fetchSROpeningSUM($data['start_date'],$data['location'],array('o.asset'=>$asset['asset'],'o.item'=>$asset['item']));
							$op_purchases = $this->pur_receiptObj->fetchSROpeningforAssetSUM($data['start_date'],$data['location'],array('pad.assetssp'=>$asset['id'],'pad.item'=>$asset['item'],'p.status'=>3),'p.purchase_receipt_date','p.location','pad.sound_quantity');
							
							$op_dispatch = $this->issueObj->fetchSROpeningforAssetSUM($data['start_date'],$data['location'],array('dd.assetssp'=>$asset['id'],'dd.item'=>$asset['item'],'d.status'=>array(2,10,3)),'d.issue_date','d.from_location','dd.quantity');
													
							$opening = $op_asset_openings + $op_purchases + $op_dispatch;
							
							//Purchase Receipt Table
							$purchases = $this->pur_receiptObj->fetchSRQuantityforAssetSUM($data['start_date'],$data['end_date'],$data['location'],array('pad.assetssp'=>$asset['id'],'pad.item'=>$asset['item'],'p.status'=>3),'p.purchase_receipt_date','p.location','pad.sound_quantity');
							
							//Dispatch Table
							$dispatch = $this->issueObj->fetchSRQuantityforAssetSUM($data['start_date'],$data['end_date'],$data['location'],array('dd.assetssp'=>$asset['id'],'dd.item'=>$asset['item'],'d.status'=>array(2,10,3)),'d.issue_date','d.from_location','dd.quantity');
							$amount = $this->assetdtlsObj->getSumAmt($data['location'],array('ad.asset'=>$asset['id'],'a.item'=>$asset['item'],'a.status'=>array(3)),'d.location','dd.amount');
							$rate = $this->assetdtlsObj->getSumAmt($data['location'],array('ad.asset'=>$asset['id'],'a.item'=>$asset['item'],'a.status'=>array(3)),'d.location','dd.rate');
							//Closing Balance
							$closing = $opening + $purchases - $dispatch; 
							
							if($opening == 0 && $purchases == 0 && $dispatch == 0):
						?>
						<?php else:
						    $closing_amount_sum += $amount;						
							$opening = ($opening != '' && $opening != 0)?number_format($opening, 2, '.', ','):'-';
							$purchases = ($purchases != '' && $purchases != 0)?number_format($purchases, 2, '.', ','):'-';
							$dispatch = ($dispatch != '' && $dispatch != 0)?number_format($dispatch, 2, '.', ','):'-';
						?>
							<tr>
								<td><?php echo $asset['code'];?></td>
								<?php if($data['item_group'] == '1'): ?>
								<td><?php echo $asset['asset'];?></td>
								<td><?php echo $this->subgroupObj->getColumn($asset['item_sub_group'],'code');?></td>
								<?php endif;?>
								<td class="blue" style="text-align:right" title="<?php echo "&#013Purchase : ".$op_purchases."&#013IntRecpt : ".$op_in_receipt."&#013Dispatch : ".$op_dispatch;?>">
									<?php echo $opening;?></td>
								<td class="green" style="text-align:right"><?php echo $purchases;?></td>
								<td class="red" style="text-align:right"><?php echo $dispatch;?></td>
								<td class="red" style="text-align:right" title="<?php echo "Shortage : ".$shortage."&#013Converted From : ".$converted_from."&#013Adjustment: ".$adjustment;?>"><?php echo $adjusted; ?></td>
								<td class="blue" style="text-align:right"><?php echo ($closing != '' && $closing != 0)?number_format($closing, 2, '.', ','):'-';?></td>
								<td class="blue" style="text-align:right"><?php echo ($rate != '' && $rate != 0)?number_format($rate, 2, '.', ','):'-';?></td>
							    <td class="blue" style="text-align:right"><?php echo ($amount != '' && $amount != 0)?number_format($amount, 2, '.', ','):'-';?></td>
							</tr>
					<?php 
							endif;
						endif;
					    $closing_sum += $closing;
						endforeach;
						
					else: 
					
					    $lists = $this->sspObj->filterSRSsp($data['location'],array('i.item_group'=>$data['item_group'], 'ssp.status' => 3),'sspd.location',$data['item_sub_group'],$data['item']);
						//echo "Purchase=".sizeof($lists)."<br>";
						$array = array();
						foreach($lists as $list):
							array_push($array, $list['id']);
						endforeach;
	                    $opening_list = $this->openingsspObj->filterSRSsp($data['start_date'],$data['location'],array('i.item_group'=>$data['item_group']),'o.opening_date','od.location',$array,$data['item_sub_group'],$data['item']);
						//echo "Purchase=".sizeof($opening_list)."<br>"; exit;
						$pur_list = $this->pur_receiptObj->filterSRSsp($data['end_date'],$data['location'],array('p.status'=>3,'p.item_group'=>$data['item_group']),'p.purchase_receipt_date','p.location',$array,$data['item_sub_group'],$data['item']);
						//echo "Purchase=".sizeof($pur_list)."<br>";
						$disp_list = $this->issueObj->filterSRSsp($data['start_date'],$data['end_date'],$data['location'],array('d.status'=>array(2,10,3),'d.item_group'=>$data['item_group']),'d.issue_date','d.from_location',$array,$data['item_sub_group'],$data['item']);
						//echo "dispatch=".sizeof($disp_list)."<br>"; 
						$row_list = array_merge($lists,$pur_list,$disp_list);
						//echo "Merge = ".sizeof($row_list)."<br>"; exit;
						//print_r($row_list); exit;
						$row_unique = array_unique($row_list, SORT_REGULAR);
						//echo "Unique = ".sizeof($row_unique)."<br>";
						foreach($row_unique as $list): 
						    if($list['id'] > 0):
							$ssps = $this->sspObj->fetchSRSspDetails($list['id']);
							foreach($ssps as $ssp);
						
							$op_ssp_openings = $this->openingsspObj->fetchSROpeningSUM($data['start_date'],$data['location'],array('o.storespare'=>$ssp['storespare'],'o.item'=>$ssp['item']));
							$op_purchases = $this->pur_receiptObj->fetchSROpeningforSspSUM($data['start_date'],$data['location'],array('pd.assetssp'=>$ssp['id'],'pd.item'=>$ssp['item'],'p.status'=>3),'p.purchase_receipt_date','p.location','pd.sound_quantity');
							$op_dispatch = $this->issueObj->fetchSROpeningforSspSUM($data['start_date'],$data['location'],array('dd.assetssp'=>$ssp['id'],'dd.item'=>$ssp['item'],'d.status'=>array(2,10,3)),'d.issue_date','d.from_location','dd.quantity');
							$opening = $op_ssp_openings + $op_purchases - $op_dispatch;
							
							$op_sum_amt = $this->openingsspObj->fetchSROpeningSUMATM($data['start_date'],$data['location'],array('o.storespare'=>$ssp['storespare'],'o.item'=>$ssp['item']));
							$op_purchases_sum_amt = $this->pur_receiptObj->fetchSROpeningforSspSUMATM($data['start_date'],$data['location'],array('pd.assetssp'=>$ssp['id'],'pd.item'=>$ssp['item'],'p.status'=>3),'p.purchase_receipt_date','p.location','pd.sound_quantity*pd.rate');
							$op_dispatch_sum_atm = $this->issueObj->fetchSROpeningforSspSUMATM($data['start_date'],$data['location'],array('dd.assetssp'=>$ssp['id'],'dd.item'=>$ssp['item'],'d.status'=>array(2,10,3)),'d.issue_date','d.from_location','dd.quantity*dd.rate');
                                                        							$p_rate = $this->pur_receiptdtlObj->getPRate($data['start_date'],$data['end_date'],$data['location'],array('pd.assetssp'=>$ssp['id'],'pd.item'=>$ssp['item'],'p.status'=>3),'rate');
 if($opening != 0):
							$opening_sum_amt = 	$op_sum_amt + $op_purchases_sum_amt - $op_dispatch_sum_atm;	
							else:
							$opening_sum_amt = 0;
							endif;
																					$opening_sum_rate = ($op_sum_amt + $op_purchases_sum_amt) / ($op_ssp_openings + $op_purchases);	
							//Purchase Receipt Table
							$purchases = $this->pur_receiptObj->fetchSRQuantityforSspSUM($data['start_date'],$data['end_date'],$data['location'],array('pd.assetssp'=>$ssp['id'],'pd.item'=>$ssp['item'],'p.status'=>3),'p.purchase_receipt_date','p.location','pd.sound_quantity');
							//Dispatch Table
							$dispatch = $this->issueObj->fetchSRQuantityforSsspSUM($data['start_date'],$data['end_date'],$data['location'],array('dd.assetssp'=>$ssp['id'],'dd.item'=>$ssp['item'],'d.status'=>array(2,10,3)),'d.issue_date','d.from_location','dd.quantity');
							$quantity = $this->sspdtlsObj->getColumn(array('storespare'=>$ssp['id'],'location'=>$data['location']),'quantity');
							
							//Purchase Receipt Table
							$purchases_sum_amt = $this->pur_receiptObj->fetchSRQuantityforSspSUMATM($data['start_date'],$data['end_date'],$data['location'],array('pd.assetssp'=>$ssp['id'],'pd.item'=>$ssp['item'],'p.status'=>3),'p.purchase_receipt_date','p.location','pd.sound_quantity*pd.rate');
							//Dispatch Table
							$dispatch_sum_amt = $this->issueObj->fetchSRQuantityforSsspSUMATM($data['start_date'],$data['end_date'],$data['location'],array('dd.assetssp'=>$ssp['id'],'dd.item'=>$ssp['item'],'d.status'=>array(2,10,3)),'d.issue_date','d.from_location','dd.quantity*dd.rate');
							
							//Closing Balance
							$closing = $opening + $purchases - $dispatch; 
							$closing_sum_amt = $opening_sum_amt + $purchases_sum_amt - $dispatch_sum_amt; 
														$closing_rate =  ($opening_sum_amt + $purchases_sum_amt) / ($opening + $purchases);

							
							if($opening == 0 && $purchases == 0 && $dispatch == 0):
						?>
						<?php else:
				            $opening = ($opening != '' && $opening != 0)?number_format($opening, 2, '.', ','):'-';
							$purchases = ($purchases != '' && $purchases != 0)?number_format($purchases, 2, '.', ','):'-';
							$dispatch = ($dispatch != '' && $dispatch != 0)?number_format($dispatch, 2, '.', ','):'-';					
														$closing_rate = ($closing_rate != '' && $closing_rate != 0)?number_format(floor($closing_rate*100)/100,2, '.', ''):'-';					
					
						?>
							<tr>
								<td><?php echo $ssp['code'];?></td>
								<?php if($data['item_group'] == '2'): ?>
								<td><?php echo $ssp['storespare'];?></td>
								<td><?php echo $this->subgroupObj->getColumn($ssp['item_sub_group'],'code');?></td>
								<?php endif;?>
								<td class="blue" style="text-align:right"><?php echo $opening;?></td>
								<td class="blue" style="text-align:right"><?php echo ($opening != '' && $opening != 0)?number_format($opening_sum_rate, 2, '.', ','):'-';?></td>
								<td class="blue" style="text-align:right"><?php echo ($opening != '' && $opening != 0)?number_format($opening_sum_amt, 2, '.', ','):'-';?></td>
								<td class="green" style="text-align:right"><?php echo $purchases;?></td>
								<td class="blue" style="text-align:right"><?php echo ($purchases != '' && $purchases != 0)?number_format($p_rate, 2, '.', ','):'-';?></td>
								<td class="blue" style="text-align:right"><?php echo ($purchases != '' && $purchases != 0)?number_format($purchases_sum_amt, 2, '.', ','):'-';?></td>
								<td class="red"  style="text-align:right"><?php echo $dispatch;?></td>
								<td class="blue" style="text-align:right"><?php echo ($dispatch != '' && $dispatch != 0)?number_format($closing_rate, 2, '.', ','):'-';?></td>
								<td class="blue" style="text-align:right"><?php echo ($dispatch != '' && $dispatch != 0)?number_format($dispatch_sum_amt, 2, '.', ','):'-';?></td>
								<td class="red"  style="text-align:right" ></td>
								<td class="blue" style="text-align:right"><?php echo ($closing != '' && $closing != 0)?number_format($closing, 2, '.', ','):'-';?></td>
								<td class="blue" style="text-align:right"><?php echo ($closing!= '' && $closing != 0)?number_format($quantity, 2, '.', ','):'-';?></td>
								<td class="blue" style="text-align:right"><?php echo ($closing!= '' && $closing != 0)?$closing_rate:'-';?></td>		  			                	
								<td class="blue" style="text-align:right"><?php echo ($closing != '' && $closing > 0 )?$closing_sum_amt:'-';?></td>

							</tr>
					<?php 
							endif;
						endif;
                        $closing_sum += $closing;
                        $grand_closing_sum_amt += $closing_sum_amt;
                                                                  $issue_amount_sum += $dispatch_sum_amt;

						endforeach;
					endif;	
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('#start_date').datepicker();
		$('#end_date').datepicker();
		$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		
		$('#item_group').on('change', function(){
			$.post(
				"<?php echo $this->url("inreport", array("action" => "getsubgroupgroup"));?>",
				{
					item_group: $(this).val(),
				},
				function(data){
					//console.log(data);
					$('#item_sub_group').html(data.subgroups);
					$('#item_sub_group option[value='+data.selected_sub_group+']').attr('selected', 'selected');
					$('#item_sub_group').trigger('chosen:updated');
					$('form').formValidation('revalidateField', $('#item_sub_group').attr('id'));
					
					$('#item').trigger('chosen:updated');
					$('#item').html(data.items);
					$('#item option[value='+data.selected_items+']').attr('selected', 'selected');
					$('#item').trigger('chosen:updated');
					$('form').formValidation('revalidateField', $('#item').attr('id'));
					$('#item').trigger('chosen:updated');
				},
				'json'
			);
		});
		
		/*** Form Validation ***/
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				location: {
					validators: {
						notEmpty: {
							message: 'Please select location'
						}
					}
				},
				item_group: {
					validators: {
						notEmpty: {
							message: 'Please select item group'
						}
					}
				},
				item_sub_group: {
					validators: {
						notEmpty: {
							message: 'Please select item sub group'
						}
					}
				},
				start_date: {
					validators: {
						notEmpty: {
							message: 'Please select start date'
						},
					}
				},
				end_date: {
					validators: {
						notEmpty: {
							message: 'Please select end date'
						}
					},
				},
				item: {
					validators: {
						notEmpty: {
							message: 'Please select item'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		var title_table = $('#location_name').val()+'('+$('#activity_name').val()+') from '+$('input#start_date').val()+' to '+$('input#end_date').val();
	    $('#example').append('<caption style="caption-side: bottom">Total Issue Value = <?php echo $issue_amount_sum;?>,Total Closing Balance Value = <?php echo $grand_closing_sum_amt;?>,  Total Stock Balance Value = <?php echo $closing_sum;?></caption>');
		if($('#item_group').val() == 1){
			var table = $('#example').DataTable({
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				"columnDefs": [
					{ "visible": false, "targets": 2 }, 
				],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true,
				"order": [[ 2, 'asc' ],[ 0, 'asc' ],[ 1, 'asc' ]],
				"displayLength": 10,
				"drawCallback": function ( settings ) {
					var api = this.api();
					var rows = api.rows( {page:'current'} ).nodes();
					var last=null;
	 
					api.column(2, {page:'current'} ).data().each( function ( group, i ) {
						if ( last !== group ) {
							$(rows).eq( i ).before(
								'<tr class="group"><td colspan="11">'+group+'</td></tr>'
							);
	 
							last = group;
						}
					} );
				}
			} );
			
			// Order by the grouping
			$('#example tbody').on( 'click', 'tr.group', function () {
				var currentOrder = table.order()[0];
				if ( currentOrder[0] === 2 && currentOrder[1] === 'asc' ) {
					table.order( [ 2, 'desc' ] ).draw();
				}
				else {
					table.order( [ 2, 'asc' ] ).draw();
				}
			} );
		}else{
			var table = $('#example').DataTable({
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				"columnDefs": [
					{ "visible": false, "targets": 2 }, 
				],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true,
				"order": [[ 2, 'asc' ],[ 0, 'asc' ],[ 1, 'asc' ]],
				"displayLength": 10,
				"drawCallback": function ( settings ) {
					var api = this.api();
					var rows = api.rows( {page:'current'} ).nodes();
					var last=null;
	 
					api.column(2, {page:'current'} ).data().each( function ( group, i ) {
						if ( last !== group ) {
							$(rows).eq( i ).before(
								'<tr class="group"><td colspan="21">'+group+'</td></tr>'
							);
	 
							last = group;
						}
					} );
				}
			} );
			
			// Order by the grouping
			$('#example tbody').on( 'click', 'tr.group', function () {
				var currentOrder = table.order()[0];
				if ( currentOrder[0] === 2 && currentOrder[1] === 'asc' ) {
					table.order( [ 2, 'desc' ] ).draw();
				}
				else {
					table.order( [ 2, 'asc' ] ).draw();
				}
			} );
		}
	} );
</script>


