<?php
/**
 * View -- of Administration/MasterController/addactivity
 * chophel@athang.com
 */
?>
<?php 
	foreach($this->vehiclemain as $row );
	foreach($this->vehiclemaindtlObj->get(array('repair'=>$row['id'])) as $rowdtls);
	//print_r($rowdtls);exit;?>
   <form id="#form" method="post" action="<?php echo $this->url('vehicle', array('action' => 'commitvehicleincome','id'=>$row['id'])); ?>" enctype="multipart/form-data">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"> <i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
        </div>     
        <div class="modal-body">    
            <div class="panel panel-default">                       
                <div class="panel-body">
                <div  class="form-group col-lg-12">
						<label for="cash" class="control-label">Payment</label>
						<div>
						
						</div>
					</div>
					<div class="form-group row" id="party" >
						<label for="party" class="col-md-4 col-form-label">Credit Customer</label>
						<div class="col-md-8">
							<select class="form-control" id="party" name="party">
							<option value="0">None</option>
							<?php foreach($party as $partys):?>
								<option value="<?php echo $partys['id'];?>"><?php echo $partys['name'];?>
								</option>
							<?php endforeach;?>
							</select>
						</div>
					</div>
					<div class="form-group row" >
						<label for="ref_no" class="col-md-4 col-form-label">Reference No</label>
						<div class="col-md-8">
							<input type="text" class="form-control" name="ref_no" value="0"
								id="ref_no" placeholder="Reference No" />
						</div>
					</div>
                </div>
            </div>
            
        </div>    
        <div class="modal-footer">
            <button type="submit" class="btn btn-warning"><i class="fa fa-check"></i> Commit </button>
            <button type="button" class="btn btn-success" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
        </div>  
    </form>  
   