<?php
/**
 * 
 * View -- of TR/VehicleController/edittransdetailAction
 * 
 */
foreach ($this->trans_dtls as $row):
    extract ($row);
endforeach; ?>
<form id="#form" method="post" action="<?php echo $this->url('vehicle', array('action' => 'edittransdetail', 'id' => $this->id)); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> Edit Transport Detail</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="date_of_handing" class="control-label">Date of Handing</label>
					<div class="date input-group" id="date_of_handing" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input type="hidden" class="form-control" name="transport_dtls_id" id="transport_dtls_id"  value = "<?php echo $transport_id; ?>"> 
						<input class="form-control span2" name="date_of_handing" id="date_of_handing" type="text" value="<?php echo $date_of_handing;?>" placeholder="date of handing" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="pool_designated" class="control-label">Pool/Designation</label>
					<select id="pool_designated" name="pool_designated" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php foreach($this->pooldtnObj->getAll() as $pooldtn):
						    $selected_pd = ($pool_designated_id == $pooldtn['id'])?"selected":"";?>
							<option value="<?php echo $pooldtn['id'];?>"<?php echo $selected_pd;?>>
								<?php echo $pooldtn['code'];?>
							</option>
						<?php endforeach;?>					
					</select>
				</div>
				<div class="form-group">
					<label for="employee" class="control-label"> Employee </label>
					<select class="form-control" name="employee" id="employee" data-placeholder="Select employee" > 
						<option value=""></option>
						<?php foreach($this->employeeObj->getAllEmployee() as $employee):
						    $selected_employee = ($employee_id == $employee['id'])?"selected":"";?>
							<option value="<?php echo $employee['id'];?>"<?php echo  $selected_employee;?>>
								<?php echo $employee['full_name'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label for="driver" class="control-label">Driver</label>
					<select class="form-control" name="driver" id="driver"  data-placeholder="Select driver" > 
						<option value=""></option>
						<?php foreach($employee_drivers as $employee_driver):
						      $selected_em_driver = ($employee_driver['id'] == $driver_id)?"selected":"";?>
							<option value="<?php echo $employee_driver['id'];?>"<?php echo $selected_em_driver;?>>
								<?php echo $employee_driver['full_name'];?>
							</option>
						<?php endforeach;?>
					</select
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>    
<script type="text/javascript">	 
$(function(){ 
	$('#date_of_handing').datepicker();
	$('#date_of_handing').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('document').ready(function(){
		$('form select').chosen();
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				date_of_handing: {
					validators: {
						notEmpty: {
							message: 'Select provide date.'
						},
					}
				},
				pool_designated: {
					validators: {
						notEmpty: {
							message: 'Please provide pool/designated.'
						}
					}
				},
				employee: {
					validators: {
						notEmpty: {
							message: 'Please provide employee.'
						}	
					}
				},
				driver: {
					validators: {
						notEmpty: {
							message: 'Please provide driver.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
});
</script>
