<?php
/**
 * 
 * View -- of TR/VehicleController/edittranshistoryAction
 * 
 */
 foreach($this->trans_histories as $trans_history):
       extract($trans_history);
  endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('vehicle', array('action' => 'edittranshistory', 'id' => $this->id)); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> Add Transport History</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="recording_date" class="control-label">Recording Date</label>
					<div class="date input-group" id="recording_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
					    <input type="hidden" class="form-control" name="transport_his_id" id="transport_his_id"  value = "<?php echo $transport_id; ?>"> 
						<input class="form-control span2" name="recording_date" id="recording_date" type="text" value="<?php echo $recording_date;?>" placeholder="recording date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="type" class="control-label">Type</label>
					<select id="type" name="type" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php foreach($this->typeObj->getAll() as $type):
						    $selected = ($type['id'] == $type_id)?"selected":"";?>
							<option value="<?php echo $type['id'];?>"<?php echo $selected;?>>
								<?php echo $type['code'];?>
							</option>
						<?php endforeach;?>					
					</select>
				</div>
				<div class="form-group">
					<label for="start_date" class="control-label">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" value="<?php echo $start_date;?>" placeholder="start date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="end_date" class="control-label">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" value="<?php echo $end_date;?>" placeholder="end date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="amount" class="control-label">Amount</label>
					<input type="text" class="form-control" name="amount" id="amount"value = "<?php echo $amount;?>" required> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>    
<script type="text/javascript">	 
$(function(){ 
	$('#recording_date').datepicker();
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#recording_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				qualification: {
					validators: {
						notEmpty: {
							message: 'Please provide qualification.'
						},
					}
				},
				institute: {
					validators: {
						notEmpty: {
							message: 'Please provide institute.'
						}
					}
				},
				location: {
					validators: {
						notEmpty: {
							message: 'Please provide location.'
						}	
					}
				},
				course: {
					validators: {
						notEmpty: {
							message: 'Please provide course.'
						}
					}
				},
				completion_year: {
					validators: {
						notEmpty: {
							message: 'Please provide completion year.'
						},
						digits: {
							message: 'Please provide valid completion year.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
});
</script>
