<?php
/**
 * 
 * View -- of TR/VehicleController/addtranshistoryAction
 * 
 */
?>
<?php foreach($rowset as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('vehicle', array('action' => 'editvehiclesecondary','id'=>$row['id'])); ?>"  enctype="multipart/form-data" >    
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> Edit Vehicle Secondary Record</h4>
    </div>     
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="registered_date" class="control-label">Date</label>
					<div class="date input-group" id="registered_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="registered_date" id="registered_date" type="text" value="<?php echo $row['registered_date'];?>" placeholder="Work Order Date"  required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group">
					<label for="license_plate" class="control-label">License Plate</label>
					<select id="license_plate" name="license_plate" class="form-control" data-placeholder="Select Head" required>
						<option value=""></option>
						<?php
							foreach ($license as $licenses):
						?>
							<option value="<?php echo $licenses['id']; ?>"<?php echo ($licenses['id'] == $row['license_plate'])?"selected":"";;?>>
							<?php echo $licenses['license_plate']; ?>
							</option>
						<?php endforeach;?>								
					</select> 
				</div>
				<div class="form-group">			
					<label for="location" class="control-label"> Location </label>
					<select id="location" name="location" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php foreach ($regions = $this->regionObj->getAll() as $region): ?>
						<optgroup label="<?php echo $region['region'];?>">
							<?php
								$locations = $locationObj->get(array('region'=>$region['id']));
								foreach ($locations as $location):
								$selected_loc = ($location['id'] == $row['location'])?"selected":"";
							?>
								<option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
								<?php echo $location['location']; ?>
								</option>
							<?php endforeach;?>
						</optgroup>
						<?php endforeach;?>									
					</select> 
				</div>
				<div class="form-group">
					<label for="class" class="control-label"> Head </label>
					<select id="head" name="head" class="form-control" data-placeholder="Select Head" required>
						<option value=""></option>
						<?php
							foreach ($head as $heads):
						?>
							<option value="<?php echo $heads['id']; ?>"<?php echo ($heads['id'] == $row['head'])?"selected":"";;?>>
							<?php echo $heads['code']; ?>
							</option>
						<?php endforeach;?>								
					</select> 
				</div>
				<div class="form-group">
					<label for="subhead" class="control-label">Subhead</label>
					<select id="subhead" name="subhead" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php
							foreach ($subhead as $subheads):
						?>
							<option value="<?php echo $subheads['id']; ?>" <?php echo ($subheads['id'] == $row['subhead'])?"selected":"";?>>
							<?php echo $subheads['name']; ?>
							</option>
						<?php endforeach;?>								
					</select> 
				</div>
				<div class="radio">
					<label>  
						<input class="ace" type="radio" name="pol" id="pol"  value="1"<?php echo ($row['pol']=='1')?"checked":"";?>/>
						<span class="lbl"> POL </span>
					</label> 
					<label>  
						<input class="ace" type="radio" name="pol" id="pol" value="0"<?php echo ($row['pol']=='0')?"checked":"";?>/>
						<span class="lbl"> Service </span>
					</label> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>    
<script type="text/javascript">
	$(function(){
		$('#registered_date').datepicker();
		$('select#head').on('change', function() {
			$.post(
				"<?php echo $this->url('vehicle', ['action'=>'getsubhead']); ?>",
				{
					headId: $(this).val()
				},
				function(data){
					$('select#subhead').html(data.subhead);
					$('select#subhead').trigger('chosen:updated');
				},'json'
			);
		});
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				license_plate: {
					validators: {
						notEmpty: {
							message: 'Please provide license plate .'
						},
					}
				},
				location: {
					validators: {
						notEmpty: {
							message: 'Please provide date of birth.'
						},
					}
				},	
				head: {
					validators: {
						notEmpty: {
							message: 'Please provide date of birth.'
						},
					}
				},	
				subhead: {
					validators: {
						notEmpty: {
							message: 'Please select posted location.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			//console.log(document.getElementsByName('license_plate')[0].value); // Console log the license plate value
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		$('form select').chosen().change(function () {
			fv.revalidateField($(this).attr('name'));
		});
	});
</script>