<?php
/**
 * 
 * View -- of Tr/VehicleController/transhistoryAction
 * 
 */
$this->headTitle($this->title);
?>
<?php 
foreach($this->transports as $row):
    extract($row);
endforeach; 
?>
<?php echo $this->partial('fleet/vehicle/partial.phtml', array('active' => 'transdetail', 'id' => $id)); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
	<div class="table-header"> Transport Details of <?php echo $transport; ?> </div>
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Date of Handing</th>
					<th>Pool/Designation</th>
					<th>Employee</th>
					<th>Driver</th>
					<th>Remarks</th>
					<th class="no-sort no-printpdf">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->trans_dtls as $row):
				?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $row['date_of_handing']; ?> </td>
						<td><?php echo $this->pooldtnObj->getColumn($row['pool_designated_id'],'code'); ?></td>
						<td><?php echo $this->employeeObj->getColumn($row['employee_id'],'full_name'); ?></td>
						<td><?php echo $this->employeeObj->getColumn($row['driver_id'],'full_name'); ?></td>
						<td><?php echo $row['remarks']; ?></td>
						<td>
							<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('vehicle', array('action'=>'edittransdetail', 'id' => $row['id']));?>" data-target="#modal">
								<i class="ace-icon fa fa-pencil bigger-120"></i>
							</a>                                                                    
						</td>
					</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable();
});
</script>




























