<?php
/**
 * 
 * View -- of Fleet/VehicleController/repairAction
 * 
 */
	$this->headTitle($this->title);
	//print_r($this->repair_maintaneses); exit;
?>
<div class="space-12"></div>
<div class="row">
    <div class="col-lg-12">
		<form method="post" action="<?php echo $this->url('vehicle',array('action'=>'vehicleincome')); ?>"  enctype="multipart/form-data" >
			<div class="form-group col-lg-2">
				<label class="control-label" for="year">Year</label>
				<select class="form-control" id="year" name="year" data-placeholder="Select" >
					<option value=""></option>
					<?php 
						for($year=date('Y');$year>=$data['minYear'];$year--):
							$selected = ($year == $data['year'])?"selected":"";
					?>
						<option value="<?php echo $year;?>" <?php echo $selected;?> >
							<?php echo $year;?> 
						</option>
					<?php endfor; ?>
				</select>
			</div>
			<div class="form-group col-lg-2">
				<label class="control-label" for="month">Month</label>
				<select class="form-control" id="month" name="month" data-placeholder="Select" >
					<?php for($month=1; $month<=12; $month++):?>
						<?php $selected = ($month == $data['month'])?'selected':'';?>
						<option value="<?php echo $month;?>" <?php echo $selected; ?>>
							<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
						</option> 
					<?php endfor;?>
				</select>
			</div>
			<div class="col-lg-2">
				<div class="space-12"></div>
				<button type="submit" class="btn btn-sm btn-primary pull-left"><i class="fa fa-refresh"></i> Refresh </button>
			</div>
			<div class="col-lg-4"></div>
			<div class="col-lg-2">
				<div class="space-12"></div>
				<?php echo $this->button(2);?>
			</div>
		</form>
	</div>
	<div class="col-lg-12">
		<div>
			<table class="table card-table text-nowrap" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Repair No.</th>
						<th>Amount</th>
						<th>Status</th>
						<th class="no-sort no-printpdf">Action</th>	
					</tr>
				</thead>
				<tbody>
					<?php  $i = 1; 
					foreach ($this->repair_maintaneses as $repair_maintanese):?>
					 <tr data-href="<?php echo $this->url('vehicle', array('action'=>'viewvehicleincome', 'id'=>$repair_maintanese['id']));?>">
						<td><?php echo $i++;?></td>
						<td><?php echo $repair_maintanese['repair_no']?></td>
						<td><?php echo $repair_maintanese['total_amount']?></td>
						<td><?php echo $this->status($repair_maintanese['status']);?></td>
						<td class="action">
							<div class="btn-group">
								<!-- <a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "30-".$repair_maintanese['id'])); ?>" title="View Activity Logs">
									<i class="ace-icon fa fa-plus bigger-120" ></i>  
								</a> -->
								<?php if($role==99 || $role==100):?>
								<a class="btn btn-xs btn-danger" href="<?php echo $this->url('vehicle', array('action' => 'deletevehicleincome', 'id' => $repair_maintanese['id'])); ?>">
								<i class="ace-icon fa fa-trash bigger-120" ></i>  
								</a>
								<?php endif;?>
							</div>
						</td>		                              
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>	
$('document').ready(function(){	
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('#dataTables').DataTable({
		"paging":   true,
		"pageLength": 20, // Set the number of rows per page to 50
	});
});
</script>

 
