<?php
/**
 * 
 * View -- of Fleet/VehicleController/viewAction
 * 
 */
	$this->headTitle($this->title);
	foreach ($this->transports as $transport);
	//print_r($transport);exit;
?>

<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Date </th>
					<th>Vehicle Group </th>
					<th>License Plate </th>
					<th>Vehicle Location </th>
					<th class="no-sort no-printpdf">Action</th>	
				</tr>
			</thead>
			<tbody>
				<?php  $i = 1; 
				foreach ($this->transports as $transport):?>
				<tr>
					<td><?php echo $i++;?></td>
					<td><?php echo $transport['registered_date'];?></td>
					<td><?php if(empty($transport['group'])): echo ""; else: echo $this->groupObj->getColumn($transport['group'],'group');endif;?></td>
					<td><?php echo $transport['license_plate'];?></td>
					<td><?php echo $this->locationObj->getColumn($transport['location'],'location');?></td>
					<td class="action"><?php echo $this->button(1,$transport['id']);?>
						
					</td>						
				</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>		
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>

 
