<?php
/**
 * 
 * View -- of Purchase/PurchaseController/viewporder
 * 
 */
?>
<?php 
	foreach($repair as $row);
		extract($row); 
             $rm_id = $row['id'];
                $rm_status = $row['status'];
				//print_r($row);
//endforeach;exit;
	$roles=explode(',',$role);
	$count=0;
	for($i=0;$i<sizeof($roles);$i++){
		if($roles[$i]==2 ||$roles[$i]==3){
			$count=1;
			break;
		}
		else{
			$count=0;
		}
	}
	

	foreach($this->RMDObject->get(array('repair' =>$id)) as $repair);
?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<form method="post" action="<?php echo $this->url('vehicle', array('action' => 'viewrepair')); ?>" >
				<div class="widget-header">
					<h5 class="widget-title lighter smaller">
						# Transport Expense Details:<strong>&nbsp;&nbsp;<?php echo $location; ?> | <?php //echo $supplier; ?> | <?php //echo $cost_center ?></strong>&nbsp;
						<?php $this->status($status);?>
					</h5>
					<div class="widget-toolbar hidden-xs">
							<button type="button" id="rm_btn" class="btn btn-white btn-warning btn-bold btn-xs"><i class="fa fa-plus"></i> <a href="<?php echo $this->url('vehicle', array('action'=>'addrepair'));?>"> Add New Repair and Maintanese</a></button>
					</div>
					<div class="widget-toolbar hidden-xs">
						<div class="btn-group">
							<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "30-".$rm_id )); ?>" title="View Activity Logs">
								<i class="ace-icon fa fa-plus bigger-120" ></i>  
							</a> 
							<a class="btn btn-xs" id="print" title="Print">
								<i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
							</a>
						</div>
					</div>
				</div>
			</form>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
								    <li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b>Work Order Date : </b><?php echo $this->dateformat($work_order_date); ?>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b>Expense no : </b><?php echo $repair_no; ?>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b>Location :  </b><?php echo $location;?>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b>Expense Amount : </b><?php echo $total_amount; ?>
									</li>
									</li>
                                  
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
								    <li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b> Voucher No. : </b> <?php echo $this->transObj->getColumn($transaction,'voucher_no'); ?> 
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b>Party : </b><?php echo $this->partyObj->getColumn($repair['party'],'name'); ?> 
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<b>Refernece Number : </b><?php echo $repair['ref_no']; ?> 
									</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i><b>Note:</b><?php echo $remarks;?> 
									</li>
								</ul>
							</div>
						</div>
						<div class="space-6"></div>
						<div class="row">
							<div class="col-lg-12" >
								<table class="table" style="border-top:2px solid #ddd;">
									<thead>
										<tr>
											<th>#</th>
											<th>Head</th>
											<th>Subhead</th>
											<th>Amount</th>
											<th>Action</th>
											
										</tr>
									</thead>
									<tbody>
										<?php $sl = 1; 
											foreach($this->RMDObject->get(array('repair' =>$id)) as $tdrow):
											?>
											<tr>
												<td><?php echo $sl++; ?></td>
												<td><?php echo $this->serviceObj->getColumn($tdrow['service'],'code');?></td>
												<td><?php echo $this->vehicleObj->getColumn($tdrow['service_item'],'name');?></td>
												<td><?php echo $tdrow['amount'];?></td>
												<?php if($userID==1):?>
												<td><a class="btn btn-xs btn-danger" href="<?php echo $this->url('vehicle', array('action'=>'deleteexpense', 'id'=>$tdrow['id']));?>"> <i class="fa fa-trash"></i></a></td>
												<?php endif;?>
											</tr>
										<?php endforeach;?>
										<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
											<th></th>
											<th colspan="2">Net Amount :</th>
											<th colspan="2"> 
											<?php echo $this->currency($total_amount);?></th>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
				
					</div>
					<div class="row">
						<div class="col-lg-12" style="text-align: right">				
						<?php if($status == '2' && $this->user_location == $location_id && $count==1):?>
								<a href="<?php echo $this->url('vehicle', array('action'=>'editrepair', 'id'=>$id));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
								<a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('vehicle', array('action'=>'processtp', 'id'=>$id.'-1'));?>" class="btn btn-warning"> <i class="fa fa-arrow-right"></i>Apply</a>
								<?php endif;?>
						</div>
					</div>
					<!-- Upload and Download file attachments -->			
					<?php   
					  // echo $this->partial('partial/attachment.phtml', array('process' => '1', 'process_id'=> $rm_id , 'status' => $rm_status));
					?>					
				    <!-- End of attachment -->
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#rm_btn').on('click',function(){
		window.document.location = "<?php echo $this->url('vehicle', array('action' => 'addrepair'));?>";
	});

</script>
