<?php
/**
 * 
 * View -- of Stock/StockController/indexAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/master/partial.phtml', array('active' => 'formula')); ?>
<div class="space-12"></div>
<div class="card">
	<div class="card-header">
		<form id="#form" method="post" action="<?php echo $this->url('formula',array('action'=>'index')); ?>"  enctype="multipart/form-data" >
			<div class="row">
				<div class="form-group col-lg-3">
					<label for="activity" class="control-label">Activity</label>
					<select class="form-control" name="activity" id="activity" data-placeholder="Select" onChange="form.submit(this)" required>
						<option value="-1">All</option>
						<?php foreach($activityObj->getAll() as $activitys):
							$selected = ($activityID == $activitys['id'])?'selected':'';?>
						<option value="<?php echo $activitys['id'];?>"<?php echo $selected;?>>
							<?php echo $activitys['activity']; ?>
						</option>
					<?php endforeach ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
				</div>	
				<div class="form-group col-lg-6">	
					<div class="clearfix">
						<div class="pull-right tableTools-container"></div>
						<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Item" href="<?php echo $this->url('formula', array('action' => 'add'));?>" >
							<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Costing Formula</span></span>
						</a>
					</div>
				</div>
			</div>			
		</form>	
		
		<div>
		   <table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Formula Name</th>
						<th>Description</th>	
						<th>Type</th>					
						<th>Actions</th>										
					</tr>
				</thead>
				<tbody>
				<?php	$i = 1; 
						foreach ($this->formulae as $formula):
					?>
						<tr class="tr-clickable" href = "<?php echo $this->url('formula', array('action'=>'view', 'id'=>$formula['id']));?>">
								<td><?php echo $i++; ?> </td> 
								<td>
								    <?php echo $formula['formula_name']; ?> 
								     <span style="font-size:12px">
									 <i>
										 <span class="label label-info"> 
											<?php echo $this->activityObj->getColumn($formula['activity'],'activity'); ?>&nbsp;&nbsp;&nbsp;
										 </span>
									 </i>        
									  &nbsp;
									  <?php $this->status($formula['status']);?>
								   </span>		
								</td> 
								<td><?php echo $formula['description']; ?></td>
								<td><?php echo $this->costingTypeObj->getColumn($formula['costing_type'], 'costing_type'); ?></td>
														                            
						        <td class="action">
    								<div class="btn-group">
    								    <a class="btn btn-xs btn-success" href="<?php echo $this->url('formula', array('action' => 'view', 'id' => $formula['id'])); ?>" title="view details">
										    <i class="ace-icon fa fa-eye bigger-120" ></i>  
									    </a>
    									<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "17-".$formula['id'])); ?>" title="View Activity Logs">
    										<i class="ace-icon fa fa-plus bigger-120" ></i>  
    							  		</a>
    						  		</div>
							    </td>						</tr>
					<?php endforeach;?>
				</tbody>
		  </table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#dataTables').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script> 
 

