<div class="form-group">
	<label for="fa_sub_head" class="control-label">Finance Sub Head</label>
	<select class="form-control" id="fa_sub_head" name="fa_sub_head" data-placeholder="Select" required>
		<option value=""></option>
		<?php foreach ($this->subheads as $subhead): ?>
			<option value="<?php echo $subhead['id']; ?>" data-payhead-type="<?php echo $this->escapeHtmlAttr($subhead['payhead_type_id']); ?>" <?php echo ($this->selectedSubhead == $subhead['id']) ? 'selected' : ''; ?>>
				<?php echo $this->escapeHtml(html_entity_decode($subhead['name'], ENT_QUOTES, 'UTF-8')); ?>
			</option>
		<?php endforeach; ?>
	</select>
</div>
