<?php
/**
 * Index -- of Advance Salary
**/
	$this->headTitle($this->title);
?>
<div class="row">
	<div class="col-lg-12">
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
			<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Advance Salary" href="<?php echo $this->url('advancesalary', array('action'=>'addadvancesalary'));?>" >
				<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Advance Salary</span></span>
			</a>
		</div>
		<div class="space-12"></div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Employee</th>
						<th>Emp ID</th>
						<th>Designation</th>
						<th>Location</th>
						<th>PayHead</th>
						<th>Initial Date</th>
						<th>Total Amount</th>
						<th>Monthly Deduction</th>
						<th class="no-sort no-printpdf">Action</th>	
					</tr>
				</thead>
				<tbody>
					<?php
						$sl = 1;
						foreach($advance_salary as $row):
					?>
					<tr data-href="<?php echo $this->url('advancesalary', array('action'=>'viewadvancesalary', 'id'=>$row['id']));?>">
						<td><?php echo $sl++;?></td>
						<td><strong><?php echo $row['full_name'];?></strong></td>
						<td><?php echo $row['emp_id'];?></td>
						<td><?php echo $row['designation'].' ('.$row['type_code'].')';?></td>
						<td><?php echo $row['location'];?></td>
						<td><strong><?php echo $this->payheadObj->getColumn($row['pay_head'],'head_type');?></strong></td>
						<td><?php echo $row['initial_date'];?></td>
						<td><?php echo $row['total_amount'];?></td>
						<td><?php echo $row['total_deduction'];?></td>
						<td class="action">
							<div class="btn-group">
								<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "26-".$row['id'])); ?>" title="View Activity Logs">
									<i class="ace-icon fa fa-plus bigger-120" ></i>  
								</a>
							</div>
						</td>								
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});

	$('#dataTables').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>