<?php
/**
 * 
 * View -- of Purchase/PurchaseController/addreceiptAction
 * 
 */
  $this->headTitle($this->title);
?>
<style>
    .input-cell {
        max-width: 100px; /* Adjust the value as per your requirement */
    }
	<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		 <div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i>&nbsp;&nbsp;Add Purchase Receipt Details
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form  id="#form" method="post" action="<?php echo $this->url('receipt', array('action' => 'addreceiptdtl','id'=>$pr)); ?>"  enctype="multipart/form-data" >    
						<div class="row">
							<table class="table small-padding">
								<tbody>
									<tr>
										<th>Item</th>
										<th>PO Qty</th>
										<th>Rate</th>
										<th>Damaged Qty</th>
										<th>Accepted Qty</th>
										<th>Amount</th>
									</tr>
										<tr>
										<?php foreach($purchase as $row):?>
										<td class="col-lg-2 ">
											<div class="form-group">
												<?php if($row['item_class']==33):?>
													<input class="form-control" name="item[]" id="item" data-placeholder="Select" value="<?php echo $row['item_name'];?>">
												<?php else:?>
												<select class="form-control" name="item[]" id="item" data-placeholder="Select"  readonly>
													<option value="<?php echo $row['item'];?>">
													<?php echo $this->itemObj->getColumn($row['item'],'name');?>
													</option>
												</select> 
												<?php endif;?>
											</div>
										</td>
										<td class="col-lg-2 input-cell">
											<div class="form-group">
												<input type="text" class="form-control "  name="po_quantity[]" id="po_quantity" value="<?php echo $row['quantity'];?>" readonly>
											</div>
										</td>
										<td class="col-lg-1">
											<div class="form-group">
												<input type="text" class="form-control tr_rate"  name="rate[]" id="rate" value="<?php echo $row['rate'];?>" readonly>
											</div>         
										</td>
										<td class="col-lg-1">
											<div class="form-group">
												<input type="text" class="form-control"  name="damage_qty[]" id="damage_qty" value="0.00">
											</div>         
										</td>
										<td class="col-lg-1">
											<div class="form-group">
												<input type="text" class="form-control tr_accepted_qty"  name="accepted_qty[]" id="accepted_qty" value="<?php echo $row['quantity'];?>">
											</div>         
										</td>
										<td class="col-lg-1">
											<div class="form-group">
												<input type="text" class="form-control tr_amount"  name="amount[]" id="amount" value="0.00" readonly>
											</div>         
										</td>
									</tr> 
									<?php endforeach;?>
								</tbody>
							</table>
						</div>
						<div class="row">
							<div class="col-lg-6"></div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="total">Total</label>
									<input type="text" class="form-control tr_total" name="total" id="total" value="0.000" readonly />
								</div>
							</div> 
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('receipt',array('viewreceipt','id'=>$pr));?>'" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
					</form>  
				</div> <!-- end of widget-main -->  
			</div> <!-- end of widget-body -->
		</div> <!-- end of widget widget-default -->
    </div> <!-- end of col-lg-12 -->
</div> <!-- end of row -->
<script type="text/javascript">
	$(document).on('input', '.tr_rate, .tr_accepted_qty', function() {
		calculateTotal($(this));
	});
	function calculateTotal(element) {
		var row = element.closest('tr');  // Get the closest table row

		var rateInput = row.find('.tr_rate');  // Adjusted these to use class selectors and scope within the row
		var quantityInput = row.find('.tr_accepted_qty');
		var totalInput = row.find('.tr_amount'); // Assuming there's a field for the total amount with the class "tr_amount"

		var rate = parseFloat(rateInput.val()) || 0;
		var quantity = parseFloat(quantityInput.val()) || 0;
		var total = rate * quantity;

		totalInput.val(total.toFixed(2));  // Assuming you want to show up to two decimal places
	}
		$(document).on('input', '.tr_amount,.tr_accepted_qty', function () {
			calculateTotalAmount();
		});
		
		function calculateTotalAmount() {
		console.log("calculateTotal amount");
		
		var row = $(this).closest('tr');  // Get the closest table row
		var total = 0;
		// Iterate over each amount input field in the table
		$('.tr_amount').each(function() {
			var amount = parseFloat($(this).val());
			
			if (!isNaN(amount)) { // Make sure it's a valid number
				total += amount;
			}
		});
		// Update the #total field with the new sum
		$('#total').val(total.toFixed(2));
	}
$(document).ready(function (){
	$('#prn_date').datepicker();
	$('#po_no').on('change', function(){
		//alert($(this).val());
		$.post(
			"<?php echo $this->url('receipt', array('action' => 'getsupplier')); ?>",
			{
				po_no: $(this).val(),
			},
			function(data){
				console.log(data);
				$("#supplier").html(data.supplier);	
				$("#supplier").trigger('chosen:updated');
			},
			'json'
		);	
	});
	// Calculate amounts for all rows after the page loads
    $('.tr_rate').each(function() {
        calculateTotal($(this));
    });
    
    // Listen for input changes in tr_rate and tr_accepted_qty fields
    $(document).on('input', '.tr_rate, .tr_accepted_qty', function() {
        calculateTotal($(this));
    });
	// Calculate totals for all rows after the page loads
    $('.tr_amount').each(function() {
        calculateTotalAmount();
    });
	$(document).on('input', '.tr_amount,.tr_accepted_qty', function () {
			calculateTotalAmount();
		});
	/******** formValidation *************/
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
	    fields: {
			'prn_date': {
				validators: {
					notEmpty: {
						message: 'Please select voucher date'
					}
				}
			},
		
			'location': {
				validators: {
					notEmpty: {
						message: 'Please select location'
					}
				}
			},
			'supplier': {
				validators: {
					notEmpty: {
						message: 'Please select supplier'
					}
				}
			},
			'po_no':{
				validators: {
					notEmpty:{
						message: 'Please select PO No.'
					},
				}
			},      
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
