<?php
/**
 * 
 * View -- of Purchase/PurchaseController/editpreceiptAction
 * 
 */
 $this->headTitle($this->title);
?>
<?php 
  foreach($this->purchase_receipt as $pur_receipt):
	  extract($pur_receipt);
	  $pr_id = $id;
	  $sel_supplier = $supplier_id;
	  $sel_activity = $activity_id;
	  $sel_location = $location_id;
  endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;&nbsp;&nbsp;Edit PRN : &nbsp;<strong><?php echo $prn_no; ?> | <?php echo $supplier; ?> | <?php echo $activity ?></strong>&nbsp;
					<?php $this->status($status);?>
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form method="post" action="<?php echo $this->url('receipt', array('action' => 'editreceipt', 'id' => $pr_id)); ?>"  enctype="multipart/form-data" >    
						 <div class="row">	
						 <input type="hidden" name="id" id="id" value="<?php echo $pr_id; ?>">
						 <input type="hidden" name="prn_no" id="prn_no" value="<?php echo $prn_no; ?>"> 
							<div class="col-lg-3">    
								<div class="form-group">
									<label for="po_date" class="control-label">PRN Date</label>
									<div class="date input-group" id="prn_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $prn_date; ?>" name="prn_date" id="prn_date" type="text" placeholder="PRN Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>	
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="activity" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
									  <?php foreach ($regions as $region): ?>
										<optgroup label="<?php echo $region['region'];?>">
											<?php  
												 // retrive locations under the above region ID
												$locations = $locationObj->get(array('l.region'=>$region['id']));
												 foreach ($locations as $location):
												 $selected = ($location['id'] == $sel_location)?"selected":"";
											?>
											 <option value="<?php echo $location['id']; ?>" <?php echo $selected;?>>
												<?php echo $location['location']; ?>
											 </option>
											<?php 
											 endforeach;
											?>
									  </optgroup>
									 <?php endforeach;  ?>									
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="activity" class="control-label">Activity</label>
									<select class="form-control" name="activity" id="activity" data-placeholder="Select" readonly="readonly" required>
										<option value=""></option>
										<?php foreach($this->activities as $activity):
										$selected=($activity['id']==$sel_activity)?'selected':'';?>
											<option value="<?php echo $activity['id'];?>" <?php echo $selected;?>>
										   		<?php echo $activity['activity']; ?>
										   	</option>
										<?php endforeach; ?>								
									</select>
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="supplier" class="control-label">Supplier</label>
									<select id="supplier" name="supplier" class="form-control" data-placeholder="Select" required readonly="readonly">
										<option value=""></option>	
										<?php foreach ($this->suppliers as $supplier): ?>
											<?php $selected = ($supplier['id'] == $sel_supplier)?"selected":""; ?>
											<option value="<?php echo $supplier['id'];?>" <?php echo $selected; ?> >
												<?php echo $supplier['name']; ?>
											</option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>
						</div>
						<div class="row">
							 <div class="col-lg-3">
								<div class="form-group">
									<label for="custom_declaration" class="control-label">Custom Declaration</label>
									<input type="text" class="form-control" value="<?php echo $custom_declaration; ?>" name="custom_declaration" id="custom_declaration" placeholder="Custom Declaration"> 
								</div>
							</div> 
							<div class="col-lg-3">
								<div class="form-group">
									<label for="challan_no" class="control-label">Challan No.</label>
									<input type="text" class="form-control" value="<?php echo $challan_no;?>" name="challan_no" id="challan_no" placeholder="Challan no." > 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="challan_date" class="control-label">Challan Date</label>
									<div class="date input-group" id="challan_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $challan_date;?>" name="challan_date" id="challan_date" type="text" placeholder="Challan Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>	
							<div class="col-lg-3">
								<div class="form-group">
									<label for="po_no" class="control-label">PO No.</label>
									<select class="form-control" name="po_no" id="po_no" data-placeholder="Select" readonly>
										<option value=""></option>
										<option value="<?php echo $purchase_order;?>" selected="selected">
											<?php echo $this->pur_ordersObj->getColumn($purchase_order, 'po_no');?>
										</option>	
									</select> 
								</div>
							</div>      				
						</div>
						<div class="row">
						   <div class="col-lg-12"> 
							  <h5>Purchase Receipt Details</h5>
								 <div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Item</th>
												<th>UOM</th>
												<th>PO Qty</th>
												<th>Balance Qty</th>
												<th>Challan Qty</th>
												<th>Damage Qty</th>
												<th>Shortage Qty</th>
												<th>Accepted Qty</th>
												<th>Sound Qty</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
										<?php 
										  if(sizeof($pr_details) > 0 ):
											$i = 1;
											foreach ($this->pr_details as $pr_detail):
										?>
											<tr>
												<td>
													<div class="form-group">
														<select id="item" name="item[]" class="form-control" data-placeholder="Select" >
															<option value=""></option>		
															<?php
															$items = $this->itemObj->getItem($purchase_order);
															 foreach ($items as $item):
																$selected = ($item['id']==$pr_detail['item_id'])?"selected":"";
															  ?>
																 <option value="<?php echo $item['id']; ?>" <?php echo $selected;?>>
																	<?php echo $item['code']; ?>
																 </option>
															 <?php endforeach; ?>															
														</select>
														<input type="hidden" name="details_id[]" id="details_id" value="<?php echo $pr_detail['id'];?>">
														<input type="hidden" name="po_details_id[]" id="po_details_id" value="<?php echo $pr_detail['po_details_id']; ?>"/>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control" data-placeholder="Select" >
															<option value=""></option>
															<?php 
																if($pr_detail['po_details_id'] > 0):
																	$pur_order_qty = $this->po_detailsObj->getColumn($pr_detail['po_details_id'],'quantity');
																	$pur_order_uom = $this->po_detailsObj->getColumn($pr_detail['po_details_id'],'uom');
																	$received_order_qty = $this->po_detailsObj->getColumn($pr_detail['po_details_id'],'received_qty');
																else:
																	$pur_order_qty = $this->po_detailsObj->getColumn(array('purchase_order' => $purchase_order, 'item' => $pr_detail['item_id']),'quantity');
																	$pur_order_uom = $this->po_detailsObj->getColumn(array('purchase_order' => $purchase_order, 'item' => $pr_detail['item_id']),'uom');
																	$received_order_qty = $this->po_detailsObj->getColumn(array('purchase_order' => $purchase_order, 'item' => $pr_detail['item_id']),'received_qty');
																endif;
																
																$basic_uom = $this->itemObj->getColumn($pr_detail['item_id'],'uom');
																$po_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$pr_detail['item_id'], 'uom'=>$pur_order_uom),'conversion');
																$pr_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$pr_detail['item_id'], 'uom'=>$pr_detail['uom_id']),'conversion');
																
																$po_basic_qty = ($basic_uom == $pur_order_uom)?$pur_order_qty: $pur_order_qty * $po_uom_conversion;
																$po_qty = ($basic_uom == $pr_detail['uom_id'])?$po_basic_qty: $po_basic_qty / $pr_uom_conversion;
																
																/** received qty **/
																$received_basic_qty = ($basic_uom == $pur_order_uom)?$received_order_qty: $received_order_qty * $po_uom_conversion;
																$received_qty = ($basic_uom == $pr_detail['uom_id'])?$received_basic_qty: $received_basic_qty / $pr_uom_conversion;
																$balance_qty = $po_qty - $received_qty;
																$balance_qty = ($balance_qty < 0)?'0.00':$balance_qty;
															?>
															<?php 
															$selected_item = $this->itemObj->get($pr_detail['item_id']);
																foreach($selected_item as $item):
																	$selected = ($item['uom']==$pr_detail['uom_id'])?"selected":"";
															?>
																<option value="<?php echo $item['uom']?>" <?php echo $selected;?> >
																	<?php echo $this->uomObj->getColumn($item['uom'], 'code');?>
																</option>
															<?php endforeach;?>
															<?php   
																$itemuoms = $this->itemuomObj->get(array('ui.item' => $pr_detail['item_id']));
																foreach($itemuoms as $uom):
																	$selected = ($uom['uom']==$pr_detail['uom_id'])?"selected":"";
															?>
																<option value="<?php echo $uom['uom'];?>" <?php echo $selected;?> >
																	<?php echo $uom['uom_code'];?>
																</option>
															<?php endforeach;?>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="po_qty[]" id="po_qty" value="<?php echo $po_qty;?>" readonly />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="balance_qty[]" id="balance_qty" value="<?php echo $balance_qty;?>" readonly />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['challan_qty'];?>" name="challan_qty[]" id="challan_qty" required />
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['damage_qty']; ?>" name="damage_qty[]" id="damage_qty" >
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['shortage_qty']; ?>" name="shortage_qty[]" id="shortage_qty" >
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['accept_qty'];?>" name="accept_qty[]" id="accept_qty" readonly >
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['sound_qty'];?>" name="sound_qty[]" id="sound_qty" readonly >
													</div>         
												</td>
												<td></td>
											</tr>
											<?php
													endforeach;
												endif;
											?>
									   </tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('receipt', array('action' => 'viewreceipt', 'id'=> $pr_id));?>'" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
					</form>     
				</div>
	        </div>   
        </div>
    </div>   
</div>	
<script type="text/javascript">
$(function() {
	$('form select').chosen({ allow_single_deselect:true});
	$('#prn_date').datepicker();
	$('#challan_date').datepicker();
	$('#prn_date').on('changeDate',function(){
	  $('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#challan_date').on('changeDate',function(){
	  $('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#trdetails_table').preceipt({
		getUom:"<?php echo $this->url('receipt', array('action'=>'getuom'));?>",
		getUomChange:"<?php echo $this->url('receipt', array('action' => 'getuomchange'));?>",
	});
});
/******** formValidation *************/
$('form').formValidation({
  framework: 'bootstrap',
  excluded: ':disabled',
  message: 'This value is not valid',
  fields: {
	  'prn_date': {
		  validators: {
			  notEmpty: {
				  message: 'Please select voucher date'
			  }
		  }
	  },

	  'location': {
		  validators: {
			  notEmpty: {
				  message: 'Please select location'
			  }
		  }
	  },
	  'activity': {
		  validators: {
			  notEmpty: {
				  message: 'Please select activity'
			  }
		  }
	  },
	  'supplier': {
		  validators: {
			  notEmpty: {
				  message: 'Please select supplier'
			  }
		  }
	  },
	  'challan_no': {
		  validators: {
			  notEmpty: {
				  message: 'Please provide challan no.'
			  }
		  }
	  },  
	  'challan_date':{
		  validators: {
			  notEmpty:{
				  message: 'Please select challan date'
			  },
		  }
	  }, 
	  'po_no':{
		  validators: {
			  notEmpty:{
				  message: 'Please select PO No.'
			  },
		  }
	  },      
	  'item[]':{
		  validators: {
			  notEmpty:{
				  message: 'Please select item'
			  },
		  }
	  },  
	  'uom[]':{
		  validators: {
			  notEmpty:{
				  message: 'Please select uom'
			  },
		  }
	  }, 
	  'po_qty[]':{
		  validators: {
			  notEmpty:{
				  message: 'Please provide PO Qty'
			  },
		  }
	  },  
	  'challan_qty[]':{
		  validators: {
			  notEmpty:{
				  message: 'Please provide challan_qty'
			  },
		  }
	  },
  }
}).on('success.field.fv', function(e, data) {
  if (data.fv.getInvalidFields().length > 0) {    /* There is invalid field */
	  data.fv.disableSubmitButtons(true);
  }
});
</script>