<?php
/**
 * 
 * View -- of Accounts/TransactionController/viewtransactionAction
 * 
 */
?>
<?php 
	foreach($this->transactionrow as $row ):
		extract($row);
		$bank_ref_type_id = $row['bank_ref_type'];
	endforeach;
	/**Get Encash detail*/
	$encash = $this->encashObj->getColumn(array('transaction_id'=>$id),'id');
?>
<?php foreach ($application as $row);
$max_activity = $this->flowtransactionObj->getMax($column='activity', $where=array('application'=>$row['id']));
$current_flow = $this->flowtransactionObj->get(array('application'=>$row['id'], 'activity'=>$max_activity));
$edit_option = 0;
if(sizeof($current_flow) > 0){
	foreach($current_flow as $current);
	$userRolesArray = explode(",", $login_role);
	$edit_option = (in_array($current['actor'],$userRolesArray))?1:0;
}
?>
<div class="space"></div>
<div class="col-lg-12">
	<div class="widget-box transparent" id="report-print">
		<div class="widget-header widget-header-large">
			<h5 class="widget-title grey lighter">
				<i class="ace-icon fa fa-file-text-o green"></i>
				<b><?php echo $voucher_type;?> | <?php echo $voucher_no;?> | <?php $this->status($status);?></b>
			</h5>
			<div class="widget-toolbar hidden-xs">
				<a style='cursor:pointer' id="print">
					<i class="ace-icon fa fa-file-pdf-o red"></i>
				</a>
			</div>
			<div class="widget-toolbar hidden-xs">
				<a class="btn btn-white btn-warning btn-bold btn-xs" title="Add new Payment"
					href="<?php echo $this->url('transaction', array('action'=>'addagainstdebit')); ?>">
				&nbsp;<i class="fa fa-plus"></i>&nbsp;</a>
			</div>
		</div>
		<div class="widget-body">
			<div class="widget-main padding-24">
				<div class="row" id="convert-tb0">
					<div class="col-lg-9" id="convert-tb1">
						<ul class="list-unstyled spaced">
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Journal Name :</b> <?php echo $voucher_type; ?>
							</li>
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Voucher Date :</b> <?php echo $voucher_date; ?> 
							</li>
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Document ID : </b> <?php echo $doc_id; ?>
							</li>
							<li>
								<i class="ace-icon fa fa-caret-left blue"><b></i>Document Type :</b> <?php echo $doc_type; ?> 
							</li>
						</ul>
					</div>
					<div class="col-lg-3" id="convert-tb3">
						<ul class="list-unstyled spaced">
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Voucher No :</b> <?php echo $voucher_no; ?>
							</li>
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Voucher Amount :	<?php echo $this->currency($voucher_amount);?> </b>
							</li>
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Bank Reference Type :</b> <?php echo $this->bank_ref_typeObj->getColumn($bank_ref_type_id,'bank_ref_type'); ?> 
							</li>
							<li>
								<i class="ace-icon fa fa-caret-left blue"></i><b>Cheque No :</b>	 <?php echo $row['cheque_no']?> 
							</li>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<ul class="list-unstyled spaced">
							<li>
								<i class="ace-icon fa fa-caret-right blue"><b></i>Naration : </b> <?php echo $remark;?>
							</li><?php if($doc_id=='Encashment'): ?>
							<a href="<?php echo $this->url('leave', array('action'=>'encashmentdtl', 'id'=>$encash));?>" class="btn btn-info btn-xs"> 
								<i class="fa fa-eye"></i> Veiw Encashment </a><?php endif;?>
						</ul>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<table class="table table-striped table-bordered table-condensed">	
							<thead>
								<th style="font-size:14px">Location</th>
								<th style="font-size:14px">Head Name</th>
								<th style="font-size:14px">Sub Head Account</th>
								<th style="font-size:14px">Amount Dr</th>
								<th style="font-size:14px">Amount Cr</th>
							</thead>
							<tbody>
								<?php $total_debit =0; $total_credit=0;?>
								<?php foreach($this->transactiondetails as $tdrow):?>
									<tr>
										<td style="font-size:13px; font-famiyl:Times New Roman"><?php echo $tdrow['location'];?></td>
										<td style="font-size:13px"><?php echo $tdrow['head'];?></td>
										<td style="font-size:13px"><?php echo $tdrow['sub_head'].'-'.$tdrow['sub_head_name'];?></td>
										<td style="font-size:13px; text-align:right"><?php echo $tdrow['debit'];?></td>
										<td style="font-size:13px; text-align:right"><?php echo $tdrow['credit'];?></td>
									</tr>
									<?php 
										$total_debit += $tdrow['debit'];
										$total_credit += $tdrow['credit'];
									?>
								<?php endforeach;?>
								<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
									<th colspan="3" style="font-size:13px"> Total : </th>
									<th style="font-size:13px; text-align:right"><?php  echo number_format((float)$total_debit, 2, '.', ',');?></th>
									<th style="font-size:13px; text-align:right"><?php  echo number_format((float)$total_credit, 2, '.', ',');?></th>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<br/>
				<div class="row">
					<div class="col-lg-3"></div>
					<div class="col-lg-6">
					   &nbsp; 
					</div>
					<div class="col-lg-3">
						<?php 
						if($status < 3)://status 3- pending?>
							<?php echo $this->button(3, $id);?>
							<?php 
						elseif($status==3||$status==18):
							if($role==6 || $role==100)://approvr edit option?>
							<?php echo $this->button(3, $id);
							 echo $this->button(1, $id);
							//if($doc_id=="Payroll"):?>
								<!-- <div class="btn-list">
									<a class="btn btn-primary"  href="<?php echo $this->url('transaction', array('action' => 'editagainstpayroll', 'id'=>$id)); ?>">
										<i class="fa fa-edit?>"></i>Edit
									</a>
							</div> -->
							<?php 
							//else:?>
								<!-- <div class="btn-list">
									<a class="btn btn-primary"  href="<?php echo $this->url('transaction', array('action' => 'editagainstdebit', 'id'=>$id)); ?>">
										<i class="fa fa-edit?>"></i>Edit
									</a>
							</div> -->
							<?php //endif  
							else:
							endif;
						endif;?>
					</div>
				</div>
				<?php echo $this->partial('partial/attachment.phtml', array('process' => '1311', 'process_id'=> $row['id'], 'applicationNO'=>$row['voucher_no'], 'login_id' =>'','status'=>$status));//$login_id?>
				<div class="row" id="convert-tb0">
					<div class="col-lg-4" id="convert-tb1">
						<ul class="list-unstyled spaced pull-left">
							<li>
								<label style="font-size:13px"> Prepared by:<strong> <?php echo $this->userObj->getColumn($author,'name');?> </strong>on:(<i><?php echo $created?></i>)</label>
							</li>
						</ul>
					</div>
					<div class="col-lg-4" id="convert-tb2">
						<?php if($voucher_id == 8):?>
						<ul class="list-unstyled spaced center"><li><label> Received By Signatory </label></li></ul>
						<?php endif;?>
					</div>
					<div class="col-lg-4" id="convert-tb3">
						<ul class="list-unstyled spaced pull-right">
							<li>
								<label> Authorized Signatory </label>
							</li>
						</ul>
					</div>
					<div class="col-lg-4" id="convert-tb1"></div>
					<div class="col-lg-4" id="convert-tb2"></div>
					<div class="col-lg-4" id="convert-tb3">
						<div class="col-auto ms-auto d-print-none pull-right">
							<div class="btn-list">
								<?php 
								if(sizeof($current_flow) > 0 && $edit_option==1):
									foreach($current_flow as $flow);
									$actions = explode('|', $flow['action']);
									for($i=0; $i < sizeof($actions); $i++):
										$buttons = $this->flowactionObj->get($actions[$i]);
										foreach($buttons as $button):?>
										<span data-bs-toggle='tooltip' data-bs-placement='top' title='<?php echo $button['action']; ?>'>
										<a class="btn <?php echo $button['class']; ?>" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('transaction', array('action' => 'processr', 'id'=>$row['id'].'-'.$button['id'].'-'.$flow['id'])); ?>">
											<i class="icon <?php echo $button['icon'];?>"></i><?php echo $button['action']; ?>
										</a></span>
										<?php
										endforeach;
									endfor;
								endif;?>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice3({
		content: '#report-print',
		src:"<?php echo $this->url('print', array('action' => 'index'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>
