<?php
/**
 * 
 * View -- of Accounts/ChartaccountController/editjournalAction
 * 
 */
?>
<?php 
    foreach($this->journal as $journal):
        extract($journal);        
		//echo $journal;
    endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('pchartaccount', array('action' => 'editjournal', 'id' => $id)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Journal</h4>
    </div> <!-- /modal-header -->
    <div class="modal-body">       
	    <div class="panel panel-default">                       
	    	<div class="panel-body"> 
	        	<div class="row">  
					<div class="col-lg-12"> 
					    <div class="form-group">
							<label for="voucher_main" class="control-label">Parent Voucher</label>
							<select id="voucher_main" name="voucher_main" class="form-control" data-placeholder="Select" required >
								<option value=""></option>
								<?php 
								foreach ($vouchers as $pv):
								$selected = ($voucher_main == $pv['id'])?'selected':'';
								?>
									<option value="<?php echo $pv['id'];?>" <?php echo $selected;?>>
									<?php echo $pv['name'];?>
									</option>
								<?php 
								endforeach;
								?>
							</select>
						</div> 
						<div class="form-group" class="control-label">
							<label for="voucher">Journal</label>
							<input type="text" class="form-control" name="voucher" id="voucher" value="<?php echo $journal;?>" size="30" placeholder="Journal" required > 
						</div>  
						<div class="form-group" class="control-label">
							<label for="prefix">Prefix</label>
							<input type="text" class="form-control" name="prefix" id="prefix" value="<?php echo $prefix;?>" size="30" placeholder="Prefix" required > 
						</div>     
					</div>   
				</div>
	    	</div>
		</div>
	</div> <!-- /modal-body -->    
	<div class="modal-footer">
	    <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
	    <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
	</div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			code: {
				validators: {
					notEmpty: {
						message: 'Please provide Code.'
					}
				}
			},
			journal: {
				validators: {
					notEmpty: {
						message: 'Please provide Journal.'
					}
				}
			},
			prefix: {
				validators: {
					notEmpty: {
						message: 'Please select Prefix.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>