<?php
/**
 * 
 * View -- of Accounts/ChartaccountController/editheadtypeAction
 * 
 */
?>
<?php 
    foreach($this->partyrole as $partyrole):
        extract($partyrole);        
    endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('pchartaccount', array('action' => 'editpartyrole', 'id' => $id)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Party Role</h4>
    </div>  <!-- /modal-header -->
    
    <div class="modal-body">       
      <div class="panel panel-default">                       
        <div class="panel-body"> 
			<div class="row"> 
				<div class="col-lg-12"> 
					<div class="form-group">
						<label for="role" class="control-label">Party Role</label>
						<input type="text" class="form-control" name="role" id="role" value="<?php echo $role;?>" size="30" required > 
					</div>   
				</div>    
			</div>    
        </div>
      </div>
    </div> <!-- /modal-body -->    
  <div class="modal-footer">
    <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
    <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
  </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			role: {
				validators: {
					notEmpty: {
						message: 'Please provide Party role.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>