<STYLE TYPE="text/css">
TD{font-size:8pt;}
</STYLE>
<?php
	$this->headTitle($this->title);	
?>
<?php echo $this->partial('purchase/report/partial.phtml', array('active' => 'prn')); ?><br/>
<div class="pull-right tableTools-container"></div>		
<div class="row">
	<div class="col-lg-12">					
		<form id="#form" method="post" action="<?php echo $this->url('purreport', array('action' => 'prdetails')); ?>"  enctype="multipart/form-data" >    
			<div class="row">						
				<div class="form-group col-lg-3">
					<label class="control-label" for="activity">Activity</label>
					<select class="form-control" name="activity" id="activity" data-placeholder="Select activity" >
						<option value="all">All</option>
						<?php  		
							foreach ($this->activities as $activity):	
							 $act_selected = ($activity['id'] == $this->activity)?"selected":"";									
						?>
							<option value="<?php echo $activity['id']; ?>" <?php echo $act_selected; ?>>
								<?php echo $activity['activity']; ?>
							</option>
						<?php endforeach;?>
					</select>
				</div>			
				<div class="form-group col-lg-3">
					<label class="control-label" for="supplier">Suppliers</label>
					<select class="form-control" name="supplier" id="supplier" data-placeholder="Select Supplier" >
						<option value="all">All</option>
						<?php  
							$suppliers = $this->partyObj->get(array('p.role'=>1));
							foreach ($suppliers as $supplier):	
                            $sup_selected = ($supplier['id'] == $this->supplier)?"selected":"";							
						?>  <option value="<?php echo $supplier['id']; ?>" <?php echo $sup_selected; ?>>
								<?php echo $supplier['name']; ?>
							</option>
						<?php endforeach;?>
					</select>
				</div>		
				<div class="col-lg-2">
					<div class="form-group">
						<label for="start_date" class="control-label">Start Date</label>
						<div class="date input-group" id="start_date" data-date-format="yyyy-mm-dd" >
							<input class="form-control span2" name="start_date" id="start_date" value="<?php echo $this->start_date;?>" type="text" placeholder="Start Date" readonly required>
							<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>
				<div class="col-lg-2">
					<div class="form-group">
						<label for="end_date" class="control-label">End Date</label>
						<div class="date input-group" id="end_date" data-date-format="yyyy-mm-dd" >
							<input class="form-control span2" name="end_date" id="end_date" value="<?php echo $this->end_date;?>" type="text" placeholder="End Date" readonly required>
							<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
				</div>
				<div class="col-lg-1"></div>
				<div class="col-lg-1">
					<div class="space-8"></div>
					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>Refresh</button>
				</div>
			</div>
		</form>
				
		<table class="table table-striped table-bordered table-hover bafra-table-medium" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>PRN No.</th>
					<th>PRN Date</th>
					<th>PO. No</th>
					<th>Activity</th>
					<th>Supplier</th>
					<th>Challan No</th>
					<th>Item</th>
					<th>UOM</th>
					<th>Challan Qty</th>
					<th>Accepted Qty</th>
					<th>Sound Qty</th>				
					<th>Challan Rate</th>
					<th>Note</th>
				</tr>
			</thead>
			<tbody>
				<?php $i = 1; 
				   foreach($this->results as $row):  //echo"<pre>"; print_r($row); exit;  ?>
				      <tr>
					      <td><?php echo $i++; ?></td>
					      <td><?php echo $row['prn_no']; ?></td>
						  <td><?php echo $row['prn_date']; ?></td>
						  <td><?php echo $this->POObj->getColumn($row['purchase_order'],'po_no'); ?></td>
						  <td><?php echo $this->activityObj->getColumn($row['activity'],'activity'); ?></td>
						  <td><?php echo $this->partyObj->getColumn($row['supplier'],'name'); ?></td>
						  <td><?php echo $row['challan_no']; ?></td>
						  <td><?php echo $this->itemObj->getColumn($row['item'],'code'); ?></td>
						  <td><?php echo $this->uomObj->getColumn($row['uom'],'code'); ?></td>
						  <td><?php echo number_format($row['challan_qty'], 3, '.', ','); ?></td>
						  <td><?php echo number_format($row['accept_qty'], 3, '.', ','); ?></td>
						  <td><?php echo number_format($row['sound_qty'], 3, '.', ','); ?></td>
						  <td>
						  <?php $supplier_Inv = $this->supInvObj->getColumn(array('purchase_receipt'=>$row['purchase_receipt']),'id');
 						        if($supplier_Inv > 0 ){
									$rate = $this->supInvDtlObj->getColumn(array('item'=>$row['item'],'supplier_invoice'=>$supplier_Inv),'rate');
									echo number_format($rate,3,'.',','); 
								}else{
									echo"NA";
								} ?></td>
						  <td><?php echo $row['note']; ?></td>
					  </tr>
				<?php endforeach; ?>
			</tbody>
		</table>				
	</div>
</div>
<script type="text/javascript">
	/*$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});*/
	$(function() {
		$('#start_date').datepicker();
		$('#start_date').on('changeDate', function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').datepicker();
		$('#end_date').on('changeDate', function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#dataTables').DataTable({
		"paging":   true,
	});
	/*** Form Validation ***/
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'supplier': {
				validators: {
					notEmpty: {
						message: 'Please select supplier'
					}
				}
			},
			'from_location': {
				validators: {
					notEmpty: {
						message: 'Please select source location'
					}
				}
			},
			'to_location': {
				validators: {
					notEmpty: {
						message: 'Please select destination location'
					}
				}
			},
			'start_date': {
				validators: {
					notEmpty: {
						message: 'Please select start date'
					}
				}
			},
			'end_date': {
				validators: {
					notEmpty: {
						message: 'Please select end date'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>

