<?php
/**
 * View -- of Purchase/PurchaseController/addporderAction
 */
  $this->headTitle($this->title);
?>
<?php echo $this->partial('store/issue/partial.phtml', array('active' => 'issue')); ?> <br/>
<?php
	$subRoles = $this->userRoleObj->get(array('user'=>$this->userID, 'subrole'=>array('15'))); 
	$depoyManager = $this->userRoleObj->get(array('user'=>$this->userID, 'subrole'=>array('9'))); 
	if(sizeof($subRoles) > 0 || (sizeof($depoyManager)>0 )){
		/* checks whether the user is admin, CEO, FECD Manager || user belongs to source or Destination Location or depoy Manager */
		$flag = true; 
	}	
	else{ 
	   $flag = false; 
	}
	if($flag):
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i>&nbsp;&nbsp;New Issue
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('inissue', array('action' => 'addissue')); ?>"  enctype="multipart/form-data" >    
						<div class="row">	
							<div class="col-lg-3">    
								<div class="form-group">
									<label for="issue_date" class="control-label">Issue Date</label>
									<div class="date input-group" id="issue_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="issue_date" id="issue_date" type="text" value="<?php echo date('Y-m-d');?>" placeholder="Dispatch Date" >								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="from_location" class="control-label">Source Location</label>
									<select id="from_location" name="from_location" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
										<?php 
											foreach($admin_locs as $admin_loc):
										?>
											<?php $selected = ($admin_loc['id'] == $user_location)?"selected":"";?>
											<option value="<?php echo $admin_loc['id'];?>" <?php echo $selected; ?>>
												<?php echo $admin_loc['location'];?>
											</option>
										<?php endforeach;?>										 
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="to_location" class="control-label">Destination Location</label>
									<select id="to_location" name="to_location" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
									  <?php 
										$regions = $this->regionObj->getAll();
										foreach ($regions as $region): ?>
										<optgroup label="<?php echo $region['region'];?>">
											<?php  
												 // retrive locations under the above region ID
												$locations = $locationObj->get(array('l.region'=>$region['id'],'l.location_type'=>array(1,2,7,4,8,3,5,6)));												 foreach ($locations as $location):?>
											 <option value="<?php echo $location['id']; ?>">
												<?php echo $location['location']; ?>
											 </option>
											<?php 
											 endforeach;
											?>
									  </optgroup>
									 <?php endforeach;  ?>	
									</select> 
								</div>
							</div>	
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="activity" class="control-label">Activity</label>
									<select id="activity" name="activity" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($this->activities as $activity):?>
											   <option value="<?php echo $activity['id'];?>"><?php echo $activity['activity']; ?></option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>		
						</div>
						<div class="row">
						    <div class="col-lg-3"> 
								<div class="form-group">
									<label for="item_group" class="control-label">Item Group</label>
									<select id="item_group" name="item_group" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($this->itemgroupObj->getAll() as $group):?>
											   <option value="<?php echo $group['id'];?>"><?php echo $group['name']; ?></option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="fcb_transport" class="control-label">FCB Transport</label>
									<div class="radio">
										<label>
											<input class="ace" type="radio" name="fcb_transport" id="fcb_transport" value="1" />
											<span class="lbl"> Yes </span>
										</label>
										<label>
											<input class="ace" type="radio" name="fcb_transport" id="fcb_transport" value="0" checked />
											<span class="lbl"> No </span>
										</label>
									</div>
								</div>
							</div> 
							<div class="col-lg-3" id="fcb">
								<div class="form-group">
									<label for="transporter_fcb" class="control-label">Name of Driver</label>
									<select class="form-control" name="transporter_fcb" id="transporter_fcb" data-placeholder="Select" > 
										<option value=""></option>
										<?php foreach($employee_driver as $emp):?>
											<option value="<?php echo $emp['id'];?>">
												<?php echo $emp['full_name'];?> (<?php echo $emp['designation']; ?>)
											</option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="col-lg-3" id="non_fcb">
								<div class="form-group">
									<label for="transporter_nonfcb" class="control-label">Name of Driver</label>
									<input type="text" class="form-control" name="transporter_nonfcb" id="transporter_nonfcb" placeholder="Name of Driver" > 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="vehicle_no" class="control-label">Vehicle No.</label>
									<input type="text" class="form-control" name="vehicle_no" id="vehicle_no" placeholder="Vehicle No." required/> 
								</div>
							</div>	
						</div>
						<div class="row">
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="party" class="control-label">Transpoter</label>
									<select id="party" name="party" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
										<?php foreach ($this->parties as $party): ?>
											<option value="<?php echo $party['id'];?>">
												<?php echo $party['name']; ?>
											</option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>						
						</div>
						<div class="row">
						   <div class="col-lg-12"> 
							  <h5>Issue Details</h5>
								 <div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Item</th>
												<th>Asset/Store Spare</th>
												<th>UOM</th>
												<th>Qty Rate</th>
												<th>Source Qty</th>
												<th>Destination Qty</th>
												<th>Issue Qty</th>
												<th>Amount</th>
												<th>Remarks</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>
													<div class="form-group">
														<select id="item" name="item[]" class="form-control"  data-placeholder="Select" required>
															<option value=""></option>								
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="assetssp" name="assetssp[]" class="form-control" data-placeholder="Select" required>
															<option value=""></option>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control" data-placeholder="Select" readonly required>
															<option value=""></option>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
												        <input name="rate[]" id="rate" type="text" class="form-control" value="0.00" readonly required />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="from_balance[]" id="from_balance" type="text" class="form-control" value="0.00" readonly required />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="to_balance[]" id="to_balance" type="text" class="form-control" value="0.00" readonly />  
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="quantity[]" id="quantity" type="text" class="form-control" value="0.00"required />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="amount[]" id="amount" type="text" class="form-control" placeholder="Amount" />
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input name="remarks[]" id="remarks" type="text" class="form-control" placeholder="Remarks" />
													</div>         
												</td>
												<td></td>											
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="row">    
							<div class="col-lg-12">
								<div class="col-lg-9"></div>
								<div class="form-group col-lg-3">
									<label for="payable_amount" class="control-label">Payable Amount</label>
									<input type="text" class="form-control" name="payable_amount" id="payable_amount"  value="0.00" readonly required>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" >
									<i class="fa fa-times"></i> Cancel 
								</button> 					
							</div>
						</div>
					</form>	
				</div><!-- widget widget-main -->
			</div>  <!-- widget widget-body -->   
		</div> <!-- widget widget-box --> 
	</div><!-- col-lg-12 -->
</div><!-- row -->
<?php else: ?> 
    <div class="alert alert-success fade in"> 
	    You don't have privilege to add new dispatch. 
	</div>
<?php endif; ?>
<script type="text/javascript">
$(function() {	
$('#issue_date').datepicker();
	$('#issue_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$("#vehicle_no").bind('keyup', function (e) {
		if (e.which >= 97 && e.which <= 122) {
			var newKey = e.which - 32;
			// I have tried setting those
			e.keyCode = newKey;
			e.charCode = newKey;
		}
		$("#vehicle_no").val(($("#vehicle_no").val()).toUpperCase());
	});
	$("#transporter_nonfcb").bind('keyup', function (e) {
		if (e.which >= 97 && e.which <= 122) {
			var newKey = e.which - 32;
			// I have tried setting those
			e.keyCode = newKey;
			e.charCode = newKey;
		}
		$("#transporter_nonfcb").val(($("#transporter_nonfcb").val()).toUpperCase());
	});
	/*** onChange of fcb_transport ***/
	if($('input[name="fcb_transport"]:checked').val() == '0'){
		$("div#fcb").hide();
		$("div#non_fcb").show();
	}else{
		$("div#fcb").show();
		$("div#non_fcb").hide();
	}
	$("input[name='fcb_transport']").change(function(e){
		if($(this).val() == '0') {
			$("div#fcb").hide();
			$("div#non_fcb").show();
			$('select#transporter_fcb option:selected').removeAttr('selected');
			$("select#transporter_fcb").trigger("chosen:updated");
			$('select#party option:selected').removeAttr('selected');
			$("select#party").trigger("chosen:updated");
		} else {
			$("div#fcb").show();
			$("div#non_fcb").hide();
			$("input[name='transporter_nonfcb']").val('');
			$('select#party option:selected').removeAttr('selected');
			$('select#party option[value=323]').attr('selected', 'selected');
			$("select#party").trigger("chosen:updated");
		}
	});
	$('#dispatch_date').datepicker();
	$('#dispatch_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#trdetails_table').issue({
		getToLocation:'<?php echo $this->url('inissue', array('action' => 'gettolocation'));?>',
		getItem:'<?php echo $this->url("inissue", array("action" => "getitemgroup"));?>',
		getDetails:'<?php echo $this->url("inissue", array("action" => "getdetails"));?>',
		getStockBalance:'<?php echo $this->url("inissue", array("action" => "getstockbalance"));?>',
	});

	/*** Form Validation ***/   
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				dispatch_date: {
					validators: {
						notEmpty: {
							message: 'Please select dispatch date.'
						},
					},
				},
				from_location: {
					validators: {
						notEmpty: {
							message: 'Please select source location.'
						}
					}
				}, 
				to_location: {
					validators: {
						notEmpty: {
							message: 'Please select destination location.'
						}
					}
				},
				activity: {
					validators: {
						notEmpty: {
							message: 'Please select activity.'
						}
					}
				},
				fcb_transport:{
					validators: {
						notEmpty: {
							message: 'Please provide fcb transport'
						}
					}
				},
				/*'transporter':{
					validators: {
						notEmpty: {
							message: 'Please provide name of driver.'
						}
					}
				},*/
				vehicle_no:{
					validators: {
						notEmpty: {
							message: 'Please provide vechile no.'
						}
					}
				},
				party:{
					validators: {
						notEmpty: {
							message: 'Please select transporter.'
						}
					}
				},
				item[]: {
					validators: {
						notEmpty: {
							message: 'Please select item.'
						}
					}
				},
				/*'batch[]': {
					validators: {
						notEmpty: {
							message: 'Please provide batch.'
						}
					}
				},*/
				from_balance[]: {
					validators: {
						greaterThan: {
							value: '1',
							message: 'The source quantity must be greater than 0'
						}
					}
				},
				uom[]: {
					validators: {
						notEmpty: {
							message: 'Please select uom.'
						}
					}
				},
				quantity[]: {
					validators: {
						notEmpty: {
							message: 'Please provide quantity.'
						},
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});

});
</script>
