<?php
/**
 * View -- of Stock/DispatchController/editdispatchAction
 */
  $this->headTitle($this->title);

?>
<?php echo $this->partial('store/issue/partial.phtml', array('active' => 'issue')); ?> <br/>
<?php
	foreach($issues as $issue):
		//echo "<pre>"; print_r($issue);
		extract($issue);
		$issue_id = $id;
		$issue_activity = $cost_center;
		$issue_party = $party;
		$issue_item_group = $item_group;
		$issue_status = $status;
	endforeach; //exit;
?>
<?php
 $subRoles = $this->userRoleObj->get(array('user'=>$this->userID, 'subrole'=>array('15'))); 
 $depoyManager = $this->userRoleObj->get(array('user'=>$this->userID, 'subrole'=>array('9'))); 
 if($issue_status != '10' && $this->user_location == $from_location && sizeof($depoyManager)>0 || sizeof($subRoles)>0): 
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;&nbsp;&nbsp;Edit Issue : &nbsp;
					<strong><?php echo $challan_no; ?> | <?php echo $this->activityObj->getColumn($activity,'activity'); ?></strong>&nbsp;
					<?php $this->status($status);?>
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('inissue', array('action' => 'editissue')); ?>"  enctype="multipart/form-data" >    
						<div class="row">	
							<div class="col-lg-3">    
								<div class="form-group">
									<input type="hidden" name="issue_id" id="issue_id" value="<?php echo $issue_id;?>"/>
									<label for="issue_date" class="control-label">Issue Date</label>
									<div class="date input-group" id="issue_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="issue_date" id="issue_date" value="<?php echo $issue_date;?>" type="text" placeholder="Issue Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="from_location" class="control-label">Source Location</label>
									<select id="from_location" name="from_location" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
										<?php 
											foreach($admin_locs as $admin_loc):
										?>
											<?php $selected = ($admin_loc['id'] == $user_location)?"selected":"";?>
											<option value="<?php echo $admin_loc['id'];?>" <?php echo $selected; ?>>
												<?php echo $admin_loc['location'];?>
											</option>
										<?php endforeach;?>										 
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="to_location" class="control-label">Destination Location</label>
									<select id="to_location" name="to_location" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
									  <?php 
										$regions = $this->regionObj->getAll();
										foreach ($regions as $region): ?>
										<optgroup label="<?php echo $region['region'];?>">
											<?php  
												$locations = $locationObj->get(array('l.region'=>$region['id'],'l.location_type'=>array(1,2,7,8,3,4,5,6)));
										 		foreach ($locations as $location):
										 			$selected_to = ($location['id']==$to_location)?"selected":"";
											?>
											 <option value="<?php echo $location['id']; ?>" <?php echo $selected_to;?>>
												<?php echo $location['location']; ?>
											 </option>
											<?php endforeach;?>
									  </optgroup>
									 <?php endforeach; ?>									
									</select> 
								</div>
							</div>	
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="activity" class="control-label">Activity</label>
									<select id="activity" name="activity" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php 
											$activities = $this->activityObj->getAll();
											foreach ($activities as $activity):
												$selected_activity = ($activity['id']==$issue_activity)?"selected":"";
										?>
									   	<option value="<?php echo $activity['id'];?>" <?php echo $selected_activity;?>>
									   		<?php echo $activity['activity']; ?>
								   		</option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>		
						</div>
						<div class="row">
						    <div class="col-lg-3"> 
								<div class="form-group">
									<label for="item_group" class="control-label">Item Group</label>
									<select id="item_group" name="item_group" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($this->groupObj->getAll() as $group):
										    	$selected_itemgroup = ($group['id']==$issue_item_group)?"selected":"";?>
											   <option value="<?php echo $group['id'];?>" <?php echo $selected_itemgroup;?> ><?php echo $group['name']; ?></option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="fcb_transport" class="control-label">FCB Transport</label>
									<div class="radio">
									<?php
										$checked1 = ($fcb_transport == 1)?"checked":"";
										$checked2 = ($fcb_transport == 0)?"checked":"";
									?>
										<label>
											<input class="ace"type="radio" name="fcb_transport" id="fcb_transport" value="1" <?php echo $checked1;?>/>
											<span class="lbl"> Yes </span>
										</label>
										<label>
											<input class="ace" type="radio" name="fcb_transport" id="fcb_transport" value="0" <?php echo $checked2;?> />
											<span class="lbl"> No </span>
										</label>
									</div>
								</div>
							</div> 
							<div class="col-lg-3" id="fcb">
								<div class="form-group">
									<label for="transporter_fcb" class="control-label">Name of Driver</label>
									<select class="form-control" name="transporter_fcb" id="transporter_fcb" data-placeholder="Select" > 
										<option value=""></option>
										<?php foreach($employee_driver as $emp):
												$selected_emp = ($emp['id'] == $transporter)?"selected":"";?>
											<option value="<?php echo $emp['id'];?>" <?php echo $selected_emp;?>>
												<?php echo $emp['full_name'];?> (<?php echo $emp['designation']; ?>)
											</option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="col-lg-3" id="non_fcb">
								<div class="form-group">
									<label for="transporter_nonfcb" class="control-label">Name of Driver</label>
									<input type="text" class="form-control" name="transporter_nonfcb" id="transporter_nonfcb" value="<?php echo $transporter;?>" placeholder="Name of Driver" > 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="vehicle_no" class="control-label">Vehicle No.</label>
									<input type="text" class="form-control" name="vehicle_no" id="vehicle_no" value="<?php echo $vehicle_no;?>" placeholder="Vehicle No."> 
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="party" class="control-label">Party</label>
									<select id="party" name="party" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
										<?php 
											foreach ($parties as $party):
												$selected_party = ($party['id']==$issue_party)?"selected":""; 
										?>
											<option value="<?php echo $party['id'];?>" <?php echo $selected_party;?>>
												<?php echo $party['name']; ?>
											</option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>							
						</div>
						<div class="row">
						   <div class="col-lg-12"> 
							  <h5>Issue Details</h5>
								 <div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Item</th>
												<?php if($item_group == 1):?>
												<th>Asset</th>
												<?php else: ?>
												<th>Store and Spare</th>
												<?php endif; ?>
												<th>UOM</th>
												<th>Rate</th>
												<th>(Source Qty)</th>
												<th>(Destination Qty)</th>
												<th>Issued Qty</th>
												<th>Amount</th>
												<th>Remarks</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<?php 
												$issue_details = $this->issue_detailsObj->get(array('issue'=>$issue_id));
												if(sizeOf($issue_details)>0):
												   //echo "<pre>"; print_r($issue_details); exit;
													foreach($issue_details as $details):
													$items = $this->itemObj->get($details['item_id']);
													foreach($items as $item);
													//echo "<pre>"; print_r($item); exit;
													if($item['item_group_id'] == 1):
													$its = $this->assetObj->getDispatchItems(array('a.status'=>'3','ad.location'=>$user_location));
													//print_r($codes); exit;
												    else:
													$its = $this->sspObj->getDispatchItems(array('ssp.status'=>'3','sspd.location'=>$user_location));
		                                            endif;
											?>
											<tr>
												<td>
													<div class="form-group">
														<select id="item" name="item[]" class="form-control"  data-placeholder="Select" required>
															<option value=""></option>	
															<?php
																foreach($its as $it):
																	$selected_item = ($it['item_id']==$details['item_id'])?"selected":"";?>
																	<option value="<?php echo $it['item_id'];?>" <?php echo $selected_item;?>>
																		<?php echo $it['name'];?>
																	</option>
															<?php endforeach; ?>
														</select>
													</div>
													<input type="hidden" name="details_id[]" id="details_id" value="<?php echo $details['id'];?>"/>
												</td>
												<?php if($item['item_group_id'] == 1):
													$assets = $this->assetObj->getIssuesAsset(array('a.item'=>$details['item_id'],'ad.location'=>$user_location));?>
												<td>
													<div class="form-group">
														<select id="assetssp" name="assetssp[]" class="form-control"  data-placeholder="Select" required>
															<option value=""></option>
															<?php
															foreach($assets as $asset): 
																$selected_assetssp = ($asset['id']==$details['assetssp'])?"selected":"";
															?>
																<option value="<?php echo $asset['id'];?>" <?php echo $selected_assetssp;?>>
																	<?php echo $asset['asset'];?>
																</option>
															<?php 		
																endforeach;
															?>
														</select>
													</div>
												</td>
												<?php else: 
												$ssps = $this->sspObj->getIssuesSsp(array('ssp.item'=>$details['item_id'],'sspd.location'=>$user_location));?>
												<td>
													<div class="form-group">
														<select id="assetssp" name="assetssp[]" class="form-control"  data-placeholder="Select" required>
															<option value=""></option>
															<?php
															foreach($ssps as $ssp): 
																$selected_assetssp = ($ssp['id']==$details['assetssp'])?"selected":"";
															?>
																<option value="<?php echo $ssp['id'];?>" <?php echo $selected_assetssp;?>>
																	<?php echo $ssp['storespare'];?>
																</option>
															<?php 		
																endforeach;
															?>
														</select>
													</div>
												</td>
												<?php endif; ?>
												<td>
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control" data-placeholder="Select" required>
															<option value=""></option>
															    <?php foreach($this->uomObj->getAll() as $uom):
																$selected_uom = ($uom['id'] == $details['uom'])?"selected":"";
																?>
																<option value="<?php echo $uom['id'];?>" <?php echo $selected_uom;?>>
																	<?php echo $uom['code'];?>
																</option>
																<?php endforeach;?>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
												        <input name="rate[]" id="rate" type="text" class="form-control" value="<?php echo $details['rate'];?>" readonly required />
													</div>
												</td>
												<?php
													$selected_item = $this->itemObj->get($details['item_id']);
													foreach($selected_item as $item);
													if($item['item_group']==1):
														$from_quantity = $this->asset_detailsObj->getColumn(array('asset'=>$details['assetssp'],'location'=>$from_location),'quantity');
														$to_quantity = $this->asset_detailsObj->getColumn(array('asset'=>$details['assetssp'],'location'=>$to_location),'quantity');
													else: 
														$from_quantity = $this->ssp_detailsObj->getColumn(array('storespare'=>$details['assetssp'],'location'=>$from_location),'quantity');
														$to_quantity = $this->ssp_detailsObj->getColumn(array('storespare'=>$details['assetssp'],'location'=>$to_location),'quantity');
													endif;
												?>
												<td>
													<div class="form-group">
														<input name="from_balance[]" id="from_balance" type="text" class="form-control" value="<?php echo $from_quantity;?>" data-old-from_balance="<?php echo $from_quantity;?>" readonly />  
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="to_balance[]" id="to_balance" type="text" class="form-control" value="<?php echo $to_quantity;?>" data-old-to_balance="<?php echo $to_quantity; ?>" readonly />  
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="quantity[]" id="quantity" type="text" class="form-control" value="<?php echo $details['quantity'];?>" required>
													</div>
												</td>
                                                <td>
													<div class="form-group">
														<input name="amount[]" id="amount" type="text" class="form-control" value ="<?php echo $details['amount'];?>"placeholder="Amount" />
													</div>         
												</td>												
												<td>
													<div class="form-group">
														<input name="remarks[]" id="remarks" type="text" class="form-control" placeholder="Remarks" value="<?php echo $details['remarks'];?>" />
													</div>         
												</td>
												<td></td>											
											</tr>
											<?php 
													endforeach;
												endif;
											?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="row">    
							<div class="col-lg-12">
								<div class="col-lg-9"></div>
								<div class="form-group col-lg-3">
									<label for="payable_amount" class="control-label">Payable Amount</label>
									<input type="text" class="form-control" name="payable_amount" id="payable_amount"  value="<?php echo $total_amount;?>" readonly required>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" >
									<i class="fa fa-times"></i> Cancel 
								</button> 					
							</div>
						</div>
					</form>	
				</div><!-- widget widget-main -->
			</div><!-- widget widget-body -->   
		</div><!-- widget widget-box --> 
	</div><!-- col-lg-12 -->
</div><!-- row -->
<?php
endif; 
?>
<script type="text/javascript">
$(function() {	
	$("#vehicle_no").bind('keyup', function (e) {
		if (e.which >= 97 && e.which <= 122) {
			var newKey = e.which - 32;
			// I have tried setting those
			e.keyCode = newKey;
			e.charCode = newKey;
		}
		$("#vehicle_no").val(($("#vehicle_no").val()).toUpperCase());
	});
	$("#transporter_nonfcb").bind('keyup', function (e) {
		if (e.which >= 97 && e.which <= 122) {
			var newKey = e.which - 32;
			// I have tried setting those
			e.keyCode = newKey;
			e.charCode = newKey;
		}
		$("#transporter_nonfcb").val(($("#transporter_nonfcb").val()).toUpperCase());
	});
	/*** onChange of fcb_transport ***/
	if($('input[name="fcb_transport"]:checked').val() == '0'){
		$("div#fcb").hide();
		$("div#non_fcb").show();
	}else{
		$("div#fcb").show();
		$("div#non_fcb").hide();
	}
	$("input[name='fcb_transport']").change(function(e){
		if($(this).val() == '0') {
			$("div#fcb").hide();
			$("div#non_fcb").show();
			$('select#transporter_fcb option:selected').removeAttr('selected');
			$("select#transporter_fcb").trigger("chosen:updated");
			$('select#party option:selected').removeAttr('selected');
			$("select#party").trigger("chosen:updated");
		} else {
			$("div#fcb").show();
			$("div#non_fcb").hide();
			$("input[name='transporter_nonfcb']").val('');
			$('select#party option:selected').removeAttr('selected');
			$('select#party option[value=323]').attr('selected', 'selected');
			$("select#party").trigger("chosen:updated");
		}
	});
	
	$('#issue_date').datepicker();
	$('#issue_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#trdetails_table').issue({
		getToLocation:'<?php echo $this->url('inissue', array('action' => 'gettolocation'));?>',
		getItem:'<?php echo $this->url("inissue", array("action" => "getitemgroup"));?>',
		getDetails:'<?php echo $this->url("inissue", array("action" => "getdetails"));?>',
		getStockBalance:'<?php echo $this->url("inissue", array("action" => "getstockbalance"));?>',
	});

	/*** Form Validation ***/  
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				dispatch_date: {
					validators: {
						notEmpty: {
							message: 'Please select dispatch date.'
						},
					},
				},
				from_location: {
					validators: {
						notEmpty: {
							message: 'Please select source location.'
						}
					}
				}, 
				to_location: {
					validators: {
						notEmpty: {
							message: 'Please select destination location.'
						}
					}
				},
				activity: {
					validators: {
						notEmpty: {
							message: 'Please select activity.'
						}
					}
				},
				fcb_transport:{
					validators: {
						notEmpty: {
							message: 'Please provide fcb transport'
						}
					}
				},
				/*'transporter':{
					validators: {
						notEmpty: {
							message: 'Please provide name of driver.'
						}
					}
				},*/
				vehicle_no:{
					validators: {
						notEmpty: {
							message: 'Please provide vechile no.'
						}
					}
				},
				party:{
					validators: {
						notEmpty: {
							message: 'Please select transporter.'
						}
					}
				},
				item[]: {
					validators: {
						notEmpty: {
							message: 'Please select item.'
						}
					}
				},
				/*'batch[]': {
					validators: {
						notEmpty: {
							message: 'Please provide batch.'
						}
					}
				},*/
				from_balance[]: {
					validators: {
						greaterThan: {
							value: '1',
							message: 'The source quantity must be greater than 0'
						}
					}
				},
				uom[]: {
					validators: {
						notEmpty: {
							message: 'Please select uom.'
						}
					}
				},
				quantity[]: {
					validators: {
						notEmpty: {
							message: 'Please provide quantity.'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});  
});
</script>
