<?php
/**
 * View -- of Store/issueController/editstockopeningdetailAction
 */
?>
<?php foreach($openingdtls as $detail);?>
<form id="#form" method="post" action="<?php echo $this->url('inissue', array('action' => 'editassetopeningdetail')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> 
			<i class="fa fa-pencil-square-o"></i> Edit Opening Details : <strong> <?php echo $this->locationObj->getColumn($detail['location'],'location');?>
		</strong><?php echo $this->status($detail['status']);?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">  
				<div class="form-group">
					<input type="hidden" name="openingdtl_id" id="openingdtl_id" value="<?php echo $detail['id'];?>" />
					<label for="quantity" class="control-label">Quantity</label>
					<input type="text" class="form-control" value="<?php echo $detail['quantity'];?>" name="quantity" id="quantity" size="30" placeholder="Quantity" required/> 
				</div>
				<div class="form-group">
					<label for="selling_price" class="control-label">Price</label>
					<input type="text" class="form-control" value="<?php echo $detail['rate'];?>" name="rate" id="rate" size="30" placeholder=" Price" required> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning btn-sm" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
	$('document').ready(function(){
		$('select').chosen({ allow_single_deselect: true });
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				quantity: {
					validators: {
						notEmpty: {
							message: 'Please provide quantity in basic uom'
						},
						numeric:{
							message: 'Please enter numeric value.'
						},
						greaterThan: {
							value: 0.1,
							message: 'The value must be greater than or equal to 0'
						},
					}
				},
				rate: {
					validators: {
						notEmpty: {
							message: 'Please provide selling price in basic uom'
						},
						numeric:{
							message: 'Please enter numeric value.'
						},
						greaterThan: {
							value: 0.1,
							message: 'The value must be greater than or equal to 0'
						},
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
</script>