<?php
/**
 * View -- of Stock/DispatchController/receivedispatchAction
 */
  $this->headTitle($this->title);
?>
<?php echo $this->partial('store/issue/partial.phtml', array('active' => 'issue')); ?> <br/>
<?php
	foreach($issues as $issue):
		//echo "<pre>"; print_r($issue);
		extract($issue);
		$issue_id = $id;
		$issue_activity = $activity;
		$issue_status = $status;
	endforeach; //exit;
?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
		font-size: 14px;
	}
</style>
<?php
	$depoyManager = $this->userRoleObj->get(array('user'=>$this->userID, 'subrole'=>array('9','21'))); 
	$admin_locs = $this->usersObj->getColumn($userID,'admin_location');
	$admin_loc_array = explode(',',$admin_locs);
	if(($issue_status == '2' ||  $issue_status == '10') && in_array($to_location, $admin_loc_array) && sizeof($depoyManager)>0): 
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;&nbsp;&nbsp;Receive Goods Issue : &nbsp;
					<strong><?php echo $challan_no; ?> | <?php echo $this->groupObj->getColumn($item_group,'name'); ?> | <?php echo $this->activityObj->getColumn($cost_center,'activity'); ?></strong>&nbsp;
					<?php echo $this->status($status);?>
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('inissue', array('action' => 'receiveissue')); ?>"  enctype="multipart/form-data" >    
						<input type="hidden" name="issue_id" id="issue_id" value="<?php echo $issue_id;?>" />
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Challan No. : <b class="red"><?php echo $challan_no;?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Source Location : <b class="red"><?php echo $from=$this->locationObj->getColumn($from_location,'location'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Activity  : <b class="red"><?php echo $this->activityObj->getColumn($cost_center,'activity'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Name of Driver : <b class="red"><?php echo $this->employeeObj->getColumn($fcb_transport,'full_name'); ?> </b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Issue Date : <b class="red"><?php echo $issue_date; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Destination Location : <b class="red"><?php echo $to=$this->locationObj->getColumn($to_location,'location');?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										 Item Group  : <b class="red"><?php echo $this->groupObj->getColumn($item_group,'name'); ?> </b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Vehicle No : <b class="red"><?php echo $vehicle_no; ?></b>
									</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-3">
								<label for="received_by" class="control-label">Received By</label>
								<select class="form-control" name="received_by" id="received_by" data-placeholder="Select" required > 
									<option value=""></option>
									<?php $employee_id = $this->usersObj->getColumn($userID,'employee');
										$employees = $this->employeeObj->getEmployee(array('e.location' => $to_location));
										foreach($employees as $emp):
											$selected_emp = ($emp['id'] == $employee_id)?'selected':'';?>
										<option value="<?php echo $emp['id'];?>" <?php echo $selected_emp;?>>
											<?php echo $emp['full_name'];?> (<?php echo $emp['designation']; ?>)
										</option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-3">
								<label for="received_date" class="control-label">Received Date</label>
								<?php $received_date = ($received_on == '0000-00-00' || $received_on == '')?date('Y-m-d'):$received_on;?>
								<div class="date input-group" id="received_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="received_date" id="received_date" value="<?php echo $received_date; ?>" type="text" placeholder="Received Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="space-6"></div>
							<div class="page-header">
								<h1>
									Receiving Goods Issued
									<small>
										<i class="ace-icon fa fa-angle-double-right"></i>
										from <?php echo $from;?> at <?php echo $to;?>
									</small>
								</h1>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12"> 
								<div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Item</th>
												<th>Store Spare/ Asset</th>
												<th>UOM</th>
												<th>Issue Qty</th>
												<th>Damage Qty</th>
												<th>Shortage Qty</th>
												<th>Accepted Qty</th>
												<th>Sound Qty</th>
												<th><?php echo $to=$this->locationObj->getColumn($to_location,'location');?> Stock Balance</th>
											</tr>
										</thead>
										<tbody>
											<?php 
												$issue_details = $this->issue_detailsObj->get(array('issue'=>$issue_id));
												if(sizeOf($issue_details)>0):
													foreach($issue_details as $details): 
													//echo "<pre>";print_r($details); exit;?>
											<tr>
												<td>
													<div class="form-group">
														<select id="item" name="item[]" class="form-control"  data-placeholder="Select" readonly="readonly" required>
															<option value="<?php echo $details['item_id'];?>">
																<?php echo $details['item'];?>
															</option>		
														</select>
													</div>
													<input type="hidden" name="issue_detail_id[]" id="issue_detail_id" value="<?php echo $details['id'];?>"/>
												</td>
												<td>
													<div class="form-group">
														<select id="batch" name="batch[]" class="form-control"  data-placeholder="Select" readonly="readonly" required>
															<?php
																$items = $this->itemObj->get($details['item_id']);
																foreach($items as $item):
																	if($item['item_group_id'] == 1):
														       	    $assets = $this->assetObj->get(array('a.id'=>$details['assetssp']));
																		foreach($assets as $asset): 
																			$selected_asset = ($asset['id']==$details['assetssp'])?"selected":"";
															?>
																<option value="<?php echo $asset['id'];?>" <?php echo $selected_asset;?>>
																	<?php echo $asset['asset'];?>
																</option>
															<?php 		endforeach;?>
															<?php
																else:
																	$spps = $this->sspObj->get(array('sp.id'=>$details['assetssp']));
																		foreach($spps as $spp): 
																			$selected_ssp = ($spp['id']==$details['assetssp'])?"selected":"";
															?>
																<option value="<?php echo $spp['id'];?>" <?php echo $selected_ssp;?>>
																	<?php echo $spp['storespare'];?>
																</option>
															<?php 		endforeach;
																	endif;
																endforeach;
															?>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control" data-placeholder="Select" required>
														    <option value=""></option>
														    <?php foreach($this->uomObj->get($details['uom']) as $uom):
															$sel_uom = ($uom['id'] == $details['uom'])?"selected":"";?>
															<option value="<?php echo $uom['id'];?>"<?php echo $sel_uom;?>>
																<?php echo $uom['code'];?>
															</option>
															<?php 		
																endforeach;
															?>
														</select>
														<input type="hidden" name="issue_qty[]" id="issue_qty" value="<?php echo $details['quantity'];?>"/>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="challan_qty[]" id="challan_qty" type="text" class="form-control" value="<?php echo $details['quantity'];?>"  readonly required>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="damage_qty[]" id="damage_qty" value="<?php echo '0.00';?>"/>
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="shortage_qty[]" id="shortage_qty" value="<?php echo '0.00';?>" />
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="accept_qty[]" id="accept_qty" value="<?php echo $details['quantity'];?>" readonly/>
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="sound_qty[]" id="sound_qty" value="<?php echo $details['quantity'];?>" readonly/>
													</div>         
												</td>
												<?php
													$selected_item = $this->itemObj->get($details['item_id']);
													foreach($selected_item as $item):
														if($item['item_group_id']==1):
															$from_quantity = $this->assetdetailsObj->getColumn(array('asset'=>$details['assetssp'],'location'=>$from_location),'quantity');
															$to_quantity = $this->assetdetailsObj->getColumn(array('asset'=>$details['assetssp'],'location'=>$to_location),'quantity');
														else: 
															$from_quantity = $this->sspdetailsObj->getColumn(array('storespare'=>$details['assetssp'],'location'=>$from_location),'quantity');
															$to_quantity = $this->sspdetailsObj->getColumn(array('storespare'=>$details['assetssp'],'location'=>$to_location),'quantity');
														endif;
												?>
												<td>
													<div class="form-group">
														<input name="to_balance[]" id="to_balance" type="text" class="form-control" value="<?php echo $to_quantity;?>" readonly />
														<input type="hidden" name="to_qty[]" id="to_qty" value="<?php echo $to_quantity;?>" />  
													</div>
												</td>				
											</tr>
											<?php 
													endforeach;
												endforeach;
											?>
											<?php endif;?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" >
									<i class="fa fa-times"></i> Cancel 
								</button> 					
							</div>
						</div>
					</form>	
				</div><!-- widget widget-main -->
			</div>  <!-- widget widget-body -->   
		</div> <!-- widget widget-box --> 
	</div><!-- col-lg-12 -->
</div><!-- row -->
<?php endif; ?>

<script type="text/javascript">
$(function() {									
	$('#received_date').datepicker();
	$('#received_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	/**** Calculations of Recieve Dispatch ****/
	$('#trdetails_table').issuereceive({
			//getConvReceivedQty:'<?php echo $this->url("dispatch", array("action" => "getconvreceivedqty"));?>',
	});	
});

	
/*** Form Validation ***/ 
const fv = FormValidation.formValidation(document.getElementById('#form'), {
	fields: {
		received_date: {
			validators: {
				notEmpty: {
					message: 'Please select received date'
				}
			}
		},
		received_by: {
			validators: {
				notEmpty: {
					message: 'Please select received by'
				}
			}
		},
		item[]: {
			validators: {
				notEmpty: {
					message: 'Please select item'
				}
			}
		},
		uom[]: {
			validators: {
				notEmpty: {
					message: 'Please select uom'
				}
			}
		},
		stock_balance[]: {
			validators: {
				greaterThan: {
					message: 'Invalid stock balance',
					inclusive: false,
					value: 0.00,
				}
			}
		},
	},
	plugins: {
		trigger: new FormValidation.plugins.Trigger(),
		bootstrap3: new FormValidation.plugins.Bootstrap3(),
		submitButton: new FormValidation.plugins.SubmitButton(),
		defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
	},
}).on('core.element.validated', function (e) {
	if (e.valid) {
		$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
		$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
	} else {
		$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
		$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
	}
});   
</script>
