<?php
/**
 * 
 * View -- of Hr/EmployeeController/addemployeeAction
 * 
 */
    $this->headTitle($this->title);
	foreach($sales as $row);//print_r($row['location']);exit;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pus"></i>&nbsp;Add Items &nbsp;&nbsp;<?php echo $row['sales_no'];?>
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('pos', array('action' => 'additems')); ?>"  enctype="multipart/form-data" >    
						<div class="row">
						<input type="hidden" name="location" id="location" value="<?php echo $row['location'];?>">
							<input type="hidden" name="sales" id="sales" value="<?php echo $row['id'];?>">
							<input type="hidden" name="sales_no" id="sales_no" value="<?php echo $row['sales_no'];?>">
							<input type="hidden" name="discount" id="discount" value="<?php echo $row['discount'];?>">
							<input type="hidden" name="cost_price" id="cost_price" value="<?php echo $row['cost_price'];?>">
						<div class="col-lg-3 form-group">
								<label class="control-label" for="item_subgroup">Item Group</label>
								<select  class="form-control" name="item_subgroup" id="item_subgroup" data-placeholder="Select" required >
									<option value=""></option>
									<?php foreach ($itemclasses as $itemclass):  
											$itemgroups = $itemgroupsObj->get(array('item_class'=>$itemclass['id']));
											foreach($itemgroups as $itemgroup):
										?>
										<optgroup label="<?php echo $itemclass['item_class']." | ".$itemgroup['item_group'];?>">
											<?php 
												$itemsubgroups = $this->itemsubgroupsObj->get(array('item_group'=>$itemgroup['id']));
												foreach($itemsubgroups as $itemsubgroup):
											?>
												<option value="<?php echo $itemsubgroup['id']; ?>">
													<?php echo $itemsubgroup['item_subgroup']; ?>
												</option>
											<?php endforeach;
											endforeach; ?>
										</optgroup>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="col-lg-3 form-group">
								<label for="item" class="control-label">Item</label>
								<select class="form-control" name="item" id="item" data-placeholder="Select" required readonly>
									<option value=""></option>
									<!-- <?php foreach($items as $item):?>
									<option value="<?php echo $item['id'];?>">
										<?php echo $item['name'];?>
									</option>
									<?php endforeach;?> -->
								</select> 
							</div>
							<div class="col-lg-1 form-group">
								<label for="quantity" class="control-label">Quantity</label>
								<input type="text" class="form-control"  name="quantity" id="quantity" value="" >
							</div>
							<div class="col-lg-3 form-group">
								<label for="basic_uom" class="control-label">Unit of Measurement</label>
								<input type="text" class="form-control"  name="basic_uom" id="basic_uom" value=" " readonly>
							</div>
							<div class="col-lg-1 form-group">
								<label for="selling_price" class="control-label">Rate</label>
								<input type="text" class="form-control"  name="rate" id="rate" value="0.00" readonly>
							</div>
                            <div class="col-lg-1 form-group">
								<label for="stock_qty" class="control-label">Stock Qty</label>
								<input type="text" class="form-control"  name="stock_qty" id="stock_qty" value="0.00" readonly>
							</div>
                            <div class="col-lg-1 form-group">
								<label for="amount" class="control-label">Total</label>
								<input type="text" class="form-control"  name="amount" id="amount" value="0.00" readonly>
							</div>
						</div>				
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12">
							   <button type="submit" class="btn btn-success"><i class="fa fa-save"></i> &nbsp; Save</button>
							</div>
						</div>	
					</form>    
				</div> 
			</div>   
      	</div>
    </div>   
</div>	
<script>
$('document').ready(function(){
	$('#item,#location').on('change', function(){
		$.post(
			"<?php echo $this->url('pos', array('action' => 'getrate')); ?>",
			{
				item:$('#item').val(),
                location:$('#location').val(),
			},
			function(data){
				console.log(data);
				$("#rate").val(data.rate);
                $("#stock_qty").val(data.quantity);	
				$("#cost_price").val(data.cost_price);	
			},
			'json'
		);	
	});
	$('#location,#item_subgroup').on('change', function(){
		//alert($("#location").val());
		$.post(
			"<?php echo $this->url('pos', array('action' => 'getItemChange')); ?>",
			{
				locationId: $("#location").val(),
				item_subgroup: $("#item_subgroup").val(),
			},
			function(data){
				console.log(data);
				$("#item").html(data.items);	
				$("#item").trigger('chosen:updated');
			},
			'json'
		);	
	});
	$('Select#item').on('change', function(){
		$.post(
			"<?php echo $this->url('pos', array('action' => 'getuom')); ?>",
			{
				itemId: $(this).val(),
			},
			function(data){
				console.log(data);
				$("#basic_uom").val(data.uom);
			},
			'json'
		);	
	});
	var rateInput = $('#rate');
	var quantityInput = $('#quantity');
  // Add an event listener for changes in the rate and quantity inputs
	rateInput.on('input', calculateTotal);
	quantityInput.on('input', calculateTotal);

  // Function to calculate the total and update the total input field
	function calculateTotal() {
		var rate = parseFloat(rateInput.val());
		var quantity = parseFloat(quantityInput.val());	
		var total = rate * quantity;
    // Check if the total is a valid number
    if (!isNaN(total)) {
      $('#amount').val(total.toFixed(2)); // Display the total with 2 decimal places
    }
  }
  const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			item_subgroup: {
				validators: {
					notEmpty: {
						message: 'Please select Item Group.'
					}
				}
			},
			item: {
				validators: {
					notEmpty: {
						message: 'Please select Item.'
					}
				}
			},
			quantity: {
				validators: {
					notEmpty: {
						message: 'Please Enter Quantity.'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>