<?php
/**
 * View -- of Stock/BatchController/viewbatchAction
 */
 $this->headTitle($this->title);
?>

<?php foreach($sales as $sale):
	extract($sale);
	$sales_id = $id;
endforeach;?>
<div class="widget widget-box" >
	<div class="widget-header">
		<h5 class="widget-title grey lighter">
			<i class="ace-icon fa fa-shopping-cart green"></i>
			<?php echo $sales_no;?>|&nbsp;&nbsp;<i></i>&nbsp;|
			<?php if($status==1):?>
			<span class="label label-danger"> Draft </span>
		<?php else: $this->status($status); endif;?>
		</h5>
		<div class="widget-toolbar hidden-xs">
			<a id="print" data-toggle="modal" data-target="#recipt_modal"  class="cursor:pointer">
				<i class="ace-icon fa fa-print fa-lg"></i>
			</a>		    
		</div>
	</div>
	<div class="widget-body"  id="report-print">
		<div class="widget-main padding-24">
			<div>
			<div class="row">
					<div class="col-lg-12" style="text-align: right">
						<?php if($status!=4):?>	
						<a class="btn btn-primary btn-sm"  href="<?php echo $this->url('pos', array('action'=>'editsales', 'id'=>$id));?>"><i class="fa fa-edit"></i> Edit Sales Entry </a>
						<?php endif;?>
						
					</div>
				</div>
				<div class="row" id="convert-tb0">
					<h5 class="widget-title grey lighter">
						<span class="label label-danger" style="display:none"> INVOICE </span>
					</h5>
					<div class="col-lg-6" id="convert-tb1">
						<table class="table">
							<tr>
								<td rowspan="2">Buyer: <br><strong><?php if($customer == 0){echo $this->locationObj->getColumn($location,'location');}else{echo $this->customerObj->getColumn($customer,'name'); }?></strong>
									<?php $partydetails=$this->partyObj->get(array('p.id'=>$customer));
									foreach ($partydetails as $dtl);?>
									<p>
									<?php if(!empty($dtl['role'])):?>
									Role:<?php echo $dtl['role'];?>,<br>
									<?php echo $dtl['address1'].','. $dtl['city'].','. $dtl['region'];?><br>
									<?php echo $dtl['country'];?><br>
									Tele No:  <?php echo $dtl['telephone'];?><br>
									Email:  <?php echo $dtl['email'];?><br>
									<?php endif;?>
									</p>
								</td>
					
								<td>Invoice No:<br><strong><?php echo $sales_no; ?></strong></td>
								<td>Date:<br><strong><?php echo $sales_date;?></strong></td>
							</tr>
							<tr>
								<td>Buyer's Order No: <br></td>
								<td>Dated:<br></td>
							</tr>
						</table>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12" >
						<table class="table table-striped table-bordered table-condensed" style="border-top:2px solid #ddd;">
							<thead >		
								<th>#</th>																
								<th>Item</th>
								<th>UOM</th>
								<th>Rate</th>
								<th>Quantity</th>
								<th>Amount</th>
							</thead>
							<tbody>
							<?php $i=1; $total=0;foreach($saledetails as $saledetail): ?>
							<tr> 
								<td><?php echo $i++;?></td>
								<td><?php echo $this->itemObj->getColumn($saledetail['item'],'name');?></td>
								<td><?php echo $saledetail['uom'];?></td>
								<td><?php echo $saledetail['rate'];?></td>
								<td><?php echo $saledetail['quantity'];?></td>
								<td><?php $amt = $saledetail['rate'] * $saledetail['quantity'];
								echo $total_amt = $amt - $saledetail['discount_qty'];?></td>
							</tr>
							<?php $total=$total+$amt;?>
							<?php endforeach;?>
							<tr>
								<td colspan="5" style="text-align:right"><b class="red">Total Amount :</b></td>
								<td colspan="2"><b><?php echo number_format($total, 2, '.', ',');?></b></td>
							</tr>
							<tr>
								<td colspan="5" style="text-align:right"><b class="red">Discount :</b></td>
								<td colspan="2"><b> <?php echo number_format($discount, 2, '.', ',');?>%</b></td>
							</tr>
							<tr>
								<td colspan="5" style="text-align:right"><b class="red">Net Amount :</b></td>

								<td colspan="2"><b> <?php if($discount == 0){echo $total;}else{echo  number_format($total-($total*($discount/100)), 2, '.', ','); }?></b></td>
							</tr>
						</tbody>
						</table>	
					</div>
				</div>
				<div class="row" id="convert-tb0">
				<table class="table" style="padding:20px;">
					<tr>
						<td>
					<p>Amount chargeable(in words)<br>
					<strong>Ngultrum <?php $readASword = $wordformat->format($total-($total*($discount/100)));echo $readASword. ' only /-'?></strong></p> 
							</td>		</tr></table>
				</div>
				<div class="row" id="convert-tb0">
					<table class="table"  style="padding:40px;">
						<tr>
							<td>
								<p style="text-decoration: underline;">
									Declaration</p><br>
									We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct
							</td>
							<td>
								 <p style="text-decoration: underline;"></p><br>
								Authorized Signatory
							</td>
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
			<div class="col-lg-5" style="text-align: right"></div>
			<div class="col-lg-7 no-print" style="text-align: right">
				<?php if($status==4):?>	
				<button type="button" class="btn btn-default btn-sm"  onclick="javascript:history.back();"><i class="fa fa-arrow-left"></i> Back </button>
				<?php else:?>
				<?php echo $this->button(2,$sales_no);?>
				<button type="button" class="btn btn-default btn-sm"  onclick="javascript:history.back();"><i class="fa fa-arrow-left"></i> Back </button> 
				<?php endif;?>
			</div>
		</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('#print').gentcpdf({
	content: '#report-print',
	src:"<?php echo $this->url('print', array('action' => 'index'));?>",
	orentation:"P",//L =landscape, P = potrait
});
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});

</script>

