<?php
/**
 * 
 * View -- of Sales/MasterpsController/serviceAction
 * 
 */

$this->headTitle($this->title);

?>
<?php //echo $this->partial('sales/masterpos/partial.phtml', array('active' => 'servicetarriff'));
?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="POST" action="<?php echo $this->url('postage', array('action' => 'postreport')); ?>" enctype="multipart/form-data" >    
						<div class="row">
							<div class="form-group col-lg-2">
								<label class="control-label" for="start_date">Start Date</label>
								<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>"  required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="end_date">End Date</label>
								<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>"  required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
							<label for="scope" class="control-label">Scope</label>
							<select class="form-control" id="scope" name="scope" data-placeholder="Select" onchange='this.form.submit()'>
								<option value="-1">All</option>
									<?php foreach($this->scopeObj->get(array('status'=>'1')) as $scopes):?>
										<option value="<?php echo $scopes['id']?>"<?php echo ($scopes['id']==$data['scope'])?'selected':'';?>>
										<?php echo $scopes['scope'];?></option>
									<?php endforeach;?>
							</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="service" class="control-label">Service</label>
								<select class="form-control" id="service" name="service" data-placeholder="Select" >
									<option value="-1">All</option>
									<?php foreach ($this->serviceObj->get(array('scope'=>$data['scope'])) as $service):?>
										<option value="<?php echo $service['id']?>"<?php echo ($service['id']==$data['service'])?'selected':'';?>>
										<?php echo $service['service'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="location" class="control-label">Location</label>
								<select class="form-control" id="location" name="location" data-placeholder="Select" >
									<option value="-1">All</option>
									<?php foreach ($this->locationObj->getAll() as $locs) :?>
										<option value="<?php echo $locs['id']?>"<?php echo ($locs['id']==$data['location'])?'selected':'';?>>
										<?php echo $locs['location'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="user" class="control-label">User</label>
								<select class="form-control" id="user" name="user" data-placeholder="Select" >
									<option value="-1">All</option>
									<?php if($data['location']=='-1'){$user=$this->userObj->getUsers();}else{$user=$this->userObj->get(array('location'=>$data['location']));}
									foreach ($user as $users):?>
										<option value="<?php echo $users['id']?>"<?php echo ($users['id']==$data['user'])?'selected':'';?>>
										<?php echo $users['name'].'-'.$this->locationObj->getColumn($users['location'],'location');?></option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="form-group col-lg-1"><br>
								<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
							</div>
						</div>
					</form>
				</div>
			<div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2);?>
				</div>
			</div>
		</div>
	</div>

	
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Article number</th>
					<th>Services</th>
					<th>Scope</th>
					<th>Country</th>
					<th>City</th>
					<th>Sales Date</th>
					<th>Bank</th>
					<th>Cash</th>
					<th>Credit</th>
					<th>User</th>
					<?php if($this->button(1)!=""):
						
						?>
						<th class="no-sort no-printpdf">Action</th>
						
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; $total_amt = 0;$bankSum=0;$cashSum=0;$creditSum=0;
					foreach ($paginator as $row):
						
					?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $row['article_no'];?></td>	
						<td><b><?php echo $this->serviceObj->getColumn($row['service'],'service') ;?></b></td>
						<td><b><?php echo $this->scopeObj->getColumn($row['scope'],'scope') ;?></b></td>
						<td><b><?php echo $this->countryObj->getColumn($row['country'],'name') ;?></b></td>
						<td><b><?php if(empty($row['city'])): echo ""; else: echo $this->cityObj->getColumn($row['city'],'city');endif;?></b></td>
						<td><?php echo $row['date'];?></td><?php if($row['cash']==0):?>
						<td><?php echo $bank=$this->postageObj->getColumn(array('id'=>$row['id']),'total_amt');?></td><?php else:?><td><?php echo $bank=0;?></td><?php endif;if($row['cash']==1):?>
						<td><?php echo $cash=$this->postageObj->getColumn(array('id'=>$row['id']),'total_amt');?></td><?php else:?><td><?php echo $cash=0;?></td><?php endif; if($row['cash']==2):?>
						<td><?php echo $credit=$this->postageObj->getColumn(array('id'=>$row['id']),'total_amt');?></td><?php else:?><td><?php echo $credit=0;?></td><?php  endif;?>					
						<td><?php echo $this->userObj->getColumn($row['author'],'name');?></td>	
					</tr>
				<?php $bankSum+=$bank;$cashSum+=$cash;$creditSum+=$credit;
				
					
				endforeach;?>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td><b>TOTAL(Nu)<b></td>
						<td><b><?php echo $bankSum;?><b></td>
						<td><b><?php echo $cashSum;?><b></td>		
						<td><b><?php echo $creditSum;?><b></td>		
						<td><b><?php echo $bankSum+$cashSum+$creditSum;?><b></td>								
					</tr>
		
			</tbody>
		</table>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$('#location').on('change', function(){
		$.post(
			"<?php echo $this->url('postage', array('action' => 'getuser')); ?>",
			{
				location: $(this).val(),
			},
			function(data){
				console.log(data);
				$("#user").html(data.users);
				$("#user").trigger('chosen:updated');
			},
			'json'
		);	
	});
});
</script>
