<?php
/**
 * 
 * View -- of Sales/MasterpsController/serviceAction
 * 
 */

$this->headTitle($this->title);

?>
<?php //echo $this->partial('sales/masterpos/partial.phtml', array('active' => 'servicetarriff'));

?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="POST" action="<?php echo $this->url('postage', array('action' => 'servicesalereport')); ?>" enctype="multipart/form-data" >    
						<div class="row">
							<div class="form-group col-lg-2">
								<label class="control-label" for="start_date">Start Date</label>
								<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>"  required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="end_date">End Date</label>
								<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>"  required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
								<label for="scope" class="control-label">Scope</label>
								<select class="form-control" id="scope" name="scope" data-placeholder="Select" onchange='this.form.submit()'>
									<option value="-1">All</option>
										<?php foreach($this->scopeObj->get(array('status'=>'1')) as $scopes):?>
											<option value="<?php echo $scopes['id']?>"<?php echo ($scopes['id']==$data['scope'])?'selected':'';?>>
											<?php echo $scopes['scope'];?></option>
										<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="service" class="control-label">Service</label>
								<select class="form-control" id="service" name="service" data-placeholder="Select" >
									<option value="-1">All</option>
									<?php foreach ($this->serviceObj->get(array('scope'=>$data['scope'])) as $service):?>
										<option value="<?php echo $service['id']?>"<?php echo ($service['id']==$data['service'])?'selected':'';?>>
										<?php echo $service['service'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="location" class="control-label">Location</label>
								<select class="form-control" id="location" name="location" data-placeholder="Select" >
									<option value="-1">All </option>
									<?php foreach ($locations as $location):?>
										<option value="<?php echo $location['id']?>"<?php echo ($location['id']==$data['location'])?'selected':'';?>>
										<?php echo $location['location'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label for="status" class="control-label">Status</label>
								<select class="form-control" id="status" name="status" data-placeholder="Select" >
									<option value="-1">All</option>
									<?php foreach ($this->statusObj->get(array(4,5)) as $statu):?>
										<option value="<?php echo $statu['id']?>"<?php echo ($statu['id']==$data['status'])?'selected':'';?>>
										<?php echo $statu['status'];?>	</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-3"></br>
								<div class="date input-group" >
								    <button type = "submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
								</div>
							</div>
						</div>
					</form>
				</div>
			<div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2);?>
				</div>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Article number</th>
					<th>Sales Date</th>
					<th>Location</th>
					<th>Services</th>
					<th>Scope</th>
					<th>Country</th>
					<th>Amount</th>
					<th>Status</th>
					<?php if($this->button(1)!=""):
						?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; $total=0;
					foreach ($paginator as $row):
					?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $row['article_no'];?></td>	
						<td><?php echo $row['date'];?></td>	
						<td><b><?php echo $this->locationObj->getColumn($row['location'],'location') ;?></b></td>
						<td><b><?php echo $this->serviceObj->getColumn($row['service'],'service') ;?></b></td>
						<td><b><?php echo $this->scopeObj->getColumn($row['scope'],'scope') ;?></b></td>
						<td><b><?php echo $this->countryObj->getColumn($row['country'],'name') ;?></b></td>
						<td><b><?php echo $row['total_amt'];?></b></td>
						<td><?php echo $this->status($row['status']);?></td>	
						<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $row['id']);?>
						</td>
						<?php endif;?>
					</tr>
				<?php 
				$total+=$row['total_amt'];
				endforeach;?>
				<tr>
					<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td></td>
						<td><b>Total</b></td>
						<td><b><?php echo $total;?></b></td>
						<td></td>
						<td></td>
						
					</tr>
			</tbody>
		</table>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
