<?php
/**
 * 
 * View -- of Stock/GoodsrequestController/addgoodsrequestAction
 * 
 */
  $this->headTitle($this->title);
?>
<?php echo $this->partial('stock/sam/partial.phtml', array('active' => 'sam')); ?><br/>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i>&nbsp;&nbsp;New Stock Adjustment
                </h5>	
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('sam', array('action'=>'addsam')); ?>"  enctype="multipart/form-data" >    
						<div class="row">	    
							<div class="form-group col-lg-4">
								<label for="sam_date" class="control-label">Stock Adjustment Date</label>
								<div class="date input-group" id="sam_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="sam_date" id="sam_date" type="text" value="<?php echo date('Y-m-d');?>" placeholder="Stock Adjustment Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div> 							
							<div class="form-group col-lg-4">
								<label for="location" class="control-label">Location</label>
								<select id="location" name="location" class="form-control" data-placeholder="Select" required>
									<option value=""></option>
									<?php foreach ($regions as $region): ?>
									<optgroup label="<?php echo $region['region'];?>">
										<?php
											$locations = $locationObj->get(array('region'=>$region['id']));
											foreach ($locations as $location):
											$selected_loc = ($location['id'] == $user_location)?"selected":"";
										?>
										 <option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
											<?php echo $location['location']; ?>
										 </option>
										<?php endforeach;?>
									</optgroup>
									<?php endforeach;?>									
								</select> 
							</div> 
							
							<div class="form-group col-lg-4">
								<label for="activity" class="control-label">Activity</label>
								<select class="form-control" name="activity" id="activity" data-placeholder="Select" required>
									<option value=""></option>
									<?php foreach($this->activities as $activity):?>
										<option value="<?php echo $activity['id'];?>">
									   		<?php echo $activity['activity']; ?>
									   	</option>
									<?php endforeach; ?>
								</select>
							</div>
						</div>
						
						<div class="row">
						   <div class="col-lg-12"> 
							  <h5>Stock Adjustment Details</h5>
								 <div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
											    <th>Adjustment Type</th>
												<th>Item Code</th>
												<th>Batch</th>
												<th>UOM</th>
												<th>Source Quantity</th>
												<th>Quantity</th>
												<th>Basic UOM</th>
												<th>Basic Quantity</th>
												<th>Remarks</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
											<tr>
											<td>
												<div class="form-group">
														<select id="sam_type" name="sam_type[]" class="form-control" data-placeholder="Select" >
															<option value=""></option>
															<?php foreach ($this->samTypes as $samType): ?>
															         <option value="<?php echo $samType['id']; ?>">
															            <?php echo $samType['sam_type']; ?>
															          </option>
															<?php endforeach; ?>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="item" name="item[]" class="form-control" data-placeholder="Select" >
															<option value=""></option>																													
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="batch" name="batch[]" class="form-control"  data-placeholder="Select">
															<option value=""></option>	
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control" data-placeholder="Select" >
															<option value=""></option>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="from_balance[]" id="from_balance" type="text" class="form-control" value="0.00" readonly required />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input name="quantity[]" id="quantity" type="text" class="form-control" value="0.00"required />
													</div>
												</td>
												<td>
													<div class="form-group">
														<select name="basic_uom[]" id="basic_uom" type="text" class="form-control" data-placeholder="Basic Uom" readonly >
															<option value=""></option>
														</select>
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input name="basic_quantity[]" id="basic_quantity" type="text" class="form-control" value="0.00" readonly />
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="remark[]" id="remark"/>
													</div>         
												</td>
												<td></td>
											</tr>
										</tbody>
									</table>
								</div> <!-- end of div -->
							</div> <!-- end of col-lg-12 -->
						</div>	<!-- end of row -->	
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('sam');?>'" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
					</form>  
				</div> <!-- end of widget-main -->  
	        </div> <!-- end of widget-body -->
        </div> <!-- end of widget widget-default -->
    </div> <!-- end of col-lg-12 -->
</div> <!-- end of row -->

<script type="text/javascript">
$(function() {
	$('#sam_date').datepicker();
	$('#sam_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#trdetails_table').stockadjust({
		getItems:'<?php echo $this->url("sam", array("action" => "getitembyactivity"));?>',
		getitemsdtls:'<?php echo $this->url("sam", array("action" => "getitemsdtls"));?>',
		getStockBalance:'<?php echo $this->url("sam", array("action" => "getStockBalance"));?>',
		getBasicQty:'<?php echo $this->url("sam", array("action" => "getbasicqty"));?>',
		getConvertedQty:'<?php echo $this->url("sam", array("action" => "getconvertedqty"));?>',
	});

	/******** formValidation *************/
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'sam_date': {
				validators: {
					notEmpty: {
						message: 'Please select goods request date'
					}
				}
			},
			'location': {
				validators: {
					notEmpty: {
						message: 'Please select location.'
					}
				}
			},
			'activity': {
				validators: {
					notEmpty: {
						message: 'Please select activity.'
					}
				}
			},   
			
			'sam_type[]': {
				validators: {
					notEmpty: {
						message: 'Please select Stock Adjustment type.'
					}
				}
			},
			
			'item[]': {
				validators: {
					notEmpty: {
						message: 'Please select item.'
					}
				}
			},
			'uom[]':{
				validators: {
					notEmpty: {
						message: 'Please select uom.'
					}
				}
			}, 
			'quantity[]':{
				validators: {
					notEmpty: {
						message: 'Please provide quantity.'
					}
				}
			}             
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>

