<?php
/**
 * View -- of Stock/SamController/editstockopeningdetailAction
 */
?>
<?php foreach($openingdtls as $detail);?>
<form id="#form" method="post" action="<?php echo $this->url('sam', array('action' => 'editstockopeningdetail')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> 
			<i class="fa fa-pencil-square-o"></i> Edit Opening Details : <strong> <?php echo $this->locationObj->getColumn($detail['location'],'location');?>
		</strong><?php echo $this->status($detail['status']);?></h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">  
				<div class="form-group">
					<input type="hidden" name="openingdtl_id" id="openingdtl_id" value="<?php echo $detail['id'];?>" />
					<input type="hidden" name="selling_price" id="selling_price" value="<?php echo $detail['selling_price'];?>" />
					<label for="location" class="control-label">Location</label>
					<select class="form-control" name="location" id="location" data-placeholder="Select" required >
					<option value=""></option>
					<?php foreach($location as $locations):?>
					<option value="<?php echo $locations['id'];?>"<?php echo ($detail['location']==$locations['id'])?'selected':'';?>>
					<?php echo $locations['location'];?></option>
					<?php endforeach;?>
					</select>
				</div>
				<div class="form-group">
					<label for="opening_stock" class="control-label">Opening Stock</label>
					<input type="text" class="form-control" value="<?php echo $detail['opening_qty'];?>" name="opening_stock" id="opening_stock" size="30" placeholder="opening stock" required/> 
				</div>
				<div class="form-group">
					<label for="quantity" class="control-label">Quantity</label>
					<input type="text" class="form-control" value="<?php echo $detail['quantity'];?>" name="quantity" id="quantity" size="30" placeholder="Quantity" required/> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning btn-sm" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	$('select').chosen({ allow_single_deselect: true });
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			quantity: {
				validators: {
					notEmpty: {
						message: 'Please provide quantity in basic uom'
					},
					numeric:{
						message: 'Please enter numeric value.'
					},
					
				}
			},
			selling_price: {
				validators: {
					notEmpty: {
						message: 'Please provide selling price in basic uom'
					},
					numeric:{
						message: 'Please enter numeric value.'
					},
				
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>