<?php
/**
 * View -- of Stock/BatchController/viewbatchAction
 */
 $this->headTitle($this->title);
?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<?php echo $this->partial('stock/sam/partial.phtml', array('active' => 'openingst')); ?><br/>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-body">
			    <form method="post" action="<?php echo $this->url('sam', array('action' => 'updatestopening', 'id'=>$id)); ?>"  enctype="multipart/form-data" >
				<div class="widget-main">
					<div id="report-print">
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12" >
								 <table class="table" style="border-top:2px solid #ddd;" id="">
								    <thead>																		
									    <th>#</th>
										<th>Batch No.</th>	
										<th>Item</th>	
										<th>Location</th>	
										<th>Opening Date</th>	
										<th>Qauntity</th>	
										<th>ELC</th>
										<th>Selling Price</th>										
										<th>Author</th>	
										<th>Created/Modified</th>										
									</thead>
									<tbody>		
                                        <?php $i=1;
											foreach($st_opening as $row): 
										?>
											<tr data-href="">
												<td><?php echo $i++;?></td>
												<td><?php echo $row['batch'];?></td>
												<td><?php echo $row['item'];?></td>
												<td><?php echo $row['location'];?></td>
												<td><?php echo $row['opening_date'];?></td>
												<td><?php echo $row['quantity'];?></td>
												<td><?php echo $row['elc'];?></td>
												<td><?php echo $row['selling_price'];?></td>
												<td><?php echo $row['author'];?></td>
												<td><?php echo $row['created'];?><b> | </b><?php echo $row['modified'];?></td>
											</tr>
										<?php endforeach;?>									
									</tbody>
								</table>
							</div>
						</div>
						<div class = "row">
							<div class="col-lg-4">
								<a href="<?php echo $this->url('sam', array('action'=>'deletestopening'));?>" class="btn btn-warning"> <i class="fa fa-refresh"></i> Delete Opening</a>
								<a href="<?php echo $this->url('sam', array('action'=>'updatestopening'));?>" class="btn btn-warning"> <i class="fa fa-refresh"></i> Update Opening</a>
								<a href="<?php echo $this->url('sam', array('action'=>'updatebatch'));?>" class="btn btn-warning"> <i class="fa fa-refresh"></i> Update Batch</a>
					        </div>
					        </div>
                        </div>
					</div>
				</div>
				</form>	
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>
