<?php
/**
 * 
 * View -- of Stock/GoodsrequestController/indexAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/dispatch/partial.phtml', array('active' => 'request')); ?> <br/>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="row">
	<div class="col-lg-12">
		<div class="row">
			<form id="#form" method="post" action="<?php echo $this->url('goodsrequest',array('action' => 'goodsrequest')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Goods Request" href="<?php echo $this->url('goodsrequest', array('action'=>'addgoodsrequest'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add GRN</span></span>
					</a>
				</div>
			</div>
		</div>
		<div>
			<table class="table table-bordered table-striped table-hover" id="dataTables">
				<thead>
					<tr>
					    <th>#</th>
						<th>GRN No.</th>
						<th>GRN Date</th>
						<th>From Location</th>
						<th>To Location</th>
						<th>GRN Type</th>
					</tr>
				</thead>
				<tbody>					
					<?php $i=1;foreach($good_request as $grn):?>
						<tr>
							<td><?php echo $i++;?></td>
							<td>
								<b><?php echo $grn['gr_no'];?></b>&nbsp;&nbsp;&nbsp;
		
								</i>        
								&nbsp;<?php $this->status($grn['status']);?>
							</td>
							<td><?php echo $grn['gr_date'];?></td>
							<td><?php echo $this->locationObj->getColumn($grn['from_location'],'location');?> </td>
							<td><?php echo $this->locationObj->getColumn($grn['to_location'],'location');?> </td>
							<td>
								<a href="<?php echo $this->url('goodsrequest', array('action'=>'viewgoodsrequest', 'id'=>$grn['id']));?>" class="btn btn-xs btn-primary"><i class="fa fa-eye"></i></a>
								&nbsp;
								<?php  if(($role==99 || $role==100) && $grn['status']==7):echo $this->button(1,$grn['id']);endif;?>
							</td>
						</tr>
					<?php endforeach;?>  
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>

