<?php
/**
 * 
 * View -- of Stock/GoodsrequestController/reorderAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/dispatch/partial.phtml', array('active' => 'requestview')); ?> <br/>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller"> 
					<i class="fa fa-shopping-cart"></i> ReOrder Goods
				</h5>
				<div class="widget-toolbar hidden-xs">
					<a style='cursor:pointer' id="print">
						<i class="ace-icon fa fa-file-pdf-o red"></i>
					</a>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-24">
					<form method="post" action="<?php echo $this->url('goodsrequest', array('action' => 'reorder')); ?>">
						<div class="row">
							<div class="col-lg-4">
								<label for="location" class="control-label">Location </label>
								<select class="form-control" name="location" id="location" data-placeholder="Select" onChange="form.submit(this)" required >
									<option value="-1">All</option>
									<?php foreach($locationObj->get('location_type',array(1,2)) as $locations):
										$selected = ($location_id == $locations['id'])?'selected':'';?>
										<option value="<?php echo $locations['id'];?>" <?php echo $selected;?>>
											<?php echo $locations['location'];?>
										</option>
									<?php endforeach; ?>
								</select>
							</div>
							<div class="col-lg-4">
								<label for="item" class="control-label">Item</label>
								<select class="form-control" name="item" id="item" data-placeholder="Select" onChange="form.submit(this)" required>
									<option value="-1">All</option>
									<?php foreach($itemObj->getAll() as $item):
										$selected = ($item_id == $item['id'])?'selected':'';?>
									<option value="<?php echo $item['id'];?>"<?php echo $selected;?>>
										<?php echo $item['code']; ?>
									</option>
									<?php endforeach ?>
								</select>
							</div>
							<div class="col-lg-4">
								<label for="item" class="control-label">Request Type</label>
								<select class="form-control" name="request_type" id="request_type" data-placeholder="Select" onChange="form.submit(this)" required>
									<option value="-1">All</option>
									<?php 
										$selected1 = ($request_type == 1)?'selected':'';
										$selected2 = ($request_type == 2)?'selected':'';
									?>
									<option value="1"<?php echo $selected1;?>>Purchase Request</option>
									<option value="2"<?php echo $selected2;?>>Dispatch Request</option>
								</select>
							</div>
						</div>	  
					</form>
					<div class="space"></div>
					<div id="report-print">	
						<table class="table" style="border-top:2px solid #ddd;">
							<thead>
								<tr>
								    <th>#</th>
									<th>Item</th>
									<th>Location</th>
									<th>Request Type</th>
									<th>Minimum Qty</th>
									<th>Current Qty</th>
								</tr>
							</thead>
							<tbody>					
								<?php $i=1;
						  			foreach($reorderdtls as $reorder):
						  				$item_id = $reorder['item'];
						  				$location = $reorder['location'];
						  				$item_valuation = $this->itemObj->getColumn($item_id,'valuation');
						  				
						  				if($item_valuation == 0): //FIFO
							  				$batch_ids = $this->batchObj->get(array('item'=>$item_id));
							  				//echo "<pre>"; print_r($batch_ids);
							  				foreach($batch_ids as $batch_id):
								  				$batch_qty = $this->batchdetailsObj->getColumn(array('batch'=>$batch_id['id'],'location'=>$location),'quantity');
								  				if(isset($batch_qty)):
								  					$total += $batch_qty;
								  				endif;
						  					endforeach;
						  				else: //Wt Moving Avg
						  					$total = $this->movingitemObj->getColumn(array('item'=>$item_id,'location'=>$location),'quantity');
						  				endif;
						  				$total = number_format((float)$total, 2, '.', '');
						  		?>
							  		<?php if($total < $reorder['min_stock_qty']):?>
									<tr class="danger">
							  			<td><?php echo $i++; ?></td>
									  	<td><b><?php echo $this->itemObj->getColumn($reorder['item'],'code'); ?></b></td>
										<td><?php echo $this->locationObj->getColumn($reorder['location'],'location'); ?></td>
										<td>
											<?php 
												if($reorder['request_type']==1):
													echo "Purchase Request";
												else:
													echo "Dispatch Request";
												endif;
											?>
										</td>
										<td><?php echo $reorder['min_stock_qty']; ?></td>
										<td><?php echo $total;?></td>	
								      	</tr>
								    <?php else:?>
									<tr>
							  			<td><?php echo $i++; ?></td>
									  	<td><b><?php echo $this->itemObj->getColumn($reorder['item'],'code'); ?></b></td>
										<td><?php echo $this->locationObj->getColumn($reorder['location'],'location'); ?></td>
										<td>
											<?php 
												if($reorder['request_type']==1):
													echo "Purchase Request";
												else:
													echo "Dispatch Request";
												endif;
											?>
										</td>
										<td><?php echo $reorder['min_stock_qty']; ?></td>
										<td><?php echo $total;?></td>	
								      	</tr>
								    <?php endif;?>
						  		<?php endforeach; ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfpayslip({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>

