<?php
/**
 * 
 * View -- of Stock/StockController/viewgoodsrequest
 * 
 */
?>
<?php echo $this->partial('stock/dispatch/partial.phtml', array('active' => 'request')); ?> <br/>
<?php 
	foreach($good_request as $grn):
		extract($grn);
		$grn_id = $id;
		$grn_status = $status;
	endforeach;
?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					# Goods Request Details:<strong>&nbsp;&nbsp;<?php echo $gr_no;?> | <?php //echo $location; ?></strong>&nbsp;
					<?php if($grn['type']==1):?>
						<span class="label label-warning">Purchase Request</span>
					<?php else:?>
						<span class="label label-info">Dispatch Request</span>
					<?php endif;?>&nbsp;
					<?php echo $this->status($status);?>
				</h5>
				
				<div class="widget-toolbar hidden-xs">	
					<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "12-".$grn_id)); ?>" title="View Activity Logs">
						<i class="ace-icon fa fa-plus bigger-120" ></i>  
					</a> |				
					<a style='cursor:pointer' id="print">
						<i class="ace-icon fa fa-file-pdf-o red"></i>
					</a>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										GRN No : <b class="red"><?php echo $gr_no; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										From Location : <b class="red"><?php echo $this->locationObj->getColumn($from_location,'location'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										GRN Type : <b class="red"><?php echo ($type==1)?"Purchase Request":"Dispatch Request";?></b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										GRN Date : <b class="red"><?php echo $gr_date; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Activity : <b class="red"><?php echo $activity; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										To Location : <b class="red"><?php echo $this->locationObj->getColumn($to_location,'location'); ?></b>
									</li>									
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>Note : <b class="red"><?php echo $note; ?> </b>
									</li>
								</ul>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12" >
								<table class="table" style="border-top:2px solid #ddd;">
									<thead>
										<tr>
											<th>#</th>
											<th>Item</th>
											<th>UOM</th>											
											<th>Requested Qty</th>
											<th>Qty as of <?php echo $this->dateformat($gr_date); ?> </th>
										</tr>
									</thead>
									<tbody>
										<?php $sl=1;foreach($gr_details as $tdrow):?>
											<tr>
												<td><?php echo $sl++;?></td>
												<td><?php echo $tdrow['item'];?></td>
												<td><?php echo $tdrow['uom'];?></td>
												<td><?php echo $tdrow['requested_qty'];?></td>
												<td><?php echo $tdrow['existing_qty'];?></td>
											</tr>
										<?php endforeach;?>
										<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;"></tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12" style="text-align: right">		
							<?php $depoyManager = $this->userRoleObj->get(array('id'=>$this->userID));
								  $purchaseOfficial = $this->userRoleObj->get(array('id'=>$this->userID));	?>						
							<?php if($grn_status == '1' && $this->user_location == $from_location && sizeof($depoyManager)>0):?>
								   <a href="<?php echo $this->url('goodsrequest', array('action'=>'editgoodsrequest', 'id'=>$grn_id));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
								  <a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('goodsrequest', array('action'=>'processgr', 'id'=>$grn_id.'-1'));?>" class="btn btn-success"> <i class="fa fa-check-square-o"></i>Send Request</a>
							<?php elseif($grn_status == '5' && $this->user_location == $to_location && (sizeof($depoyManager)>0 || sizeof($purchaseOfficial)>0)): ?>
							      <a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('goodsrequest', array('action'=>'processgr', 'id'=>$grn_id.'-2'));?>" class="btn btn-success"> <i class="fa fa-check-square-o"></i>&nbsp; Receive GRN</a>
							<?php endif;?>
						</div>
					</div>
					<!-- Upload and Download file attachments -->			
					<?php   
					  // echo $this->partial('partial/attachment.phtml', array('process' => '12', 'grn_id'=> $payment_id , 'status' => $grn_status));
					?>					
				    <!-- End of attachment -->
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>
