<?php
/**
 * View -- of Purchase/ContractorController/editcontractorAction
 */
  $this->headTitle($this->title);
?>
<style>
	table#trdetails_table > thead > tr {
		background: rgba(179, 174, 174, 0.18);
		border-top:2px solid #ddd;
		border-bottom:3px solid #ddd;
		color: #707070;
		font-weight: 400;
	}
	table#trdetails_table > tbody > tr > td {
	    padding: 8px;
	    line-height: 1.8;
	    vertical-align: top;
	    font-size: 13.5px;
    }
</style>
<?php 
	foreach($contractor_invoice as $con_inv):
		extract($con_inv);
		$con_inv_id = $id;
		$con_inv_status = $status;
		$contractor_name = $contractor;
		$location_name = $location;
		$activity_name = $activity;
		//echo "<pre>";print_r($con_inv);
	endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
				<i class="fa fa-pencil"></i>&nbsp;&nbsp;&nbsp;Edit Contractor Invoice :	
				<strong>&nbsp;<?php echo $invoice_no; ?> | <?php echo $contractor; ?> | <?php echo $activity; ?></strong>&nbsp;
					<?php $this->status($con_inv_status);?>
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('contractor', array('action' => 'editcontractor')); ?>" enctype="multipart/form-data">    
						<div class="row">	
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="invoice_date" class="control-label">Invoice Date</label>
									<div class="date input-group" id="invoice_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="invoice_date" id="invoice_date" value="<?php echo $invoice_date;?>" type="text" placeholder="Invoice Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-4">
								<div class="form-group">
									<label for="start_date" class="control-label">Start Date</label>
									<div class="date input-group" id="start_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="start_date" id="start_date" value="<?php echo $from_date;?>" type="text" placeholder="Start Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>	   				
							<div class="col-lg-4">
								<div class="form-group">
									<label for="end_date" class="control-label">End Date</label>
									<div class="date input-group" id="end_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="end_date" id="end_date" value="<?php echo $to_date;?>" type="text" placeholder="End Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
						</div>
						<div class="row">	
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="location" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($regions as $region): ?>
										<optgroup label="<?php echo $region['region'];?>">
											<?php 
												$locations = $locationObj->get(array('l.region'=>$region['id']));
												foreach ($locations as $location):
												$selected = ($location['id']==$location_id)?"selected":"";
											?>
											 <option value="<?php echo $location['id']; ?>" <?php echo $selected;?>>
												<?php echo $location['location']; ?>
											 </option>
											<?php endforeach;?>
										</optgroup>
										<?php endforeach;?>									
									</select> 
								</div>
							</div>
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="activity" class="control-label">Activity</label>
									<select class="form-control" name="activity" id="activity" data-placeholder="Select" required>
										<option value=""></option>
										<?php 
											foreach($this->activities as $activity):
											$selected = ($activity['id']==$activity_id)?"selected":"";
										?>
											<option value="<?php echo $activity['id'];?>" <?php echo $selected;?>>
										   		<?php echo $activity['activity']; ?>
										   	</option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="contractor" class="control-label">Contractor</label>
									<select id="contractor" name="contractor" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
										<?php 
											foreach ($this->contractors as $contractor):
											$selected = ($contractor['id']==$contractor_id)?"selected":"";
										?>
											<option value="<?php echo $contractor['id'];?>" <?php echo $selected; ?> >
												<?php echo $contractor['name']; ?>
											</option>
										<?php endforeach;?>								
									</select> 
									<input type="hidden" name="con_inv_id" id="con_inv_id" value="<?php echo $con_inv_id;?>"/>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
							<div class="space-12"></div>
								<div class="page-header">
									<h1>
										<div class="col-lg-9">
											Contractor Invoice Details
											<small>
												<i class="ace-icon fa fa-angle-double-right"></i>
												Loading, Unloading, Shifting &amp; Repacking Charges
											</small>
										</div>
										<div class="col-lg-3">
											<button type="button" id="refresh_btn" class="btn btn-info pull-right"><i class="fa fa-refresh"></i> Refresh </button>
										</div>
									</h1>
									<div class="space-12"></div>
									<div class="space-12"></div>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-lg-12">
								<div class="con_inv_details">
									<div class="clearfix">
										<label><i class="blue fa fa-user"></i> <strong>Contractor:</strong></label> <span><?php echo $contractor_name; ?></span>.&nbsp;&nbsp;
										<label><i class="red fa fa-map-marker"></i> <strong>Location:</strong></label> <span><?php echo $location_name;?></span>.&nbsp;&nbsp;
										<label><i class="purple fa fa-tags"></i> <strong>Activity:</strong></label> <span><?php echo $activity_name;?></span>.&nbsp;&nbsp;
										<label><i class="green fa fa-calendar"></i> <strong>Period From :</strong></label> <span><?php echo $from_date.' to '.$to_date;?></span>
									</div>
									<div class="space-6"></div>
									<table class="table table-striped table-bordered table-hover table-condensed">
										<thead>
											<tr>
												<th>#</th>
												<th>Charges</th>
												<th>Qty Processed (MT|CASE)</th>
												<th>Rate (<?php echo $this->currency_code();?>)</th>
												<th>Amount (<?php echo $this->currency_code();?>)</th>
												<th>View Details</th>
											</tr>
										</thead>
										<tbody>
											<?php 
												if(sizeof($con_inv_details)>0):
												$sl=1;
												foreach($con_inv_details as $con_inv_detail):
											?>
												<tr id="<?php echo $con_inv_detail['work_type'];?>">
													<td><?php echo $sl++;?></td>
													<td><b><?php echo $work_type_code = $this->worktypeObj->getColumn($con_inv_detail['work_type'],'work_type');?></b></td>
													<td>
														<?php
															echo $con_inv_detail['qty'];
														?>
													</td>
													<td>
														<?php
															echo $con_inv_detail['rate'];
														?>
													</td>
													<td>
														<?php 
															$total += $con_inv_detail['amount'];
															echo $con_inv_detail['amount'];
														?>
													</td>
													<td class="form-group">
														<input type="radio" name="details" value="1" id="details"><?php echo $work_type_code."&nbsp;Details";?>
													</td>
												</tr>
												<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $con_inv_detail['work_type'];?>" />
												<input type="hidden" name="qty[]" id="qty" value="<?php echo $con_inv_detail['qty'];?>" />
												<input type="hidden" name="rate[]" id="rate" value="<?php echo $con_inv_detail['rate'];?>" />
												<input type="hidden" name="amount[]" id="amount" value="<?php echo $con_inv_detail['amount'];?>" />
											<?php endforeach;
												else:
											?>
												<tr>
													<td colspan="7">No Data Available</td>
												</tr>
											<?php endif;?>
										</tbody>
										<tfoot>
											<tr>
												<th style="text-align:right" colspan="4"><i>Grand Total</i></th>
												<th colspan="2">
												<?php 
													echo $grand_total = number_format((float)$total, 2, '.', '');
												?>
												<input type="hidden" name="invoice_amount" id="invoice_amount" value="<?php echo $grand_total;?>" />
												</th>
											</tr>
										</tfoot>
									</table>
									<div class="row"> 
										<div class="col-lg-6"></div>
										<div class="col-lg-3">
											<div class="form-group">
												<label for="deduction">Deduction(<?php echo $this->currency_code();?>)</label>
												<input type="text" class="form-control tr-deduction" name="deduction" id="deduction" value="<?php echo $deduction?>" />
											</div>
										</div>
										<div class="col-lg-3">
											<div class="form-group">
												<label for="payable_amount">Payable Amount(<?php echo $this->currency_code();?>)</label>
												<input type="text" class="form-control tr-payable_amount" name="payable_amount" id="payable_amount" value="<?php echo $payable_amount;?>" readonly />
											</div>
										</div>  
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="details">
								</div>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
					</form>  
				</div> <!-- end of widget-main -->  
	        </div> <!-- end of widget-body -->
        </div> <!-- end of widget widget-default -->
    </div> <!-- end of col-lg-12 -->
</div> <!-- end of row -->

<script type="text/javascript">
$(function() {
	$('#invoice_date').datepicker();
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#invoice_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#refresh_btn').click(function(){
		$('form').formValidation('revalidateField',$('input#start_date'));
		$('form').formValidation('revalidateField',$('input#end_date'));
		$('form').formValidation('revalidateField',$('#location'));
		$('form').formValidation('revalidateField',$('#activity'));
		$('form').formValidation('revalidateField',$('#contractor'));
		var validation = $('form small[data-fv-result = "INVALID"]').length;
		if(validation <= 0){
			$.post( 
				"<?php echo $this->url('contractor', array('action' => 'getconinvdetails'));?>",
				{	
					'start_date': $('input#start_date').val(),
					'end_date': $('input#end_date').val(),
					'location': $('#location').val(), 
					'activity': $('#activity').val(),
					'contractor':$('#contractor').val(),
				}, 
				function(data) {
					$('div.con_inv_details').html( data ); 
			});	
			//$('div.message_box').hide();
		}
	});
	
	$( "input:radio" ).on( "click", function() {
		var id = $(this).closest('tr').attr('id');
		$.post( 
			"<?php echo $this->url('contractor', array('action' => 'getdetails'));?>",
			{	
				'id': id,
				'start_date': $('input#start_date').val(),
				'end_date': $('input#end_date').val(),
				'location': $('#location').val(), 
				'activity': $('#activity').val(),
				'contractor':$('#contractor').val(),
			}, 
			function(data) {
				$('div.details').html( data ); 
		});	            
	  });
});
	/******** formValidation *************/
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'invoice_date': {
				validators: {
					notEmpty: {
						message: 'Please select invoice date'
					}
				}
			},
			'location': {
				validators: {
					notEmpty: {
						message: 'Please select location'
					}
				}
			},
			'activity': {
				validators: {
					notEmpty: {
						message: 'Please select activity'
					}
				}
			},
			'contractor': {
				validators: {
					notEmpty: {
						message: 'Please select contractor'
					}
				}
			},  
			'start_date':{
				validators: {
					notEmpty:{
						message: 'Please select start date'
					},
				}
			}, 
			'end_date':{
				validators: {
					notEmpty:{
						message: 'Please select end date'
					},
				}
			},               
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
</script>
