<?php
/**
 * View --> Purchase/ContractorController/getconinvdetails.pthml
 * ajax response
 */
?>
<?php 
	$start_date = $data['start_date'];
	$end_date = $data['end_date'];
	$location = $data['location'];
	$activity = $data['activity'];
	$contractor = $data['contractor'];
?>
<div class="clearfix message_box">
	<label><i class="blue fa fa-user"></i> <strong>Contractor:</strong></label> <span><?php echo $this->partyObj->getColumn($contractor,'code'); ?></span>.&nbsp;&nbsp;
	<label><i class="red fa fa-map-marker"></i> <strong>Location:</strong></label> <span><?php echo $this->locationObj->getColumn($location,'location');?></span>.&nbsp;&nbsp;
	<label><i class="purple fa fa-tags"></i> <strong>Activity:</strong></label> <span><?php echo $this->activityObj->getColumn($activity, 'activity');?></span>.&nbsp;&nbsp;
	<label><i class="green fa fa-calendar"></i> <strong>Period From :</strong></label> <span><?php echo $data['start_date'].' to '.$data['end_date'];?></span>
</div>	
<div class="space-6"></div>
<?php 
	$current_month = date('m',strtotime($start_date));
	if($last_month == $current_month):
?>
	<div class="alert alert-warning fade in">
		<h3><center>The <span class="red">Invoice</span> has been already generated for this month. </center></h3>
	</div>
<?php endif;?>
<table class="table table-striped table-bordered table-hover table-condensed">
	<thead>
		<tr>
			<th>#</th>
			<th>Charges</th>
			<th>Qty Processed (MT|CASE|BAG|PCS)</th>
			<th>Rate (<?php echo $this->currency_code();?>)</th>
			<th>Amount (<?php echo $this->currency_code();?>)</th>
			<th>View Details</th>
		</tr>
	</thead>
	<tbody>
<?php 
	$sl = 1;
	/*************** Purchase Receipt *****************/
	if($contractor == '4183'): 
	    // Standard UOM Costing for; (FEED is BAG*1 =>141003 and  BAG => 14001)=>item_class(28), (FARM TOOLS is PEC*1=>141002 and PEC =>26001)=>item_class(4),(FERTILIZER is BAG * 1 =>141003 and BAG => 14001)=>item_class(22), (SEED is PEC*1 =>141002 and PEC =>26001)=>item_class(20)
		if($activity == 7):
			$pur_receipt = $this->prnObj->getByDate($start_date, $end_date, array('location'=>$location,'activity'=>$activity,'status'=>'3'));
			foreach($pur_receipt as $prn):
				$prn_details = $this->prn_detailsObj->get(array('d.purchase_receipt'=>$prn['id']));
				foreach($prn_details as $pr_detail):
					$prn_item = $pr_detail['item_id'];
					$prn_uom = $pr_detail['uom_id'];
					$prn_qty = $pr_detail['accept_qty'];
					$prn_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$prn_item, 'uom'=>$prn_uom),'conversion');
					$basic_uom = $this->itemObj->getColumn($prn_item,'uom');
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$prn_item,'costing_uom'=>'1'),'uom');
					$item_subgroup = $this->itemObj->getColumn(array('id'=>$pr_detail['item_id']),'item_subgroup');
					$item_group = $this->itemsubgroupObj->getColumn(array('id'=>$item_subgroup),'item_group');
					$item_class = $this->itemgroupObj->getColumn(array('id'=>$item_group),'item_class');
					//Farm Tools 
					if($item_class == '4'):
						if($prn_uom == $standard_uom):
							$prn_PCE_qty = $prn_qty;
						else:
							$prn_basic_qty = ($prn_uom == $basic_uom)?$prn_qty:$prn_qty*$prn_uom_conversion;
							$prn_PCE_conversion = $this->itemuomObj->getColumn(array('item'=>$prn_item, 'uom'=>$standard_uom),'conversion');
							$prn_PCE_qty = ($basic_uom == $standard_uom)?$prn_basic_qty:$prn_basic_qty*$prn_PCE_conversion;
						endif;
						$pec_sumprnqty += $prn_PCE_qty;	
					elseif($item_class == '28' || $item_class == '22'):
						if($prn_uom == $standard_uom): 
							$prn_BAG_qty = $prn_qty;
						else:
							$prn_basic_qty = ($prn_uom == $basic_uom)?$prn_qty:$prn_qty*$prn_uom_conversion;
							$prn_BAG_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>array('141003')),'conversion');
							$prn_BAG_qty = ($basic_uom == $standard_uom)?$prn_basic_qty:$prn_basic_qty/$prn_BAG_conversion;
						endif;
						$bag_sumprnqty += $prn_BAG_qty;
					endif;
				endforeach;
			endforeach;
			
			/*************** Dispatch InReceipt *****************/
			$intreceipt = $this->dispatchObj->getByDate($start_date, $end_date, array('to_location'=>$location,'activity'=>$activity,'status'=>'3'));
			foreach($intreceipt as $recdisp):
				$rec_details = $this->disp_detailsObj->get(array('d.dispatch'=>$recdisp['id']));
				foreach($rec_details as $rec_detail):
					//echo "<pre>"; print_r($rec_detail); 
					$rec_item = $rec_detail['item_id'];
					$rec_uom = $rec_detail['basic_uom'];
					$rec_qty = $rec_detail['accepted_qty'];
					$rec_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$rec_item, 'uom'=>$rec_uom),'conversion');
					$basic_uom = $this->itemObj->getColumn($rec_item,'uom');
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$rec_item,'costing_uom'=>'1'),'uom'); 
					$item_subgroup = $this->itemObj->getColumn(array('id'=>$rec_detail['item_id']),'item_subgroup');
					$item_group = $this->itemsubgroupObj->getColumn(array('id'=>$item_subgroup),'item_group');
					$item_class = $this->itemgroupObj->getColumn(array('id'=>$item_group),'item_class');
					if($item_class == '4'):// Farm Tools
						if($rec_uom == $standard_uom):
							$rec_pce_qty = $rec_qty;
						else:
							$rec_basic_qty = ($rec_uom == $basic_uom)?$rec_qty:$rec_qty*$rec_uom_conversion;
							$rec_PCE_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'141002'),'conversion');
							$rec_PEC_qty = ($basic_uom == $standard_uom)?$rec_basic_qty:$rec_basic_qty*$rec_PCE_conversion;
						endif;
						$pec_sumrec_qty += $rec_PEC_qty;
					elseif($item_class == '28' || $item_class == '22'):
						if($rec_uom == $standard_uom):
							$rec_BAG_qty = $rec_qty;
						else:
							$rec_basic_qty = ($rec_uom == $basic_uom)?$rec_qty:$rec_qty*$rec_uom_conversion;
							$rec_BAG_conversion = $this->itemuomObj->getColumn(array('item'=>$rec_item, 'uom'=>$standard_uom),'conversion');
							$rec_BAG_qty = ($basic_uom == $standard_uom)?$rec_basic_qty:$rec_basic_qty/$rec_BAG_conversion;
						endif;
						$bag_sumrec_qty += $rec_BAG_qty;
					endif;
				endforeach;
			endforeach; 
			
		else:
		
		$pur_receipt = $this->prnObj->getByDate($start_date, $end_date, array('location'=>$location,'activity'=>$activity,'status'=>'3'));
			foreach($pur_receipt as $prn):
				$prn_details = $this->prn_detailsObj->get(array('d.purchase_receipt'=>$prn['id']));
				foreach($prn_details as $pr_detail):
					$prn_item = $pr_detail['item_id'];
					$prn_uom = $pr_detail['uom_id'];
					$prn_qty = $pr_detail['accept_qty'];
					$prn_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$prn_item, 'uom'=>$prn_uom),'conversion');
					$basic_uom = $this->itemObj->getColumn($prn_item,'uom');
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$prn_item,'costing_uom'=>'1'),'uom');
					
					if($standard_uom == '59001'): //METRIC TONES
						if($prn_uom == $standard_uom):
							$prn_MT_qty = $prn_qty;
						else:
							$prn_basic_qty = ($prn_uom == $basic_uom)?$prn_qty:$prn_qty*$prn_uom_conversion;
							$prn_MT_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'59001'),'conversion');
							$prn_MT_qty = ($basic_uom == $standard_uom)?$prn_basic_qty:$prn_basic_qty/$prn_MT_conversion;
						endif;
						$wt_sumprnqty += $prn_MT_qty;
						//$Processed_UOM = '59001';
					else: //CASES
						if($prn_uom == $standard_uom):
							$prn_CASE_qty = $prn_qty;
						else:
							$prn_basic_qty = ($prn_uom == $basic_uom)?$prn_qty:$prn_qty*$prn_uom_conversion;
							$prn_CASE_conversion = $this->itemuomObj->getColumn(array('item'=>$prn_item, 'uom'=>$standard_uom),'conversion');
							$prn_CASE_qty = ($basic_uom == $standard_uom)?$prn_basic_qty:$prn_basic_qty/$prn_CASE_conversion;
						endif;
						$case_sumprnqty += $prn_CASE_qty;
						//$Processed_UOM = '-1'; //CASES
					endif;
				endforeach;
			endforeach;
			
			/*************** Dispatch InReceipt *****************/
			$intreceipt = $this->dispatchObj->getByDate($start_date, $end_date, array('to_location'=>$location,'activity'=>$activity,'status'=>'3'));
			foreach($intreceipt as $recdisp):
				$rec_details = $this->disp_detailsObj->get(array('d.dispatch'=>$recdisp['id']));
				foreach($rec_details as $rec_detail):
					//echo "<pre>"; print_r($rec_detail); 
					$rec_item = $rec_detail['item_id'];
					$rec_uom = $rec_detail['basic_uom'];
					$rec_qty = $rec_detail['accepted_qty'];
					$rec_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$rec_item, 'uom'=>$rec_uom),'conversion');
					$basic_uom = $this->itemObj->getColumn($rec_item,'uom');
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$rec_item,'costing_uom'=>'1'),'uom');
					
					if($standard_uom == '59001'): //METRIC TONES
						if($rec_uom == $standard_uom):
							$rec_MT_qty = $rec_qty;
						else:
							$rec_basic_qty = ($rec_uom == $basic_uom)?$rec_qty:$rec_qty*$rec_uom_conversion;
							$rec_MT_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'59001'),'conversion');
							$rec_MT_qty = ($basic_uom == $standard_uom)?$rec_basic_qty:$rec_basic_qty/$rec_MT_conversion;
						endif;
						$wt_sumrec_qty += $rec_MT_qty;
					else:
						if($rec_uom == $standard_uom):
							$rec_CASE_qty = $rec_qty;
						else:
							$rec_basic_qty = ($rec_uom == $basic_uom)?$rec_qty:$rec_qty*$rec_uom_conversion;
							$rec_CASE_conversion = $this->itemuomObj->getColumn(array('item'=>$rec_item, 'uom'=>$standard_uom),'conversion');
							$rec_CASE_qty = ($basic_uom == $standard_uom)?$rec_basic_qty:$rec_basic_qty/$rec_CASE_conversion;
						endif;
						$case_sumrec_qty += $rec_CASE_qty;
						//$Processed_UOM = '-1'; //CASES 
					endif;
				endforeach;
			endforeach; 
		endif;
		$MT_unloading = $wt_sumprnqty + $wt_sumrec_qty;
		$CASE_unloading = $case_sumprnqty + $case_sumrec_qty;
		$BAG_unloading = $bag_sumprnqty + $bag_sumrec_qty;
		$PEC_unloading = $pec_sumprnqty + $pec_sumrec_qty;
			
		?>
		<?php if($MT_unloading > 0):
				$wt_work_type = 2; //unload MT
				$wt_charge_tax = $this->worktypeObj->getColumn($wt_work_type,'charge_tax');
				$wt_charge_tax_value = $this->chargetaxObj->getColumn($wt_charge_tax,'value');
		?>
			<tr id='2'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($wt_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$MT_unloading, 2, '.', '');?></td>
				<td><?php echo $wt_charge_tax_value;?></td>
				<td>
					<?php $wt_amount = $MT_unloading * $wt_charge_tax_value;
						echo $wt_net_unloading = number_format((float)$wt_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Unload MT Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $wt_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $MT_unloading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $wt_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $wt_net_unloading;?>" />
		<?php endif;?>
		<?php if($CASE_unloading > 0):
				$case_work_type = 4; //unload CASE
				$case_charge_tax = $this->worktypeObj->getColumn($case_work_type,'charge_tax');
				$case_charge_tax_value = $this->chargetaxObj->getColumn($case_charge_tax,'value');
		?>
			<tr id='4'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($case_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$CASE_unloading, 2, '.', '');?></td>
				<td><?php echo $case_charge_tax_value;?></td>
				<td>
					<?php $case_amount = $CASE_unloading * $case_charge_tax_value;
						echo $case_net_unloading = number_format((float)$case_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Unload CASE Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $case_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $CASE_unloading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $case_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $case_net_unloading;?>" />
		<?php endif;?>
		<?php if($BAG_unloading > 0):
				$bag_work_type = 12; //unload BAG
				$bag_charge_tax = $this->worktypeObj->getColumn($bag_work_type,'charge_tax');
				$bag_charge_tax_value = $this->chargetaxObj->getColumn($bag_charge_tax,'value');
		?>
			<tr id='12'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($bag_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$BAG_unloading, 2, '.', '');?></td>
				<td><?php echo $bag_charge_tax_value;?></td>
				<td>
					<?php $bag_amount = $BAG_unloading * $bag_charge_tax_value;
						echo $bag_net_unloading = number_format((float)$bag_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Unload BAG Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $bag_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $BAG_unloading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $bag_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $bag_net_unloading;?>" />
		<?php endif;?>
		<?php if($PEC_unloading > 0):
				$pec_work_type = 9; //unload PCE
				$pec_charge_tax = $this->worktypeObj->getColumn($pec_work_type,'charge_tax');
				$pec_charge_tax_value = $this->chargetaxObj->getColumn($pec_charge_tax,'value');
		?>
			<tr id='9'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($pec_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$PEC_unloading, 2, '.', '');?></td>
				<td><?php echo $pec_charge_tax_value;?></td>
				<td>
					<?php $pec_amount = $PEC_unloading * $pec_charge_tax_value;
						echo $pec_net_unloading = number_format((float)$pec_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Unload PEC Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $pec_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $PEC_unloading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $pec_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $pec_net_unloading;?>" />
		<?php endif;?>

		<?php 
			/*************** Goods Dispatch *****************/
		if($contractor == '4183'):
			if($activity == 7):
				$dispatch = $this->dispatchObj->getByDate($start_date, $end_date, array('from_location'=>$location,'activity'=>$activity,'status'=>array('2','3','10')));
				foreach($dispatch as $disp):
					$disp_details = $this->disp_detailsObj->get(array('d.dispatch'=>$disp['id']));
					foreach($disp_details as $disp_detail):
						$disp_item = $disp_detail['item_id'];
						$disp_uom = $disp_detail['uom_id'];
						$disp_qty = $disp_detail['quantity'];
						$disp_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$disp_item, 'uom'=>$disp_uom),'conversion');
						$basic_uom = $this->itemObj->getColumn($disp_item,'uom');
						$standard_uom = $this->itemuomObj->getColumn(array('item'=>$disp_item,'costing_uom'=>'1'),'uom');
						$item_subgroup = $this->itemObj->getColumn(array('id'=>$disp_detail['item_id']),'item_subgroup');
						$item_group = $this->itemsubgroupObj->getColumn(array('id'=>$item_subgroup),'item_group');
						$item_class = $this->itemgroupObj->getColumn(array('id'=>$item_group),'item_class');
						
						if($item_class == '4'):
							if($disp_uom == $standard_uom):
								$disp_PEC_qty = $disp_qty;
							else:
								$disp_basic_qty = ($disp_uom == $basic_uom)?$disp_qty:$disp_qty*$disp_uom_conversion;
								$disp_PEC_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>array('141002','26001')),'conversion');
								$disp_PEC_qty = ($basic_uom == $standard_uom)?$disp_basic_qty:$disp_basic_qty*$disp_PEC_conversion;
							endif;
						    $pec_sumdispqty += $disp_PEC_qty;
						elseif($item_class == '28' || $item_class == '22'):
							if($disp_uom == $standard_uom):
								$disp_BAG_qty = $disp_qty;
							else:
								$disp_basic_qty = ($disp_uom == $basic_uom)?$disp_qty:$disp_qty*$disp_uom_conversion;
								$disp_BAG_conversion = $this->itemuomObj->getColumn(array('item'=>$disp_item, 'uom'=>$standard_uom),'conversion');
								$disp_BAG_qty = ($basic_uom == $standard_uom)?$disp_basic_qty:$disp_basic_qty/$disp_BAG_conversion;
							endif;
							$bag_sumdispqty += $disp_BAG_qty;
						endif;
					endforeach;
				endforeach; 
				/*************** Sales *****************/
				$sales = $this->salesObj->getByDate($start_date, $end_date, array('s.location'=>$location,'i.activity'=>$activity,'s.status'=>'3'));
				foreach($sales as $sale):
					//echo "<pre>"; print_r($sale); 
					$sale_item = $sale['item'];
					$sale_uom = $sale['uom'];
					$sale_qty = $sale['quantity'];
					$sale_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$sale_item, 'uom'=>$sale_uom),'conversion');
					$basic_uom = $sale['basic_uom'];
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$sale_item,'costing_uom'=>'1'),'uom');

					$item_subgroup = $this->itemObj->getColumn(array('id'=>$sale_item ),'item_subgroup');
					$item_group = $this->itemsubgroupObj->getColumn(array('id'=>$item_subgroup),'item_group');
					$item_class = $this->itemgroupObj->getColumn(array('id'=>$item_group),'item_class');

						if($item_class == '4'):
							if($sale_uom == $standard_uom):
								$sale_PEC_qty = $sale_qty;
							else:
								$sale_basic_qty = ($sale_uom == $basic_uom)?$sale_qty:$sale_qty*$sale_uom_conversion;
								$sale_PEC_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>array('141002')),'conversion');
								$sale_PEC_qty = ($basic_uom == $standard_uom)?$sale_basic_qty:$sale_basic_qty*$sale_PEC_conversion;
							endif;
							$pec_sumsaleqty += $sale_PEC_qty;
						elseif($item_class == '28' || $item_class == '22'):
								if($sale_uom == $standard_uom):
									$sale_BG_qty = $sale_qty;
								else:
									$sale_basic_qty = ($sale_uom == $basic_uom)?$sale_qty:$sale_qty*$sale_uom_conversion;
									$sale_BG_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>array('141003')),'conversion');
									$sale_BG_qty = ($basic_uom == $standard_uom)?$sale_basic_qty:$sale_basic_qty/$sale_BG_conversion;
								endif;
								$bg_sumsaleqty += $sale_BG_qty;
					    endif;
				endforeach;
				
			else:
			
				$dispatch = $this->dispatchObj->getByDate($start_date, $end_date, array('from_location'=>$location,'activity'=>$activity,'status'=>array('2','3','10')));
				foreach($dispatch as $disp):
					$disp_details = $this->disp_detailsObj->get(array('d.dispatch'=>$disp['id']));
					foreach($disp_details as $disp_detail):
						//echo "<pre>"; print_r($disp_detail); 
						$disp_item = $disp_detail['item_id'];
						$disp_uom = $disp_detail['uom_id'];
						$disp_qty = $disp_detail['quantity'];
						$disp_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$disp_item, 'uom'=>$disp_uom),'conversion');
						$basic_uom = $this->itemObj->getColumn($disp_item,'uom');
						$standard_uom = $this->itemuomObj->getColumn(array('item'=>$disp_item,'costing_uom'=>'1'),'uom');
						
						if($standard_uom == '59001'): //METRIC TONES
							if($disp_uom == $standard_uom):
								$disp_MT_qty = $disp_qty;
							else:
								$disp_basic_qty = ($disp_uom == $basic_uom)?$disp_qty:$disp_qty*$disp_uom_conversion;
								$disp_MT_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'59001'),'conversion');
								$disp_MT_qty = ($basic_uom == $standard_uom)?$disp_basic_qty:$disp_basic_qty/$disp_MT_conversion;
							endif;
							$wt_sumdispqty += $disp_MT_qty;
							//$Processed_UOM = '59001';
						else: //CASES
							if($disp_uom == $standard_uom):
								$disp_CASE_qty = $disp_qty;
							else:
								$disp_basic_qty = ($disp_uom == $basic_uom)?$disp_qty:$disp_qty*$disp_uom_conversion;
								$disp_CASE_conversion = $this->itemuomObj->getColumn(array('item'=>$disp_item, 'uom'=>$standard_uom),'conversion');
								$disp_CASE_qty = ($basic_uom == $standard_uom)?$disp_basic_qty:$disp_basic_qty/$disp_CASE_conversion;
							endif;
							$case_sumdispqty += $disp_CASE_qty;
							//$Processed_UOM = '-1'; //CASES 
						endif;
					endforeach;
				endforeach; 
				/*************** Sales *****************/
				$sales = $this->salesObj->getByDate($start_date, $end_date, array('s.location'=>$location,'i.activity'=>$activity,'s.status'=>'3'));
				foreach($sales as $sale):
					//echo "<pre>"; print_r($sale); 
					$sale_item = $sale['item'];
					$sale_uom = $sale['uom'];
					$sale_qty = $sale['quantity'];
					$sale_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$sale_item, 'uom'=>$sale_uom),'conversion');
					$basic_uom = $sale['basic_uom'];
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$sale_item,'costing_uom'=>'1'),'uom');
					
					if($standard_uom == '59001'): //METRIC TONES
						if($sale_uom == $standard_uom):
							$sale_MT_qty = $sale_qty;
						else:
							$sale_basic_qty = ($sale_uom == $basic_uom)?$sale_qty:$sale_qty*$sale_uom_conversion;
							$sale_MT_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'59001'),'conversion');
							$sale_MT_qty = ($basic_uom == $standard_uom)?$sale_basic_qty:$sale_basic_qty/$sale_MT_conversion;
						endif;
						$wt_sumsaleqty += $sale_MT_qty;
						//$Processed_UOM = '59001';
					else: //CASES
						if($sale_uom == $standard_uom):
							$sale_CASE_qty = $sale_qty;
						else:
							$sale_basic_qty = ($sale_uom == $basic_uom)?$sale_qty:$sale_qty*$sale_uom_conversion;
							$sale_CASE_conversion = $this->itemuomObj->getColumn(array('item'=>$sale_item, 'uom'=>$standard_uom),'conversion');
							$sale_CASE_qty = ($basic_uom == $standard_uom)?$sale_basic_qty:$sale_basic_qty/$sale_CASE_conversion;
						endif;
						$case_sumsaleqty += $sale_CASE_qty;
						//$Processed_UOM = '-1'; //CASES 
					endif;
				endforeach;
			endif;			
			endif;			
			$MT_loading = $wt_sumdispqty + $wt_sumsaleqty;
			$CASE_loading = $case_sumdispqty + $case_sumsaleqty;
			$BAG_loading = $bg_sumdispqty + $bg_sumsaleqty;
			$PEC_loading = $pec_sumdispqty + $pec_sumsaleqty;
			
			
		?>
		<?php if($MT_loading > 0):
				$wt_work_type = 1; //load MT
				$wt_charge_tax = $this->worktypeObj->getColumn($wt_work_type,'charge_tax');
				$wt_charge_tax_value = $this->chargetaxObj->getColumn($wt_charge_tax,'value');
		?>
			<tr id='1'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($wt_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$MT_loading, 2, '.', '');?></td>
				<td><?php echo $wt_charge_tax_value;?></td>
				<td>
					<?php $wt_amount = $MT_loading * $wt_charge_tax_value;
						echo $wt_net_loading = number_format((float)$wt_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Load MT Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $wt_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $MT_loading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $wt_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $wt_net_loading;?>" />
		<?php endif;?>
		<?php if($CASE_loading > 0):
				$case_work_type = 3; //load CASE
				$case_charge_tax = $this->worktypeObj->getColumn($case_work_type,'charge_tax');
				$case_charge_tax_value = $this->chargetaxObj->getColumn($case_charge_tax,'value');
		?>
			<tr id="3">
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($case_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$CASE_loading, 2, '.', '');?></td>
				<td><?php echo $case_charge_tax_value;?></td>
				<td>
					<?php $case_amount = $CASE_loading * $case_charge_tax_value;
						echo $case_net_loading = number_format((float)$case_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Load CASE Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $case_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $CASE_loading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $case_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $case_net_loading;?>" />
		<?php endif;?>
		<?php if($BAG_loading > 0):
				$bag_work_type = 11; //load BAG
				$bag_charge_tax = $this->worktypeObj->getColumn($bag_work_type,'charge_tax');
				$bag_charge_tax_value = $this->chargetaxObj->getColumn($bag_charge_tax,'value');
		?>
			<tr id="11">
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($bag_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$BAG_loading, 2, '.', '');?></td>
				<td><?php echo $bag_charge_tax_value;?></td>
				<td>
					<?php $bag_amount = $BAG_loading * $bag_charge_tax_value;
						echo $bag_net_loading = number_format((float)$bag_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Load BAG Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $bag_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $BAG_loading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $bag_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $bag_net_loading;?>" />
		<?php endif;?>
		<?php if($PEC_loading > 0):
				$pec_work_type = 13; //load PEC
				$pec_charge_tax = $this->worktypeObj->getColumn($pec_work_type,'charge_tax');
				$pec_charge_tax_value = $this->chargetaxObj->getColumn($pec_charge_tax,'value');
		?>
			<tr id="13">
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($pec_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$PEC_loading, 2, '.', '');?></td>
				<td><?php echo $pec_charge_tax_value;?></td>
				<td>
					<?php $pec_amount = $PEC_loading * $pec_charge_tax_value;
						echo $pec_net_loading = number_format((float)$pec_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Load PEC Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $pec_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $PEC_loading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $pec_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $pec_net_loading;?>" />
		<?php endif;?>

		<?php
			/***************** Repacking & Shifting *********************/
			$repackings = $this->repackingObj->getByDate($start_date, $end_date, array('location'=>$location,'activity'=>$activity,'contractor'=>$contractor,'status'=>'3'));
			foreach($repackings as $repacking):
				$pack_item = $repacking['item'];
				$pack_uom = $repacking['uom'];
				$pack_qty = $repacking['quantity'];
				$pack_rate = $repacking['rate'];
				$pack_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$pack_item, 'uom'=>$pack_uom),'conversion');
				$basic_uom = $this->itemObj->getColumn($pack_item,'uom');
				$standard_uom = $this->itemuomObj->getColumn(array('item'=>$pack_item,'costing_uom'=>'1'),'uom');
				if($repacking['work_type'] == 1): //Repacking
					if($standard_uom == '59001'): //METRIC TONES
						if($pack_uom == $standard_uom):
							$repacking_MT_qty = $pack_qty;
							$repacking_MT_rate = $pack_rate;
						else:
							$repacking_basic_qty = ($pack_uom == $basic_uom)?$pack_qty:$pack_qty*$pack_uom_conversion;
							$repacking_MT_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'59001'),'conversion');
							$repacking_MT_qty = ($basic_uom == $standard_uom)?$repacking_basic_qty:$repacking_basic_qty/$repacking_MT_conversion;
							
							$repacking_basic_rate = ($pack_uom == $basic_uom)?$pack_rate:$pack_rate/$pack_uom_conversion;
							$repacking_MT_rate = ($basic_uom == $standard_uom)?$repacking_basic_rate:$repacking_basic_rate*$repacking_MT_conversion;
						endif;
						$MT_repacking += $repacking_MT_qty;
						$Rate_MT_repacking = $repacking_MT_rate;
						$repacking_MT_amount = $repacking_MT_qty * $repacking_MT_rate;
						$Amount_MT_repacking += $repacking_MT_amount;
						//$Processed_UOM = '59001';
					else: //CASES
						if($pack_uom == $standard_uom):
							$repacking_CASE_qty = $pack_qty;
							$repacking_CASE_rate = $pack_rate;
						else:
							$repacking_basic_qty = ($pack_uom == $basic_uom)?$pack_qty:$pack_qty*$pack_uom_conversion;
							$repacking_CASE_conversion = $this->itemuomObj->getColumn(array('item'=>$pack_item, 'uom'=>$standard_uom),'conversion');
							$repacking_CASE_qty = ($basic_uom == $standard_uom)?$repacking_basic_qty:$repacking_basic_qty/$repacking_CASE_conversion;
							
							$repacking_basic_rate = ($pack_uom == $basic_uom)?$pack_rate:$pack_rate/$pack_uom_conversion;
							$repacking_CASE_rate = ($basic_uom == $standard_uom)?$repacking_basic_rate:$repacking_basic_rate*$repacking_CASE_conversion;
						endif;
						$CASE_repacking += $repacking_CASE_qty;
						$Rate_CASE_repacking += $repacking_CASE_rate;
						$repacking_CASE_amount = $repacking_CASE_qty * $repacking_CASE_rate;
						$Amount_CASE_repacking += $repacking_CASE_amount;
						//$Processed_UOM = '-1'; //CASES 
					endif;
				else: // Shifting
					if($standard_uom == '59001'): //METRIC TONES
						if($pack_uom == $standard_uom):
							$shifting_MT_qty = $pack_qty;
							$shifting_MT_rate = $pack_rate;
						else:
							$shifting_basic_qty = ($pack_uom == $basic_uom)?$pack_qty:$pack_qty*$pack_uom_conversion;
							$shifting_MT_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>'59001'),'conversion');
							$shifting_MT_qty = ($basic_uom == $standard_uom)?$shifting_basic_qty:$shifting_basic_qty/$shifting_MT_conversion;
							
							$shifting_basic_rate = ($pack_uom == $basic_uom)?$pack_rate:$pack_rate/$pack_uom_conversion;
							$shifting_MT_rate = ($basic_uom == $standard_uom)?$shifting_basic_rate:$shifting_basic_rate*$shifting_MT_conversion;
						endif;
						$MT_shifting += $shifting_MT_qty;
						$Rate_MT_shifting = $shifting_MT_rate;
						$shifting_MT_amount = $shifting_MT_qty * $shifting_MT_rate;
						$Amount_MT_shifting += $shifting_MT_amount;
						//$Processed_UOM = '59001';
					else: //CASES
						if($pack_uom == $standard_uom):
							$shifting_CASE_qty = $pack_qty;
							$shifting_CASE_rate = $pack_rate;
						else:
							$shifting_basic_qty = ($pack_uom == $basic_uom)?$pack_qty:$pack_qty*$pack_uom_conversion;
							$shifting_CASE_conversion = $this->itemuomObj->getColumn(array('item'=>$pack_item, 'uom'=>$standard_uom),'conversion');
							$shifting_CASE_qty = ($basic_uom == $standard_uom)?$shifting_basic_qty:$shifting_basic_qty/$shifting_CASE_conversion;
							
							$shifting_basic_rate = ($pack_uom == $basic_uom)?$pack_rate:$pack_rate/$pack_uom_conversion;
							$shifting_CASE_rate = ($basic_uom == $standard_uom)?$shifting_basic_rate:$shifting_basic_rate*$shifting_CASE_conversion;
						endif;
						$CASE_shifting += $shifting_CASE_qty;
						$Rate_CASE_shifting += $shifting_CASE_rate;
						$shifting_CASE_amount = $shifting_CASE_qty * $shifting_CASE_rate;
						$Amount_CASE_shifting += $shifting_CASE_amount;
						//$Processed_UOM = '-1'; //CASES 
					endif;
				endif;
			endforeach;
		?>
		<?php if($MT_repacking > 0):
			$repacking_MT_work_type = 5; //repacking MT
		?>
			<tr id='5'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($repacking_MT_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$MT_repacking, 2, '.', '');?></td>
				<td><?php echo number_format((float)$Rate_MT_repacking, 2, '.', '');?></td>
				<td>
					<?php 
						echo $wt_net_repacking = number_format((float)$Amount_MT_repacking, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Repacking MT Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $repacking_MT_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $MT_repacking;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $Rate_MT_repacking;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $wt_net_repacking;?>" />
		<?php endif;?>

		<?php if($CASE_repacking > 0):
			$repacking_CASE_work_type = 7; //repacking CASE
		?>
			<tr id='7'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($repacking_CASE_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$CASE_repacking, 2, '.', '');?></td>
				<td><?php echo number_format((float)$Rate_CASE_repacking, 2, '.', '');?></td>
				<td>
					<?php 
						echo $case_net_repacking = number_format((float)$Amount_CASE_repacking, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Repacking CASE Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $repacking_CASE_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $CASE_repacking;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $Rate_CASE_repacking;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $case_net_repacking;?>" />
		<?php endif;?>
		<?php if($MT_shifting > 0):
			$shifting_MT_work_type = 6; //shifting MT
		?>
			<tr id='6'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($shifting_MT_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$MT_shifting, 2, '.', '');?></td>
				<td><?php echo number_format((float)$Rate_MT_shifting, 2, '.', '');?></td>
				<td>
					<?php 
						echo $wt_net_shifting = number_format((float)$Amount_MT_shifting, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Shifting MT Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $shifting_MT_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $MT_shifting;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $Rate_MT_shifting;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $wt_net_shifting;?>" />
		<?php endif;?>

		<?php if($CASE_shifting > 0):
			$shifting_CASE_work_type = 8; //shifting CASE
		?>
			<tr id='8'>
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($shifting_CASE_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$CASE_shifting, 2, '.', '');?></td>
				<td><?php echo number_format((float)$Rate_CASE_shifting, 2, '.', '');?></td>
				<td>
					<?php 
						echo $case_net_shifting = number_format((float)$Amount_CASE_shifting, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Shifting CASE Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $shifting_CASE_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $CASE_shifting;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $Rate_CASE_shifting;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $case_net_shifting;?>" />
		<?php endif;?>
		
	<?php else:
		    $pur_order = $this->poObj->getByDate($start_date, $end_date, array('location'=>$location,'activity'=>$activity,'status'=>array('2','3')));
			//print_r($pur_order); exit;
			foreach($pur_order as $po):
				$po_details = $this->po_detailsObj->get(array('d.purchase_order'=>$po['id']));
				foreach($po_details as $po_detail):
					$po_item = $po_detail['item_id'];
					$po_uom = $po_detail['uom_id'];
					$po_qty = $po_detail['quantity'];
					$po_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$po_item, 'uom'=>$po_uom),'conversion');
					$basic_uom = $this->itemObj->getColumn($po_item,'uom');
					$standard_uom = $this->itemuomObj->getColumn(array('item'=>$po_item,'costing_uom'=>'1'),'uom');
					
					$item_subgroup = $this->itemObj->getColumn(array('id'=>$po_detail['item_id']),'item_subgroup');
					$item_group = $this->itemsubgroupObj->getColumn(array('id'=>$item_subgroup),'item_group');
					$item_class = $this->itemgroupObj->getColumn(array('id'=>$item_group),'item_class');
					
					if($item_class == '28'):// 28 - FEED
						if($po_uom == 	$standard_uom):
							$po_BG_qty = $po_qty;
						else:
							$po_basic_qty = ($po_uom == $basic_uom)?$po_qty:$po_qty*$po_uom_conversion;
							$po_BG_conversion = $this->scalarconversionObj->getColumn(array('from_uom'=>$basic_uom,'to_uom'=>array('141003')),'conversion');
							$po_BG_qty = ($basic_uom == $standard_uom)?$prn_basic_qty:$po_basic_qty/$po_BG_conversion;
						endif;
						$soure_bg_sumprnqty += $po_BG_qty;
					endif;				
				endforeach;
			endforeach;
			$BAG_loading_source = $soure_bg_sumprnqty;
			//echo $BAG_loading_source; exit;
			?>
			<?php if($BAG_loading_source > 0):
				$bags_work_type = 10; //load BAG AT SOURCE
				$bags_charge_tax = $this->worktypeObj->getColumn($bags_work_type,'charge_tax');
				$bags_charge_tax_value = $this->chargetaxObj->getColumn($bags_charge_tax,'value');
			 ?>
			<tr id="10">
				<td><?php echo $sl++;?></td>
				<td><b><?php echo $this->worktypeObj->getColumn($bags_work_type,'work_type');?></b></td>
				<td><?php echo number_format((float)$BAG_loading_source, 2, '.', '');?></td>
				<td><?php echo $bags_charge_tax_value;?></td>
				<td>
					<?php $bags_amount = $BAG_loading_source * $bags_charge_tax_value;
						echo $bags_net_loading = number_format((float)$bags_amount, 2, '.', '');
					?>
				</td>
				<td class="form-group">
					<input type="radio" name="details" value="1" id="details"/> Load BAG at Source Details
				</td>
			</tr>
			<input type="hidden" name="work_type[]" id="work_type" value="<?php echo $bags_work_type;?>" />
			<input type="hidden" name="qty[]" id="qty" value="<?php echo $BAGS_loading;?>" />
			<input type="hidden" name="rate[]" id="rate" value="<?php echo $bags_charge_tax_value;?>" />
			<input type="hidden" name="amount[]" id="amount" value="<?php echo $bags_net_loading;?>" />
		    <?php endif;?>
	<?php endif;?>
		</tbody>
	<tfoot>
		<tr>
			<th style="text-align:right" colspan="4"><i>Grand Total</i></th>
			<th colspan="2">
                        <?php 
				$grand_total = $case_net_unloading + $pec_net_unloading + $bag_net_unloading + $wt_net_unloading + $case_net_loading  
				+ $bags_net_loading + $bag_net_loading + $pec_net_loading + $wt_net_loading + $wt_net_repacking + $case_net_repacking + $wt_net_shifting + $case_net_shifting;
				echo $grand_total = number_format((float)$grand_total, 2, '.', '');
			?>
			<input type="hidden" name="invoice_amount" id="invoice_amount" value="<?php echo $grand_total;?>" />
			</th>
		</tr>
	</tfoot>
</table>
<div class="row"> 
	<div class="col-lg-6"></div>
	<div class="col-lg-3">
		<div class="form-group">
			<label for="deduction">Deduction(<?php echo $this->currency_code();?>)</label>
			<input type="text" class="form-control tr-deduction" name="deduction" id="deduction" value="0.00" />
		</div>
	</div>
	<div class="col-lg-3">
		<div class="form-group">
			<label for="payable_amount">Payable Amount(<?php echo $this->currency_code();?>)</label>
			<input type="text" class="form-control tr-payable_amount" name="payable_amount" id="payable_amount" value="<?php echo $grand_total;?>" readonly />
		</div>
	</div>  
</div>
<script>
	$('#deduction').change(function(){
		var payable_amount = $('#invoice_amount').val() - $(this).val();
		payable_amount = parseFloat(payable_amount).toFixed(2);
		$('#payable_amount').val(payable_amount);
	});
	$( "input:radio" ).on( "click", function() {
		var id = $(this).closest('tr').attr('id');
		$.post( 
			"<?php echo $this->url('contractor', array('action' => 'getdetails'));?>",
			{	
				'id': id,
				'start_date': $('input#start_date').val(),
				'end_date': $('input#end_date').val(),
				'location': $('#location').val(), 
				'activity': $('#activity').val(),
				'contractor':$('#contractor').val(),
			}, 
			function(data) {
				$('div.details').html( data ); 
		});	            
	});
</script>
