<?php
/**
 * View -- of Purchase/ContractorController/repackingAction
 */
	$this->headTitle($this->title);
	echo $this->partial('purchase/contractor/partial.phtml', array('active' => 'repacking')); 
?><br/>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="card">
	<div class="card-header">
		<div class="row">
			<form id="#form" method="post" action="<?php echo $this->url('contractor',array('action' => 'repacking')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-toggle="modal" data-target="#modal" data-tooltip="tooltip" data-placement="top" title="Add New Repacking" href="<?php echo $this->url('contractor', array('action'=>'addrepacking'));?>">
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add</span></span>
					</a>
				</div>
			</div>
		</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Invoice No./<br>Invoice Date</th>
						<th>Work Type/<br>Contractor</th>
						<th>Location/<br>Activity</th>
						<th>Item Name</th>
						<th>UOM</th>
						<th>Qty</th>
						<th>Rate (<?php //echo $this->currency_code();?>)</th>
						<th>Amount (<?php //echo $this->currency_code();?>)</th>
						<th class="no-sort no-printpdf">Action</th>
					</tr>
				</thead>
				<tbody>
					<?php $sl = 1;?>
					<?php foreach($repackings as $row): //echo "<pre>"; print_r($row);?>
					<tr>
						<td><?php echo $sl++;?></td>	
						<td>
							<strong><?php echo $row['repacking_no'];?></strong>
							<?php $this->status($row['status']);?>/<br>
							<?php echo $row['repacking_date']; ?>
						</td>
						<td>
							<?php echo ($row['work_type']=='1')?'Repacking':'Shifting';?>/<br>
							<?php echo $this->partyObj->getColumn($row['contractor'],'code');?>
						</td>
						<td>
							<?php echo $this->locationObj->getColumn($row['location'],'location');?>/<br>
							<?php echo $this->activityObj->getColumn($row['activity'],'activity');?>
						</td>
						<td><?php echo $this->itemObj->getColumn($row['item'],'code');?></td>
						<td><?php echo $this->uomObj->getColumn($row['uom'],'code');?></td>
						<td><?php echo $row['quantity'];?></td>
						<td><?php echo $row['rate'];?></td>
						<td><?php echo $row['amount'];?></td>
						<td class="action">
							<div class="btn-group">
								<?php if($row['status'] == '1'):?>
								<a class="btn btn-xs btn-info" href="<?php echo $this->url('contractor',array('action'=>'editrepacking','id'=>$row['id'])); ?>" title="Edit" data-toggle="modal" data-target="#modal">
									<i class="ace-icon fa fa-pencil bigger-120" ></i> 
								</a>
								<a class="btn btn-xs btn-success" href="<?php echo $this->url('contractor',array('action'=>'commitrepacking','id'=>$row['id'])); ?>" title="Commit">
									<i class="ace-icon fa fa-check bigger-120" ></i> 
								</a>
								<?php endif;?>
								<a data-toggle="modal" data-target = "#modal" class="btn btn-xs btn-danger" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "14-".$row['id'])); ?>" title="View Activity Logs" >
									<i class="ace-icon fa fa-plus bigger-120" ></i>  
								</a>
							</div>
						</td>	 	
					</tr>							
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
});
</script>
