<?php
/**
 * View -- of Sales/FundController/addfundtransferAction
 */
?>
<div class="row">
	<div class="col-lg-12">
        <div class="widget widget-box">
            <div class="widget-header">
            	<h5 class="widget-title lighter smaller">
	            	<i class="fa fa-asterisk"></i> New Fund Transfer
	             </h5>
            </div>
            <div class="widget-body">
				<div class="widget-main">
					<form  id="transForm" method="post" action="<?php echo $this->url('fund', array('action' => 'addfundtransfer')); ?>"  enctype="multipart/form-data" >    
						<div class="row"> 
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="transfer_date" class="control-label">Fund Transfer Date</label>
									<div class="date input-group" id="transfer_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="transfer_date" id="transfer_date" type="text" value="<?php echo date('Y-m-d');?>" placeholder="Transfer Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-4">
								<div class="form-group">
									<label for="transfer_amount" class="control-label">Fund Transfer Amount(<?php echo $this->currency_code();?>)</label>
									<input type="text" class="form-control" name="transfer_amount" id="transfer_amount" placeholder="Fund Transfer Amount" required />
								</div>
							</div>   
						</div>
						<div class="row">
							<div class="col-lg-12"> 
								<h5>Fund Transfer Details</h5>
								<div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>#</th>
												<th>Location</th>
												<th>Activity</th>
												<th>Head</th>
												<th>Sub Head</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td class="col-lg-2">
													<h4 class="smaller ligher blue"><b>Source Details :</b></h4>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="from_location" name="from_location" class="form-control" data-placeholder="Select" required>
															<option value=""></option>
															<?php 
																foreach ($regions as $region):
															?>
																<optgroup label="<?php echo $region['region'];?>">
																		<?php  
																			 // retrive locations under the above region ID
																			 $locations = $locationObj->get(array('l.region'=>$region['id']));
																			  
																			 foreach ($locations as $location):
																		 ?>
																		 <option value="<?php echo $location['id']; ?>">
																			<?php echo $location['location']; ?>
																		 </option>
																		 <?php 
																			 endforeach;
																		 ?>
																 </optgroup>
															<?php 
															  endforeach;
															?>
														</select>
													</div>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="from_activity" name="from_activity" class="form-control"  data-placeholder="Select" required >
															<option value=""></option>
															<?php 
															foreach ($activities as $activity):
															?>
																<option value="<?php echo $activity['id'];?>">
																<?php echo $activity['activity']; ?>
																</option>
															<?php 
															endforeach;
															?>
														</select>
													</div>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="from_head" name="from_head" class="form-control tr_head" data-placeholder="Select" required>
															<option value=""></option>
															<?php 
																foreach ($heads as $head):
															?>
																<option value="<?php echo $head['id'];?>"><?php echo $head['code'];?></option>
															<?php 
																endforeach;
															?>
														</select>
													</div>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="from_sub_head" name="from_sub_head" class="form-control" data-placeholder="Select" required>
															<option value=""></option>
														</select>
													</div>
												</td>
											</tr>
											<tr>
												<td class="col-lg-2">
													<h4 class="smaller ligher green"><b>Destination Details :</b></h4>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="to_location" name="to_location" class="form-control" data-placeholder="Select" required >
															<option value=""></option>
															<?php 
																foreach ($regions as $region):
															?>
																<optgroup label="<?php echo $region['region'];?>">
																		<?php  
																			 // retrive locations under the above region ID
																			 $locations = $locationObj->get(array('l.region'=>$region['id']));
																			  
																			 foreach ($locations as $location):
																		 ?>
																		 <option value="<?php echo $location['id']; ?>">
																			<?php echo $location['location']; ?>
																		 </option>
																		 <?php 
																			 endforeach;
																		 ?>
																 </optgroup>
															<?php 
															  endforeach;
															?>
														</select>
													</div>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="to_activity" name="to_activity" class="form-control"  data-placeholder="Select" required >
															<option value=""></option>
															<?php 
															foreach ($activities as $activity):
															?>
																<option value="<?php echo $activity['id'];?>">
																<?php echo $activity['activity']; ?>
																</option>
															<?php 
															endforeach;
															?>
														</select>
													</div>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="to_head" name="to_head" class="form-control tr_head" data-placeholder="Select" required >
															<option value=""></option>
															<?php 
																foreach ($heads as $head):
															?>
																<option value="<?php echo $head['id'];?>"> <?php echo $head['code'];?></option>
															<?php 
																endforeach;
															?>
														</select>
													</div>
												</td>
												<td class="col-lg-2">
													<div class="form-group">
														<select id="to_sub_head" name="to_sub_head" class="form-control" data-placeholder="Select" required >
															<option value=""></option>
														</select>
													</div>
												</td>
											</tr>									
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<div class="form-group">
									<label for="remarks">Remark (Narration)</label>
									<textarea class="form-control" name="remark" id="remark" ></textarea>  
								</div>
							</div>
						</div>
						<br/>
						<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
						<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button> 
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<br/>
<script type="text/javascript">
	$(function() {
		$('#transfer_date').datepicker();
		
		$("#from_head").change(function() {
			$("#from_sub_head").load('<?php echo $this->url("ajresponse", array("action" => "getsubhead")); ?>'+'/'+ $(this).val(), function() {
				$("#from_sub_head").trigger("chosen:updated");
			});
		});
		
		$("#to_head").change(function() {
			$("#to_sub_head").load('<?php echo $this->url("ajresponse", array("action" => "getsubhead")); ?>'+'/'+ $(this).val(), function() {
				$("#to_sub_head").trigger("chosen:updated");
			});
		});
		
		//formValidation
		$('form')         
		.formValidation({
			framework: 'bootstrap',
	        excluded: ':disabled',
	        message: 'This value is not valid',
	        fields: {
	            'transfer_date': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please enter fund transfer date'
	                    }
	                }
	            },
	            'transfer_amount': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please provide fund transfer amount'
	                    },
						numeric: {
							message: 'Please provide numeric value'
						}
	                }
	            }, 
	            'from_location': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select source location'
	                    }
	                }
	            },
	            'from_activity': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select source activity'
	                    }
	                }
	            },
	            'from_head': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select source head'
	                    }
	                }
	            }, 
	            'from_sub_head': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select source subhead'
	                    }
	                }
	            },  
				'to_location': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select destination location'
	                    }
	                }
	            },
	            'to_activity': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select destination activity'
	                    }
	                }
	            },
	            'to_head': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select destination head'
	                    }
	                }
	            }, 
	            'to_sub_head': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select destination subhead'
	                    }
	                }
	            },  
	        }
		})
		.on('success.field.fv', function(e, data) {
            if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
                data.fv.disableSubmitButtons(true);
            }
        });
		$('#transfer_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
	});
</script> 
