<?php
/**
 * View -- of Sales/SalesController/salesAction
 */
	$this->headTitle($this->title);	
?>

<div class="row">
	<div class="col-lg-12">
		<div class="row">
			<form id="#form" method="post" action="<?php echo $this->url('fund'); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$data['minYear'];$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Fund Transfer" href="<?php echo $this->url('fund', array('action'=>'addfundtransfer'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add</span></span>
					</a>
				</div>
			</div>
		</div>
		
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Transfer No</th>
						<th>Transfer Date</th>
						<th>From Location</th>
						<th>To Location</th>
						<th style="text-align:right" >Transfer Amount (<?php //echo $this->currency_code();?>)</th>
						<th class="no-sort no-printpdf">Action</th>						
					</tr>
				</thead>
				<tbody>
					<?php $i=1;
					foreach($fundtransfers as $fund):
						$year = date('Y', strtotime($fund['transfer_date']));
						$month = date('m',strtotime($fund['transfer_date']));
						
						if($year == $data['year'] && $month == $data['month']):
					?>
						<tr data-href="<?php echo $this->url('fund', array('action'=>'viewfundtransfer', 'id'=>$fund['id']));?>">
							<td><?php echo $i++;?></td>
							<td>
								<?php echo $fund['transfer_no'];?> 
								&nbsp;
								<?php $this->status($fund['status']);?>
							</td>
							<td><?php echo $fund['transfer_date'];?></td>
							<td>
								<b><?php echo $this->locationObj->getColumn($fund['from_location'],'location');?></b>, 
								<?php echo $this->activityObj->getColumn($fund['from_activity'],'activity');?>, 
								<i><?php echo $this->subheadObj->getColumn($fund['from_sub_head'],'name');?></i>
							</td>
							<td>
								<b><?php echo $this->locationObj->getColumn($fund['to_location'],'location');?></b>, 
								<?php echo $this->activityObj->getColumn($fund['to_activity'],'activity');?>, 
								<i><?php echo $this->subheadObj->getColumn($fund['to_sub_head'],'name');?></i>
							</td>
							<td style="text-align:right" ><?php echo $fund['transfer_amount'];?></td>
							<td class="action">
								<div class="btn-group">
									<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "28-".$fund['id'])); ?>" title="View Activity Logs">
										<i class="ace-icon fa fa-plus bigger-120" ></i>  
							  		</a>
						  		</div>
							</td>
						</tr>
					<?php endif;
						endforeach; ?>
				</tbody>	
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>
$("tr[data-href]").each(function(){
	$(this).find('td').not('td.action').each(function(){
		$(this).css('cursor','pointer');
		$(this).bind('click',function() {
			window.document.location = $(this).closest('tr').attr("data-href");
		});
	});
});
</script>