<?php
/**
 * 
 * View -- of Sales/FundController/viewfundtransferAction
 * 
 */
?>
<?php 
	foreach($this->fundtransfers as $row ):
		extract($row);
	endforeach;
?>
<div class="space"></div>
<div class="col-lg-12">
	<div class="widget-box transparent">
		<div class="widget-header widget-header-large">
			<h3 class="widget-title grey lighter">
				<i class="ace-icon fa fa-money green"></i>
				<?php echo $transfer_no;?> | <?php $this->status($status);?>
			</h3>
			<div class="widget-toolbar hidden-xs">
				<a style='cursor:pointer' id="print">
					<i class="ace-icon fa fa-file-pdf-o red"></i>
				</a>
			</div>
			<div class="widget-toolbar hidden-xs">
				<a class="btn btn-white btn-warning btn-bold btn-xs" title="Add New Fund Transfer"
					href="<?php echo $this->url('fund', array('action'=>'addfundtransfer')); ?>">
				&nbsp;<i class="fa fa-plus"></i>&nbsp;</a>
			</div>
		</div>
		<div class="widget-body">
			<div class="widget-main padding-24">
				<div id="report-print">
					<div class="row" id="convert-tb0">
						<div class="col-lg-6" id="convert-tb1">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Transfer Date: <b class="red"><?php echo $transfer_date; ?> </b>
								</li>
							</ul>
						</div>
						<div class="col-lg-6" id="convert-tb2">
							<ul class="list-unstyled spaced pull-right">
                                                                <li>
									<i class="ace-icon fa fa-caret-right blue"></i>Transfer No: <b class="red"><?php echo $transfer_no;?> </b>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Transfer Amount:	<b class="red"><?php echo $this->currency($transfer_amount);?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Naration: <b class="red"><?php echo $remark;?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
						<table class="table table-striped table-bordered table-condensed">	
							<thead>
								<th>#</th>
								<th>Location</th>
								<th>Activity</th>
								<th>Head Name</th>
								<th>Sub Head Account</th>
							</thead>
							<tbody>
								<tr>
									<td><b>From Location</b></td>
									<td><?php echo $this->locationObj->getColumn($from_location,'location');?></td>
									<td><?php echo $this->activityObj->getColumn($from_activity,'activity');?></td>
									<td>
										<?php 
											$from_head = $this->subheadObj->getColumn($from_sub_head,'head');
											echo $this->headObj->getColumn($from_head,'name');
										?>
									</td>
									<td><?php echo $this->subheadObj->getColumn($from_sub_head,'name');?></td>
								</tr>
								<tr>
									<td><b>To Location</b></td>
									<td><?php echo $this->locationObj->getColumn($to_location,'location');?></td>
									<td><?php echo $this->activityObj->getColumn($to_activity,'activity');?></td>
									<td>
										<?php 
											$to_head = $this->subheadObj->getColumn($to_sub_head,'head');
											echo $this->headObj->getColumn($to_head,'name');
										?>
									</td>
									<td><?php echo $this->subheadObj->getColumn($to_sub_head,'name');?></td>
								</tr>
							</tbody>
						</table>
					</div>
					<br/>
					<div class="row">
						<div class="col-lg-3">
							<label> Prepared by: <?php echo $this->userObj->getColumn($author,'name');?></label>
							<br/><br/>
						</div>
						<div class="col-lg-6">
						   &nbsp; 
						</div>
						<div class="col-lg-3">
							<?php if($status == '1'):?>
								<a href="<?php echo $this->url('fund', array('action'=>'editfundtransfer', 'id'=>$id));?>" class="btn btn-success"> <i class="fa fa-pencil"></i> Edit</a>
								<a href="<?php echo $this->url('fund', array('action'=>'bookfundtransfer', 'id'=>$id));?>" class="btn btn-info"> <i class="fa fa-money"></i> Book Fund Tranfer </a>
							<?php endif; ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$('#print').genpdfinvoice({
	content: '#report-print',
	src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
	orentation:"P",//L =landscape, P = potrait
});
</script>
