<?php  
	switch ($this->po_sinv){
	case  1:    $po_inv_label = "Purchase Order";
				$sinvdtls = $this->podtlsObj->get($this->sinvdtl_id);
				foreach ($sinvdtls as $row):
					//print_r($row);						  
					extract($row);
					$given_uom = $uom_id;
					$sinv_detail = $id;
					$basic_uom = $this->itemObj->getColumn($item_id, "uom");
					if($basic_uom == $given_uom)
					{  
					  $c_rate = $rate; $basicQty = $quantity; 
					}
					else
					{ 
					  $conversion = $this->uomitemObj->getColumn(array('item'=>$item_id, 'uom'=>$given_uom), "conversion");
					  $conversion = ($conversion > 0)?$conversion:1;
					  $c_rate = $rate / $conversion;  
					  $basicQty = $quantity * $conversion;							
					}											
					$c_qty = $quantity;							
					$challan_unit = $uom;							
				endforeach;
				$result = $this->uomitemObj->get(array('item'=>$item_id, 'costing_uom'=>'1'));
				if(sizeof($result)>0) { 
					foreach($result as $dtl); $c_units = $dtl['conversion'];
				}else{
					$uomDtls = $this->uomObj->get($basic_uom);
					foreach($uomDtls as $uomdtl): $uom_type = $uomdtl['uom_type']; endforeach; 
					if($uom_type == '2' ||  $uom_type == '3'){ $c_units = '1000'; }
					else{ ?>
					 <div class="alert alert-warning fade in"> 
						*Standard UOM not assigned for costing
					 </div>
					<?php exit;  }					
				}
				break;
	case 2:     $po_inv_label = "Supplier Invoice";
				$sinvdtls = $this->sinvdtlsObj->get($this->sinvdtl_id);
				foreach ($sinvdtls as $row):	
					//print_r($row);
					extract($row);
					$given_uom = $uom_id;
					$sinv_detail = $id;
					$basic_uom = $this->itemObj->getColumn($item_id, "uom");
					if($basic_uom == $given_uom)
					{ $c_rate = $rate;  $basicQty = $quantity;  }
					else
					{
						$conversion = $this->uomitemObj->getColumn(array('item'=>$item_id, 'uom'=>$given_uom), "conversion"); 
						$conversion = ($conversion > 0)?$conversion:1;
						$c_rate = $rate / $conversion;  
						$basicQty = $quantity * $conversion;							  
					}												
					$c_qty = $quantity;
					$challan_unit = $uom; 
				endforeach;
				$result = $this->uomitemObj->get(array('item'=>$item_id, 'costing_uom'=>'1'));
				if(sizeof($result)>0) { 
					foreach($result as $dtl); $c_units = $dtl['conversion'];
				}else{
					$uomDtls = $this->uomObj->get($basic_uom);
					foreach($uomDtls as $uomdtl): $uom_type = $uomdtl['uom_type']; endforeach; 
					if($uom_type == '2' ||  $uom_type == '3'){ $c_units = '1000'; }
					else{ ?>
					 <div class="alert alert-warning fade in"> 
						*Standard UOM not assigned for costing
					 </div>
					<?php exit; }					
				}
				break;
	} // end of switch  	
	$item_code = $this->itemObj->getColumn($this->item_id, 'name');	
?>
<div class="alert alert-success fade in"> 
     * Costing Details of <b><?php echo $item_code; ?> </b>
</div>
<div id="row">
   <div class="col-lg-4">
	  <table class="table table-striped table-bordered table-hover" id="dataTables">		
		<thead>	<tr><th> <?php echo  $po_inv_label; ?> &nbsp;Details </th><th> Value </th></tr></thead>
		<tbody>
			<tr>
				<td><b><?php echo  $po_inv_label; ?> Rate</b></td>
				<td><?php echo $c_rate; ?> </td>
			</tr>
			<tr>
    			<td><b>Basic UOM | Basic Quantity</b></td>
    			<td><?php echo $this->uomObj->getColumn($basic_uom,"code"); ?> | <?php echo $basicQty; ?></td>
			</tr>
			<tr>
				<td><b><?php echo  $po_inv_label; ?> UOM | Quantity</b></td>
				<td> <?php echo $challan_unit; ?> | <?php echo $c_qty; ?></td>
			</tr>
			<tr>
				<td><b>Units/UoM</b></td>
				<td><?php echo $c_units; ?> <input type="hidden" name="unit_uom" value="<?php echo $c_units;?>" ></td>
			</tr>
			
			<?php 
			if(sizeof($invdefdtls)>0):
				foreach ($invdefdtls as $defdata):				
				?>
				<tr>
					<td><b><?php echo $defdata['def_field']; ?></b></td>
					<td><?php echo $defdata['data']; ?></td>
				</tr>
				<?php 
				endforeach;
			endif; 
			?>	
			<?php if($this->valuation == "1"): 
			$prevDtls = $this->costItemDtlsObj->getLatestCostingDtls($this->item_id); ?>
			<tr><td colspan="2"><b>Reference Purchase Details</b></td>				
			<?php 
			if(sizeof($prevDtls) > 0):
			   foreach ($prevDtls as $dtl): 
			        $ref_rate = $dtl['rate'];
			        $batch_id = $dtl['batch'];
			        $po_sinv_dtl_id = $dtl['po_sinv_dtl'];
			        $costing_sheet_id = $dtl['costing_sheet'];
					$rate_taken = $dtl['rate_taken'];
			   endforeach;
			   
			    foreach($this->costSheetObj->get($costing_sheet_id) as $sheet):
			          $ref_po_sinv = $sheet['po_invoice'];
			          $po_sinv_no = $sheet['po_invoice_no'];
				endforeach;
			   
				if($ref_po_sinv == "1"){
					//PO 
					$po_sinv_No = $this->porderObj->getColumn($po_sinv_no, 'po_no'); 
					$label_po_sinv = "Purchase Order";
				}else{
					//Supplier Inv.
					$po_sinv_No = $this->sinvObj->getColumn($po_sinv_no, 'invoice_no');
					$label_po_sinv = "Supplier Invoice";
				}  
			?>
			<tr><td><b><?php echo  $label_po_sinv; ?> No. </b></td><td><?php echo $po_sinv_No; ?></td> </tr>
			<tr>
				<td><b>Current Stock Rate</b></td>
				<td><?php echo $ref_rate; ?></td>
			</tr>
			<tr>
				<td><b>Rate Taken For Costing</b></td>
				<td><?php
						$actual_rate_taken = $dtl['rate_taken_value'];
						if($actual_rate_taken == ''):
							if($rate_taken == 1){
								$rate_label = "Previous Stock Rate";
								$actual_rate_taken = $dtl['ref_rate'];
							}elseif($rate_taken == 2){
								$rate_label = "Current Stock Rate";
								$actual_rate_taken = $dtl['rate'];
							}elseif($rate_taken == 3){
								$rate_label = "Wt.Moving Avg Rate";
								$actual_rate_taken = $dtl['avg_rate'];
							}else{
								$rate_label = "Current Stock Rate Default";
								$actual_rate_taken = $dtl['rate'];
							}
						else:
							if($rate_taken == 1){
								$rate_label = "Previous Stock Rate";
							}elseif($rate_taken == 2){
								$rate_label = "Current Stock Rate";
							}elseif($rate_taken == 3){
								$rate_label = "Wt.Moving Avg Rate";
							}else{
								$rate_label = "Current Stock Rate Default";
							}
							$actual_rate_taken = $actual_rate_taken;
						endif;
						echo $rate_label." | ".$actual_rate_taken;
					?>
				</td>
			</tr>
			<tr><td><b>Current Stock Balance</b></td>
			<td><?php echo $stock_balance = $this->movingItemTableObj->getStockBalance($column='quantity', $where=array('item'=>$this->item_id)); ?></td></tr>
			<?php else: ?>
			<tr>
				<td colspan="2"><i> * Cannot fetch previous costing records, the item must be new </i></td>
			</tr>
			<?php endif; 
			endif; 
			?>						 
		</tbody>
	</table>
	<?php if($this->valuation == "1" && sizeof($prevDtls) > 0): ?>
		<h4>Weighted Moving Average</h4>
		<h6> X = (X1 * Y1 + X2 * Y2) / ( Y1 + Y2 ) </h6>
		<span> where,<br> X1, Y1 = New purchase Rate, Quantity
			<br> X2, Y2 = Current Stock Rate, Balance Quantity <br>
			X = Weighted Moving Average Rate
		</span> 
	<?php
		$X1 = $c_rate ; $X2 = $actual_rate_taken; $Y1 = $basicQty; $Y2 = $stock_balance;
		$X = round(($X1 * $Y1 + $X2 * $Y2) / ( $Y1 + $Y2 ),3);
		echo "<h5> X = ". $X . "</h5>"?> 
	<?php endif; ?>
	</div>	
	<div class="col-lg-8">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Costing Head</th>
					<th>Value</th>
					<th>Calculation</th>
					<th>Formula</th>
				</tr>
			</thead>		  
			<tbody>	  
			<?php 	
			$sl = 1;
			$sheetValue = array();		
			foreach ($this->costformuladtls as $formuladtl): 
			 // echo"<pre>"; print_r($formuladtl);   		
			?>
			   <tr>		     
					<td><?php echo $sl++; ?></td>
					<td><b><?php echo $formuladtl['description']; ?></b></td>
					<td>
					<?php 
						// calculation
						$string = $formuladtl['formula'];
						$needle1 = "[";
						$needle2 = "]";
						$lastPos = 0;
						$Pos = 0;
						$start_pos = array();
						$end_pos = array();
					   
						while (($lastPos = strpos($string, $needle1, $lastPos))!== false) {
							$start_pos[] = $lastPos;						
							$lastPos = $lastPos + strlen($needle1);						
						}
						
						while (($Pos = strpos($string, $needle2, $Pos))!== false) {
							$end_pos[] = $Pos;
							$Pos = $Pos + strlen($needle2);
						} 
						
						$variables = array();					
						if($start_pos[0] > 0 ){
								$opt = substr($string, 0, 1); 
								array_push($variables, $opt);
						}		
							
						for($i = 0; $i < sizeof($start_pos); $i++){                          		
							$len = $end_pos[$i] - $start_pos[$i]; 
							$var = substr($string, $start_pos[$i] + 1, $len - 1);
							if(strlen($var) > 0) { array_push($variables, $var ); }
							
							$j = $i + 1;
						
							$diff = $start_pos[$j] - $end_pos[$i]; 
							if($diff > 2){
								 for($k = $len+1; $k < ($len+$diff); $k++){
									  $opt = substr($string, $start_pos[$i]+$k, 1);  
									  array_push($variables, $opt);
									}		
							}						
							else{
							  $operPos = $start_pos[$i] + $len + 1 ;
							  $operator = substr($string, $operPos, 1);
							  if(strlen($operator) > 0 ) { array_push($variables, $operator); }
							}
						}
										  
						$formula = ""; 
						
						foreach($variables as $var):
							$stored_operators = array("/","*","-","+", "(", ")"); 
							//Check whether the variable is operator or not
							if( in_array($var, $stored_operators)){
								$formula =  $formula.$var;
							}
							else
							{      
								$table = substr($var, 0, 1); // get the table name to fetch data
								switch($table)
								{
									case "I":// get the supplier Invoice columns value
											$field = substr($var, 2);
											if($field == "rate"):
												if($this->valuation == "1" && sizeof($prevDtls) > 0){
													 $value = $selling_price;
												}
												else{
													$value = $c_rate;
												}
											elseif($field == "unit_uom"):
													$value = $c_units;
											elseif($field=="quantity"):
												   $value = $basicQty; 								
											endif;
											$formula = $formula.$value;
											break; 
									case "S": //get values from formula sheet 		
											$field = substr($var, 2);
											$formula = $formula.$sheetValue[$field];
											  break;
									case "C": // get values from charge tax
											$field = substr($var, 2);
											$chargeDtls = $this->chargeObj->get(array('charge_tax'=>$field));
											foreach ($chargeDtls as $charge):
												if($charge['percentage'] == "1"){
													$chargeValue = $charge['value']/100;
												}
												else {
													$chargeValue = $charge['value'];
												}
												//echo "<i>[".$field.":".$chargeValue."]</i>&nbsp;";  
												$formula = $formula . $chargeValue; 
											endforeach;
											//  echo  $chargeValue; 
											break;
									case "B": // get values from Item table
											$field = substr($var, 2);
											$field_name = ($field == "BST")?"bst":"net_weight";
											$b_value = $this->itemObj->getColumn($item_id, $field_name);
											if($field_name == "net_weight"){
												$net_uom = $this->itemObj->getColumn($item_id, "scalar_uom"); 
												if( $net_uom == "13001"){ 
													$wt_value = $b_value / 10000;  
												}elseif($net_uom == "15001"){ 
													$wt_value = $b_value / 1000; 
												}											   
												$formula = $formula.$wt_value;
											}elseif($field_name == "bst"){
													$bstValue = $b_value/100;
													$formula = $formula.$bstValue;
											} 	
											break;
									case "D": 
											$defValue = 0;								
											$field = substr($var, 2);  
											$invDefFieldID = $this->InvDefFieldObj->getColumn(array('def_field'=>$field),'id');
											if($invDefFieldID > 0){ 
												$invDefDtlID = $this->InvDefDtlsObj->getColumn(array('inv_def'=>$this->invdefID,'inv_def_field'=>$invDefFieldID), 'id'); 
												if($invDefDtlID > 0){  
													$defValue = $this->InvDefDataObj->getColumn(array('sinv_details'=>$this->sinvdtl_id, 'def_details'=> $invDefDtlID),'data'); 
												}
											}
											$formula = $formula.$defValue;  
								}
							}	 						
						endforeach; 
											 
						$sheetValue[$formuladtl['description']] = eval('return '.$formula.";"); 
						if($formuladtl['elc'] == '1'){ 
							echo "<b>".round($sheetValue[$formuladtl['description']], 3)."<i>&nbsp;[elc]</i></b>";  					  
						}else{ 
							echo round($sheetValue[$formuladtl['description']], 3); 
						}				    
					?>			
				</td>
				<td> <?php echo $formula."&nbsp;"; ?></td>
				<td><span style="font-size:12px;">   <?php echo $formuladtl['formula']; ?></span></td>
			  </tr>
			<?php endforeach;?>		    
			</tbody>
		</table>
	</div>
</div>
*Make sure <b><i>[elc]</i></b> is placed against the standard costing UOM instead of Basic UOM, Otherwise please contact Administrator.

