<?php
/**
 * View -- Stock\CostingController\speffectdateAction
 */
?>
<div class="modal-panel">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h5 class="modal-title"> <i class="fa fa-asterisk"></i> Set Selling Price Effect Date </h5>
	</div>  <!-- /modal-header -->

	<div class="modal-body">
		<form id="#form" method="post" action="<?php echo $this->url('cost', array('action' => 'speffectdate')); ?>"  enctype="multipart/form-data" >
			<div class="row"> 	
				<div class="col-lg-6 form-group">
					<input type="hidden" name="costing_sheet_id" id="costing_sheet_id" value="<?php echo $costing_sheet_id; ?>" />
					<label for="sp_effect_date" class="control-label">Set Selling Price Effect Date</label>
					<div class="date input-group" id="sp_effect_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="sp_effect_date" id="sp_effect_date" type="text" placeholder="Selling Price Effect Date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="space-12"></div>
					<button type="submit" class="btn btn-success btn-sm"><i class="fa fa-check"></i> Save SP Effect Date </button>
				</div>
			</div>
		</form>
	</div>
	<div class="modal-footer">
		<div class="row">
			<div class="col-lg-12">
				<table class="table table-striped table-bordered table-hover" >
					<thead>
						<tr>
							<th>#</th>
							<th>Item</th>
							<th>Batch</th>
							<th>Batch Status</th>
                                                        <th>SP Effect Date</th>
						<tr>
					</thead>
					<tbody>
						<?php
							$i = 1;
							foreach($costingitems as $costingitem):
						?>
						<tr>
							<td><?php echo $i++;?></td>
							<td><?php echo $this->itemObj->getColumn($costingitem['item'],'name');?></td>
							<td><?php echo $this->batchObj->getColumn($costingitem['batch'],'batch');?></td>
							<td><?php echo $this->status($this->batchObj->getColumn($costingitem['batch'],'status'));?></td>
                                                        <td><?php echo $costingitem['sp_effect_date'];?></td>
						</tr>
						<?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>	
	</div>
</div>
<script type="text/javascript">
	$('#sp_effect_date').datepicker();
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				sp_effect_date: {
					validators: {
						notEmpty: {
							message: 'Please Select Sp Effect Date.'
						},
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
	$('#sp_effect_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
</script>

