<?php if(sizeof($this->invDtls) > 0): ?>
<?php 
 if($this->po_sinv == 1):
    $po_sinv = "Purchase Order";	
	$route = "purorder"; $action = "viewporder"; 		
	$po_sinv_no = $this->porderObj->getColumn($this->po_sinv_id, 'po_no');							
 elseif($this->po_sinv == 2):
    $po_sinv = "Supplier Invoice";
	$route = "supplier"; $action = "viewsupplierinv"; 
	$po_sinv_no = $this->invoiceObj->getColumn($this->po_sinv_id, 'invoice_no');
 endif; 
 //check if any of the item is wt. moving avg
 foreach ($this->invDtls as $invdtl):
	$item_valuation = $this->itemObj->getColumn($invdtl['item_id'],'valuation');
	$check_array = array();
	if($item_valuation == '1'):
		array_push($check_array,$invdtl['id']);
	endif;
 endforeach;
?>
<h4>List of Items<?php echo $po_sinv; ?> No. <a href="<?php echo $this->url($route, array('action'=>$action, 'id'=>$this->po_sinv_id));?>" target="_blank"><?php echo $po_sinv_no;?></a></h4>
<table class="table table-striped table-bordered table-hover" id="trdetails_table">
	<thead>
		<tr>
			<th>#</th>
			<th>Item</th>
			<th>Batch No</th>
			<th>Status</th>
			<?php if(sizeof($check_array)>0):?>
			<th>Current Stock Rate</th>
			<th>New Purchase Rate</th>
			<th>Weighted Moving Avg</th>
			<?php endif;?>
			<th>Action <label class="ace bolder blue">
			<input type="checkbox" id="checkAll" class="ace" />
			  &nbsp;<span class="lbl"> Select All</span>
		    </label></th>
		</tr>
	</thead>
	<tbody>
	    <?php 
			$sl = 1;
			$i=0;
			foreach ($this->invDtls as $invdtl):	
			//echo"<pre>";print_r($invdtl);		  
				extract($invdtl);
				$given_uom = $uom_id;
				$sinv_detail = $id;
				$basic_uom = $this->itemObj->getColumn($item_id, "uom");
				if($basic_uom == $given_uom)
				{  
				  $c_rate = $rate; $basicQty = $quantity; 
				}
				else
				{ 
				  $conversion = $this->uomitemObj->getColumn(array('item'=>$item_id, 'uom'=>$given_uom), "conversion");
				  $conversion = ($conversion > 0)?$conversion:1;
				  $c_rate = $rate / $conversion;  
				  $basicQty = $quantity * $conversion;							
				}		
				//$c_rate = round($c_rate,3);
				$c_qty = $quantity;							
				$challan_unit = $uom;
					
				$item_valuation = $this->itemObj->getColumn($item_id,'valuation');
				if($item_valuation == "1"): 
					$prevDtls = $this->costItemDtlsObj->getLatestCostingDtls($item_id); 
			
					if(sizeof($prevDtls) > 0):
						foreach ($prevDtls as $dtl): 
							$ref_rate = $dtl['rate'];
							$batch_id = $dtl['batch'];
							$po_sinv_dtl_id = $dtl['po_sinv_dtl'];
							$costing_sheet_id = $dtl['costing_sheet'];
							$rate_taken = $dtl['rate_taken'];
						endforeach;
						$actual_rate_taken = $dtl['rate_taken_value'];
						if($actual_rate_taken == ''):
							if($rate_taken == 1){
								$actual_rate_taken = $dtl['ref_rate'];
							}elseif($rate_taken == 2){
								$actual_rate_taken = $dtl['rate'];
							}elseif($rate_taken == 3){
								$actual_rate_taken = $dtl['avg_rate'];
							}else{
								$actual_rate_taken = $dtl['rate'];
							}
						else:
							$actual_rate_taken = $actual_rate_taken;
						endif;
						
						$stock_balance = $this->movingItemTableObj->getStockBalance($column='quantity', $where=array('item'=>$item_id));
						$stock_balance = round($stock_balance,3);
						$X1 = $c_rate ; $X2 = $actual_rate_taken; $Y1 = $basicQty; $Y2 = $stock_balance;
						$X = round(($X1 * $Y1 + $X2 * $Y2) / ( $Y1 + $Y2 ),3);
					endif;
				endif;
			?>
				<tr>
	                <td><?php echo $sl++; ?></td>
	                <td>
						<a href="<?php echo $this->url('stock', array('action' => 'viewitem', 'id' => $invdtl['item_id'])); ?>" target="_blank">	
						<?php echo $this->itemObj->getColumn($invdtl['item_id'],'code'); ?>
						</a>			
					</td>
	                <td></td>
	                <td><?php echo $invdtl['status']; ?></td>
					<?php if(sizeof($check_array)>0):
						if(sizeof($prevDtls) > 0):?>
	                <td><input type="radio" class="tr-rate" name="rate-<?php echo $invdtl['id'];?>" id="rate-<?php echo $invdtl['id'];?>" value="<?php echo $actual_rate_taken; ?>" <?php echo ($ref_rate == $c_rate)?'checked':'';?> /> <?php echo $this->decimal($ref_rate); ?></td>
	                <?php else:?>
					<td>-</td>
					<?php endif;?>
					
					<td><input type="radio" class="tr-rate" name="rate-<?php echo $invdtl['id'];?>" id="rate-<?php echo $invdtl['id'];?>" value="<?php echo $c_rate; ?>" <?php echo ($ref_rate <  $c_rate)?'checked':'';?>/> <?php echo $this->decimal($c_rate); ?></td>
	                
					<?php if(sizeof($prevDtls) > 0): ?>
					<td><input type="radio" class="tr-rate" name="rate-<?php echo $invdtl['id'];?>" id="rate-<?php echo $invdtl['id'];?>" value="<?php echo $X; ?>" <?php echo ($ref_rate >  $c_rate)?'checked':'';?>/> <?php echo $this->decimal($X); ?></td>
	                <?php else:?>
					<td>-</td>
					<?php endif; 
					endif;?>
					<td class="form-group">
					    <?php $valuation = $this->itemObj->getColumn($invdtl['item_id'],'valuation'); ?> 
						<input type="hidden" name="itemvaluation" id="itemvaluation" value="<?php echo $valuation;?>" />
		                <input type="hidden" name="sinvid[]" id="sinvid" value="<?php echo $invdtl['id']; ?>" class="sinvid">		                		              
		                  <input class="valuation" type="checkbox" name="valuation[]" id="valuation" value="<?php echo $invdtl['id']; ?>" > 
						   <?php if($valuation == "0"){ ?> FIFO (First In First Out)&nbsp;	<?php } 
						         elseif($valuation == "1"){ ?>  Weighted Moving Average <?php } ?>	
		            </td>
				</tr>
	           <?php
	       endforeach;
	    ?>
	</tbody>
</table>
<strong>* Confirm and be sure about the Item valuation [FIFO or Weighted Moving Average] before costing</strong>
   
<?php endif; ?>				

<script>
	var i = 0;
	$('tbody tr').each(function(){
		$(this).attr('id', ++i); 
		var oldid = $(this).find('input:hidden.sinvid').attr('id');
		$(this).find('input:hidden.sinvid').attr('id', oldid + '-' + i);   

		var old = $(this).find('input#valuation').attr('id');
		$(this).find('input#valuation').attr('id', old + '-' + i);
		
		var old1 = $(this).find('input#itemvaluation').attr('id');
		$(this).find('input#itemvaluation').attr('id', old1 + '-' + i);
	}); 

	$( "input:checkbox.valuation" ).on( "click", function() {
		var id = $(this).closest('tr').attr('id');
		if ( $('#valuation-'+ id).prop( "checked" ) ) { 
			$.post(
				"<?php echo $this->url('cost', array('action' => 'calculatecost')); ?>",
				{
					sinvid: $('#sinvid-'+ id).val(),
					itemvaluation: $('#itemvaluation-'+ id).val(),
					elc_source: $("#elc_source").val(),
					selling_price: $("input[name=rate-"+$('#sinvid-'+id).val()+"]:checked").val(),
				},
				function(data){
					//console.log(data);
					$("#costdtls").html(data);
				}
			);
		}
		else{
			$( "#costdtls" ).empty(); 
		};	
	});  
	
	$( ".tr-rate" ).on( "change", function() {
		var id = $(this).closest('tr').attr('id');
		if ( $('#valuation-'+ id).prop( "checked" ) ) { 
			$.post(
				"<?php echo $this->url('cost', array('action' => 'calculatecost')); ?>",
				{
					sinvid: $('#sinvid-'+ id).val(),
					itemvaluation: $('#itemvaluation-'+ id).val(),
					elc_source: $("#elc_source").val(),
					selling_price: $("input[name=rate-"+$('#sinvid-'+id).val()+"]:checked").val(),
				},
				function(data){
					//console.log(data);
					$("#costdtls").html(data);
				}
			);
		}
		else{
			$( "#costdtls" ).empty(); 
		};	
	});  
	$("#checkAll").change(function () {
		$("input:checkbox").prop('checked', $(this).prop("checked"));
		// $( "#costdtls" ).empty();
	}); 
</script>
