<?php
/**
 * 
 * View -- of Sales/MasterposController/addsubservicesAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'addfees')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-plus"></i> Add Fees</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="sub_service" class="control-label">Fees</label>
					<input type="text" class="form-control" name="sub_service" id="sub_service" placeholder="Sub Service" required>
				</div>
				<div class="form-group">
                    <label for="service" class="control-label">Service</label>
					<select class="form-control" name="service" id="service" data-placeholder="Select" required > 
						<option value="-1">None</option>	
						<?php foreach($service as $row): ?>
                            <option value="<?php echo $row['id'];?>">
								<?php echo $row['service'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
                sub_service: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide service.'
                        }
                    }
                },
                service: {
                    validators: {
                        callback: {
                            message: 'Please Select Services.',
                            callback: function(input) {
                                return (input.value != "-1");
                            }
                        }
                    }
                },
            },
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
