<?php
/**
 * 
 * View -- of Hr/MasterController/addapptypeAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'addservicetarriff')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> Service Tarriff</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			                       
			<div class="panel-body"> 
				<div class="form-group">
                    <label for="scope" class="control-label">Scope</label>
					<select class="form-control" name="scope" id="scope" data-placeholder="Select" required > 
						<option value="-1">None</option>	
						<?php foreach($scope as $row): ?>
                            <option value="<?php echo $row['id'];?>">
								<?php echo $row['scope'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group">
                    <label for="service" class="control-label">Service</label>
					<select class="form-control" name="service" id="service" data-placeholder="Select" required > 
						<option value="-1">None</option>	
					</select>
				</div>
				<div id="international" class="form-group">
					<label for="country" class="control-label">Country</label>
					<select class="form-control" name="country" id="country" data-placeholder="Select"  > 
						<option value=""></option>
						<?php foreach($country as $countrys):?>
							<option value="<?php echo $countrys['id'];?>"><?php echo $countrys['name'];?></option>
						<?php endforeach;?>
					</select>
				</div>
				<div id="international" class="form-group">
					<label for="city" class="control-label">City</label>
					<select class="form-control" name="city" id="city" data-placeholder="Select"  > 
						<option value=""></option>
					</select>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	$('select#scope').on('change', function () {
			if ($(this).val() === '1') {
				$('div#international').hide();
			} else {
				$('div#international').show();
			}
		});

	$('select#scope').on('change',function(){
		$.post(
			"<?php echo $this->url('postage', array('action' => 'getservice'));?>",
			{
				scopeId: $(this).val(),
			},
			function(data){
				$('select#service').html(data.service);
				$('select#service').trigger('chosen:updated');
			},
			'json'
		);
	});
	$('select#country').on('change',function(){
		$.post(
			"<?php echo $this->url('masterpos', array('action' => 'getcity'));?>",
			{
				countryId: $(this).val(),
			},
			function(data){
				$('select#city').html(data.city);
				$('select#city').trigger('chosen:updated');
			},
			'json'
		);
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			apptype: {
					validators: {
						notEmpty: {
							message: 'Please provide appointment type.'
						}
					}
				},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
