<?php
/**
 * View -- of Administration/MasterController/addactivity
 * chophel@athang.com
 */
?>
<?php 
	foreach($this->fixslab as $row );?>
    <form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'deletefixslab','id'=>$row['id'])); ?>" enctype="multipart/form-data">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"> <i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
        </div>     
        <div class="modal-body">    
            <div class="panel panel-default">                       
                <div class="panel-body">
                <input type="hidden" name="tarrif_for_services_id"  value="<?php echo $row['tarrif_for_services_id'] ?>"> 
                        <i class="ace-icon fa fa-trash fa-2x red"></i>
                        <b>Do you want to continue to delete?</b>
                        <h5 class="widget-title grey lighter">
                    </h5>
                </div>
            </div>
        </div>    
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger"><i class="fa fa-check"></i> Delete </button>
            <button type="button" class="btn btn-success" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
        </div>  
    </form>  
