<?php
/**
 * 
 * View -- of Sales/MasterposController/addsubservicesAction
 * 
 */
    foreach($postoffice as $row);
?>
<form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'editpostoffice','id'=>$row['id'])); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-edit"></i> Edit Post Office</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="post_office" class="control-label">Post Office</label>
					<input type="text" class="form-control" name="post_office" value="<?php echo $row['post_office']?>"id="post_office" placeholder="Post Office" required>
				</div>
				<div class="form-group">
					<label for="post_code" class="control-label">Postal Code</label>
					<input type="text" class="form-control" name="post_code" id="post_code" value="<?php echo $row['post_code']?>" placeholder="Postal Code" required>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
              post_code: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide post code.'
                        }
                    }
                },
                post_office: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide post offcie.',
                        }
                    }
                },
            },
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
