<?php
/**
 * 
 * View -- of Sales/MasterposController/addaservicesAction
 * 
 */
foreach($service as $row);
?>
<form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'editservice','id'=>$row['id'])); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-edit"></i> Edit Service</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="service" class="control-label">Service</label>
					<input type="text" class="form-control" name="service" id="service" value="<?php echo $row['service'];?>"placeholder="Service" required>
				</div>
				<div class="form-group">
					<label for="scope" class="control-label">Scope</label>
					<select class="form-control" id="scope" name="scope" data-placeholder="Select" required >
						<option value=""></option>
						<?php foreach ($scope as $scopes):
						$selected = ($row['scope']==$scopes['id'])?'selected':'';?>
							<option value="<?php echo $scopes['id'];?>" <?php echo $selected;?>>
								<?php echo $scopes['scope'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<!-- <div class="form-group">
					<label for="status" class="control-label">Status</label>
					<input type="text" class="form-control" name="status" id="status" placeholder="Service" required>
				</div> -->
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
                service: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide service.'
                        }
                    }
                },
                scope: {
                    validators: {
                        callback: {
                            message: 'Please Select Scope.',
                            callback: function(input) {
                                return (input.value != '-1');
                            }
                        }
                    }
                },
            },
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
