<?php
/**
 * 
 * View -- of Sales/MasterController/addschemetype
 * 
 */
?>
<?php foreach($fixfactor as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'editfixedfactor','id'=>$row['id'])); ?>" enctype="multipart/form-data">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> Add New Service</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">  
				<div class="form-group">
					<label for="scope" class="control-label">Scope</label>
					<select class="form-control" name="scope" id="scope" data-placeholder="Select" required > 
						<option value=""></option>
                        <?php foreach($scope as $scopes): ?>
                            <option value="<?php echo $scopes['id'];?>" <?php echo ($scopes['id'] == $row['scope'])?'selected':'';?>>
								<?php echo $scopes['scope'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group">
                    <label for="service" class="control-label">Service</label>
					<select class="form-control" name="service" id="service" data-placeholder="Select" required > 
						<option value="-1">None</option>	
						<?php foreach($service as $services): ?>
                            <option value="<?php echo $services['id'];?>" <?php echo ($services['id'] == $row['service'])?'selected':'';?>>
								<?php echo $services['service'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group col-lg-4">
					<input type="radio" name="country" value="1" <?php echo ($row['country']=='1')?"checked":"";?> id="blue-radio">
					<label for="blue-radio">Country</label><br>
				</div>
				<div class="form-group col-lg-4">
					<input type="radio" name="city" value="1" <?php echo ($row['city']=='1')?"checked":"";?> id="blue-radio"> 
					<label for="green-radio">City</label><br>
				</div>
				<div class="form-group col-lg-4">
					<input type="radio" name="scope" value="1" <?php echo ($row['service_scope']=='1')?"checked":"";?> id="blue-radio"> 
					<label for="green-radio">Scope</label><br>
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	$('select#scope').on('change',function(){
		$.post(
			"<?php echo $this->url('postage', array('action' => 'getservice'));?>",
			{
				scopeId: $(this).val(),
			},
			function(data){
				$('select#service').html(data.service);
				$('select#service').trigger('chosen:updated');
			},
			'json'
		);
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			service: {
				validators: {
					notEmpty: {
						message: 'Please select service.'
					}
				}
			},
			
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>







