<?php
/**
 * 
 * View -- of Sales/MasterposController/addsubservicesAction
 * 
 */
foreach($feestarriff as $row);
?>
<form id="#form" method="post" action="<?php echo $this->url('masterpos', array('action' => 'editfeestarriff','id'=>$row['id'])); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-edit"></i> Edit Fees Tarriff</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="scope" class="control-label">Scope</label>
					<select class="form-control" name="scope" id="scope" data-placeholder="Select" required > 
						<option value=""></option>
                        <?php foreach($scope as $scopes): ?>
                            <option value="<?php echo $scopes['id'];?>" <?php echo ($scopes['id'] == $row['scope'])?'selected':'';?>>
								<?php echo $scopes['scope'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
				<div class="form-group">
                    <label for="service" class="control-label">Service</label>
					<select class="form-control" name="service" id="service" data-placeholder="Select" required > 
						<option value="-1">None</option>	
						<?php foreach($service as $services): ?>
                            <option value="<?php echo $services['id'];?>" <?php echo ($services['id'] == $row['service'])?'selected':'';?>>
								<?php echo $services['service'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
               <div class="form-group">
                    <label for="fees" class="control-label">Fees</label>
					<select class="form-control" name="fees" id="fees" data-placeholder="Select" required > 
						<option value="-1">None</option>	
						<?php foreach($fees as $fee): ?>
                            <option value="<?php echo $fee['id'];?>"<?php echo ($fee['id'] == $row['fees'])?'selected':'';?>>
								<?php echo $fee['fees'];?>
							</option>
						<?php
						endforeach;
						?>
					</select>
				</div>
                <div class="form-group">
					<label for="charges" class="control-label">Charges</label>
					<input type="text" class="form-control" name="charges" id="charges" value="<?php echo $row['charges']?>"placeholder="Sub Service" required>
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
    $('select#service').on('change',function(){
		$.post(
			"<?php echo $this->url('masterpos', array('action' => 'getsubservice'));?>",
			{
				serviceId: $(this).val(),
			},
			function(data){
				$('select#subservice').html(data.subservice);
				$('select#subservice').trigger('chosen:updated');
			},
			'json'
		);
	});
	$('select#scope').on('change',function(){
		$.post(
			"<?php echo $this->url('masterpos', array('action' => 'getservice'));?>",
			{
				scopeId: $(this).val(),
			},
			function(data){
				$('select#service').html(data.service);
				$('select#service').trigger('chosen:updated');
			},
			'json'
		);
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
                subservice: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide service.'
                        }
                    }
                },
                charges: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide charges.'
                        }
                    }
                },
                service: {
                    validators: {
                        callback: {
                            message: 'Please Select Services.',
                            callback: function(input) {
                                return (input.value != "-1");
                            }
                        }
                    }
                },
                fees: {
                    validators: {
                        callback: {
                            message: 'Please Select fees.',
                            callback: function(input) {
                                return (input.value != "-1");
                            }
                        }
                    }
                },
            },
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
