<?php
/**
 * View -- of Stock/TransportController/addtransporterinvAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/transporter/partial.phtml', array('active' => 'invoice')); ?> <br/>
<style>
	.checkbox{
		margin-top:3px;
		margin-bottom:3px;"
	}
</style>
<?php 
	foreach($transinvs as $transinv):
		extract($transinv);
	    $transinv_id = $id;
	    //echo "<pre>";print_r($transinv);
	endforeach;
?>

<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;&nbsp;Edit<strong> &nbsp;&nbsp;<?php echo $transport_inv_no; ?> |
					<?php echo $this->locationObj->getColumn($location,'location')?> | 
					<?php echo $this->activityObj->getColumn($activity,'activity'); ?></strong>&nbsp;
					<?php $this->status($status);?>
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('transporter', array('action' => 'edittransporterinv'));?>" enctype="multipart/form-data" >
						<div class="row">
							<div class="col-lg-3">
								<div class="form-group">
									<label for="transport_inv_no" class="control-label">Transport Invoice No:</label>
									<input type="text" class="form-control" name="transport_inv_no" id="transport_inv_no"  value="<?php echo $transport_inv_no;?>"placeholder="Enter Transport Invoice Number"required>
									<input type="hidden" id="transinv_id" name="transinv_id" value="<?php echo $transinv_id;?>"/>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="transport_inv_date" class="control-label">Transport Invoice Date</label>
									<div class="date input-group" id="transport_inv_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="transport_inv_date" id="transport_inv_date" value="<?php echo $transport_inv_date;?>" type="text" placeholder="Transport Invoice Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="location" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($this->locationObj->getAll() as $locations): 
										$selected = ($location == $locations['id'])?"selected":"";?>
											<option value="<?php echo $locations['id'];?>"<?php echo $selected;?>>
												<?php echo $locations['location']; ?>
											</option>
										<?php endforeach; ?>							
									</select> 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="transporter" class="control-label">Transporter</label>
									<select id="transporter" name="transporter" class="from-control" data-placeholder="Select" required>
										<option value=""> </option>
										<?php foreach($transporters as $transporters):
										$selected = ($transporter == $transporters['id'])?"selected":"";?>
										<option value="<?php echo $transporters['id'];?>" <?php echo $selected;?>>
											<?php echo $transporters['code'];?>
										</option>
									    <?php endforeach;?>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-3">
								<div class="form-group">
									<label for="from_date" class="control-label">Start Date</label>
									<div class="date input-group" id="from_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="from_date" id="from_date" value="<?php echo $from_date;?>" type="text" placeholder="Transport Start Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="to_date" class="control-label">End Date</label>
									<div class="date input-group" id="to_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="to_date" id="to_date" value="<?php echo $to_date;?>" type="text" placeholder="Transport End date" readonly required >
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-lg-12">
							<div class="space-12"></div>
								<div class="page-header">
									<h1>
										<div class="col-lg-9">
											Transporter Invoice Details
											<small>
												<i class="ace-icon fa fa-angle-double-right"></i>
												From Transport Charge
											</small>
										</div>
										<div class="col-lg-3">
											<button type="button" id="refresh_btn" class="btn btn-info pull-right"><i class="fa fa-refresh"></i> Refresh </button>
										</div>
									</h1>
									<div class="space-12"></div>
									<div class="space-12"></div>
								</div>
							</div>
						</div>
						
						<div class="row">
							<div class="col-lg-12">
								<div class="transp_inv_details">
									<div class="clearfix message_box">
										<label><i class="blue fa fa-user"></i> <strong>Transporter:</strong></label> <span><?php echo $this->partyObj->getColumn($transporter,'code'); ?></span>.&nbsp;&nbsp;&nbsp;
										<label><i class="purple fa fa-tags"></i> <strong>Location:</strong></label> <span><?php echo $this->locationObj->getColumn($location, 'location');?></span>.&nbsp;&nbsp;
										<label><i class="green fa fa-calendar"></i> <strong>Period From :</strong></label> <span><?php echo $from_date.' to '.$to_date;?></span>
									</div>
									<div class="space-6"></div>
									<table class="table table-striped table-bordered table-hover" id="trdetails_table">
										<thead>
											<tr>
												<th>#</th>
												<th>Challan No</th>
												<th>Transport Charge No</th>
												<th>Transport Date</th>
												<th>Activity</th>
												<th>Vehicle No.</th>
												<th>Qty (MT)</th>
												<th>Amount (<?php echo $this->currency_code();?>)</th>
												<th>Deduction (<?php echo $this->currency_code();?>)</th>
												<th>Payable Amount (<?php echo $this->currency_code();?>)</th>
												<th>
													<div class="checkbox">
														<label>
															<input name="selectAll" id="selectAll" type="checkbox" class="ace" />
															<span class="lbl"> Select All</span>
														</label>
													</div>
												</th>
											</tr>
										</thead>
										<tbody>
											<?php 	
											/* transport charge */
											$transport_charge = $this->transchargeObj->getByDate($from_date,$to_date,array('location'=>$location,'transporter'=>$transporter, 'status'=>'3'));  
											//echo "<pre>";print_r($transport_charge); exit;
											$i = 1;
											foreach($transport_charge as $trans_charge):
												//echo "<pre>"; print_r($trans_charge);
											    $trans_id = $trans_charge['id'];
												$amount = $trans_charge['transportation_charge'];?>
													<tr>
														<td>
															<?php echo $i++;?> 
														</td>
														<td>
															<?php echo $this->dispatchObj->getColumn($trans_charge['dispatch'],'challan_no');?>
														</td>
														<td>
															<?php echo $trans_charge['transport_no'];?>
														</td>
														<td>
															<?php echo $trans_charge['transport_date'];?>
														</td>
														<td><?php echo $this->activityObj->getColumn($trans_charge['activity'],'prefix');?></td>
														<td>
															<?php echo $this->dispatchObj->getColumn($trans_charge['dispatch'],'vehicle_no');?>
														</td>
														<td><?php echo $trans_charge['qty'];?></td>
														<td>
															<input type="text" class="form-control" name="amount[]" id="amount" value="<?php echo number_format((float)$amount, 2, '.', '');?>" readonly />
														</td>
														<td>
															<?php
																$deduction = $this->transinvdtlsObj->getColumn(array('transport_charge'=>$trans_id),'deduction');
																$deduction = (is_numeric($deduction))?$deduction:"0.00"; 
															?>
															<input type="text" class="form-control" name="deduction_<?php echo $trans_id; ?>" id="deduction"  value="<?php echo $deduction;?>">
														</td>
														<td>
															<input type="text" class="form-control" name="payable_amount[]" id="payable_amount"  value="<?php echo $amount;?>" readonly>
														</td>
														<td>
															<div class="checkbox">
																<label>
																<?php
																	$present = $this->transinvdtlsObj->isPresent(array('transport_charge'=> $trans_charge['id']));
																	$checked = ($present)?"checked":"";
																?>
																	<input name="transp_status[]" id="transp_status" value="<?php echo $trans_id;?>" type="checkbox" class="ace" <?php echo $checked;?>/>
																	<span class="lbl"></span>
																</label>
															</div>
														</td>
													</tr>
											<?php //endif; 
											endforeach;		
										?>	
										</tbody>	
									</table>
									<div class="row">
										<div class="col-lg-3"></div>
										<div class="col-lg-3">
											<label class="control-label" for="total_amount">Total Amount</label>
											<input type="text" class="form-control" name="total_amount" id="total_amount" value="<?php echo $total_amount;?>" readonly>
										</div>
										<div class="col-lg-3">
											<label class="control-label" for="total_deduction">Total Deduction</label>
											<input type="text" class="form-control" name="total_deduction" id="total_deduction" value="<?php echo $total_deduction?>" readonly>
										</div>
										<div class="col-lg-3">
											<label class="control-label" for="total_payable_amount">Total Payable Amount</label>
											<input type="text" class="form-control" name="total_payable_amount" id="total_payable_amount" value="<?php echo $total_payable_amount?>" >
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-12"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<a class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </a>   		
							</div>
						</div>
					</form>
				</div>	
			</div>
		</div>		
	</div>
</div>
<script type="text/javascript">
$(function() {
	$('#transport_inv_date').datepicker();
	$('#from_date').datepicker();
	$('#to_date').datepicker();
	$('#transport_inv_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#from_date').on('changeDate', function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#to_date').on('changeDate', function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#trdetails_table').transinv();
	$("input[name='selectAll']").change(function(){
		if($(this).prop('checked')){
			$('.tr-transp_status').prop('checked', true);
		}else{
			$('.tr-transp_status').prop('checked', false);
		}
	}); 
	
	$('#refresh_btn').click(function(){
		$('form').formValidation('revalidateField',$('input#from_date'));
		$('form').formValidation('revalidateField',$('input#to_date'));
		$('form').formValidation('revalidateField',$('#location'));
		//$('form').formValidation('revalidateField',$('#activity'));
		$('form').formValidation('revalidateField',$('#transporter'));
		var validation = $('form small[data-fv-result = "INVALID"]').length;
		if(validation <= 0){
			$.post( 
				"<?php echo $this->url('transporter', array('action' => 'gettransinvdetails'));?>",
				{	
					'from_date': $('input#from_date').val(),
					'to_date': $('input#to_date').val(),
					'location': $('select#location').val(), 
					//'activity': $('#activity').val(),
					'transporter':$('#transporter').val(),
				}, 
				function(data) {
					$('div.transp_inv_details').html( data ); 
			});	
			$('div.message_box').hide();
		}
	});
});
//formValidation
const fv = FormValidation.formValidation(document.getElementById('#form'), {
	fields: {
		'transport_inv_no': {
			validators: {
				notEmpty: {
					message: 'Please enter transport invoice number'
				}
			}
		},
		'transport_inv_date': {
			validators: {
				notEmpty: {
					message: 'Please select transport invoice date'
				}
			}
		},
		'location': {
			validators: {
				notEmpty: {
					message: 'Please select location'
				}
			}
		},
		/*'activity': {
			validators: {
				notEmpty: {
					message: 'Please select activity'
				}
			}
		},*/
		'from_date': {
			validators: {
				notEmpty: {
					message: 'Please select transport invoice start date'
				}
			}
		},
		'to_date': {
			validators: {
				notEmpty: {
					message: 'Please select transport invoice end date'
				}
			}
		},
		'transporter': {
			validators: {
				notEmpty: {
					message: 'Please select transporter'
				}
			}
		},
	},
	plugins: {
		trigger: new FormValidation.plugins.Trigger(),
		bootstrap3: new FormValidation.plugins.Bootstrap3(),
		submitButton: new FormValidation.plugins.SubmitButton(),
		defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
	},
}).on('core.element.validated', function (e) {
	if (e.valid) {
		$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
		$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
	} else {
		$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
		$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
	}
});
</script>		