<?php
/**
 * View -- of Stock/TransportController/transporterinvAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/transporter/partial.phtml', array('active' => 'invoice')); ?> <br/>
<?php $minYear = date('Y', strtotime($minYear)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<form method="post" action="<?php echo $this->url('transporter', array('action'=>'transporterinv')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Transport Invoice" href="<?php echo $this->url('transporter', array('action'=>'addtransporterinv'));?>" >
							<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add</span></span>
					</a>
				</div>
			</div>
		</div>
		<div> 
			<table class="table table-bordered table-striped table-hover" id="dataTables">
			    <thead>
			        <tr>
			        	<th>#</th>
				        <th>Transporter Invoice</th>
				        <th>Invoice Date</th>
				        <th>Transporter</th>
				        <th>Start Date</th>
				        <th>End Date</th>
				        <th>Payable Amount(<?php //echo $this->currency_code();?>)</th>
				        <th>Action</th>
			        </tr>
			    </thead>
			    <tbody> 	
				<?php $i = 1;
				foreach($transinvs as $row):
					$transinv_id = $row['id'];
				?>
				    <tr data-href="<?php echo $this->url('transporter', array('action'=>'viewtransporterinv', 'id'=>$transinv_id));?>">
				    	<td><?php echo $i++;?></td>
				        <td>
				        	<b><?php echo $row['transport_inv_no'];?></b>&nbsp;&nbsp;&nbsp;
				        	<i><?php echo $this->locationObj->getColumn($row['location'], 'location');?>&nbsp;&nbsp;&nbsp;
				        	
							&nbsp;<?php $this->status($row['status']);?>
				        </td>
				        <td><?php echo $row['transport_inv_date'];?></td>
				        <td><?php echo $this->transporterObj->getColumn($row['transporter'],'code');?></td>
				        <td><?php echo $row['from_date'];?></td>
				        <td><?php echo $row['to_date'];?></td>
				        <td><?php echo $row['payable_amount'];?></td>
				       	<td class="action">
							<div class="btn-group">
								<a data-toggle="modal" data-target = "#modal" class="btn btn-xs btn-danger" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "8-".$row['id'])); ?>" title="View Activity Logs">
									<i class="ace-icon fa fa-plus bigger-120" ></i>  
								</a>
							</div>
						</td>
				    </tr>   
				<?php endforeach;?>
			    </tbody>
			</table>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
	$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
});
</script>
