<?php
/**
 * View -- of Stock/TransportController/transportchargeAction
 */
$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/transporter/partial.phtml', array('active' => 'charge')); ?> <br/>
<?php $minYear = date('Y', strtotime($minYear)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<form method="post" action="<?php echo $this->url('transporter',array('action'=>'transportcharge')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
				<div class="col-lg-6">
					<div class="clearfix">
						<div class="pull-right tableTools-container"></div>
					</div>
				</div>
			</form>
		</div>	
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
                        <th>Dispatch No.</th>
						<th>Transport No.</th>
						<th>Transporter</th>
						<th>Source Location</th>
						<th>Destination Location</th>
						<th>Transport Date</th>
						<th>TC (<?php //echo $this->currency_code();?>)</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $sl=1;?>
				<?php foreach($transport_charges as $row):?>
					<tr data-href="<?php echo $this->url('transporter', array('action'=>'viewtranspcharge', 'id'=>$row['id']));?>">
						<td><?php echo $sl++;?></td>
                        <td><b><?php echo $this->dispatchObj->getColumn($row['dispatch'],'challan_no');?></b></td>
						<td>
							<b><?php echo $row['transport_no'];?></b>&nbsp;&nbsp;&nbsp;
								<i><?php echo $this->locationObj->getColumn($row['location'],'location');?>&nbsp;&nbsp;&nbsp;
								<span class="label label-info"> 
									<?php echo $this->activityObj->getColumn($row['activity'],'activity'); ?> &nbsp;&nbsp;&nbsp;
								</span></i>&nbsp;
							 	<?php $this->status($row['status']);?>
								<?php if($row['invoiced'] == 1 && $row['status'] == 3):?>
									<span class="badge badge-danger pull-right"> 
										Invoiced 
									</span>
								<?php endif;?>
							</td>				
						</td>
						<td><?php echo $this->transporterObj->getColumn($row['transporter'],'name');?></td>
						<td><?php echo $this->locationObj->getColumn($row['source_location'],'location');?></td>
						<td><?php echo $this->locationObj->getColumn($row['destination_location'],'location');?></td>
						<td><?php echo $row['transport_date'];?></td>
						<td><?php echo $row['transportation_charge'];?></td>
						<td class="action">
							<div class="btn-group">
								<a data-toggle="modal" data-target = "#modal" class="btn btn-xs btn-danger" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "7-".$row['id'])); ?>" title="View Activity Logs">
									<i class="ace-icon fa fa-plus bigger-120" ></i>  
								</a>
							</div>
						</td>	
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
});
</script>
