<?php 
	/**
	* View -- of Stock\TransportController\viewtransportAction 
	*/
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/transporter/partial.phtml', array('active' => 'invoice')); ?> <br/>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<?php foreach($transinvs as $transinv):
	extract($transinv);
	//echo "<pre>";print_r($transinv);
	$transinv_id = $id;
	$trans_status = $status;?>
<?php endforeach;?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					# Transporter Invoice Details:<strong> &nbsp;&nbsp;<?php echo $transport_inv_no; ?> |
					<?php echo $this->locationObj->getColumn($location,'location')?> | 
					<?php //echo $this->activityObj->getColumn($activity,'activity'); ?></strong>&nbsp;
					<?php $this->status($status);?>
				</h5>
				<div class="widget-toolbar hidden-xs">
					<?php if($status == 3):?>
					<button type="button" id="payment_btn" class="btn btn-white btn-danger btn-bold btn-xs"><i class="fa fa-money"></i> Transporter Payment </button>
					<?php endif;?>
				</div>
				<div class="widget-toolbar hidden-xs">
					<a style='cursor:pointer' id="print">
						<i class="ace-icon fa fa-file-pdf-o red"></i>
					</a>
				</div>	
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Invoice No : <b class="red"><a target="_blank" href="<?php echo $this->url('transaction', array('action'=>'viewtransaction', 'id'=>$transaction_id));?>"><?php echo $transport_inv_no;?> </b></a>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Location : <b class="red"><?php echo $locationObj->getColumn($transinv['location'], 'location'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Start Date : <b class="red"><?php echo $from_date; ?></b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Invoice Date: <b class="red"><?php echo $transport_inv_date; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Transporter : <b class="red"><?php echo $partyObj->getColumn($transinv['transporter'], 'code'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										End Date : <b class="red"> <?php echo $to_date; ?></b>
									</li>
								</ul>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12">
								<div class="table-responsive">
									<h5 class="blue"><strong>Transporter Invoice Details</strong></h5>
									<table class="table" id="trtransviews_table" style="border-top:2px solid #ddd;">
										<thead>
											<tr>
												<th>#</th>
												<th>Challan No.</th>
												<th>Transport Charge No.</th>
												<th>Transport Date</th>
												<th>Activity</th>
												<th>Vehicle No</th>
												<th>Qty (MT)</th>
												<th>Amount (<?php //echo $this->currency_code();?>)</th>
												<th>Deduction (<?php //echo $this->currency_code();?>)</th>
												<th>Payable Amount (<?php //echo $this->currency_code();?>)</th>
											</tr>
										</thead>
										<tbody>
											<?php $i=1;
												foreach($transinvdtlObj->get(array('transporter_invoice'=>$transinv_id)) as $transinvdtl):?>
											<tr>
												<td><?php echo $i++;?></td>
												<td><?php
														$dispatch_id = $this->transchargeObj->getColumn($transinvdtl['transport_charge'],'dispatch');
														echo $this->dispatchObj->getColumn($dispatch_id,'challan_no'); ?>
												</td>
												<td><?php echo $transchargeObj->getColumn($transinvdtl['transport_charge'], 'transport_no');?></td>
												<td><?php echo $transinvdtl['transport_date'];?></td>
												<td><?php echo $this->activityObj->getColumn($transinvdtl['activity'],'activity');?></td>
												<td><?php echo $this->dispatchObj->getColumn($dispatch_id,'vehicle_no'); ?></td>
												<td><?php echo $this->transchargeObj->getColumn($transinvdtl['transport_charge'],'qty');?></td>
												
												<td><?php echo $transinvdtl['amount'];?></td>
												<td><?php echo $transinvdtl['deduction'];?></td>
												<td><?php echo $transinvdtl['payable_amount'];?></td>
											</tr>
											<?php $net_payable += $transinvdtl['payable_amount'];?>
											<?php endforeach;?>
											<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
												<th colspan="7"><?php echo $net_payable;?></th>
												<th colspan="2">
													Net Invoice Amount : <?php echo $net_payable;?>
												</th>
											</tr>	
										</tbody>
									</table>
								</div>	
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12" style="text-align: right">
							<?php if($trans_status == '1' || $trans_status == '2'):?>
								<a href="<?php echo $this->url('transporter',array('action'=>'edittransporterinv', 'id'=>$transinv_id));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
								<a href="<?php echo $this->url('transporter',array('action'=>'committransinv', 'id'=>$transinv_id));?>" class="btn btn-success"> <i class="fa fa-check-square-o"></i>Commit</a>
							<?php endif;?>
						</div>
					</div>
					<!-- Upload and Download file attachments -->			
					<?php   
					   //echo $this->partial('partial/attachment.phtml', array('process' => '8', 'process_id'=> $transinv_id , 'status' => $trans_status));
					?>					
				    <!-- End of attachment -->
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#payment_btn').on('click',function(){
		window.document.location = "<?php echo $this->url('payment', array('action' => 'addpayment','id' => "4-".$transinv_id));?>";
	});
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
</script>
