<?php
/**
 * View -- of Administration/MasterController/addactivity
 * chophel@athang.com
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('benefit', array('action' => 'addmaster')); ?>" enctype="multipart/form-data">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
    </div>     
    <div class="modal-body">    
		<div class="panel panel-default">                       
			<div class="panel-body">
				<div class="form-group">
					<label for="name" class="control-label">Category</label>
					<input type="text" class="form-control" name="name" id="name" size="30" placeholder='Category' > 
				</div> 
				<div class="form-group">
					<label for="head" class="control-label">Head(COA)</label>
					<select id="head" name="head" class="form-control" data-placeholder="Select" required >
						<option value=""></option>
						<?php 
						foreach ($ps_heads as $psh):
						?>
							<option value="<?php echo $psh['id'];?>">
							<?php echo $psh['name']; ?>
							</option>
						<?php 
						endforeach;
						?>
					</select>
				</div>  
            </div>
        </div>
    </div>    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>  
<script>
$(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			name: {
				validators: {
					notEmpty: {
						message: 'Please select Category.'
					}
				}
			},
			activity: {
				validators: {
					notEmpty: {
						message: 'Please provide Activity.'
					}
				}
			},
			prefix: {
				validators: {
					notEmpty: {
						message: 'Please provide Activity Prefix.'
					}
				}
			},
			status: {
				validators: {
					notEmpty: {
						message: 'Please select status.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>