<?php
/**
 * 
 * Index -- of PSWF-EMI
 * 
 */
$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(3169,3186,3187,3180)); ?>
<div class="row">
	<div class="col-lg-12">
		<?php $currentYear = (int)date('Y');
			$minYear = ($this->minYear == 0)? date('Y'):$this->minYear;?>
			<div class="row">
				<form>
					<div class="form-group col-lg-2">
						<label for="year" class="control-label">Year</label>
						<select name="year" id="year" class="form-control">
							<option value="-1">All</option>
							<?php for($year = $currentYear; $year >= $minYear; $year--):
								$selected = ($this->year == $year)?'selected':''; ?>
								<option value="<?php echo $year;?>" <?php echo $selected;?>> <?php echo $year; ?> </option>
							<?php endfor;?>
						</select>
					</div>
				</form>
			<div class="clearfix">
				<?php echo $this->button(2);?>
			</div>
		</div>
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>EMI for the month</th>
					<th>Total Employees</th>
					<th>Total Benefit</th>
					<th>Total emi</th>
					<th class="no-sort no-printpdf">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php  $i=1;
					foreach ($this->emi as $row):
						$my=$row['year']."-".$row['month']."-".$row['location'];?>
						<tr data-href="<?php echo $this->button(4, $my); ?>" >
							<td><?php echo $i; ?> </td>
							<td><strong><?php echo date("F, Y", strtotime("1-".$row['month']."-".$row['year'])); ?></strong> </td>
							<td style=""><?php echo $this->emiObj->getCount(array('month'=>$row['month'], 'year'=>$row['year']));?></td>
							<td style=""><?php echo $this->currency($this->emiObj->getSum(array('month'=>$row['month'], 'year'=>$row['year']),'benefit_amount'));?></td>
							<td style="">
							    <?php 
							        $deduction = $this->emiObj->getSum(array('month'=>$row['month'], 'year'=>$row['year']),'emi');
							        echo $deduction;?>
					        </td>
							<td><?php echo $this->button(1, $my);?></td>    
						</tr>
				        <?php 
						$i++;
					endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
<script>
	$("tr[data-href]").each(function(){ 
		if($(this).attr('data-href')!='#'){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).attr("data-href");
			});
		}
	});
	$('document').ready(function(){
		$('#dataTables').DataTable();
	});
</script>
