<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
	$this->headTitle($this->title);
?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
			<form method="post" action="<?php echo $this->url('benefit', array('action' => 'history')); ?>" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="location">Location</label>
					<select class="form-control" id="location" name="location" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['location'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($location as $locations):
							$sel_dept = ($locations['id'] == $data['location'])?'selected':'';
						?>
						<option value="<?php echo $locations['id'];?>" <?php echo $sel_dept;?>>
							<?php echo $locations['location'];?>
						</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="emp_status">Employee Status</label>
					<select class="form-control" id="emp_status" name="emp_status" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['status'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($this->empStatus->getAll() as $emp_status):
							$sel_status = ($emp_status['id'] == $data['status'])?'selected':'';
						?>
						<option value="<?php echo $emp_status['id'];?>" <?php echo $sel_status;?>>
							<?php echo $emp_status['status'];?>
						</option>
						<?php endforeach;?>
					</select>
				</div>
			</form>
			</div>
		</div>
		
			<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
	</div>
		</div>
		</div>
		<div>
			<table class="table table-striped table-hover table-condensed" style="width:100%;" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Employee_id</th>
						<th>CID</th>
						<th>Department</th>
						<th>Location</th>
						<th>Position Title</th>
						<th>Status</th>
						<?php if($this->button(1)!=""):?>
						<th class='no-sort'>Action</th>
						<?php endif;?>
					</tr>
				</thead>
				<tbody>
					<?php $j = 1; foreach ($employee as $rows):?>
						<tr data-href="<?php echo $this->button(4, $rows['id']); ?>">
							<td><?php echo $j++; ?> </td>
							<td><b><?php echo $rows['full_name']; ?></b></td>
							<td><?php echo $rows['emp_id']; ?></td>
							<td><?php echo $rows['cid']; ?></td>
							<td><?php echo $this->department->getColumn($rows['department'],'department'); ?></td>
							<td><?php echo $this->locationObj->getCOlumn($rows['location'],'location'); ?></td>
							<td><?php echo $this->ptitle->getColumn($rows['position_title'],'position_title'); ?></td>
							<td>
								<?php foreach($this->empStatus->get($rows['status']) as $stat);?>
								<span class="label label-sm label-<?php echo $stat['color'];?>"><?php echo $stat['status'];?></span>
							</td>
						<?php if($this->button(1)!=""):?>
								<td><?php echo $this->button(1,$rows['id']);?></td>
							<?php endif;?>
						</tr>
					<?php 
					endforeach;  
					?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>

