<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
$this->headTitle($this->title);
?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2,$id);?>
		</div>
	</div>
	<div class="table-responsive">
		<div class="table-header col-lg-4"> PSWF Benefit History of <?php echo $this->employeeObj->getColumn($id,'full_name'); ?> </div>
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Date</th>
					<th>Category</th>
					<th>Subject</th>
					<th>Requested Amount</th>
					<th>Approved Amount</th>
                    <th>Status</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($empbenefit as $rows):
				?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $rows['date']; ?> </td>
						<td><?php echo $this->categoryObj->getColumn($rows['category'],'name'); ?></td>
						<td><?php echo $rows['subject']; ?></td>
						<td><?php echo $rows['requested_amt'];?> </td>
						<td><?php echo $rows['approved_amt'];?>  </td>
                        <td><?php echo $this->status($rows['status']);?>  </td>
						<?php if($this->button(1)!=""):?>
						<td><?php echo $this->button(1, $rows['id']);?></td>
						<?php endif;?>
					</tr>
				<?php 
				endforeach;  
				?>
			</tbody>
		</table>
	</div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>





























