<?php
/**
 * 
 * View -- of Report/SalesreportController/salesregisterAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('reports/salesreport/partial.phtml', array('active' => 'salesregister')); ?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box transparent">
			<div class="widget-header">
				<div class="col-lg-12">
					<h5 class="widget-title lighter smaller">
						<i class="fa fa-gears"></i> Generate Sales Register
					</h5>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<form method="post" action="<?php echo $this->url('salesreport', array('action' => 'salesregister')); ?>"  enctype="multipart/form-data" >    
						<div class="row">
							<div class="form-group col-lg-2">
								<label class="control-label" for="region">Region</label>
								<select class="form-control" name="region" id="region" data-placeholder="Select" >
									<option value=""></option>
									<option value="-1" <?php echo ($data['region']=='-1')?'selected':'';?> >All</option>
									<?php 
										$regions = $this->regionObj->getAll();
										foreach($regions as $region):
											$selected_reg = ($region['id']==$data['region'])?'selected':'';
									?>
										<option value="<?php echo $region['id'];?>" <?php echo $selected_reg;?> >
											<?php echo $region['region'];?>
										</option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="location">Location</label>
								<select class="form-control" name="location" id="location" data-placeholder="Select" >
									<option value=""></option>
									<option value="-1" <?php echo ($data['location']=='-1')?'selected':'';?> >All</option>
									<?php 
										$locations = $this->locationObj->getSalesLocation('-1');
										foreach($locations as $location):
											$selected_loc = ($location['id']==$data['location'])?'selected':'';
									?>
										<option value="<?php echo $location['id'];?>" <?php echo $selected_loc;?> >
											<?php echo $location['location'];?>
										</option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="activity">Activity</label>
								<select class="form-control" name="activity" id="activity" data-placeholder="select" >
									<option value=""></option>
									<option value="-1" <?php echo ($data['activity']=='-1')?'selected':'';?> >All</option>
									<?php 
										$activities = $this->activityObj->getAll();
										foreach($activities as $activity):
											$selected_act = ($activity['id'] == $data['activity'])?'selected':'';
									?>
										<option value="<?php echo $activity['id'];?>" <?php echo $selected_act; ?>>
											<?php echo $activity['activity'];?>
										</option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="itemgroup">Item Group</label>
								<select class="form-control" name="itemgroup" id="itemgroup" data-placeholder="select" >
									<option value=""></option>
									<option value="-1" <?php echo ($data['itemgroup']=='-1')?'selected':'';?> >All</option>
									<?php 
										$itemgroups = $this->itemgroupObj->getAll();
										foreach($itemgroups as $itemgroup):
											$selected_grp = ($itemgroup['id'] == $data['itemgroup'])?'selected':'';
									?>
										<option value="<?php echo $itemgroup['id'];?>" <?php echo $selected_grp; ?>>
											<?php echo $itemgroup['item_group'];?>
										</option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="start_date">Start Date</label>
								<div class="date input-group" id="start_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="end_date">End Date</label>
								<div class="date input-group" id="end_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-2">
								<label class="control-label" for="payment">Credit/Cash/All</label>
								<select class="form-control" name="payment" id="payment" data-placeholder="select" >
									<option value=""></option>
									<option value="-1" <?php echo ($data['payment']=='-1')?'selected':'';?> >All</option>
									<option value="0" <?php echo ($data['payment']=='0')?'selected':'';?> >Cash</option>
									<option value="1" <?php echo ($data['payment']=='1')?'selected':'';?> >Credit</option>
								</select>
							</div>
							<div class="form-group col-lg-2">
								<label class="control-label" for="customer">Customer</label>
								<select class="form-control" name="customer" id="customer" data-placeholder="select" >
									<option value=""></option>
									<option value="-1" <?php echo ($data['customer']=='-1')?'selected':'';?> >All</option>
									<?php 
										if($data['payment']==1):
										$customers = $this->partyObj->get(array('p.role' => 8));
										foreach($customers as $customer):
											$selected_cus = ($customer['id'] == $data['customer'])?'selected':'';
									?>
										<option value="<?php echo $customer['id']?>" <?php echo $selected_cus;?>>
											<?php echo $customer['code'];?>
										</option>
									<?php endforeach;endif;?>
								</select>
							</div>
							<div class="col-lg-6"></div>
							<div class="col-lg-2">
								<div class="space-12"></div>
								<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="hr hr-dotted"></div>
<div id="report-print">
	<div class="row">
		<div class="col-lg-12">
			<div class="table-header clearfix">
				<label><i class="green fa fa-map-marker"></i> <strong>Region:</strong></label> <span><?php echo ($data["region"] == -1 || !isset($data['region']))? "All Regions": $this->regionObj->getColumn($data["region"], 'region');?></span>.&nbsp;&nbsp;
				<label><i class="red fa fa-map-marker"></i> <strong>Location:</strong></label> <span><?php echo ($data["location"] == -1 || !isset($data['location']))? "All Locations": $this->locationObj->getColumn($data["location"], 'location');?></span>.&nbsp;&nbsp;
				<label><i class="purple fa fa-tags"></i> <strong>Activity:</strong></label> <span><?php echo ($data["activity"] == -1 || !isset($data['activity']))? "All Activities": $this->activityObj->getColumn($data["activity"], 'activity');?></span>.&nbsp;&nbsp;
				<label><i class="green fa fa-tags"></i> <strong>Item Group:</strong></label> <span><?php echo ($data["itemgroup"] == -1 || !isset($data['itemgroup']))? "All Groups": $this->itemgroupObj->getColumn($data["itemgroup"], 'item_group');?></span>.&nbsp;&nbsp;
				<label><i class="blue fa fa-money"></i> <strong>Cash/Credit/All :</strong></label>
					<span>
						<?php 
							if($data['payment']== '-1' || !isset($data['payment'])){
								echo 'All';
							}else if($data['payment']=='0'){
								echo 'Cash Sales';
							}else{
								echo 'Credit Sales';
							}
						?>
					</span>.&nbsp;&nbsp;
				<label><i class="green fa fa-users"></i> <strong>Customer:</strong></label> <span><?php echo ($data["customer"] == -1 || !isset($data['customer']))? "All Customer": $this->partyObj->getColumn($data["customer"], 'code');?></span>.&nbsp;&nbsp;
				<label><i class="green fa fa-calendar"></i> <strong>Date:</strong></label> <span><?php echo (!isset($data['start_date']))?'-select-':$data['start_date'].' to '.$data['end_date'];?></span>
				<div class="pull-right">
					<a title="Export to Excel" id="excel">
						<i class="ace-icon fa fa-file-excel-o fa-lg white"></i>
					</a>&nbsp;&nbsp;
					<a title="Print PDF" id="print">
						<i class="ace-icon fa fa-file-pdf-o fa-lg white"></i>
					</a>&nbsp;&nbsp;
				</div>
			</div>
			<div class="space-12"></div>
			<input type="hidden" id="region" name="region" value="<?php echo ($data["region"] == -1 || !isset($data['region']))? "All Regions": $this->regionObj->getColumn($data["region"], 'region');?>"/>
			<input type="hidden" id="location" name="location" value="<?php echo ($data["location"] == -1 || !isset($data['location']))? "all Locations": $this->locationObj->getColumn($data["location"], 'location');?>"/>
			<input type="hidden" id="activity" name="activity" value="<?php echo ($data["activity"] == -1 || !isset($data['activity']))? "All Activities": $this->activityObj->getColumn($data["activity"], 'activity');?>"/>
			<input type="hidden" id="itemgroup" name="itemgroup" value="<?php echo ($data["itemgroup"] == -1 || !isset($data['itemgroup']))? "All Groups": $this->itemgroupObj->getColumn($data["itemgroup"], 'item_group');?>"/>
		    <input type="hidden" id="payment" name="payment" value="<?php if($data['payment']== '-1' || !isset($data['payment'])){echo 'Both Cash & Credit Sales';}else if($data['payment']=='0'){echo 'Cash Sales';}else{echo 'Credit Sales';}?>"/>
		    <input type="hidden" id="customer" name="customer" value="<?php echo ($data["customer"] == -1 || !isset($data['customer']))? "All Customer": $this->partyObj->getColumn($data["customer"], 'code');?>"/>			
            <input type="hidden" id="start_date" name="start_date" value="<?php echo $data['start_date'];?>"/>
		    <input type="hidden" id="end_date" name="end_date" value="<?php echo $data['end_date'];?>"/>
			<div>
				<table class="table table-hover" id="table2excel">
					<thead>
						<tr>
							<th>Date</th>
							<th>Sales No</th>
							<th>CASH/Customer</th>
							<th>Item Name</th>
							<th style="text-align:right">Quantity</th>
							<th style="text-align:right">Unit Rate</th>
							<th style="text-align:right">Amount</th>
							<th style="text-align:right">Discount</th>
							<th style="text-align:right">Net Amount</th>
						</tr>
					</thead>
					<tbody>	
					<?php 
						$sales = $this->salesObj->getSales($data);
						$total_amt = 0;
						$total_dis = 0;
						foreach($sales as $sale):
							$sales_dtls = $this->salesObj->getSalesDetails($data, $sale['sales_no']);
							$sl_sum_amt = 0;
							$sl_sum_dis = 0;
							foreach($sales_dtls as $sales_dtl):
								$sale_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$sales_dtl['sl_item'],'uom'=>$sales_dtl['sl_uom']),'conversion');
								$sale_uom_conversion = ($sale_uom_conversion == '')?'1':$sale_uom_conversion;
								$basic_quantity = ($sales_dtl['basic_uom']==$sales_dtl['sl_uom'])?$sales_dtl['quantity']:$sales_dtl['quantity']*$sale_uom_conversion;
								$basic_rate = ($sales_dtl['basic_uom']==$sales_dtl['sl_uom'])?$sales_dtl['rate']:$sales_dtl['rate']/$sale_uom_conversion;
								$basic_amount = $basic_quantity * $basic_rate;
								
								//total amount
								$total_amt += $basic_amount;
								
								$sl_sum_amt +=$basic_amount;
								if($sales_dtl['free_item']==0 && $sales_dtl['free_item_uom']==0):
									$sl_sum_dis += $sales_dtl['discount_qty'];
									//total dis
									$total_dis += $sales_dtl['discount_qty'];
								endif;
							endforeach;
							$sl_sum_net = $sl_sum_amt - $sl_sum_dis;
					?>
						<tr style="border-top:3px solid #ddd;border-bottom:3px solid #ddd;">
							<td><?php echo $sale['sales_date'];?></td>
							<td><?php echo $sale['sales_no'];?></td>
							<td>
								<?php
									if($sale['credit'] == 1):
										echo $this->partyObj->getColumn($sale['customer'],'code');
									else:
										echo 'CASH';
									endif;
								?>
							</td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align:right"><strong><?php echo number_format($sl_sum_amt,'2','.',',');?></strong></td>
							<td style="text-align:right"><strong><?php echo number_format($sl_sum_dis,'2','.',',');?></strong></td>
							<td style="text-align:right"><strong><?php echo number_format($sl_sum_net,'2','.',',');?></strong></td>
						</tr>
					<?php
							$sale_items = $this->salesObj->getSalesItems($data,$sale['sales_no']);
							foreach($sale_items as $sale_item):
								$sl_item_dtls = $this->salesObj->getSaleItemDtls($data,$sale['sales_no'],$sale_item['sl_item']);
								$sum_qty = 0;
								$sum_rate = 0;
								$sum_amt = 0;
								$sum_dis = 0;
								foreach($sl_item_dtls as $sl_item_dtl):
									$sale_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$sl_item_dtl['sl_item'],'uom'=>$sl_item_dtl['sl_uom']),'conversion');
									$sale_uom_conversion = ($sale_uom_conversion == '')?'1':$sale_uom_conversion;
									$basic_quantity = ($sl_item_dtl['basic_uom']==$sl_item_dtl['sl_uom'])?$sl_item_dtl['quantity']:$sl_item_dtl['quantity']*$sale_uom_conversion;
									$basic_rate = ($sl_item_dtl['basic_uom']==$sl_item_dtl['sl_uom'])?$sl_item_dtl['rate']:$sl_item_dtl['rate']/$sale_uom_conversion;
									$basic_amount = $basic_quantity * $basic_rate;
									$sum_qty += $basic_quantity;
									$sum_rate += $basic_rate;
									$sum_amt += $basic_amount;
									if($sl_item_dtl['free_item']==0 && $sl_item_dtl['free_item_uom']==0):
										$sum_dis += $sl_item_dtl['discount_qty'];
									endif;	
								endforeach;
								$sum_net = $sum_amt - $sum_dis;
					?>
						<tr>
							<td></td>
							<td></td>
							<td></td>
							<td><?php echo $sale_item['code'];?></td>
							<td style="text-align:right"><?php echo number_format($sum_qty,'2','.',',');?></td>
							<td style="text-align:right"><?php echo number_format($sum_rate,'2','.',',');?></td>
							<td style="text-align:right"><?php echo number_format($sum_amt,'2','.',',');?></td>
							<td style="text-align:right"><?php echo number_format($sum_dis,'2','.',',');?></td>
							<td style="text-align:right"><?php echo number_format($sum_net,'2','.',',');?></td>
						</tr>
					<?php
							endforeach;
						endforeach;
						$total_net = $total_amt - $total_dis;
					?>
						<tr style="border-top:3px solid #ddd;border-bottom:3px solid #ddd;">
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td></td>
							<td style="text-align:right"><strong>Total</strong></td>
							<td style="text-align:right"><strong><?php echo number_format($total_amt,'2','.',',');?></strong></td>
							<td style="text-align:right"><strong><?php echo number_format($total_dis,'2','.',',');?></strong></td>
							<td style="text-align:right"><strong><?php echo number_format($total_net,'2','.',',');?></strong></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$(function() {
			$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
	
	var doc_loc = $('input#region').val() + $('input#location').val() + ',' + $('input#activity').val() + ',' + $('input#payment').val()  + $('input#customer').val() + '(from: '+$('input#start_date').val()+' to: '+$('input#end_date').val()+')';
		$("#excel").click(function(){
		  $("#table2excel").table2excel({
			// exclude CSS class
			exclude: ".noExl",
			name: "Worksheet Name",
			filename: "Slesregister_for_"+doc_loc, //do not include extension
		  }); 
		});
		//get location by region
		$('#region').on('change',function(){
			$.post(
				'<?php echo $this->url('salesreport',array('action'=>'getlocation'));?>',
				{
					'region' : $(this).val(),
				},
				function(data){
					//console.log(data);
					$('#location').html(data.location);
					$('#location option:selected').removeAttr('selected');
					$('#location').trigger('chosen:updated');
				},
				'json'
			);
		});
		//get customer if it is credit
		$('#payment').on('change',function(){
			$.post(
				'<?php echo $this->url('salesreport',array('action'=>'getcustomer'));?>',
				{
					'payment' : $(this).val(),
				},
				function(data){
					//console.log(data);
					$('#customer').html(data.customer);
					$('#customer option:selected').removeAttr('selected');
					$('#customer').trigger('chosen:updated');
				},
				'json'
			);
		});
	/*** Form Validation ***/
	$('form').formValidation({
			framework: 'bootstrap',
			excluded: ':disabled',
			message: 'This value is not valid',
			fields: {
				'region': {
					validators: {
						notEmpty: {
							message: 'Please select region'
						}
					}
				},
				'location': {
					validators: {
						notEmpty: {
							message: 'Please select location'
						}
					}
				},
				'activity': {
					validators: {
						notEmpty: {
							message: 'Please select activity'
						}
					}
				},
				'itemgroup': {
					validators: {
						notEmpty: {
							message: 'Please select item group'
						}
					}
				},
				'start_date': {
					validators: {
						notEmpty: {
							message: 'Please select start date'
						}
					}
				},
				'end_date': {
					validators: {
						notEmpty: {
							message: 'Please select end date'
						}
					}
				},
				'payment': {
					validators: {
						notEmpty: {
							message: 'Please select cash/credit/all'
						}
					}
				},
				'customer': {
					validators: {
						notEmpty: {
							message: 'Please select customer'
						}
					}
				},
			}
		}).on('success.field.fv', function(e, data) {
			if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
				data.fv.disableSubmitButtons(true);
			}
		});
	});
</script>
