<?php
/**
 * 
 * View -- of Accounts/AssetController/addbankaccountAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('accounts/asset/partial.phtml', array('active' => 'bankaccount')); ?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i> New Bank Account
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('asset', array('action' => 'addbankaccount')); ?>" enctype="multipart/form-data" >
						<div class=row>    
							<div class="form-group col-lg-4">
								<label for="account" class="control-label">Account</label>
								<input type="text" class="form-control" name="account" id="account" placeholder="Account" required>
							</div>
							<div class="form-group col-lg-4">
								<label for="code" class="control-label">Code</label>
								<input type="text" class="form-control" name="code" id="code" placeholder="Code" required>
							</div>
							<div class="form-group col-lg-4">
								<label for="bank" class="control-label">Bank</label>
								<select class="form-control" id="bank" name="bank" data-placeholder="Select" required >
									<option value=""></option>
									<?php 
									foreach ($banks as $bank):
									?>
										<option value="<?php echo $bank['id'];?>">
											<?php echo $bank['bank'];?>
										</option>
									<?php
									endforeach;
									?>
								</select>
							</div> 
						</div>
						<div class="row">
							<div class="form-group col-lg-4">
								<label for="branch" class="control-label">Branch</label>
								<input type="text" class="form-control" name="branch" id="branch" placeholder="Branch" required>
							</div>
							<div class="form-group col-lg-4">
								<label for="region" class="control-label">Region</label>
								<select class="form-control" id="region" name="region" data-placeholder="Select" required >
									<option value=""></option>
									<?php 
									foreach ($regions as $region):
									?>
										<option value="<?php echo $region['id'];?>">
											<?php echo $region['region'];?>
										</option>
									<?php
									endforeach;
									?>
								</select>
							</div>     
							<div class="form-group col-lg-4">
								<label for="location" class="control-label">Location</label>
								<select class="form-control chosen-widget" id="location" name="location" data-placeholder="Select" required >
									<option value=""></option>
								</select>
							</div>  
						</div>
						<div class="row">
							<div class="col-lg-12">  
								<h5 class='header blue'>Sub Head Details</h5>
								<table id="head_table" class="table small-padding">
									<thead>
										<tr>
											<th>Head Type</th>
											<th>Head</th>
											<th>&nbsp;</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>
												<div class="form-group">
													<select class="form-control head_type" id="head_type" name="head_type[]" data-placeholder="Select" required>
														<option value=""></option>
														<?php 
														foreach ($headtypes as $headtype):
														?>
															<option value="<?php echo $headtype['id'];?>">
																<?php echo $headtype['head_type'];?>
															</option>
														<?php
														endforeach;
														?>
													</select>
												</div>
											</td>
											<td>
												<div class="form-group">
													<select class="form-control" id="head" name="head[]" data-placeholder="Select" required>
														<option value=""></option>
													</select>
												</div>
											</td>
											<td width="30px;"></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button>
							</div>
						</div> 
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$('document').ready(function(){	
	$("#region").change(function() { 
		$('#location').load("<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function() {
			$("#location").trigger('chosen:updated');
			$('form').formValidation('revalidateField','location');
		});
	});
	/****** dynamic insertion of table row*******/
	$('#head_table').subhead({src:'<?php echo $this->url("ajresponse", array("action" => "gethead")); ?>'});	
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			account: {
					validators: {
						notEmpty: {
							message: 'Please provide account.'
						}
					}
				},
				code: {
					validators: {
						notEmpty: {
							message: 'Please provide code.'
						}
					}
				},
				bank: {
					validators: {
						notEmpty: {
							message: 'Please provide bank.'
						}
					}
				},
				location: {
					validators: {
						notEmpty: {
							message: 'Please select location.'
						}
					}
				},
				/*'head_type[]': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select Head Type'
	                    }
	                }
	            },
	            'head[]': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select Head'
	                    }
	                }
	            }, */
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>
	
