<?php
/**
 * 
 * View -- of Accounts/AssetController/addincomeheadAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('accounts/asset/partial.phtml', array('active' => 'expenseledger')); ?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i> New Expense Ledger
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form id="form" method="post" action="<?php echo $this->url('asset', array('action' => 'addexpenseledger')); ?>" enctype="multipart/form-data" >
						<div class="row">
							<div class="form-group col-lg-3">
								<label for="location" class="control-label">Location</label>
								<select class="form-control" id="location" name="location" data-placeholder="Select" required >
									<option value="-1">All</option>
									<?php 
									foreach ($locations as $location):
									?>
										<option value="<?php echo $location['id'];?>">
											<?php echo $location['location'];?>
										</option>
									<?php
									endforeach;
									?>
								</select>
							</div>   
							<div class="form-group col-lg-3">
								<label for="expense_code" class="control-label">Expense Code</label>
								<input type="text" class="form-control" name="expense_code" id="expense_code" placeholder="Expense Ledger Code" required>
							</div>
							<div class="form-group col-lg-3">
								<label for="expense_name" class="control-label">Expense Name</label>
								<input type="text" class="form-control" name="expense_name" id="expense_name" placeholder="Expense Ledger Name" required>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">  
								<h5 class='header blue'>Sub Head Details</h5>
								<table id="head_table" class="table small-padding">
									<thead>
										<tr>
											<th>Head Type</th>
											<th>Head</th>
											<th>&nbsp;</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>
												<div class="form-group">
													<select class="form-control head_type" id="head_type" name="head_type[]" data-placeholder="Select" required>
														<option value=""></option>
														<?php 
														foreach ($headtypes as $headtype):
														?>
															<option value="<?php echo $headtype['id'];?>">
																<?php echo $headtype['head_type'];?>
															</option>
														<?php
														endforeach;
														?>
													</select>
												</div>
											</td>
											<td>
												<div class="form-group">
													<select class="form-control" id="head" name="head[]" data-placeholder="Select" required>
														<option value=""></option>
													</select>
												</div>
											</td>
											<td width="30px;"></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button>
							</div>
						</div> 
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
	$(function() {	
		/****** dynamic insertion of table row*******/
		$('#head_table').subhead({src:'<?php echo $this->url("ajresponse", array("action" => "gethead")); ?>'});	

		const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			    expense_code: {
					validators: {
						notEmpty: {
							message: 'Please provide Expense Code.'
						}
					}
				},
				expense_name: {
					validators: {
						notEmpty: {
							message: 'Please provide Expense Name.'
						}
					}
				},
				location: {
					validators: {
						notEmpty: {
							message: 'Please select location.'
						}
					}
				},
				credit_sales: {
					validators: {
						notEmpty: {
							message: 'Please select credit Sales.'
						}
					}
				},
				'head_type[]': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select Head Type'
	                    }
	                }
	            },
	            'head[]': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please select Head'
	                    }
	                }
	            },
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>
	
