<?php
/**
 * 
 * View -- of Stock/MasterController/additemgroupAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('stock', array('action' => 'addsellingprice')); ?>"  enctype="multipart/form-data" >
	<div class="form-group col-lg-3">
		<h3 class="grey">
			<i class="fa fa-balance-scale  fa-x red"></i>
			 Selling Price Of Item
		</h3>
   </div>
		<div class="panel panel-default">                       
			<div class="panel-body">  
				<div class="row">
					<div class="form-group col-lg-3">
						<label for="supplier"  class="col-md-4  control-label" style="padding-top:7px">Supplier</label>
						<select class="form-control" name="supplier" id="supplier" data-placeholder="Select"> 
							<option value=""></option>
							<?php foreach($supplier as $suppliers):?>
								<option value="<?php echo $suppliers['id'];?>"><?php echo $suppliers['name'];?></option>
							<?php endforeach;?>
						</select>
					</div>
					<div class="form-group col-lg-3">
						<label for="item" class="col-md-4 control-label" style="padding-top:7px">Item</label>
						<select class="form-control" name="item" id="item" data-placeholder="Select"> 
							<option value=""></option>
						
						</select>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6">
					<div class="panel panel-default">
						<div class="panel-body">
						<h5 class="widget-title grey lighter">
							<i class="ace-icon fa fa-hourglass fa-x green"></i>
							<b>Items Details</b>
						</h5>
						<div class="form-group row">
							<label for="specification" class="col-sm-4 col-form-label">Specification</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="specification" id="specification"
									placeholder="specification" />
							</div>
						</div>
						<div class="form-group row">
							<label for="quantity" class="col-sm-4 col-form-label">Quantity</label>
							<div class="col-sm-8">
								<input type="text" class="form-control" name="quantity" id="quantity"
									placeholder="quantity" />
							</div>
						</div>

						<label for="remark" class="control-label"> Remarks </label>
						<textarea type="text" class="form-control" name="remark" id="remark" rows="2" placeholder="Remark if any" ></textarea>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="panel panel-default">
						<div class="row">
							<div class="col-lg-12">
								<div class="panel-body">
									<div class="form-group">
										<h5 class="widget-title grey lighter">
											<i class="ace-icon fa fa-dollar fa-x green"></i>
											<b>Cost details</b>
										</h5>
										<div class="form-group row">
											<label for="rate_nu" class="col-md-4 col-form-label">Rate(Nu)</label>
											<div class="col-md-8">
												<input type="decimal" class="form-control" name="rate_nu"
													id="rate_nu" placeholder=" Rate" />
											</div>
										</div>
										<div  class="form-group">
											<div class="form-group row">
												<label for="freight_charge" class="col-md-4 col-form-label">Freight charge</label>
												<div class="col-md-8">
													<input type="decimal" class="form-control"
														name="freight_charge" id="freight_charge"
														placeholder="Freight charge" />
												</div>
											</div>
											<div class="form-group row">
												<label for="sale_tax" class="col-md-4 col-form-label">Sales Tax(15%)</label>
												<div class="col-md-8">
													<input type="decimal" class="form-control"
														name="sale_tax" id="sale_tax"
														placeholder="Sales Tax" />
												</div>
											</div>
											<div class="form-group row">
												<label for="total_charge"
													class="col-md-4 col-form-label">Total Chrages</label>
												<div class="col-md-8">
													<input type="decimal" class="form-control" name="total_charge"
														id="total_charge" placeholder="Total Chrages" />
												</div>
											</div>
										</div>
										<div class="form-group row">
											<label for="cost_price" class="col-md-4 col-form-label">Cost Price</label>
											<div class="col-md-8">
												<input type="decimal" class="form-control" name="cost_price"
													id="cost_price" placeholder="Cost Price" required />
											</div>
										</div>
										<div  class="form-group row">
											<label for="selling_price" class="col-md-4 col-form-label">
											Selling Price</label>
											<div class="col-md-8">
												<input type="decimal" class="form-control" name="selling_price"
													id="selling_price" placeholder="Insurance Amount" required />
											</div>
										</div>
										
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
        </div>	
		<div style="padding-left:800px; padding-top: -200px;">
			<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
			<button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel
			</button>
		</div> 
</form>
<script>
$('document').ready(function(){
	//$('form select').chosen();
$('#supplier, #item').on('change', function () {
		//alert($('#supplier').val());
			$.post(
				"<?php echo $this->url('stock', array('action' => 'getcostdetails'));?>",
				{
					supplierId: $('#supplier').val(),
					itemId: $('#item').val(),
					
				},
				function(data){
					$('#quantity').val(data.quantity);
					$('#freight_charge').val(data.freight_charge);
					$('#rate_nu').val(data.paid_amount);
				},
				'json'
			);
		});
		$('#supplier').on('change', function () {
		//alert($('#supplier').val());
			$.post(
				"<?php echo $this->url('stock', array('action' => 'getitem'));?>",
				{
					supplierId: $('#supplier').val(),
					
				},
				function(data){
					$('select#item').html(data.item);
					$('select#item').trigger('chosen:updated');
				},
				'json'
			);
		});

		/**calculation of total amount based on the given variables**/

		var rate_nu = $('#rate_nu');
		var sale_tax = $('#sale_tax');
		var freight_charge = $('#freight_charge');
		var quantity=$('#quantity');
		
		// Add an event listener for changes in the rate and quantity inputs
		rate_nu.on('input', calculateTotal);
		sale_tax.on('input', calculateTotal);
		freight_charge.on('input', calculateTotal);
		quantity.on('input', calculateTotal);
		// Trigger the calculateTotal function initially when the page loads
		calculateTotal();
		// Function to calculate the total and update the total input field
		function calculateTotal(rate_nu_val) {
			var rate_nu_val= parseFloat(rate_nu.val().replace(',', '')) || 0;
			var sale_tax_val = parseFloat(sale_tax.val().replace(',', '')) || 0;
			var freight_charge_val = parseFloat(freight_charge.val().replace(',', '')) || 0;
			var quantity_val = parseFloat(quantity.val().replace(',', '')) || 0;
		

			if (isNaN(rate_nu_val)) {
				rate_nu_val = 0;
			}
			if (isNaN(sale_tax_val)) {
				sale_tax_val = 0;
			}
			if (isNaN(freight_charge_val)) {
				freight_charge_val = 0;
			}
			if (isNaN(quantity_val)) {
				quantity_val = 0;
			}
			//console.log("Postage Rate:", rate_nu_val);

			var total = rate_nu_val + sale_tax_val + freight_charge_val;
		
			var cost_price=total/quantity_val
				console.log("Postage Rate:", cost_price);
			// Check if the total is a valid number
			if (!isNaN(total)) {
				$('#total_charge').val(total.toFixed(2)); // Display the total with 2 decimal places
			}
			if (!isNaN(cost_price)) {
				$('#cost_price').val(cost_price.toFixed(2)); // Display the total with 2 decimal places
			}
		}
		/**
		 * End of Calculation
		 */
		/**
		 * **************************************************Money Order**********************************************************
		 */
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			itemclass: {
				validators: {
					notEmpty: {
						message: 'Please provide item class.'
					}
				}
			},
			itemgroup: {
				validators: {
					notEmpty: {
						message: 'Please provide item group.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide description for item group.'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>