<?php
/**
 * 
 * View -- of Stock/MsaterController/itemgroupAction
 * 
 */
	$this->headTitle($this->title);
?>

<?php echo $this->partial('stock/stock/partial.phtml', array('active' => 'itemclass')); ?>
<div class="space-12"></div>
<div class="card">
	<div class="card-header">
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
			<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-toggle="modal" data-target="#modal" data-tooltip="tooltip" data-placement="top" title="Add New Item Group" href="<?php echo $this->url('stock', array('action' => 'additemclass'));?>" >
				<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Item Class</span></span>
			</a>
		</div>
	</div>
	<div>
		<table class="table table-bordered table-striped table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Item Class</th>
					<th>Description</th>
					<th class="no-sort">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($itemclasses as $itemclass):
				?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><b><?php echo $itemclass['item_class']; ?></b></td> 
						<td><?php echo $itemclass['description']; ?></td>                               
						<td>
							<div class="btn-group">
								<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('stock', array('action'=>'edititemclass', 'id' => $itemclass['id']));?>" data-target="#modal">
									<i class="ace-icon fa fa-pencil bigger-120"></i>
								</a>                   
							</div>
						</td>
					</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
