<?php
/**
 * 
 * View -- of Stock/MsaterController/itemgroupAction
 * 
 */
	$this->headTitle($this->title);
?>

<?php echo $this->partial('stock/stock/partial.phtml', array('active' => 'itemsubgroup')); ?>
<div class="card">
	<div class="card-header">
		<form method="post"> 
			<div class="row">
				<div class="form-group col-lg-3">
					<label for="itemclass" class="label-control">Item Group</label>
					<select class="form-control" data-placeholder="Select" name="item_group" id="item_group" onchange='this.form.submit()' >
						<option value="" ></option>
						<option value="-1" <?php echo ($group_id == '-1')?"selected":"";?> >All</option>
						<?php 
							$itemgroups = $this->itemgroupObj->getAll();
							foreach($itemgroups as $itemgroup):
								$selected_group = ($group_id == $itemgroup['id'])?"selected":"";
						?>
							<option value="<?php echo $itemgroup['id'];?>" <?php echo $selected_group;?>>
								<?php echo $itemgroup['item_group'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="clearfix col-lg-9">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-toggle="modal" data-target="#modal" data-tooltip="tooltip" data-placement="top" title="Add New Item Sub-Group" href="<?php echo $this->url('stock', array('action' => 'additemsubgroup'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Item Sub-Group</span></span>
					</a>
				</div>
			</div>
		</form>
		<div>
			<table class="table table-bordered table-striped table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Item Sub-Group</th>
						<th>Description</th>
						<th>Item Group</th>
						<th>Item Class</th>
						<th class="no-sort">Action</th>
					</tr>
				</thead>
				<tbody>
					<?php
						$i = 1; 
						foreach ($this->itemsubgroups as $itemsubgroup):
					?>
							<tr>
								<td><?php echo $i++; ?> </td>
								<td><b><?php echo $itemsubgroup['item_subgroup']; ?></b></td> 
								<td><?php echo $itemsubgroup['description']; ?></td>                               
								<td><?php echo $this->itemgroupObj->getColumn($itemsubgroup['item_group'],'item_group'); ?></td> 
								<td>
									<?php 
										$item_class = $this->itemgroupObj->getColumn($itemsubgroup['item_group'],'item_class'); 
										echo $this->itemclassObj->getColumn($item_class,'item_class');
									?>
								</td> 
								<td>
									<div class="btn-group">
										<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('stock', array('action'=>'edititemsubgroup', 'id' => $itemsubgroup['id']));?>" data-target="#modal">
											<i class="ace-icon fa fa-pencil bigger-120"></i>
										</a>                                                                    
									</div>
								</td>
							</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
