<?php
/**
 * View -- of Stocki/StockController/viewitem
 */
?>
<?php 
//echo "<pre>"; print_r($items);
	foreach($this->items as $item ):
		extract($item);
		$item_id = $id;
		$item_author_id = $author;
	endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					# Item Details:<strong>&nbsp;&nbsp;<?php echo $item_code; ?>&nbsp;
					<b class="red"> | <?php echo $name;?> </b></strong>&nbsp;&nbsp;
					<?php
						 if($status==1 || $status==4):
						 	$status_name = "Active";
						 	$label = "success";
						 else:
						 	$status_name = "Inactive";
						 	$label = "danger";
						 endif;
					 ?>
					<span class="label label-<?php echo $label;?>">
						&nbsp; <?php echo $status_name; ?> &nbsp;
					</span>
				</h5>
				<div class="widget-toolbar hidden-xs">
					<div class="btn-group">
						<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "24-".$item_id)); ?>" title="View Activity Logs">
							<i class="ace-icon fa fa-plus bigger-120" ></i>  
						</a> 
						<a class="btn btn-xs" id="print" title="Print">
							<i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
						</a>
					</div>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-24">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-4" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Item Code : <b class="red"><?php echo $code; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										<?php 
											$item_group = $this->itemsubgroupObj->getColumn($item_subgroup,'item_group');
											$item_class = $this->itemgroupObj->getColumn($item_group,'item_class');
										?>
										Item Class: <b class="red"><?php echo $this->itemclassObj->getColumn($item_class,'item_class'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Basic Unit Of Measure: <b class="red"><?php echo $this->uomObj->getColumn($uom,'description'); ?></b>
									</li>								
									
									
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Item Name: <b class="red"><?php echo $name; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Item Group: <b class="red"><?php echo $this->itemgroupObj->getColumn($item_group,'item_group'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Barcode : <b class="red"><?php echo $barcode; ?></b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb3">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Item Sub-Group: <b class="red"><?php echo $this->itemsubgroupObj->getColumn($item_subgroup,'item_subgroup'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Item Valuation : <b class="red"><?php echo ($valuation==1)?"Weighted Moving Average":"First In First Out"; ?></b>
									</li>
								
								</ul>
							</div>
						</div>
					</div><?php
					if($item_group==65 || $item_group==66):?>
					<div class="row">
						<div class="col-lg-7">
						</div>
						<div class="col-lg-5" style="text-align: right">
							<!--<a href="<?php //echo $this->url('stock', array('action'=>'deleteitem', 'id'=>$item_id));?>" class="btn btn-warning"> <i class="fa fa-trash"></i> Delete </a>-->
							<?php echo $this->button(6,$item_id,'','1055')?>
							<!--button type="button" class="btn btn-danger" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button--> 
						</div>
							<div class="row">
								<div class="col-lg-12" >
									<table class="table" style="border-top:2px solid #ddd;">
										<thead>
											<tr>
												<th>#</th>
												<th>Item</th>
												<th>UOM</th>											
												<th>Quantity</th>
												<th>Rate(Nu)</th>
												<th>Value(Nu)</th>
												<th>Status</th>
												<th>Action</th>		
											</tr>
										</thead>
										<tbody>
											<?php $sl=1;foreach($materials as $tdrow):?>
												<tr>
													<td><?php echo $sl++;?></td>
													<td><?php echo $this->itemObj->getColumn($tdrow['material'],'name');?></td>
													<td><?php echo $this->uomObj->getColumn($tdrow['uom'],'code');?></td>
													<td><?php echo $tdrow['quantity'];?></td>
													<td><?php echo $tdrow['rate'];?></td>
													<td><?php echo $tdrow['value'];?></td>
													<td><?php echo $this->status($tdrow['status']);?></td>
													<td><?php if($tdrow['status']!=4):echo $this->button(6,$tdrow['id'],'','1056');endif;?></td>
												</tr>
											<?php endforeach;?>
											<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;"></tr>
										</tbody>
									</table>
								</div>
							</div>
							<div class="col-lg-12" style="text-align: right">
							<?php $iteml=$materialsObj->get(array('item'=>$item_id,'status'=>3));if(empty($iteml)):?>
							<button type="button" class="btn btn-success"><i class="fa fa-check"></i> Completed </button> 
							<?php else:
							echo $this->button(6,$item_id,'','1057');
							endif;?>
						</div>
					</div><?php endif;?>
				</div>
			</div>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice2({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
</script>
