<?php
/**
 * 
 * View -- of Realestate/MaindataController/editpercentAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('rsdata', array('action' => 'addstoragetype')); ?>"  enctype="multipart/form-data" >                 
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="fa fa-plus"></i> Add Storage Type </h4>
    </div><!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="form-group">
					<label for="location" class="control-label"> Location </label>
					<select class="form-control" id="location" name="location" dataplaceholder="~Select~" required >
						<option value=""></option>
						<?php foreach($locations as $loc):?>
							<option value="<?php echo $loc['id'];?>"> <?php echo $loc['location'];?> </option>
						<?php endforeach;?>
					<select>
				</div>
				<div class="form-group">
					<label for="operator" class="control-label"> Operator </label>
					<select class="form-control" id="operator" name="operator" dataplaceholder="~Select~" required >
						<option value=""></option>
						<?php foreach($operators as $ope):?>
							<option value="<?php echo $ope['id'];?>"> <?php echo $ope['operator'];?> </option>
						<?php endforeach;?>
					<select>
				</div>
				<div class="form-group">
					<label for="storage" class="control-label"> Type </label>
					<input class="form-control" name="storage" id="storage" placeholder="Storege Type" required />
				</div>
			</div>
        </div>
    </div><!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script type="text/javascript">
	$('form select').chosen();
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				storage: {
					validators: {
						notEmpty: {
							message: 'Please provide a value.'
						}
					}
				},
				location: {
					validators: {
						notEmpty: {
							message: 'Please select an option.'
						}
					}
				},
				operator: {
					validators: {
						notEmpty: {
							message: 'Please select an option.'
						}
					}
				},		
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
</script>  
