<?php
/**
 * 
 * View -- of Realestate/MaindataController/editpercentAction
 * 
 */
?>
<?php foreach($datas as $da):
		extract($da);
	endforeach;
?>
<form  id="#form" method="post" action="<?php echo $this->url('rsdata', array('action' => 'editfloor','id' => $id)); ?>"  enctype="multipart/form-data" >                 
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="fa fa-pencil"></i> Edit Floor </h4>
    </div><!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="form-group">
					<label for="floor" class="control-label"> Floor Name </label>
					<input class="form-control" name="floor" id="floor" value="<?php echo $floor;?>" required />
				</div>
			</div>
        </div>
    </div><!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script type="text/javascript">
	$('form select').chosen();
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				floor: {
					validators: {
						notEmpty: {
							message: 'Please provide a value.'
						}
					}
				},
				region: {
					validators: {
						notEmpty: {
							message: 'Please select an option.'
						}
					}
				}	
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
</script>  
