<?php
/**
 *
 * 	view -- of Realestate/MaindataController/indexAction
 *
 */?>
<?php echo $this->partial('realestate/maindata/partial.phtml',array('active' => 'building'));?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Building Id</th>
					<th>Building Name</th>
					<th>Region</th>
					<th>Location</th>
					<th>Custodian</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;					
				  foreach ($building as $rows):					  						
				?>
					<tr data-href="<?php echo $this->button(4, $rows['id']); ?>">
						<td><?php echo $i++; ?> </td>
						<td><?php echo $rows['building_id']; ?></td>
						<td><strong><?php echo $rows['name']; ?></strong></td>	
						<td><?php echo $this->region->getColumn($rows['region'],'region'); ?></td>
						<td><?php echo $this->location->getColumn($rows['location'],'location'); ?></td>
						<td><?php echo $this->employee->getColumn($rows['custodian'],'full_name'); ?></td>
						<td><?php echo $this->button(1, $rows['id']); ?></td>
					
					</tr>
				<?php 
				$i++;
				endforeach;  
				?>
			</tbody>
		</table>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});

	$('document').ready(function(){
		$('#dataTables').DataTable({
		"paging":   true,
	});
	});
</script>
 