<?php 
/**
*
* View Selling Price  Accounts/TransactionController/cashbook
*
*/
$this->headTitle($this->title);
//echo $this->partial('accounts/report/partial.phtml', array('active' => 'cashbook'));
?>
<?php echo $this->tabs_helper(array(684,691,685,686,687,688,689,690)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="post" action="<?php echo $this->url('report', array('action' => 'cashbook'));?>" enctype="multipart/form-data">
					<div class="row">
						<div class="col-lg-3">
							<div class="form-group">
								<label for="location" class="control-label">Location</label>
								<select id="location" name="location" class="form-control" data-placeholder="Select" required>
									<option value=""></option>
									<?php foreach($this->locationObj->getAll() as $locations):
									$selected = ($location_id == $locations['id'])?"selected":"";?>
										<option value="<?php echo $locations['id'];?>" <?php echo $selected;?>>
											<?php echo $locations['location'];?>
										</option>
									<?php endforeach;?>
								</select> 
							</div>
						</div>
						<div class="col-lg-3">
							<div class="form-group">
								<label for="cashaccount" class="control-label">Cash Account</label>
								<select class="form-control chosen-widget" id="cashaccount" name="cashaccount" data-placeholder="Select" required >
									<option value=""></option>
								</select>
							</div>
						</div>
						<div class="col-lg-2">
							<div class="form-group">
								<label for="start_date" class="control-label">Start Date</label>
								<div class="date input-group" id="start_date" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="start_date" id="start_date" value="<?php echo $start_date;?>" type="text" placeholder="Start Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						</div>
						<div class="col-lg-2">
							<div class="form-group">
								<label for="end_date" class="control-label">End Date</label>
								<div class="date input-group" id="end_date" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="end_date" id="end_date" value="<?php echo $end_date;?>" type="text" placeholder="End Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						</div>
						<div class="form-group col-lg-2">
							<div class="space-12"></div>
							<label>
								<?php $checked = ($cash_detail == '1')?'checked':'';?>
								<input name="cash_details" id="cash_details" type="checkbox" value="1" class="ace" <?php echo $checked;?>/>
								<span class="lbl"> Cash Book Details </span>
							</label>
						</div>
						<div class="col-lg-2"> <br/>
							<button type="submit" id="refresh_btn" class="btn btn-info pull-right"><i class="fa fa-refresh"></i> Refresh </button>
						</div>
					</div>
				</form>	
			</div>
	    </div>
	</div>
</div>
<div class="hr hr-dotted"></div>

<div id="report-print">
	<div class="row">
		<div class="col-lg-12">
			<div class="table-header clearfix">
				<label><i class="white fa fa-map-marker"></i> <strong>Location:</strong></label> <span><?php echo $this->locationObj->getColumn($location_id, 'location');?></span>.&nbsp;&nbsp;
				<label><i class="white fa fa-calendar"></i> <strong>From Date:</strong></label> <span><?php echo $start_date;?></span>.&nbsp;&nbsp;
				<label><i class="white fa fa-calendar"></i> <strong>To Date:</strong></label> <span><?php echo $end_date;?></span>
				<input type="hidden" id="loc" name="loc" value="<?php echo $this->locationObj->getColumn($location_id, 'location');?>"/>
				<input type="hidden" id="start_date" name="start_date" value="<?php echo $start_date;?>"/>
				<input type="hidden" id="end_date" name="end_date" value="<?php echo $end_date;?>"/>
				<div class="pull-right">
					<a title="Export to Excel" id="excel">
						<i class="ace-icon fa fa-file-excel-o fa-lg white"></i>
					</a>&nbsp;&nbsp;
					<a title="Print PDF" id="print">
						<i class="ace-icon fa fa-file-pdf-o fa-lg white"></i>
					</a>&nbsp;&nbsp;
				</div>
			</div>
			<table class="table table-hover" id="table2excel">
				<thead>
					<tr>
						<th></th>
						<th>Txn Type</th>
						<th>Voucher No</th>
						<th>Txn Date</th>
						<th style="text-align:right">Receipt</th>
						<th style="text-align:right">Payment</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><strong>Opening Balance</strong></td>
						<td></td>
						<td></td>
						<td><strong>
							<?php 
								  $date = $start_date;
								  $date = strtotime($date);
								  $date = strtotime("-1 day", $date);
								  $closing_date = date('Y-m-d', $date);
								  echo $closing_date;
							?></strong>
						</td>
						<td class="green" style="text-align:right">
							<?php $open_tot_receipt=0;$open_tot_payment=0;

								  $cashAccountID = $this->cashAccountObj->getColumn(array('location'=>$location_id),'id');
								  $closingBalanceYr=0;
								  if($cashAccountID > 0 ){
									  $subHeadID = $this->subheadObj->getColumn(array('type'=>'6', 'ref_id'=>$cashAccountID),'id');
									  if($subHeadID > 0 ){
										  $present_Yr = Date('Y');
										  $closing_Yr = $present_Yr - 2;
										  $closingDtls = $this->closingObj->get(array('year'=>$closing_Yr, 'sub_head'=>$subHeadID));
										  foreach($closingDtls as $dtl):
											$closingBalanceYr = $dtl['closing_dr'] - $dtl['closing_cr'];
										  endforeach;
									  }else{ ?>
										   <div class="alert alert-warning fade in"> * Sub Ledger or Sub Head not created for this location </div>
									  <?php
									  }
								  }
								  else{
									  ?>
										<div class="alert alert-warning fade in"> * No Cash Accounts selected </div>
									  <?php
								  }
								  $i = 1; 
							?>
							<?php $i = 1;
						      $i = 1; 
								 // $fixed_start_date = "2015-01-01";
								 // $open_date = $fixed_start_date;
								 // $open_date = strtotime($open_date);
								 // $open_date = strtotime("-10 year", $open_date);
								 // $opening_date = date('Y-m-d', $open_date);
								 $opening_date = '2017-07-01';
							foreach($this->headObj->getCash(array('h.head_type'=> '10'), 'id') as $head):
							$head_id = $head['id'];
							$open_tot_payment=0;
							$opening_balance=0;
						   $vouchers = $this->transactionObj->getVouchersPresent($opening_date,$closing_date,$location_id, $head_id);
							foreach($vouchers as $voucher):
							  $tot_open_receipt = 0.00; $tot_open_payment = 0.00;	
								foreach($this->transactionObj->getDisinctTID($voucher['voucher_type'],$opening_date,$closing_date,$location_id, $head_id) as $transactions):
									foreach($this->transactiondetailObj->getCash($voucher['voucher_type'],$opening_date,$closing_date,array('transaction'=> $transactions['transaction_id'], 'td.head' => $head_id, 'td.location' =>$location_id)) as $transdtl):
										$tot_open_receipt += $transdtl['debit']; 
										$tot_open_payment += $transdtl['credit']; 
									endforeach;
								endforeach;
								$open_tot_receipt += $tot_open_receipt;
								$open_tot_payment += $tot_open_payment;
							 endforeach;
						    endforeach;
							$opening_balance = ($open_tot_receipt - $open_tot_payment) + $closingBalanceYr;
							//echo '<pre>';print_r($opening_balance);exit;
							?>
							<strong>
							<?php echo number_format((float)$grand_tot_receipt = $opening_balance, 2, '.', ',');?>
							</strong>
						</td>
						<td class="purple" style="text-align:right"><strong><?php echo number_format((float)$grand_tot_payment = 0.00, 2, '.', ',');?></strong></td>
					</tr>
					<?php $i = 1; 
					foreach($this->headObj->getCash(array('h.head_type'=> '10'), 'id') as $head):
					    $head_id = $head['id'];
						 $vouchers = $this->transactionObj->getVouchersPresent($start_date,$end_date,$location_id, $head_id);
						 foreach($vouchers as $voucher):
							?>
							<?php
								$tot_receipt = 0.00; $tot_payment = 0.00;
								foreach($this->transactionObj->getDisinctTID($voucher['voucher_type'],$start_date,$end_date,$location_id, $head_id) as $transactions):
									foreach($this->transactiondetailObj->getCash($voucher['voucher_type'],$start_date,$end_date,array('transaction'=> $transactions['transaction_id'], 'td.head' => $head_id, 'td.location' =>$location_id)) as $transdtl):
								$tot_receipt += $transdtl['debit'];
								$tot_payment += $transdtl['credit'];
							
								endforeach;
								endforeach;
							?>
							<tr>
								<td><strong><?php echo $this->journalObj->getColumn($transdtl['voucher_type'],'journal')." amount";?></strong></td>
								<td></td>
								<td></td>
								<td></td>
								<td class="green" style="text-align:right"><strong><?php echo number_format((float)$tot_receipt, 2, '.', ','); $grand_tot_receipt += $tot_receipt;?></strong></td>
								<td class="purple" style="text-align:right"><strong><?php echo number_format((float)$tot_payment, 2, '.', ','); $grand_tot_payment += $tot_payment;?></strong></td>
							</tr>
							<?php 
								if($cash_detail == '1'):
								foreach($this->transactionObj->getDisinctTID($voucher['voucher_type'],$start_date,$end_date,$location_id,$head_id) as $transactions):
									foreach($this->transactiondetailObj->getCash($voucher['voucher_type'],$start_date,$end_date,array('transaction'=> $transactions['transaction_id'], 'td.head' => $head_id, 'td.location' =>$location_id)) as $transdtl):
							?>
							<tr>
								<td><?php echo $transdtl['remark'];?></td>
								<td><?php if($location_id == '7'):
								        echo $txn_heads = $this->transactiondetailObj->getCashBookHead(array('td.transaction'=>$transactions['transaction_id']));
								    endif;
								?></td>
                                <td><?php echo $transdtl['voucher_no']; ?></td>
								<td><?php echo $transdtl['voucher_date'];?></td>
								<td class="green" style="text-align:right"><?php echo number_format((float)$transdtl['debit'], 2, '.', ',');?></td>
								<td class="purple" style="text-align:right"><?php echo number_format((float)$transdtl['credit'], 2, '.', ',');?></td>
							</tr>
							<?php 
								endforeach;
								endforeach;
							else:
							?>
							<tr>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
							<?php endif;?>
					<?php 
						endforeach;
					endforeach;
					?>
					<tr>
						<td><strong>Total Amount</strong></td>
						<td></td>
						<td></td>
						<td></td>
						<td class="green" style="text-align:right"><strong><?php echo number_format((float)$grand_tot_receipt, 2, '.', ',');?></strong></td>
						<td class="purple" style="text-align:right"><strong><?php echo number_format((float)$grand_tot_payment, 2, '.', ',');?></strong></td>
					</tr>
					<tr>
						<td></td>
						<td></td>
						<td></td>
						<td><strong>Closing Balance</strong></td>
						<td></td>
						<td class="purple" style="text-align:right"><strong><?php echo number_format((float)$grand_tot_receipt-$grand_tot_payment, 2, '.', ',');?></strong></td>
					</tr>	
				</tbody>	
			</table>
		</div>
	</div>
</div>

<script text="text/javascript">
$(function() {
	$('#location').on('change',function(){
		//alert($('#region').val());
		$.post(
			'<?php echo $this->url('report', array('action' => 'getcashaccount')); ?>',
			{
				location: $(this).val(),
			},
			function(data){
				//console.log(data);	
				$('#cashaccount').html(data.ca);	
				$("#cashaccount").trigger("chosen:updated");			
			},
			'json'
		);
	});
	$('#start_date').datepicker();
	$('#start_date').on('changeDate', function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').datepicker();
	$('#end_date').on('changeDate', function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L = landscape, P = potrait
	});
	var doc_loc = $('input#loc').val()+'(from: '+$('input#start_date').val()+' to: '+$('input#end_date').val()+')';
	$("#excel").click(function(){
		$("#table2excel").table2excel({
		// exclude CSS class
		exclude: ".noExl",
		name: "Worksheet Name",
		filename: "CashBook_"+doc_loc, //do not include extension
		}); 
	});

	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'location': {
						validators: {
							notEmpty: {
								message: 'Please select loc'
							}
						}
					},
					'start_date': {
						validators: {
							notEmpty: {
								message: 'Please select start date'
							}
						}
					},
					'end_date': {
						validators: {
							notEmpty: {
								message: 'Please select end date'
							}
						}
					},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});	
</script>