<?php
/**
 * 
 * View -- of Accounts/TransactionController/indexAction
 * 
 */
$this->headTitle($this->title);
?>
<?php //echo $user;exit;
$minYear='';
$minYear = date('Y', strtotime($minYear)); ?>
<?php 
$total_credit=0;
$total_debit=0;?>
<div class="card">
    <div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="post" action="<?php echo $this->url('report',array('action' => 'sdr')); ?>"  enctype="multipart/form-data" >
					<div class="form-group col-lg-2">
						<label class="control-label" for="start_date">Start Date</label>
						<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
							<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
							<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
						</div>
					</div>
					<div class="form-group col-lg-2">
						<label class="control-label" for="end_date">End Date</label>
						<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
							<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
							<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
						</div>
					</div> 
					<div class="form-group col-lg-3">
						<label for="ledger" class="label-control">Ledger</label>
						<select class="form-control" data-placeholder="Select" name="ledger" id="ledger" >
							<option value="" ></option>
							<option value="-1">All</option>
							<?php 
								$heads = $this->headObj->getAll();
								foreach($heads as $head):
									$selected_head = ($head['id'] == $data['ledger'])?"selected":"";
							?>
								<option value="<?php echo $head['id'];?>" <?php echo $selected_head;?>>
									<?php echo $head['code'];?>
								</option>
							<?php endforeach;?>
						</select>
					</div>
					<div class="form-group col-lg-3">
						<label for="subledger" class="label-control">Sub-Ledger</label>
						<select class="form-control" data-placeholder="Select" name="subledger" id="subledger" >
							<option value="-1">All</option>
							<?php 
								$dubledgers = $this->subheadObj->getAll();
								foreach($dubledgers as $subhead):
								$selected_sl = ($subhead['id']==$data['subledger'])?"selected":"";
							?>
								<option value="<?php echo $subhead['id'];?>" <?php echo $selected_sl;?>>
									<?php echo $subhead['code'];?>
								</option>
							<?php endforeach;?>				
						</select>		
					</div> 
					<div class="form-group col-lg-2">
						<div class="space-12"></div>
						<button type="submit" class="btn btn-sm btn-primary pull-left"><i class="fa fa-refresh"></i> Refresh </button>
					</div>
				</form>
			</div>
			<div class="col-lg-3">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2,$page);?>
				</div>
			</div>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Ledger</th>
					<th>Sub-Ledger</th>
					<th>Rate</th>
					<th>SDR(credit)</th>
					<th>SDR(Debit)</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1+(($page-1)*25); foreach ($paginator as $row):
				    $total_credit += $row['credit_sdr'];
					$total_debit += $row['debit_sdr'];?>
						<tr>
							<td><?php echo $i++; ?> </td>
							<td>
								<span style="color:#666;font-size:95%;"><?php echo $this->headObj->getColumn($row['head'],'name');?></span>
							</td>
							<td>
							   <span class=""><?php echo $this->subheadObj->getColumn($row['sub_head'],'name');?></span>
							</td>
							<td>
							   <span class=""><?php echo $row['rate'];?></span>
							</td>
							<td>
							    <span style="color:#666;font-size:95%;"><?php echo $row['credit_sdr'];?></span>
							</td>
							<td>
							    <span style="color:#666;font-size:95%;"><?php echo $row['debit_sdr'];?></span>
							</td>
						</tr>
				    <?php 
				endforeach;//exit;?>
				<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
					<th colspan="4" style="font-size:13px"> Total : </th>
					<th style="font-size:13px; text-align:right"><?php  echo number_format((float)$total_credit, 2, '.', ',');?>(SDR)</th>
					<th style="font-size:13px; text-align:right"><?php  echo number_format((float)$total_debit, 2, '.', ',');?>(SDR)</th>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<script>
$(function(){
	$('#start_date').datepicker();	
    $('#end_date').datepicker();	
	$("tr[data-href]").each(function(){ 
		if($(this).attr('data-href')!='#'){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).attr("data-href");
			});
		}
	});
	$('#dataTables').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
});
</script>

