<?php
  $subHeadDtls = $this->subheadObj->get(array('head'=>$this->head), $order='name');
  //echo '<pre>';print_r($subHeadDtls);exit;
  if(sizeof($subHeadDtls) > 0){	
	     ?>		  
			<div class="col-lg-12">
			<h3>RECONCILE <?php  echo " [ ",$this->headObj->getColumn($this->head, 'name'); ?>] </h3>
				<table class="table" id="trdetails_table" style="border-top:2px solid #ddd;">
					<thead>
						<tr>
							<th>#</th>							
							<th>Sub Ledger/SubHead</th>
							<th>Voucher Amount</th>
							<th>Voucher Date</th>
							<th>Reconcile Date</th>
						</tr>
					</thead>
					<tbody>
					<?php 
					$i=1;
					foreach($subHeadDtls as $row):
					    $result = $this->transactiondetailsObj->gettransactiondtls($row['id'],$user_location);
						if(!empty($result)):
							foreach( $result as $dtl):						
							$vamount = $dtl['debit'];
							$vdates = $dtl['voucher_dates'];
							$id = $dtl['id'];
							//echo '<pre>';print_r($result);?>
							<tr> 
								<td><?php echo $i++; ?> </td>
								<td><strong><?php echo $row['code'].'-'.$row['name']; ?> </strong>
								<input type ="hidden" name="head[]" value="<?php echo $this->headObj->getColumn($this->head, 'id'); ?>">
								<input type="hidden" name="sub_head[]" value="<?php echo $row['id']; ?>">
								<input type="hidden" value="<?php echo $id; ?>" name="transactiondtl_id[]"> </td>
								<td><div class="form-group"> <input type="amount" name="amount[]" id="amount" class="form-control" value="<?php echo $vamount; ?>" step="0.001"  disabled></div></td>
								<td><div class="form-group"> <input type="vdate" name="vdate[]" id="vdate" class="form-control" value="<?php echo $vdates; ?>" step="0.001"  disabled></div></td>
								<td>
									<div class="form-group">
										<div class="date input-group" id="reconcile_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
											<input class="form-control span2" name="reconcile_date[]" id="reconcile_date" value= "<?php //echo date('Y-m-d');?>" placeholder="<?php echo date('Y-m-d');?>" >
											<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
										</div>
									</div>
								</td>
							</tr>
					        <?php
					        endforeach;
					    endif;
 					endforeach;//exit;
					?>
					</tbody>
				</table>
			</div>
<?php			
  }
?>
<script type="text/javascript">
	$(function() {
		$('#reconcile_date').datepicker();
		$('form').formValidation({
			framework: 'bootstrap',
	        excluded: ':disabled',
	        message: 'This value is not valid',
	        fields: {
	            'reconcile_date': {
	                validators: {
	                    notEmpty: {
	                        message: 'Please enter Reconcile date'
	                    }
	                }
	            },           
	        }
		})
		.on('success.field.fv', function(e, data) {
            if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
                data.fv.disableSubmitButtons(true);
            }
        });
		$('#voucher_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
	});
</script> 
