<?php
/**
 * View -- of Stock/StockmovementController/stockmovementAction
 */
	$this->headTitle($this->title);
	$total_stock_value=0;
	$total_credit_value=0;
	$total_cash_value=0;
?>
<style>
	tr.group,
	tr.group:hover {
		background-color: #ddd !important;
		font: 15px "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}
</style>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$start = $time;
?>
<div class="row">
	<div class="col-lg-12">
		<form method="post" action="<?php echo $this->url('stockreport', array('action' => 'locationstockmovement')); ?>"  enctype="multipart/form-data" >    
			<div class="row">
			    <div class="form-group col-lg-2">
					<label for="region" class="control-label">Region</label>
					<input type="hidden" name="region_name" id="region_name" value="<?php echo $this->regionObj->getColumn($data['region'],'region');?>" />
					<select id="region" name="region" class="form-control" data-placeholder="Select" required>
						<option value=""></option>
						<?php foreach($this->regionObj->getAll() as $region):
							$selected_region = ($data['region']==$region['id'])?"selected":"";?>
							<option value="<?php echo $region['id'];?>"<?php echo $selected_region;?>>
								<?php echo $region['region'];?>
							</option>
							<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="location">Location</label>
					<input type="hidden" name="location_name" id="location_name" value="<?php echo $this->locationObj->getColumn($location['id'],'location');?>" >
					<select class="form-control" name="location" id="location" data-placeholder="select" >
						<option value="-1">All</option>
						<?php  
							$locations = $locationObj->get(array('l.region'=>$data['region'],'l.location_type'=>array(1,2,7,8)));
							foreach ($locations as $location):
								$selected_loc = ($location['id']==$data['location'])?"selected":"";
						?>
							<option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
								<?php echo $location['location']; ?>
							</option>
						<?php endforeach;?>								
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label for="location_type" class="control-label">Location Type</label>
					<input type="hidden" name="location_type_name" id="location_type_name" value="<?php echo ($location['id']=='-1')?'All Locations':$this->locationObj->getColumn($location['id'],'location');?>" />
					<select name="location_type" id="location_type" class="form-control" data-placeholder="Select">
						<option value="-1" <?php echo ($data['location_type']=='-1')?'selected':'';?>>All</option>
						<?php foreach($this->locationtypeObj->get(array('id'=>array(1,2,7,8))) as $location_type):
							$selected_location_type = ($data['location_type']==$location_type['id'])?'selected':'';
						?>
							<option value="<?php echo $location_type['id'];?>" <?php echo $selected_location_type; ?>>
								<?php echo $location_type['location_type'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="activity">Activity</label>
					<input type="hidden" name="activity_name" id="activity_name" value="<?php echo $this->activityObj->getColumn($data['activity'],'activity');?>" >
					<select class="form-control" name="activity" id="activity" data-placeholder="select" >
						<option value=""></option>
						<?php 
							$activities = $this->activityObj->getAll();
							foreach($activities as $activity):
							$selected_act = ($activity['id']==$data['activity'])?"selected":"";
						?>
							<option value="<?php echo $activity['id'];?>" <?php echo $selected_act;?>>
								<?php echo $activity['activity'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="start_date">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="end_date">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="form-group col-lg-2">
					<label class="control-label" for="item">Stock Item</label>
					<select class="form-control" name="item" id="item" data-placeholder="select" >
						<option value="-1" <?php echo ($data['item'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($stock_items as $stock_item):
							$selected_item = ($stock_item['item_id'] == $data['item'])?'selected':'';
						?>
							<option value="<?php echo $stock_item['item_id'];?>" <?php echo $selected_item;?> >
								<?php echo $stock_item['code'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="col-lg-10">
					<div class="space-8"></div>
					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>Refresh</button>
				</div>
			</div>
		</form>
		<div class="hr hr-dotted"></div>
		<div class="space-4"></div>
		<div>
			<table class="table table-striped table-condensed table-bordered table-hover" id="example">
				<thead>
					<tr>
					    <th>Location</th>
						<th>Item</th>
						<?php if($data['activity'] == '1' || $data['activity'] == 7): ?>
						<th>Batch</th>
						<th>Supplier</th>
						<?php endif;?>
						<th>Opening</th>
						<th>Purchase</th>
						<th>IntRecpt</th>
						<th>Dispatch</th>
						<th>Dumped</th>
						<th>Adjusted</th>
						<th>Credit</th>
						<th>Cash</th>
						<th>Intransit</th>
						<th>Closing</th>
						<th>Actual Qty</th>
						<th>ELC</th>
						<th>SP</th>
						<th>Stock Value</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					if($data['location'] == '-1'):
    					if($data['location_type'] != '-1'):
    					    $locations = $this->locationObj->get(array('l.location_type'=>$data['location_type'],'l.region'=>$data['region']));
    					else:
    					    $locations = $this->locationObj->get(array('l.location_type'=>array(1,2,7,8),'l.region'=>$data['region']));
    				    endif;
    				else:
    				    $locations = $this->locationObj->get($data['location']);
    				endif;
				    foreach($locations as $location):
					if($data['activity'] == 1 || $data['activity'] == 7):
						$lists = $this->batchObj->filterSMBatch($location['id'],array('i.activity'=>$data['activity'], 'i.valuation'=>0, 'b.status' => 3),'d.location',$data['item']);
						//echo "From batch=".sizeof($lists)."<br>";
						$array = array();
						foreach($lists as $list):
							array_push($array, $list['id']);
						endforeach;
						$opening_list = $this->openingObj->filterSMBatch($data['start_date'],$location['id'],array('i.activity'=>$data['activity']),'o.opening_date','od.location',$array,$data['item']);
						//echo "Opening=".sizeof($opening_list)."<br>";
						$pur_list = $this->pur_receiptObj->filterSMBatch($data['end_date'],$location['id'],array('p.status'=>3,'p.activity'=>$data['activity']),'p.prn_date','p.location',$array,$data['item']);
						//echo "Purchase=".sizeof($pur_list)."<br>";
						$disp_list = $this->dispatchObj->filterSMBatch($data['start_date'],$data['end_date'],$location['id'],array('d.status'=>array(2,10,3),'d.activity'=>$data['activity']),'d.dispatch_date','d.from_location',$array,$data['item']);
						//echo "dispatch=".sizeof($disp_list)."<br>";
						$rept_list = $this->dispatchObj->filterSMReceiptBatch($data['end_date'],$location['id'],array('d.status'=>array(3),'d.activity'=>$data['activity']),'d.received_on','d.to_location',$array,$data['item']);
						//echo "receipt=".sizeof($rept_list)."<br>";
						$tras_list_date = $this->dispatchObj->filterSMBatchTransitDate($data['end_date'],$location['id'],array('d.activity'=>$data['activity'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location',$array,$data['item']);
						//echo "In-Transit-Date=".sizeof($tras_list_date)."<br>";
						$tras_list_status = $this->dispatchObj->filterSMBatchTransitStatus($data['end_date'],$location['id'],array('d.activity'=>$data['activity'],'d.status'=>array(2,10)),'d.dispatch_date','d.to_location',$array,$data['item']);
						//echo "In-Transit-Status=".sizeof($tras_list_status)."<br>";
						$converted_to_list = $this->itemconversionObj->filterSMBatchto($data['start_date'],$data['end_date'],$location['id'],array('c.status'=>array(3),'i.activity'=>$data['activity']),'c.conversion_date','c.location',$array,$data['item']);
						//echo "converted to list =".sizeof($converted_to_list)."<br>";
						$converted_from_list = $this->itemconversionObj->filterSMBatchfrom($data['start_date'],$data['end_date'],$location['id'],array('c.status'=>array(3),'i.activity'=>$data['activity']),'c.conversion_date','c.location',$array,$data['item']);
						//echo "converted from list=".sizeof($converted_from_list)."<br>";	
						$sale_list = $this->salesObj->filterSMBatch($data['start_date'],$data['end_date'],$location['id'],array('i.activity'=>$data['activity'],'s.status'=>3),'s.sales_date','s.location',$array,$data['item']);
						//echo "Sales=".sizeof($sale_list)."<br>";
						$sam_list = $this->samObj->filterSMBatch($data['start_date'],$data['end_date'],$location['id'],array('s.activity'=>$data['activity'],'s.status'=>3),'s.sam_date','s.location',$array,$data['item']);
						//echo "Sam=".sizeof($sam_list)."<br>";
						$row_list = array_merge($lists,$opening_list,$pur_list,$disp_list,$rept_list,$tras_list_date,$tras_list_status,$converted_to_list,$converted_from_list,$sale_list,$sam_list);
						//echo "Merge = ".sizeof($row_list)."<br>";
						$row_unique = array_unique($row_list, SORT_REGULAR);
						//echo "Unique = ".sizeof($row_unique)."<br>";
						$total_stock_value = 0;
						$total_credit_value = 0;
						$total_cash_value = 0;
						foreach($row_unique as $list): 
						    if($list['id'] > 0):
							$batches = $this->batchObj->fetchSMBatchDetails($list['id']);
							foreach($batches as $batch);
							
							if($location['id'] != '-1'):
								$batch_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$location['id']),'landed_cost');
								//$batch_elc = $batch['landed_cost'];
								$batch_elc = $batch_elc/$batch['unit_uom'];
								$batch_sp = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$location['id']),'selling_price');
								
								$total_qty = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$location['id']),'quantity');
							else:
								$total_elc = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'landed_cost');
								$total_no = $this->batch_dtlsObj->getCount(array('batch'=>$batch['id']));
								$batch_elc = $total_elc/$total_no;
								$batch_elc = $batch_elc/$batch['unit_uom'];
								
								$total_sp = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'selling_price');
								$batch_sp = $total_sp/$total_no;
								
								$total_qty = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'quantity');
							endif;
							//Opening Stock Table
							$op_stock_openings = $this->openingObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('o.batch'=>$batch['batch'],'o.item'=>$batch['item']));
							
							$op_purchases = $this->pur_receiptObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('pd.batch'=>$batch['id'],'pd.item'=>$batch['item'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
							
							$op_dispatch = $this->dispatchObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,10,3)),'d.dispatch_date','d.from_location','dd.basic_quantity');
							$op_in_receipt = $this->dispatchObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>3),'d.received_on','d.to_location','dd.accepted_qty');
							
							$op_converted_to = $this->itemconversionObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('converted_item_batch'=>$batch['id'],'converted_item'=>$batch['item'],'status'=>3),'conversion_date','location','converted_basic_qty');
							$op_converted_from = $this->itemconversionObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('batch'=>$batch['id'],'item'=>$batch['item'],'status'=>3),'conversion_date','location','basic_qty');
							
							$op_credit = $this->salesObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							$op_cash = $this->salesObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							
							$op_dump = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>array(1,2),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$op_shortage = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>3,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$op_sales_promotion = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>4,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$op_adjustment = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							
							$opening = $op_stock_openings + $op_purchases + $op_adjustment - $op_dispatch + $op_in_receipt + $op_converted_to - $op_converted_from - $op_credit - $op_cash - $op_dump - $op_shortage -$op_sales_promotion;
							
							//Purchase Receipt Table
							$purchases = $this->pur_receiptObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('pd.batch'=>$batch['id'],'pd.item'=>$batch['item'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
							
							//Dispatch Table
							$dispatch = $this->dispatchObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,10,3)),'d.dispatch_date','d.from_location','dd.basic_quantity');
							$in_receipt = $this->dispatchObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>3),'d.received_on','d.to_location','dd.accepted_qty');
							$in_transit_date = $this->dispatchObj->fetchSMTransitQtyDateSUM($data['end_date'],$location['id'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit_status = $this->dispatchObj->fetchSMTransitQtyStatusSUM($data['end_date'],$location['id'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,10)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit = $in_transit_date + $in_transit_status;
							//Item Conversion
							$converted_to = $this->itemconversionObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('converted_item_batch'=>$batch['id'],'converted_item'=>$batch['item'],'status'=>3),'conversion_date','location','converted_basic_qty');
							$converted_from = $this->itemconversionObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('batch'=>$batch['id'],'item'=>$batch['item'],'status'=>3),'conversion_date','location','basic_qty');
							//Sales Table
							$credit = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							$cash = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							//SAM Table
							$dump = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>array(1,2),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$shortage = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>3,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$sales_promotion = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>4,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$adjustment = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							
							//Adjusted - sum of $shorage and $converted from
							$adjusted = $shortage + $converted_from + $adjustment + $sales_promotion;
							//Sum of $converted_to and $in_receipt
							$int_conv = $in_receipt + $converted_to;
							
							//Closing Balance
							$closing = $opening + $purchases + $in_receipt + $adjustment - $dispatch + $converted_to - $converted_from - $dump - $shortage - $cash - $credit - $sales_promotion; 
							if($opening == 0 && $purchases == 0 && $in_receipt == 0 && $dispatch == 0 &&$dump == 0 && $adjustment == 0 && $shortage == 0 &&$cash == 0 && $credit== 0 && $in_transit == 0 && $converted_to == 0 && $converted_from == 0 && $sales_promotion == 0):
						?>
						<?php else:
						    $credit_value = $credit * $batch_sp;
						    $credit_value = number_format($credit_value, 2, '.', '');
					        $total_credit_value += $credit_value;
					        $cash_value = $cash * $batch_sp;
					        $cash_value = number_format($cash_value, 2, '.', '');
					        $total_cash_value += $cash_value; 
					        
							$opening = ($opening != '' && $opening != 0)?number_format($opening, 2, '.', ','):'-';
							$purchases = ($purchases != '' && $purchases != 0)?number_format($purchases, 2, '.', ','):'-';
							$in_receipt = ($in_receipt != '' && $in_receipt != 0)?number_format($in_receipt, 2, '.', ','):'-';
							$dispatch = ($dispatch != '' && $dispatch != 0)?number_format($dispatch, 2, '.', ','):'-';
							$converted_to = ($converted_to != '' && $converted_to != 0)?number_format($converted_to, 2, '.', ','):'-';
							$converted_from = ($converted_from != '' && $converted_from != 0)?number_format($converted_from, 2, '.', ','):'-';
							$dump = ($dump != '' && $dump != 0)?number_format($dump, 2, '.', ','):'-';
							$shortage = ($shortage != '' && $shortage != 0)?number_format($shortage, 2, '.', ','):'-';
							$credit = ($credit != '' && $credit != 0)?number_format($credit, 2, '.', ','):'-';
							$cash = ($cash != '' && $cash != 0)?number_format($cash, 2, '.', ','):'-';
							$in_transit = ($in_transit != '' && $in_transit != 0)?number_format($in_transit, 2, '.', ','):'-';
							$adjusted = ($adjusted != '' && $adjusted != 0)?number_format($adjusted, 2, '.', ','):'-';
							$int_conv = ($int_conv != '' && $int_conv != 0)?number_format($int_conv, 2, '.', ','):'-';
						?>
							<tr>
						        <td><?php echo $location['location']?></td>
								<td><?php echo $batch['code'];?></td>
								<?php if($data['activity'] == '1' || $data['activity'] == '7'): ?>
								<td><?php echo $batch['batch'];?></td>
								<td><?php echo $this->partyObj->getColumn($batch['supplier'],'code');?></td>
								<?php endif;?>
								<td class="blue" style="text-align:right" title="<?php echo "Opening : ".$op_stock_openings."&#013Purchase : ".$op_purchases."&#013IntRecpt : ".$op_in_receipt."&#013Convert To : ".$op_converted_to."&#013Convert From : ".$op_converted_from."&#013Dispatch : ".$op_dispatch."&#013Dumped : ".$op_dump."&#013Shortage : ".$op_shortage."&#013Credit : ".$op_credit."&#013Cash : ".$op_cash;?>">
									<?php echo $opening;?></td>
								<td class="green" style="text-align:right"><?php echo $purchases;?></td>
								<td class="green" style="text-align:right" title="<?php echo "IntRecpt : ".$in_receipt."&#013Converted To : ".$converted_to;?>"><?php echo $int_conv;?></td>
							
								<td class="red" style="text-align:right"><?php echo $dispatch;?></td>
								<td class="red" style="text-align:right"><?php echo $dump; ?></td>
								<td class="red" style="text-align:right" title="<?php echo "Shortage : ".$shortage."&#013Converted From : ".$converted_from."&#013Adjustment: ".$adjustment;?>"><?php echo $adjusted; ?></td>
								<td class="red" style="text-align:right"><?php echo $credit;?></td>
								<td class="red" style="text-align:right"><?php echo $cash;?></td>
								<td class="purple" style="text-align:right"><?php echo $in_transit;?></td>
								<td class="blue" style="text-align:right"><?php echo ($closing != '' && $closing != 0)?number_format($closing, 2, '.', ','):'-';?></td>
								<td class="orange" style="text-align:right"><?php echo number_format($total_qty, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format($batch_elc, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format($batch_sp, 2, '.', ',');?></td>
								<td style="text-align:right">
									<?php 
										$sv = $closing * $batch_elc;
										$total_stock_value += $sv;
										echo number_format($sv, 2, '.', ',');
									?>
								</td>
							</tr>
					<?php 
							endif;
						endif;
						endforeach;
					else:
						$items = $this->batchObj->fetchSMDistinctItems(array('i.activity'=>$data['activity'], 'i.valuation'=>1, 'b.status' => 3),$data['item']);
						$total_stock_value = 0;
						$total_credit_value = 0;
						$total_cash_value = 0;
						foreach($items as $item):
							if($location['id'] != '-1'):
								$spbatches = $this->movingitemspObj->getBatchRow(array('item' => $item['item_id']),'sp_effect_date',$data['start_date'],$data['end_date']);
								if(sizeof($spbatches)==0){
									$spbatches = $this->movingitemspObj->getBatchByDate(array('m.item' => $item['item_id']),$data['start_date']);
								}
								$moving_elc_sum = 0;
								$moving_count = 0;
								foreach($spbatches as $spbatch):
									$batch_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$spbatch['batch'],'location'=>$location['id']),'landed_cost');
									$unit_uom = $this->batchObj->getColumn($spbatch['batch'],'unit_uom');
									$batch_elc = $batch_elc/$unit_uom;
									$moving_elc_sum += $batch_elc;
									$moving_count += 1;
								endforeach;
								$dated = date('Y-m-d');
								$moving_elc = $moving_elc_sum/$moving_count;
								$moving_sp = $this->movingitemspObj->getRateColumn(array('m.item'=>$item['item_id'],'bd.location'=>$location['id']),$dated);
								
								$total_qty = $this->movingObj->getSUM(array('item' => $item['item_id'],'location'=>$location['id']),'quantity');
							else:
								$spbatches = $this->movingitemspObj->getBatchByDate(array('m.item' => $item['item_id']),$data['start_date']);
								foreach($spbatches as $spbatch);
								
								$unit_uom = $this->batchObj->getColumn($spbatch['batch'],'unit_uom');
								$total_elc = $this->batch_dtlsObj->getSUM(array('batch'=>$spbatch['batch']),'landed_cost');
								$total_no = $this->batch_dtlsObj->getCount(array('batch'=>$spbatch['batch']));
								$moving_elc = $total_elc/$total_no;
								$moving_elc = $moving_elc/$unit_uom;
								
								$total_sp = $this->batch_dtlsObj->getSUM(array('batch'=>$spbatch['batch']),'selling_price');
								$moving_sp = $total_sp/$total_no;
								$total_qty = $this->movingObj->getSUM(array('item' => $item['item_id']),'quantity');
							endif;
							//Opening Stock Table
							$op_stock_openings = $this->openingObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('o.item'=>$item['item_id']));
							
							$op_purchases = $this->pur_receiptObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('pd.item'=>$item['item_id'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
							
							$op_dispatch = $this->dispatchObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10,3)),'d.dispatch_date','d.from_location','dd.basic_quantity',$openingDate);
							$op_in_receipt = $this->dispatchObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('dd.item'=>$item['item_id'],'d.status'=>3),'d.received_on','d.to_location','dd.accepted_qty');
							
							$op_converted_to = $this->itemconversionObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('converted_item'=>$item['item_id'],'status'=>3),'conversion_date','location','converted_basic_qty');
							$op_converted_from = $this->itemconversionObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('item'=>$item['item_id'],'status'=>3),'conversion_date','location','basic_qty');
							
							$op_credit = $this->salesObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.item'=>$item['item_id'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							$op_cash = $this->salesObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.item'=>$item['item_id'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							
							$op_dump = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>array(1,2),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$op_shortage = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>3,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$op_sales_promotion = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>4,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$op_adjustment = $this->samObj->fetchSMOpeningSUM($data['start_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							
							$plus_opening = $op_stock_openings + $op_purchases + $op_adjustment + $op_in_receipt + $op_converted_to;
							$minus_opening = $op_dispatch + $op_converted_from + $op_credit + $op_cash + $op_dump + $op_shortage + $op_sales_promotion;
							$opening = $plus_opening - $minus_opening;
							
							//Purchase Receipt Table
							$purchases = $this->pur_receiptObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('pd.item'=>$item['item_id'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
							//Dispatch Table
							$dispatch = $this->dispatchObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10,3)),'d.dispatch_date','d.from_location','dd.basic_quantity');
							$in_receipt = $this->dispatchObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('dd.item'=>$item['item_id'],'d.status'=>3),'d.received_on','d.to_location','dd.accepted_qty');
							$in_transit_date = $this->dispatchObj->fetchSMTransitQtyDateSUM($data['end_date'],$location['id'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit_status = $this->dispatchObj->fetchSMTransitQtyStatusSUM($data['end_date'],$location['id'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit = $in_transit_date + $in_transit_status;
							//Item Conversion
							$converted_to = $this->itemconversionObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('converted_item'=>$item['item_id'],'status'=>3),'conversion_date','location','converted_basic_qty');
							$converted_from = $this->itemconversionObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('item'=>$item['item_id'],'status'=>3),'conversion_date','location','basic_qty');
							//Sales Table
							$credit = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.item'=>$item['item_id'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							$cash = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.item'=>$item['item_id'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							//SAM Table
							$dump = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>array(1,2),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$shortage = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>3,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$sales_promotion = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>4,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							$adjustment = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$location['id'],array('sd.item'=>$item['item_id'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							
							//Adjusted - sum of $shorage and $converted from
							$adjusted = $shortage + $converted_from + $adjustment + $sales_promotion;
							//Sum of $converted_to and $in_receipt
							$int_conv = $in_receipt + $converted_to;
							
							//Closing Balance
							$closing = $opening + $purchases + $in_receipt + $adjustment - $dispatch + $converted_to - $converted_from - $dump - $shortage - $cash - $credit - $sales_promotion; 
							if($opening == 0 && $purchases == 0 && $in_receipt == 0 && $dispatch == 0 && $dump == 0 && $shortage == 0 && $adjustment == 0 && $cash == 0 && $credit== 0 && $in_transit == 0 && $converted_to == 0 && $converted_from == 0 && $sales_promotion == 0):
						?>
						<?php else:
						        $credit_value = $credit * $moving_sp;
						        $total_credit_value += $credit_value;
						        $cash_value = $cash * $moving_sp;
						        $total_cash_value += $cash_value;
						        
								$opening = ($opening != '' && $opening != 0)?number_format($opening, 2, '.', ','):'-';
								$purchases = ($purchases != '' && $purchases != 0)?number_format($purchases, 2, '.', ','):'-';
								$in_receipt = ($in_receipt != '' && $in_receipt != 0)?number_format($in_receipt, 2, '.', ','):'-';
								$dispatch = ($dispatch != '' && $dispatch != 0)?number_format($dispatch, 2, '.', ','):'-';
								$converted_to = ($converted_to != '' && $converted_to != 0)?number_format($converted_to, 2, '.', ','):'-';
								$converted_from = ($converted_from != '' && $converted_from != 0)?number_format($converted_from, 2, '.', ','):'-';
								$dump = ($dump != '' && $dump != 0)?number_format($dump, 2, '.', ','):'-';
								$shortage = ($shortage != '' && $shortage != 0)?number_format($shortage, 2, '.', ','):'-';
								$credit = ($credit != '' && $credit != 0)?number_format($credit, 2, '.', ','):'-';
								$cash = ($cash != '' && $cash != 0)?number_format($cash, 2, '.', ','):'-';
								$in_transit = ($in_transit != '' && $in_transit != 0)?number_format($in_transit, 2, '.', ','):'-';
								$adjusted = ($adjusted != '' && $adjusted != 0)?number_format($adjusted, 2, '.', ','):'-';
								$int_conv = ($int_conv != '' && $int_conv != 0)?number_format($int_conv, 2, '.', ','):'-';
							?>
							<tr>
							    <td><?php echo $location['location']?></td>
								<td><?php echo $item['code'];?></td>
								<?php if($data['activity'] == '1' || $data['activity'] == '7'): ?>
								<td><?php echo $this->partyObj->getColumn($item['supplier'],'code');?></td>
								<td><?php echo 'NA';?></td>
								<?php endif;?>
								<td class="blue" style="text-align:right" title="<?php echo "Opening : ".$op_stock_openings."&#013Purchase : ".$op_purchases."&#013IntRecpt : ".$op_in_receipt."&#013Convert To : ".$op_converted_to."&#013Convert From : ".$op_converted_from."&#013Dispatch : ".$op_dispatch."&#013Dumped : ".$op_dump."&#013Shortage : ".$op_shortage."&#013Credit : ".$op_credit."&#013Cash : ".$op_cash;?>">
									<?php echo $opening;?></td>
								<td class="green" style="text-align:right"><?php echo $purchases;?></td>
								<td class="green" style="text-align:right" title="<?php echo "IntRecpt : ".$in_receipt."&#013Converted To : ".$converted_to;?>"><?php echo $int_conv;?></td>
								<td class="red" style="text-align:right"><?php echo $dispatch;?></td>
								<td class="red" style="text-align:right"><?php echo $dump; ?></td>
								<td class="red" style="text-align:right" title="<?php echo "Shortage : ".$shortage."&#013Converted From : ".$converted_from."&#013Adjustment : ".$adjustment;?>"><?php echo $adjusted; ?></td>
								<td class="red" style="text-align:right"><?php echo $credit;?></td>
								<td class="red" style="text-align:right"><?php echo $cash;?></td>
								<td class="purple" style="text-align:right"><?php echo $in_transit;?></td>
								<td class="blue" style="text-align:right"><?php echo ($closing != '' && $closing != 0)?number_format($closing, 2, '.', ','):'-';;?></td>
								<td class="orange" style="text-align:right"><?php echo number_format($total_qty, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format($moving_elc, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format($moving_sp, 2, '.', ',');?></td>
								<td style="text-align:right"><?php 
										$sv = $closing * $moving_elc;
										$total_stock_value += $sv;
										echo number_format($sv, 2, '.', ',');
									?>
								</td>
							</tr>
						<?php 
								endif;
						endforeach;
					endif;
					endforeach;
					?>
				</tbody>
			</table>
		</div>
		<strong>Total Stock Balance Value = <?php echo $this->currency($total_stock_value);?></strong>(<?php //echo $this->numtoWords(number_format($total_stock_value, 3, '.', ''));?>)<br>
		Total Credit Sales Amount = <?php echo $this->currency($total_credit_value);?><br>
		Total Cash Sales Amount = <?php echo $this->currency($total_cash_value);?>
	</div>
</div>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$finish = $time;
	$total_time = round(($finish - $start), 4);
	echo "<p class='pull-right'>Stock Movement Report generated in ".$total_time." seconds.</p>";
?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#start_date').datepicker();
		$('#end_date').datepicker();
		$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#region').on('change', function(){
			//alert($(this).val());
			$.post(
				"<?php echo $this->url('batch', array('action' => 'getreglocation')); ?>",
				{
					region_id: $(this).val(),
				},
				function(data){
					//console.log(data);
					$("#location").html(data.location);
					$("#location").trigger('chosen:updated');				
				},
				'json'
			);	
		});
		$('#activity').on('change', function(){
			$.post(
				"<?php echo $this->url("stockreport", array("action" => "getitemactivity"));?>",
				{
					activity: $(this).val(),
				},
				function(data){
					//console.log(data);
					$('#item').html(data.item);
					$('#item option:selected').removeAttr('selected');
					$('item option[value='+data.selected_item+']').attr('selected', 'selected');
					$('#item').trigger('chosen:updated');
					$('form').formValidation('revalidateField', $('#item').attr('id'));
				},
				'json'
			);
		});
		/*** Form Validation ***/
		$('form').formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid',
				fields: {
				    'region' : {
					 	validators: {
							notEmpty: {
								message: 'Please select region'
						  	}
					  	}
				  	},
					'location': {
					 	validators: {
							notEmpty: {
								message: 'Please select location'
						  	}
					  	}
				  	},
					'activity': {
						validators: {
							notEmpty: {
								message: 'Please select activity'
							}
						}
					},
					'location_type' : {
						validators: {
							notEmpty: {
								message: 'Please select location type'
							}
						}
					},
					'start_date': {
						validators: {
							notEmpty: {
								message: 'Please select start date'
							},
						}
					},
					'end_date': {
						validators: {
							notEmpty: {
								message: 'Please select end date'
							}
						},
					},
					'item': {
						validators: {
							notEmpty: {
								message: 'Please select item'
							}
						}
					},
				}
			}).on('success.field.fv', function(e, data) {
				if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
					data.fv.disableSubmitButtons(true);
			}
		});
		
		var title_table = $('#location_name').val()+'('+$('#activity_name').val()+') from '+$('input#start_date').val()+' to '+$('input#end_date').val();
		if($('#activity').val() == 1 || $('#activity').val() == 7){
			var table = $('#example').DataTable({
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				"columnDefs": [
					{ "visible": false }, 
				],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true,
			} );
			
		}else{
			$('#example').DataTable( {
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				columnDefs: [ {
					visible: false
				} ],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true
			} );
		}
	} );
</script>
