<?php
/**
 * View -- of Purchase/BatchController/editbatchAction
 */
?>
<?php 
	foreach($batch as $batch_rows):	
	extract($batch_rows);
	$batch_id = $id;
	$batch_status = $status;
	$costing = $costing; 
	endforeach;
	if($batch_status == '2' && $costing == "2"){  $readonly = ''; } else {  $readonly = 'readonly';}
	$valuation = $this->itemObj->getColumn($item, 'valuation');
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;Edit Batch : &nbsp;<strong>&nbsp;&nbsp;<?php echo $batch; ?> | <?php echo $item_code; ?></strong>&nbsp;
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('batch', array('action' => 'editbatch', 'id' => $batch_id)); ?>"  enctype="multipart/form-data" >    
						 <div class="row">
							  <input type="hidden" name="batch_id" id="batch_id" value="<?php echo $batch_id;?>" /> 
							  <div class="col-lg-4"> 
								<div class="form-group">
									<label for="item" class="control-label">Item</label>
									<select class="form-control" name="item" id="item" data-placeholder="Select" required>
										<option value=""></option>
										<option value="<?php echo $item;?>" selected>
											<?php echo $item_code;?>
										</option>
									</select> 
								</div>
							</div>
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="uom" class="control-label">UOM</label>
									<select class="form-control" name="uom" id="uom" data-placeholder="Select" required>
										<option value=""></option>
										<option value="<?php echo $uom;?>" selected>
											<?php echo $uom_code;?>
										</option>
									</select>
								</div>
							</div>	
							<div class="col-lg-4">
								<div class="form-group">
									<label for="batch_date" class="control-label">Batch Date</label>
									<div class="date input-group" id="batch_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $batch_date; ?>" name="batch_date" id="batch_date" type="text" placeholder="Batch Date" <?php echo $readonly; ?> required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>  							
						</div>
						<div class="row">
							<div class="col-lg-4">  
								<div class="form-group">
									<label for="quantity" class="control-label">Quantity</label>
									<input type="text" class="form-control" name="quantity" id="quantity" value="<?php echo $quantity;?>" <?php echo $readonly; ?> required/>
								</div>
							</div>
							<div class="col-lg-4">  
								<div class="form-group">
									<label for="landed_cost" class="control-label">Landed Cost</label>
									<input type="text" class="form-control" name="landed_cost" id="landed_cost" value="<?php echo $landed_cost;?>" <?php echo $readonly; ?> required/>
								</div>
							</div>
							<div class="col-lg-4">
								<div class="form-group">
									<label for="expiry_date" class="control-label">Expiry Date</label>
									<div class="date input-group" id="expiry_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $expiry_date; ?>" name="expiry_date" id="expiry_date" type="text" placeholder="Expiry Date">
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
						</div>
						

						<?php
						if($batch_status == '2' && $costing == "2"){ 
						    $results = $this->batchDetailsObj->get(array('batch'=>$batch_id));
						    ?>
						    <div class="row"> 	
							<div class="col-lg-12"> 
						    <table class="table" id="trdetails_table" style="border-top:2px solid #ddd;">
						      <thead>
							  <tr>
								<th>#</th>
								<th>Location</th>	
								<th>Quantity in Basic UOM</th>
								<th>Landed Cost/Units UOM</th>
								<th>Selling Price  (<?php echo $this->currency_code();?>)</th>
							 </tr>
						     </thead>
						     <tbody>
						    <?php
						    $sl = 1;
						    foreach($results as $row):
                                                       ?>
						          <tr>
							     <td><?php echo $sl++;?> 
							        <input type="hidden" name="batchdtlID[]" value="<?php echo $row['id']; ?>" >
							     </td>
                                 <td><?php echo $this->locationObj->getColumn($row['location'],'location'); ?></td>
							     <td><input type="text" name="qty[]" value="<?php echo $row['actual_quantity']; ?>" class="form-control"></td>
							     <td><input type="text" name="est_landed_cost[]" value="<?php echo $row['landed_cost']; ?>" class="form-control"></td>
							     <td><input type="text" name="selling_price[]" value="<?php echo $row['selling_price']; ?>" class="form-control"></td>
							  </tr>
						       <?php
						    endforeach; ?>
                                                 </tbody>
						 </table>
						 </div> 
						 </div>
						<?php } ?>
                                                 
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success" onClick="return confirm('Are you sure')"><i class="fa fa-save"></i> Save Details</button>
								<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('batch');?>'" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
						
					</form>    
				</div> 
	  		</div>   
      	</div>
    </div>   
</div>	
					
<script type="text/javascript"> 
$(function() {
	$('#batch_date').datepicker();
	$('#expiry_date').datepicker(); 
	$('#sp_effect_date').datepicker(); 
 	
	$('#expiry_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});

    //formValidation
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'unit_uom': {
				validators: {
					notEmpty: {
						message: 'Please insert the units in UOM.'
					}
				}
			},
			'quantity': {
				validators: {
					notEmpty: {
						message: 'Please input the opening quantity'
					}
				}
			},
			'landed_cost': {
				validators: {
					notEmpty: {
						message: 'Please select the landed cost.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
}); 
</script>
   
