<?php echo $this->partial('stock/batch/partial2.phtml', array('active' => 'locationsp')); ?> <br/>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
		<div class="widget-header">
			<h5 class="widget-title lighter smaller">
				<i class="fa fa-pencil"></i>&nbsp;&nbsp;<strong><?php echo $this->title; ?></strong>&nbsp;
			</h5>
		</div><!-- end of widget-header -->
		<div class="widget-body">
			<div class="widget-main">
				<form id="#form" method="post" action="<?php echo $this->url('batch', array('action' => 'locationsp')); ?>"  enctype="multipart/form-data" >    
					<div class="row">
						<div class="col-lg-4"> 
							<div class="form-group">
							<?php $activities = $this->activityObj->getAll(); ?>
								<label for="activity" class="control-label">Activity</label>
								<select class="form-control" name="activity" id="activity" data-placeholder="Select" required>
									<option value=""></option>
									<?php foreach($activities as $activity): ?>
										<option value="<?php echo $activity['id'];?>">
											<?php echo $activity['activity'];?>
										</option>
									<?php endforeach; ?>
								</select> 
							</div>
						</div>

						<div class="col-lg-4"> 
							<div class="form-group">
								<label for="item" class="control-label">Item</label>
								<select class="form-control" name="item" id="item" data-placeholder="Select" required>
									<option value=""></option>						
								</select> 
							</div>
						</div>
						<div class="col-lg-4"> 
							<div class="form-group">
								<label for="uom" class="control-label">Batch</label>
								<select class="form-control" name="batch" id="batch" data-placeholder="Select" required>
									<option value=""></option>						
								</select>
							</div>
						</div>				
					</div>
					<div class="row">	
						<div id="locationDtl"></div>			
					</div>
				</form>
			</div> 
		</div>   
	</div>
</div> 
</div>

<script type="text/javascript">                                                          
$(function() {
	$('#adjust_date').datepicker();  	
	$('#adjust_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});	
	//alert($("#activity").val());
        $("#activity").change(function() {	
		$("#item").load('<?php echo $this->url("sam", array("action" => "getitembyactivity")); ?>/'+ $("#activity").val(), function() {
			$("#item").trigger("chosen:updated");
		});
		$("#locationDtl").html("");
		$("#batch").val("");
	});	

	$("#item").change(function() {	  
		$("#batch").load('<?php echo $this->url("batch", array("action" => "getitembatch")); ?>/'+ $("#item").val(), function() {
			$("#batch").trigger("chosen:updated");
		});	   	
	});

	$("#batch").change(function() {
		$('#locationDtl').load("<?php echo $this->url('batch', array('action' => 'checklocation')); ?>/"+ $("#batch").val(), function() {
			$("#locationDtl").trigger('chosen:updated');  
		});
	});

	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'item': {
				validators: {
					notEmpty: {
						message: 'Please select an item.'
					}
				}
			},
			'activity': {
				validators: {
					notEmpty: {
						message: 'Please select an activity.'
					}
				}
			},
			'batch': {
				validators: {
					notEmpty: {
						message: 'Please select a batch'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
}); 
</script>