<?php 
/**
*
* View Selling Price  Stock/BatchController/spupdate
*
*/
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/batch/partial.phtml', array('active' => 'spupdate'));?> <br/>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box transparent">
			<div class="widget-header">
				<div class="col-lg-12">
					<h5 class="widget-title lighter smaller">
						<i class="fa fa-calendar-o"></i> View Selling Price Effect Date of Food Grain Items
					</h5>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<form id="#form" method="post" action="<?php echo $this->url('batch', array('action' => 'spupdate')); ?>"  enctype="multipart/form-data" >    
						<div class="row">
							<div class="form-group col-lg-3">
								<label for="location" class="control-label">Location</label>
								<input type="hidden" name="location_name" id="location_name" value="<?php echo $this->locationObj->getColumn($data['location'],'location');?>" />
								<select name="location" id="location" class="form-control" data-placeholder="Select">
									<option value=""></option>
									<?php foreach($this->locationObj->get(array('l.location_type'=>array(1,2,7,8))) as $location):
										$selected_location = ($data['location']==$location['id'])?'selected':'';
									?>
										<option value="<?php echo $location['id'];?>" <?php echo $selected_location; ?>>
											<?php echo $location['location'];?>
										</option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-3">
								<label class="control-label" for="start_date">Start Date</label>
								<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-3">
								<label class="control-label" for="end_date">End Date</label>
								<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						
							<div class="col-lg-3">
								<div class="space-12"></div>
								<button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-refresh"></i> Refresh </button>
							</div>
						</div>
					</form>
					<div>
						<table class="table table-striped table-condensed table-bordered table-hover" id="dataTables">
							<thead>
								<tr>
									<th>#</th>
									<th>Item</th>
									<th>UoM</th>
									<th>SP Effect-Date</th>
									<th>Selling Price (<?php //echo $this->currency_code();?>)</th>
								</tr>
							</thead>
							<tbody>
								<?php
									$i = 1;
									$today = date('Y-m-d');
									$mv_sp_details = $this->movingitemspObj->getspEffectdate($data['start_date'], $data['end_date']);
									$locations = $this->locationObj->get($data['location']);
									foreach($locations as $location):
										foreach($mv_sp_details as $row):
											if($row['sp_effect_date'] > $today){
												$class = 'info';
											}elseif($row['sp_effect_date'] < $today){
												$class = 'success';
											}else{
												$class = 'danger';
											}
								?>	
									<tr class="<?php echo $class;?>">
										<td><?php echo $i++;?></td>
										<td><?php echo $row['code'];?></td>
										<td><?php echo $this->uomObj->getColumn($row['uom'],'code');?></td>
										<td><?php echo $row['sp_effect_date'];?></td>
										<td style="text-align:right">
											<?php 
												$sp = $this->batchdtlObj->getColumn(array('batch'=>$row['batch'],'location'=>$location['id']),'selling_price');
												echo ($sp == '')?'-':$sp;
											?>
										</td>
									</tr>
								<?php endforeach;
								endforeach;?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$(function() {
		/*** Form Validation ***/
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				'location': {
					validators: {
						notEmpty: {
							message: 'Please select location'
						}
					}
				},
				'start_date': {
					validators: {
						notEmpty: {
							message: 'Please select start date'
						}
					}
				},
				'end_date': {
					validators: {
						notEmpty: {
							message: 'Please select end date'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		/** dataTable **/
		var title_table = $('#location_name').val()+' from '+$('input#start_date').val()+' to '+$('input#end_date').val();
		$('#dataTables').DataTable({
			"paging":   true,
		});
	});
</script>
