<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
		<div class="widget-header">
			<h5 class="widget-title lighter smaller">
				<i class="fa fa-pencil"></i>&nbsp;&nbsp;<strong><?php echo $this->title; ?></strong>&nbsp;
			</h5>
		</div><!-- end of widget-header -->
		<div class="widget-body">
		<div class="widget-main">
		     <form id="#form" method="post" action="<?php echo $this->url('batch', array('action' => 'addmarginadjust', 'id' => $batch_id)); ?>"  enctype="multipart/form-data" >    
			 <div class="row">
			  <div class="col-lg-3">
				<div class="form-group">
					<label for="sp_effect_date" class="control-label">Selling Price Effect Date</label>
					<div class="date input-group" id="sp_effect_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" value="<?php echo $this->sp_effect_date;?>" name="sp_effect_date" id="sp_effect_date" type="text" placeholder="sp_effect_date" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
			 </div>  

			  <div class="col-lg-3"> 
				<div class="form-group">
					<label for="activity" class="control-label">Activity</label>
					<select class="form-control" name="activity" id="activity" data-placeholder="Select" required>						
						<?php 
						$activities = $this->activityObj->get($activityID);
						foreach($activities as $activity): ?>
							<option value="<?php echo $activity['id'];?>">
								<?php echo $activity['activity'];?>
							</option>
						<?php endforeach; ?>
					</select> 
				</div>
			 </div>

			 <div class="col-lg-3"> 
				<div class="form-group">
					<label for="item" class="control-label">Item</label>
					<select class="form-control" name="item" id="item" data-placeholder="Select" required>
						<?php 
						$itemDtls = $this->itemObj->get($itemID);
						foreach($itemDtls as $itemdtl):						           
						?>
						<option value="<?php echo $itemdtl['id'];?>">
								<?php echo $itemdtl['code'];?>
							</option>
						<?php endforeach; ?>												
					</select> 
				</div>
			</div>
			<div class="col-lg-3"> 
				<div class="form-group">
					<label for="uom" class="control-label">Batch</label>
					<select class="form-control" name="batch" id="batch" data-placeholder="Select" required>
						<?php 
						$batchDtls = $this->batchObj->get($batchID);
						foreach($batchDtls as $batchdtl): $batchUom = $batchdtl['uom'];?>
							<option value="<?php echo $batchdtl['id'];?>">
								<?php echo $batchdtl['batch'];?>
							</option>
						<?php endforeach; ?>
					</select>
				</div>
			</div>											
		    </div>
           <?php $standard_UOMs = $this->itemUomObj->get(array('item'=>$itemID, 'costing_uom'=>'1'));
				 foreach($standard_UOMs as $suomRow):
					 $standard_UOM = $suomRow['uom_code'];
					 $conversion = $suomRow['conversion'];
				 endforeach;
			?>			
		    <div class="row">
			  <div class="col-lg-4"> 
			    <h4>Batch Details</h4>
			       <table class="table table-bordered table-striped table-hover">
				   <thead>
				    <tr>  
					 <th>Elements</th>
					 <th>Details</th>					
				    </tr>
				    </thead>
				    <tbody>
				     <tr><td>Batch Date</td><td><?php echo $this->dateformat($batchdtl['batch_date']); ?></td></tr> 
					 <tr><td>Source Location</td><td><?php echo $this->locationObj->getColumn($batchdtl['location'],'location'); ?></td></tr> 
				     <tr><td>Source Location ELC</td><td><?php echo $this->currency($batchdtl['landed_cost']); ?></td></tr> 					 
				     <tr><td>Standard Costing UOM</td><td><?php  echo $standard_UOM; ?></td></tr>
				   </tbody>
				</table>
			    </div>		   	
              <div class="col-lg-2">
			   <br>&nbsp;<br/>&nbsp;<p/>&nbsp;
			          <button type="submit" class="btn btn-warning" name="button" value="1"><i class="fa fa-refresh"></i> Generate Selling Price </button>                                
				
			   </div>
		     </div>

		     <div class="row">
                     <div class="col-lg-4"> 
					 <h4>Margin Details </h4>				
					   <table class="table table-bordered table-striped table-hover">  
						   <thead>
							<tr>   
								<th>sl</th>
								<th>Location</th>
								<th>old Margin%</th>
								<th>New Margin%</th>
							</tr>
							</thead>
						 <tbody>
						  <?php  $sl =1; $v = 1;
						  for($i=0;$i < sizeof($locationID); $i++){ ?>
						   <tr>
								<td><?php echo $sl++; ?> </td>
								<td>
								  <?php echo $this->locationObj->getColumn($locationID[$i],'location'); ?>
								  <input type="hidden" name="location_type[]" class="form-control" value="<?php echo $locationID[$i]; ?>">
								</td>
								<td> <?php echo $prev_margins[$i]; ?>
									<input type="hidden" name="prev_margin[]" class="form-control" value="<?php echo $prev_margins[$i]; ?>">
								</td>
								<td> <input type="text" name="new_margin[]" class="form-control" value="<?php echo $new_margins[$i]; ?>"></td>
						  </tr>
						   <?php
						   }
						   ?>				    
					   </tbody>
					</table>
			    </div>		
                <div class="col-lg-6"> 
			       <h4>Selling Price at various Locations </h4>				
			       <?php
			         $unit_uom = $this->CostingItemsObj->getColumn(array('batch'=>$batchID, 'item'=>$itemID), 'unit_uom');
                     $uom_code = $this->uomObj->getColumn($batchUom,'code');
			         $batchDtls = $this->batchDtlsObj->get(array('batch'=>$batchID)); 
				    if(sizeof($batchDtls)>0){  ?>
                   <table class="table table-bordered table-striped table-hover">
				   <thead>
				    <tr>   
					 <th><label class="ace bolder blue">
						<input type="checkbox" id="checkAll" class="ace" />
						&nbsp;<span class="lbl"> Select All</span>
					</label>
					</th>
					<th>#</th>
					 <th>Location</th>		
					 <th>New Margin% | Value</th>
					 <th>ELC/<?php echo  $standard_UOM;  ?></th>
					 <th>New SP/<?php echo  $standard_UOM;  ?></th>					
					 <th>New SP/<?php echo $uom_code;?></th>
					 <th>Old SP/<?php echo $uom_code;?></th>
				    </tr>
				    </thead>
				     <tbody>
				 <?php $sl = 1; $j=0;
					   foreach($batchDtls as $dtl): ?> 
					      <tr>
						    <td><input type="checkbox" name="sl[]"  value="<?php echo $j++; ?>" class="form-control" > 
							<input type="hidden" name="dtl[]"  value="<?php echo $dtl['id']; ?>" ></td><td><?php echo $sl++; ?></td>
					        <td>
						    <?php  $locationDtls = $this->locationObj->get($dtl['location']); 
						     foreach($locationDtls as $locdtl);
						          echo $locdtl['location'];  
							  ?>&nbsp;&nbsp;&nbsp;&nbsp;
							   <span class="label label-info"> 
								<?php  echo $locdtl['location_type'];	?>						    
							   </span>
							  <?php
						?></td>
						<input type="hidden" name="landed_cost[]" value="<?php echo $dtl['landed_cost']; ?>">
						<input type="hidden" name="location[]" value="<?php echo $dtl['location']; ?>">
						 <?php							      
						     for($i=0;$i<sizeof($locationID);$i++){
								  if($locationID[$i] == $locdtl['id']){
								 ?><?php 
								   $margin_value = $dtl['landed_cost'] * ($new_margins[$i]/100);								 
								   if($dtl['landed_cost'] > 0 ){ 
								   $sp_unit_uom = $dtl['landed_cost'] + $margin_value; 
								   }else {  $sp_unit_uom = 0; }	 ?>
								 <td><input type="hidden" name="prev_margin[]" class="form-control" value="<?php echo $prev_margins[$i]; ?>"><input type="hidden" name="margin[]" value="<?php echo $new_margins[$i];?>"> <?php echo $new_margins[$i];?> | <?php echo number_format($margin_value,3,'.',','); ?></td>
								 <td><?php echo $dtl['landed_cost']; ?> </td>
								 <td><?php echo number_format($sp_unit_uom,2,'.',','); ?> </td>
								 <td><?php $sp_basic = $sp_unit_uom / $conversion; ?> 
								 <input type="text" name="sp[]" value="<?php echo round($sp_basic,2); ?>">
								 </td>
								 <td><?php echo $dtl['selling_price']; ?> </td>
								 <?php
							  }							 
						     }
						  ?>						 
				              </tr>	      
			            <?php endforeach; ?>
			             </tbody>
				   </table>
				     <button type="submit" class="btn btn-success" name="button" value="2"><i class="fa fa-check"></i> Save Margin Details &nbsp; </button>
			        <?php
				 }
				 else{
				 ?>
                          <div class="alert alert-info fade in">  
				       Batch Details and selling price not found.
				   </div>
				 <?php
				 }
			       ?>
			  </div>
		     </div>		   
		  </form>
		</div> 
	   </div>   
      	</div>
    </div>    
</div>	            
<script type="text/javascript">                                                          
$(function() {
	$('#sp_effect_date').datepicker();  
}); 
$("#checkAll").change(function () {
	$("input:checkbox").prop('checked', $(this).prop("checked"));
});
</script>                       
