<?php
/**
 *
 * View -- of Store/PaymentController/editpaymentAction
 *
 */
$this->headTitle($this->title);
?>
<?php 
    foreach($payments as $sup_pay):
		extract($sup_pay);
		$payment_id = $id;
		$bank_charge_amt = $bank_charge; 
		$sel_location = $location_id;
		$sel_item_group = $item_group_id;
		$sel_activity = $activity_id;
		$sel_acc_type = $acc_type;
		$sel_bankreftype = $bank_ref_type;
    endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;&nbsp;&nbsp;Edit Payment : &nbsp;<strong><?php echo $payment_no; ?> | <?php echo $supplier; ?><?php echo $activity?></strong>&nbsp;
					<?php echo $this->status($status);?>
                </h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('inpurpayment', array('action' => 'editpayment', 'id' => $sup_pay_id)); ?>"  enctype="multipart/form-data" >
						<input type="hidden" name="payment_id" id="payment_id" value="<?php echo $payment_id; ?>" />
						<div class="row">
							<div class="form-group col-lg-3">
								<label for="purchase_payment_date" class="control-label">Payment Date</label>
								<div class="date input-group" id="purchase_payment_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd">
									<input class="form-control span2" name="purchase_payment_date" id="purchase_payment_date" type="text" placeholder="Payment Date" value="<?php echo $payment_date; ?>" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i> </span>
								</div>
							</div>
							<div class="form-group col-lg-3">
								<label for="location" class="control-label">Location</label> 
								<select class="form-control" id="location" name="location" data-placeholder="Select" required>
									<option value=""></option>
									<?php foreach ($regions as $region): ?>
									<optgroup label="<?php echo $region['region'];?>">
										<?php 
											$locations = $locationObj->get(array('l.region'=>$region['id']));
											foreach ($locations as $location):
											$selected = ($location['id']==$sel_location)?'selected':'';
										?>
										<option value="<?php echo $location['id']; ?>" <?php echo $selected;?>>
											<?php echo $location['location']; ?>
										</option>
										<?php endforeach; ?>
									</optgroup>
									<?php endforeach;  ?>
								</select>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="item_group" class="control-label">Item Group</label>
									<select id="item_group" name="item_group" class="form-control" data-placeholder="Select" readonly="readonly" required>
										<option value=""></option>
										<?php foreach ($this->groupObj->getAll() as $group):
										    $slted = ($group['id'] == $sel_item_group)?"selected":"";?>
											<option value="<?php echo $group['id'];?>"<?php echo $slted;?>><?php echo $group['name']; ?></option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="cost_center" class="control-label">Cost Center</label>
									<select class="form-control" name="cost_center" id="cost_center" data-placeholder="Select" readonly="readonly" required>
										<option value=""></option>
									<?php foreach($this->activityObj->getAll() as $act):
										$selected =($act['id']==$sel_activity)?'selected':'';?>
											<option value="<?php echo $act['id'];?>" <?php echo $selected;?>>
										   		<?php echo $act['activity']; ?>
										   	</option>
										<?php endforeach; ?>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
						  	<div class="form-group col-lg-3">
								<label for="supplier" class="control-label">Supplier</label> 
								<input class = "form-control" type ="text" id ="supplier" name ="supplier" value = "<?php echo $supplier;?>"/>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
								    <label for="cashbank" class="control-label">Check Cash or Bank</label> 
								<div class="form-group radio">                                			
									<label>
										<input class="ace" type="radio" name="bank" id ="bank" value="3" checked >
										<span class="lbl"> Bank Account </span>
									</label>
									<label>
										<input class="ace" type="radio" name="cash" id = "cash" value="4" >
										<span class="lbl"> Cash Account </span>
									</label>	
								</div>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="bcaccount" class="control-label">Select Bank Or Cash Account</label>
									<select class="form-control" id="bcaccount" name="bcaccount" data-placeholder="Select" >
										<option value=""></option>
										<?php 
										if($sel_acc_type == 3):
										    $accounts = $this->bankaccountObj->getAll();
										else:
										    $accounts = $this->cashaccountObj->getAll();
										endif;
										foreach($accounts as $account):
										$selected =($account['id']==$sel_acc_type)?'selected':'';?>
											<option value="<?php echo $account['id'];?>" <?php echo $selected;?>>
										   		<?php echo $account['code']; ?>
										   	</option>
										<?php endforeach; ?>
									</select>
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group"> 
									<label for="acc_ref_type" class="control-label">Select Account Reference Type</label>
									<select class="form-control" id="acc_ref_type" name="acc_ref_type" data-placeholder="Select" >
										<option value=""></option>
										<?php foreach($this->bankreftypeObj->getAll() as $bankreftype):
										$selected =($bankreftype['id']== $sel_bankreftype)?'selected':'';?>
											<option value="<?php echo $bankreftype['id'];?>" <?php echo $selected;?>>
										   		<?php echo $bankreftype['bank_ref_type']; ?>
										   	</option>
										<?php endforeach; ?>
									</select>
								</div>
							</div>
						</div>
						<div class ="row">
							<div class="col-lg-3">
								<div class="form-group">
									<label for="cheque" class="control-label">Cheque No.</label>
									<input class = "form-control" type ="text" id ="cheque_no" name ="cheque_no" value = "<?php echo $cheque_no;?>"/>
								</div>
							</div>	
						    <div class="form-group col-lg-3">
								<label for="bank_charge" class="control-label">Bank Charge(<?php echo $this->currency_code();?>)</label>							
							    <input type="text" class="form-control" name="bank_charge" id="bank_charge" value="" placeholder="Bank Charge"/>
							</div>
							<div class="form-group col-lg-3">
								<div class="space-10"></div>
								<label>
									<?php $check = ($bank_charge > 0)?'checked':'';?>
									<input name="check_bank_charge" id="check_bank_charge" type="checkbox" value="1" class="ace" <?php echo $check;?> />
									<span class="lbl red"> *Check if Bank Charge is required</span>
								</label>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<h5>Payment Details</h5>
								<div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Invoice No.</th>
												<th>Payable Amount(<?php echo $this->currency_code();?>)</th>
											</tr>
										</thead>
										<tbody>
										    <?php 
											foreach($this->paymentdetailsObj->get(array('payment'=>$payment_id)) as $paymentdtl):?>
											<tr>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="invoice_no[]" id="invoice_no" value="<?php echo $paymentdtl['invoice_no']?>" readonly />
													    <input type="hidden" name="details_id[]" id="details_id" value="<?php echo $paymentdtl['id'];?>" />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="payable_amount[]" id="payable_amount" value="<?php echo $paymentdtl['payment_amt'];?>" readonly />
													</div>
												</td>
											</tr>
											<?php endforeach;?>
										</tbody>
									</table>
									</table>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-9"></div>
							<div class="form-group col-lg-3">
								<label for="payment_amount" class="control-label">Payment Amount(<?php echo $this->currency_code();?>)</label> 
								<input type="text" class="form-control" name="payment_amount" id="payment_amount" value="<?php echo $payment_amount; ?>" placeholder="Payment Amount" readonly />
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-9">
								<button type="submit" class="btn btn-success">
									<i class="fa fa-check"></i> Save
								</button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button>
							</div>
						</div>
					</form>
				</div><!-- widget-main -->
			</div><!-- widget-body -->
		</div><!-- widget-box -->
	</div><!-- col-lg-12 -->
</div><!-- row -->

<script type="text/javascript">
$(function(){
	//* when back account is already checked, get bank account and account reference type *//
	$('input[name=bank]:radio:checked').ready(function(){
		$.post(
			"<?php echo $this->url('payment', array('action' => 'getaccount'));?>",
			{
				bank_type: $('input[name=bank]:radio:checked').val(),
			},
			function(data){
				//console.log(data);
				$('select#bcaccount').html(data.acc);
				$('select#acc_ref_type').html(data.br);
				$('select#bcaccount').trigger('chosen:updated');
				$('select#acc_ref_type').trigger('chosen:updated');
			},
			'json'
		);
	});
	//* On changing the account to cash, get cash account and disable account reference type*//
	$('#cash').on('change',function(){
		if ($("input[name='bank']").is(':checked')) {
			$('input[name=bank]').removeAttr('checked');
		$.post(
			"<?php echo $this->url('payment', array('action' => 'getaccount'));?>",
			{
				bank_type: $(this).val(),
			},
			function(data){
				//console.log(data);
				$('select#acc_ref_type').html("");
				$('select#acc_ref_type').attr("readonly", true);
				$("#cheque").attr("disabled", "disabled");
				$('select#acc_ref_type').trigger('chosen:updated');
				$('cheque').trigger('chosen:updated');
				$('select#bcaccount').html(data.acc);
				$('select#bcaccount').trigger('chosen:updated');
			},
			'json'
			);
		}
	});
   //* On changing the account to bank, get bank account and disable account reference type*//
	$('#bank').on('change',function(){
		if ($("input[name='cash']").is(':checked')) {
			$('input[name=cash]').removeAttr('checked');
		$.post(
			"<?php echo $this->url('payment', array('action' => 'getaccount'));?>",
			{
				bank_type: $(this).val(),
			},
			function(data){
				//console.log(data);
				$('select#acc_ref_type').html(data.acc);
				$('select#acc_ref_type').html(data.br);
				$('select#acc_ref_type').attr("readonly", false);
				$('select#acc_ref_type').trigger('chosen:updated');
				$('select#bcaccount').html(data.acc);
				$('select#bcaccount').trigger('chosen:updated');
			},
			'json'
			);
		}
	});
	//** To disable the check field when cheque is selected *//
	$('#acc_ref_type').on('change',function(){
		if($(this).val() == 1){$("#cheque").removeAttr("disabled");
		$("#cheque").focus();}else{$("#cheque").attr("disabled", "disabled");}
		$('form').formValidation('revalidateField','cheque');
	});	
	
	$('#payment_date').datepicker();
	$('#payment_date').on('changeDate',function(){
		$('form').formValidation('revalidateField','payment_date');
	});	
});
/******** formValidation *************/
const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			payment_date: {
				validators: {
					notEmpty: {
						message: 'Please select payment date.'
					}
				}
			},
			location: {
				validators: {
					notEmpty: {
						message: 'Please select location.'
					}
				}
			},
			activity: {
				validators: {
					notEmpty: {
						message: 'Please select activity.'
					}
				}
			},
			payment_type: {
				validators: {
					notEmpty: {
						message: 'Please select payment type.'
					}
				}
			},   
			party: {
				validators: {
					notEmpty: {
						message: 'Please select supplier.'
					}
				}
			},  
			invoice[]: {
				validators: {
					notEmpty: {
						message: 'Please select invoice.'
					}
				}
			}, 
			invoice_amount[]: {
				validators: {
					notEmpty: {
						message: 'Please provide invoice no.'
					}
				}
			}, 
			payable_amount[]: {
				validators: {
					notEmpty: {
						message: 'Please provide payable amount.'
					}
				}
			},
			net_pay_amount: {
				validators: {
					notEmpty: {
						message: 'Please provide net payable amount.'
					}
				}
			},  
			payment_amount: {
				validators: {
					notEmpty: {
						message: 'Please provide payment amount.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
</script>
