<?php
/**
 * 
 * View -- of Realestate/ContractorawardController/indexAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php //echo $this->partial('realestate/contractoraward/partial.phtml',array('active' => 'contawarding'));?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Project</th>
					<th>Name of Firm</th>
					<th>CDB No.</th>
					<th>Award Date</th>
					<th>Project Cost</th>
					<th>Start Date</th>
					<th>End Date</th>
					<th class="no-sort no-printpdf">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php $i=1;					
				  foreach ($contractoraward as $rows):					  						
				?>
					<tr data-href="<?php echo $this->button(4, $rows['id']); ?>">
						<td><?php echo $i++; ?> </td>
						<td><strong><?php echo $rows['project']; ?></strong></td>	
						<td><?php echo $rows['contractor_name']; ?></td>
						<td><?php echo $rows['cdb_no']; ?></td>	
						<td><?php echo $rows['award_date']; ?></td>	
						<td><?php echo $rows['actual_amt']; ?></td>	
						<td><?php echo $rows['start_date']; ?></td>	
						<td><?php echo $rows['end_date']; ?></td>	
						<td class="action">
							<!--a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" 
									href="<?php //echo $this->url('acl', array('action' => 'activitylog', 'id' => "31-".$rows['id'])); ?>" title="View Activity Logs">
									<i class="ace-icon fa fa-plus smaller-120" ></i>
							</a-->
							<a class="btn btn-xs btn-primary" data-toggle="modal" data-target="#modal" 
									href="<?php echo $this->url('contaward', array('action' => 'advance', 'id' => $rows['id'])); ?>" title="Advance">
									<i class="ace-icon fa fa-plus smaller-120" > Advance </i>
							</a>
							<a class="btn btn-xs btn-success" data-toggle="#" data-target="#" 
									href="<?php echo $this->url('contaward', array('action' => 'runningamt', 'id' => $rows['id'])); ?>" title="Running Bill">
									<i class="ace-icon fa fa-plus smaller-120" > Running Bill </i>
							</a>
						</td>
						<?php //echo $this->button(1, $rows['id']); ?>
					
					</tr>
				<?php 
				$i++;
				endforeach;  
				?>
			</tbody>
		</table>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});

	$('document').ready(function(){
		$('#dataTables').DataTable();
	});
</script>


