<?php // view partial.phtml 
  $contawarding = ($this->active == "contawarding")?"active":"";
  $rents = ($this->active == "rents")?"active":"";
?>
<br/>
<ul class="nav nav-tabs padding-18" id="myTab" >
	<li class="<?php echo $contawarding; ?>">
		<a href="<?php echo $this->url('contaward', array('action' => 'index')); ?>">
			<i class="blue ace-icon fa fa-user bigger-120"> </i>
			<span class="hidden-xs" >Contract Award</span>
		</a>
	</li>
	<li class="<?php echo $rents; ?>">
		<a href="<?php echo $this->url('contaward', array('action' => '')); ?>">
			<i class="blue ace-icon fa fa-users bigger-120"> </i>
			<span class="hidden-xs" >Monthly Rent View</span>
		</a>
	</li>
</ul>

