<?php
/**
 * 
 * View -- of Realestate/ContractorawardController/addcontawardAction
 * 
 */
	$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('contaward', array('action' => 'runningamt', 'id' => $id)); ?>"  enctype="multipart/form-data" >
	<div class="row">
		<div class="col-lg-12"> 
			<div class="widget-box">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Running Bill
				</div>
				<div class="widget-body">
					<div class="widget-main padding-24"> 
						<div class="row">
							<div class="form-group col-lg-4">
								<label for="bill" class="control-label"> Bill Type </label>
								<select class="form-control" name="bill" id="bill" dataplaceholder="Select" >
									<option value=""></option>
									<option value="1" <?php echo ($final_bill == 'Final Bill')?'disabled':'';?>>Running Bill</option>
									<option value="2" <?php echo ($final_bill == 'Final Bill')?'disabled':'';?>>Final Bill</option>
								</select>
							</div>
							<div class="form-group col-lg-4">
								<label for="bill_date" class="control-label">Bill Date</label>
								<div class="date input-group" id="bill_date" data-date="today" data-date-format="yyyy-mm-dd">
									<input class="form-control span2" name="bill_date" id="bill_date" type="text" placeholder="Bill Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-4">
								<label for="cdb_no" class="control-label"> Bill No. </label>
								<input class="form-control" id="cdb_no" name="cdb_no" placeholder="CDB No." required />
								<input type="hidden" class="form-control" id="retention_percent" value="<?php echo $retention_percent;?>" required />
								<input type="hidden" class="form-control" id="tds_percent" value="<?php echo $tds_percent;?>" required />
							</div>
						</div>
						
						<div class="row">
							<div class="form-group col-lg-4">
								<label for="running_amt" class="control-label">Running Amount</label>
								<input class="form-control" name="running_amt" id="running_amt" placeholder="Running Amount" required />
							</div>
							<div class="form-group col-lg-4">
								<label for="retaining_amt" class="control-label">Retention Money</label>
								<input class="form-control" id="retaining_amt" name="retaining_amt" placeholder="<?php echo $retention_percent;?> % of Running Amount" readonly />
							</div>
							<div class="form-group col-lg-4">
								<label for="tds" class="control-label">TDS</label>
								<input class="form-control" id="tds" name="tds" placeholder="<?php echo $tds_percent;?> % of Running Amount" readonly >
							</div>
						</div>
						<div class="row">
							<div class="form-group col-lg-4">
								<label for="adjustment" class="control-label"> Advance Adjustment </label>
								<input class="form-control" name="adjustment" id="adjustment" placeholder="Adjustment Amount" value="0.00" />
							</div>
							<div class="form-group col-lg-4">
								<label for="adj_against" class="control-label"> Adjustment Against </label>
								<select class="form-control" name="adj_against" id="adj_against" dataplaceholder="Select" >
									<option value=""></option>
									<option value="1">Mobilization Advance</option>
									<option value="2">Secured Advance</option>
									<option value="3">Any Other Advance</option>
								</select>
							</div>
							<div class="form-group col-lg-4">
								<label for="actual_amt" class="control-label">Net Payable Amount</label>
								<input type="text" class="form-control" name="actual_amt" id="actual_amt" placeholder="" readonly />
							</div>
						</div>
						<div class="space-6"></div>
						<div class="row">
							<div class="col-lg-12">
								<div>
									<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
									<button type="button" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>  
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript"> 	
    $(function() {
		var retention_percent = $('input[id=retention_percent]').val();
		var tds_percent = $('input[id=tds_percent]').val();
		
		$('#running_amt').on('change', function(){
			var running_amt = $(this).val();
			//var adjust = $('input[name=adjustment]').val();
			//var running_amt = running_amount - adjust;
			
			//retaining amount
			var retain_amt = running_amt * (retention_percent/100); //10% = 0.1
			$('#retaining_amt').val(parseFloat(retain_amt).toFixed(2));
			
			//tds amount
			var tds_amt = running_amt * (tds_percent/100); //2% = 0.02
			$('#tds').val(parseFloat(tds_amt).toFixed(2));
			
			var adjust = $('input[name=adjustment]').val();
			
			var payable_amt = running_amt - retain_amt - tds_amt - adjust;
			//actual amount to pay
			$('#actual_amt').val(parseFloat(payable_amt).toFixed(2));
		});
		
		var adjust = $('input[name=adjustment]').val();
		if(adjust == 0){
			$("#adj_against").prop("disabled", true);
		}else{
			$("#adj_against").prop("disabled", false);
		}
		
		$('#adjustment').on('change', function(){
			if(adjust == 0){
				$("#adj_against").prop("disabled", true);
			}else{
				$("#adj_against").prop("disabled", false);
			}
			var adjust = $(this).val();
			//running amt - 12 % of running amt
			var running_amt = $('input[name=running_amt]').val();
			//var running_amt = running_amount - adjust;
			
			//retaining amount
			var retain_amt = running_amt * (retention_percent/100); //10% = 0.1
			//$('#retaining_amt').val(parseFloat(retain_amt).toFixed(2));
			
			//tds amount
			var tds_amt = running_amt * (tds_percent/100); //2% = 0.02
			//$('#tds').val(parseFloat(tds_amt).toFixed(2));
			
			var payable_amt = running_amt - retain_amt - tds_amt - adjust;
			$('#actual_amt').val(parseFloat(payable_amt).toFixed(2));
		});
		
	});
	
	$('form select').chosen();
	$('#bill_date').datepicker();
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				bill: {
					validators: {
						notEmpty: {
							message: 'Please select Bill Type.'
						}
					}
				},
				cdb_no: {
					validators: {
						notEmpty: {
							message: 'Please provide CDB No.'
						}
					}
				},
				running_amt: {
					validators: {
						notEmpty: {
							message: 'Please provide Running Amount.'
						},
						numeric: {
							message: 'Enter Numeric Values Only'
						}
					}
				},
				adjustment: {
					validators: {
						notEmpty: {
							message: 'Please provide Adjustment Amount.'
						},
						numeric: {
							message: 'Enter Amount in Figures'
						}
					}
				},
				adj_against: {
					validators: {
						notEmpty: {
							message: 'Please select Adjustment Against.'
						},
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});

		$('#bill_date').on('changeDate',function(){
			$('form').formValidation('revalidateField','bill_date');
		});
	});
</script>

