<?php
/**
 * 
 * View -- of Sales/SchemeController/editscbatchAction
 * 
 */
?>
<?php 
	foreach($schemebatches as $schemebatch):
		extract($schemebatch);
		$sc_id = $id;
		$location_id = $location;
		$batch_id = $batch;
	endforeach;?>
<form id="#form" method="post" action="<?php echo $this->url('schemes', array('action' => 'editscbatch')); ?>"  enctype="multipart/form-data" >                 
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="fa fa-asterisk"></i> Edit Mapped Batch</h4>
    </div><!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="form-group">
					<input type="hidden" name="sc_id" id="sc_id" value="<?php echo $sc_id; ?>">
					<input type="hidden" name="scheme_id" id="scheme_id" value="<?php echo $scheme_id; ?>">
					<label  for="item" class="control-label">Item</label>
					<select class="form-control" style="width:100%;" data-placeholder="Select" name="item" id="item" required >
							<option value="<?php echo $item_id;?>">
								<?php echo $itemObj->getColumn($item_id, 'code'); ?>
							</option>
					</select>
				</div>
				<?php 
					$item_valuation = $this->itemObj->getColumn($item_id,'valuation');
				?>
				<input type="hidden" name="item_valuation" id="item_valuation" value="<?php echo $item_valuation;?>" />
				<?php if($item_valuation == 0){ ?>
				<div class="form-group">
					<label  for="batches" class="control-label">Batch</label>
					<select class="form-control" style="width:100%;" data-placeholder="Select" name="batches" id="batches" required >
						<option value="-1">All</option>
						<?php 
							$batches = $this->batchObj->get(array('b.item'=>$item_id));
							foreach($batches as $batch):
								$selected = ($batch['id'] == $batch_id)?'selected':'';?>
							<option value="<?php echo $batch['id'];?>" <?php echo $selected;?>>
								<?php echo $batch['batch'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<?php } ?>
				<div class="form-group">
					<label  for="location" class="control-label">Location</label>
					<select class="form-control" style="width:100%;" data-placeholder="Select" name="location" id="location" required >
						<option value="-1">All</option>
						<?php foreach ($locationObj->getAll() as $locations):
						$selected = ($locations['id'] == $location_id)?'selected':'';?>
							<option value="<?php echo $locations['id'];?>"<?php echo $selected;?>>
								<?php echo $locations['location']; ?>
							</option>
						<?php endforeach;?>	
					</select>
				</div>
			</div>
		</div>                    
    </div><!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script type="text/javascript">
$('select').chosen({ allow_single_deselect: true });		
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			batch: {
				validators: {
					notEmpty: {
						message: 'Please Select batch.'
					}
				}
			},
			location: {
				validators: {
					notEmpty: {
						message: 'Please Select location.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
