<?php
/**
 * View -- of Sales/SchemeController/addsdetailsAction
 */
  $this->headTitle($this->title);
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i>&nbsp;&nbsp;New Scheme Details
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form method="post" action="<?php echo $this->url('schemes', array('action' => 'addsdetails')); ?>"  enctype="multipart/form-data" >    <div class="row">
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="scheme_type" class="control-label">Scheme Type</label>
									<select id="scheme_type" name="scheme_type" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
										<?php foreach ($this->schemetypes->getAll() as $schemetype):?>
											<option value="<?php echo $schemetype['id'];?>">
												<?php echo $schemetype['scheme_type']; ?>
											</option>
										<?php endforeach; ?>
									</select> 
								</div>	
							</div>		
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="supplier" class="control-label">Supplier</label>
									<select id="supplier" name="supplier" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
										<?php foreach ($this->suppliers as $supplier): ?>
											<option value="<?php echo $supplier['id'];?>">
												<?php echo $supplier['name']; ?>
											</option>
										<?php endforeach; ?>							
									</select> 
								</div>
							</div>							
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="activity" class="control-label">Activity</label>
									<select id="activity" name="activity" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($this->activities as $activity):?>
										   <option value="<?php echo $activity['id'];?>"><?php echo $activity['activity']; ?></option>
										<?php endforeach; ?>						
									</select> 
								</div>
							</div>
						</div>		
						<div class="row">	
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="item" class="control-label">Item</label>
									<select id="item" name="item" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
									</select> 
								</div>
							</div>
							<div class="col-lg-4">
								<div class="form-group">
									<label for="head" class="control-label">Head</label>
									<select id="head" name="head" class="form-control" data-placeholder="Select" required>
										<option value=""> </option>
										<?php foreach ($this->headObj->getAll() as $head):?>
											<option value="<?php echo $head['id'];?>">
												<?php echo $head['code'];?>
											</option>
										<?php endforeach;?>
									</select>		
								</div>	
							</div>		
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="sub_head" class="control-label">Sub Head</label>
									<select id="sub_head" name="sub_head" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
									</select> 
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="scheme_date" class="control-label">Scheme Date</label>
									<div class="date input-group" id="scheme_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="scheme_date" id="scheme_date" type="text" placeholder="Scheme Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>		
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="from_date" class="control-label">Start Date</label>
									<div class="date input-group" id="from_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="from_date" id="from_date" type="text" placeholder="From Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="to_date" class="control-label">End Date</label>
									<div class="date input-group" id="to_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="to_date" id="to_date" type="text" placeholder="To Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
						</div>
						<div class="row">		
							<div class="col-lg-4">
								<div class="form-group">
									<label for="claim" class="control-label"> Claim:</label>
									<?php 
									$checked1 = ($data['claim'] == "1")?"checked":"";
									$checked2 = ($data['claim'] == "0")?"checked":"";
									?>
									<div class="radio">
										<label> 
											<input class="ace" type="radio" name="claim" id="claim" value="1" <?php echo $checked1;?> checked />
											<span class="lbl"> Yes </span>
										</label> 
										<label> 
											<input class="ace" type="radio" name="claim" id="claim" value="0" <?php echo $checked2;?> /> 
											<span class="lbl"> No </span>
										</label>
									</div>
								</div>	
							</div>
						</div>
						<div class="row">
						   <div class="col-lg-12"> 
								<h5>Scheme Details</h5>
								<div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>UOM</th>
												<th class="qty_slab_sc">Qty Slab 1</th>
												<th class="qty_slab_sc">Qty Slab 2</th>
												<th class="unit_qty_sc">Unit Qty</th>
												<th class="free_item_sc">Free Item</th>
												<th class="free_item_sc">Free Item UOM</th>
												<th>Discount/Qty</th>
												<th>&nbsp;</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td  class="col-lg-3">
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control"  data-placeholder="Select" required>
															<option value=""></option>
														</select>
													</div>
												</td> 
												<td class="qty_slab_sc">
													<div class="form-group">
														<input type="text" class="form-control" name="qty_slab1[]" id="qty_slab1"  required>
													</div>
												</td>
												<td class="qty_slab_sc">
													<div class="form-group">
														<select id="qty_slab2" name="qty_slab2[]" class="form-control" data-placeholder="Select" required>
															<option value="-1">Above</option>
														<?php for ($i = 1; $i <= 5000; $i++) : ?>
															<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
														<?php endfor; ?>
														</select>
													</div>
												</td>
												<td class="unit_qty_sc">
													<div class="form-group">
														<input type="text" class="form-control" name="unit_quantity[]" id="unit_quantity"  required>
													</div>
												</td>
												<td class="col-lg-4 free_item_sc">
													<div class="form-group">
														<select id="free_item" name="free_item[]" class="form-control" data-placeholder="Select" required>
															<option value=""></option>
														</select>
													</div>
												</td>
												<td class="col-lg-3 free_item_sc">
													<div class="form-group">
														<select id="free_item_uom" name="free_item_uom[]" class="form-control" data-placeholder="Select" required>
															<option value=""></option>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="discount_qty[]" id="discount_qty"  required>
													</div>
												</td>	
												<td></td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>	
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<a class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </a>  					
							</div>
						</div>
					</form>	
				</div><!-- widget widget-main -->
			</div>  <!-- widget widget-body -->   
		</div> <!-- widget widget-box --> 
	</div><!-- col-lg-12 -->
</div><!-- row -->

<script type="text/javascript">
    $(function() {
		$('#scheme_date').datepicker();
	  	$('#from_date').datepicker();
	  	$('#to_date').datepicker();
		$('#trdetails_table').schemej({
			getSubhead:"<?php echo $this->url('ajresponse', array('action'=>'getsubhead'));?>",
			getItem: "<?php echo $this->url("schemes", array("action" => "getitemactivity")); ?>",
			getItemUom: "<?php echo $this->url("schemes", array("action" => "getitemuom")); ?>",
		});
	    //formValidation
		$('form').formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid',
				fields: {
					'scheme_date': {
					 	validators: {
							notEmpty: {
								message: 'Please select scheme date'
						  	}
					  	}
				  	},
					'activity': {
						validators: {
							notEmpty: {
								message: 'Please select activity'
							}
						}
					},
					'supplier': {
						validators: {
							notEmpty: {
								message: 'Please select supplier'
							}
						}
					},
					'head': {
						validators: {
							notEmpty: {
								message: 'Please select head'
							}
						}
					},
					'sub_head': {
						validators: {
							notEmpty: {
								message: 'Please select sub head'
							}
						}
					},
					'item': {
						validators: {
							notEmpty: {
								message: 'Please select item'
							}
						}
					}, 
					'scheme_type': {
						validators: {
							notEmpty: {
								message: 'Please select scheme type'
							}
						}
					},    
					'from_date': {
						validators: {
							notEmpty: {
								message: 'Please select start date'
							}
						}
					},
					'to_date': {
						validators: {
							notEmpty: {
								message: 'Please select end date'
							}
						}
					},
					'uom[]': {
						validators: {
							notEmpty: {
								message: 'Please select uom'
							}
						}
					},
					'free_item[]': {
						validators: {
							notEmpty: {
								message: 'Please select free item'
							}
						}
					},
					'free_item_uom[]': {
						validators: {
							notEmpty: {
								message: 'Please select free item uom'
							}
						}
					},
					'discount_qty[]': {
						validators: {
							notEmpty: {
								message: 'Please enter discount quantity'
							}
						}
					},
				}
				}).on('success.field.fv', function(e, data) {
				  if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
						data.fv.disableSubmitButtons(true);
			      }
		});
	  
		$('#scheme_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});

		$('#from_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});

		$('#to_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
	});  
</script>
