<?php
/**
 * 
 * View -- of Stock/MasterController/adduomtypeAction
 * 
 */
?>
<?php foreach($dispatch_dtls as $dispatch_dtl);
foreach($this->dispatchObj->get(array('id'=>$dispatch_dtl['dispatch'])) as $row);?>
<form id="#form" method="post" action="<?php echo $this->url('dispatch', array('action' => 'editdispatchdtls','id'=> $dispatch_dtl['id'])); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i>Dispatch Details</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
	<input type="hidden" name="dispatch_id" value=<?php echo $row['id']?>>
	<input type="hidden" id="from_location" value=<?php echo $row['from_location']?>>
	<input type="hidden" id="to_location" value=<?php echo $row['to_location']?>>
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="item" class="control-label">Item</label>
					<select class="form-control ace" name="item" id="item" data-placeholder="Select" required>
						<option value=""></option>
						 <?php foreach($this->itemObj->getAll() as $items):
							$selected = ($dispatch_dtl['item'] == $items['id'])?"selected":"";?>
							 <option value="<?php echo $items['id'];?>"<?php echo $selected;?>><?php echo $items['name'];?></option>
						<?php endforeach;?>		
					</select>		
				</div>
				<div class="form-group">
					<label for="uom" class="control-label">Uom</label>
					<select class="form-control ace" name="uom" id="uom" data-placeholder="Select" required>
						<option value=""></option>
						 <?php foreach($uom as $uoms):
							$selected = ($dispatch_dtl['uom'] == $uoms['id'])?"selected":"";?>
							 <option value="<?php echo $uoms['id'];?>"<?php echo $selected;?>><?php echo $uoms['code'];?></option>
						<?php endforeach;?>	
					</select>	
				</div>
				<div class="form-group">
					<label for="from_balance" class="control-label">Source Qty</label>
					<input type="text" class="form-control" name="from_balance" id="from_balance"  placeholder="Stock Quantity"/> 
				</div>
				<div class="form-group">
					<label for="to_balance" class="control-label">Destination Qty</label>
					<input type="text" class="form-control" name="to_balance" id="to_balance"  placeholder="Destination Qty"/> 
				</div>
				<div class="form-group">
					<label for="quantity" class="control-label">Dispatched Qty</label>
					<input type="text" class="form-control" name="quantity" id="quantity" value="<?php echo $dispatch_dtl['quantity'];?>"  placeholder="Quantity"/> 
				</div>
				<div class="form-group">
					<label for="remarks" class="control-label">Remarks</label>
					<input type="text" class="form-control" name="remarks" id="remarks"  value="<?php echo $dispatch_dtl['remarks'];?>" placeholder="Remarks"/> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	$("select#item").change(function() {
		$.post(
			"<?php echo $this->url('sam', array('action' => 'getuom'));?>",
			{
				itemId: $(this).val(),
			},
			function(data){
				//console.log(data);	
				$('select#uom').html(data.uom);
				$('select#uom').trigger('chosen:updated');
				},
			'json'
		);	
	});
	$("#item,#from_location,#to_location").change(function() {
		$.post(
			"<?php echo $this->url('dispatch', array('action' => 'getquantity'));?>",
			{
				itemId: $('#item').val(),
				from_loc: $('#from_location').val(),
				to_loc: $('#to_location').val(),
			},
			function(data){
				//console.log(data);	
				$('#from_balance').val(data.from_balance);
				$('#to_balance').val(data.to_balance);
			},
			'json'
		);	
	});
	$('#from_location').trigger('change');
	$('#to_location').trigger('change');
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			item: {
				validators: {
					notEmpty: {
						message: 'Please provide item.'
					}
				}
			},
			uom: {
				validators: {
					notEmpty: {
						message: 'Please provide UOM'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>