
<?php
/**
 * 
 * View -- of Accounts/ChartaccountController/addclassAction
 * 
 */
//$this->headTitle($this->title);
?>
<form  id="#form" method="post" action="<?php echo $this->url('mastera', array('action' => 'addassettype')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Asset Type</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
        <div class="panel panel-default">                       
            <div class="panel-body"> 
                <div class="row">
					<div class="col-lg-6"> 
					    <div class="form-group">
							<label for="name" class="control-label">Name</label>
							<input class="form-control" name="name" id="name" size="30" placeholder="Name" required> 
						</div>  
						<div class="form-group">
							<label for="code" class="control-label">Code</label>
							<input class="form-control" name="code" id="code" size="30" placeholder="Code" required> 
						</div>
					</div>  
					<div class="col-lg-6"> 
						<div class="form-group">
							<label for="classid" class="control-label">Class</label>
							<select id="classid" name="classid" class="form-control" data-placeholder="Select" required>
								<option value=""></option>
								<?php 
								foreach ($class as $class):
								?>
									<option value="<?php echo $class['id'];?>">
									<?php echo $class['name']; ?>
									</option>
								<?php 
								endforeach;
								?>
							</select>
						</div>       
						<div class="form-group">
							<label for="subhead" class="control-label">Subhead</label>
							<select class="form-control chosen-widget" id="subhead" name="subhead" data-placeholder="Select" required >
								<option value=""></option>
							</select>
						</div>						
					</div> 
					<div class="form-group col-lg-6">
						<label for="manual" class="control-label">Manually Depreciate</label>
						<div class="radio">
							<label>  
								<input class="ace" type="radio" name="manual" id="manual"  value="1"/>
								<span class="lbl"> Yes </span>
							</label> 
							<label>  
								<input class="ace" type="radio" name="manual" id="manual" value="0"/>
								<span class="lbl"> No </span>
							</label> 
						</div>	
					</div>
					<div class="form-group col-lg-6">
						<label for="depreciation" class="control-label">Depreciation</label>
						<select class="form-control chosen-widget" id="depreciation" name="depreciation" data-placeholder="Select" required >
							<option value=""></option>
							<?php foreach($depreSh as $dep):?>
								<option value="<?php echo $dep['id'];?>"><?php echo $dep['name'];?>
							<?php endforeach;?>
						</select>
					</div>				
				</div> 
            </div>
        </div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal"><i class="fa fa-times"></i> Cancel </button>
    </div>  
</form>
<script>
$(function(){
	$('#classid').on('change',function(){
	//	alert($('#class_id').val());
		$.post(
			"<?php echo $this->url('mastera', array('action' => 'getsubhead')); ?>",
			{
				class_id: $(this).val(),
				
			},
			function(data){
				console.log(data);	
				$('#subhead').html(data.shead);	
				$("#subhead").trigger("chosen:updated");			
			},
			'json'
		);
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			code: {
				validators: {
					notEmpty: {
						message: 'Please select Code.'
					}
				}
			},
			name: {
				validators: {
					notEmpty: {
						message: 'Please provide  Name.'
					}
				}
			},
			
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>