<?php
/**
 * 
 * View -- of Hr/EmployeeController/indexAction
 * 
 */
    $this->headTitle($this->title);
    $minYear='';
    $minYear = date('Y', strtotime($minYear));
?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
			 <form id="#form" method="post" action="<?php echo $this->url('ima',array('action' => 'expense')); ?>"  enctype="multipart/form-data" >
                 <div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
							<?php 
								for($year=date('Y');$year>=$minYear;$year--):
									$selected = ($year == $data['year'])?"selected":"";
							?>
								<option value="<?php echo $year;?>" <?php echo $selected;?> >
									<?php echo $year;?> 
								</option>
							<?php endfor; ?>
						</select>
					</div>
					<div class="form-group col-lg-3">
						<label class="control-label" for="month">Month</label>
						<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
							<?php $select_month = ($data['month'] == '-1')?"selected":"";?>
							<option value="-1" <?php echo $select_month;?>>All</option>
							<?php for($month=1; $month<=12; $month++):?>
								<?php $selected = ($month == $data['month'])?'selected':'';?>
								<option value="<?php echo $month;?>" <?php echo $selected; ?>>
									<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
								</option> 
							<?php endfor;?>
						</select>
					</div>
					<div class="col-lg-2">
						<div class="row">
							<div class="form-group col-lg-8">
							<label class="control-label" for="date">Date</label>
							<select class="form-control" id="date" name="date" data-placeholder="Select" onchange='this.form.submit()'>
								<?php $select_date = ($data['date'] == '-1')?'selected':'';?>
								<option value="-1" <?php echo $select_date;?>>All</option>
								<?php
									for($i=1;$i<=$this->maxdate;$i++):
										$selected = ($i == $data['date'])?"selected":"";
								?>
									<option value="<?php echo $i;?>"<?php echo $selected;?>>
										<?php echo $i;?>
									</option>
								<?php endfor;?>
							</select>
							</div>
						</div>
					</div>
			    </form> 
			</div>
		</div>
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
    <div>
        <table class="table table-striped table-hover table-condensed" style="width:100%;" id="dataTables">
            <thead>
                <tr>
                  <th>#</th>
					<th>Voucher</th>
					<th>Voucher Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 1; foreach ($transTable as $row):?>
                   <?php if($role==100 ||$role==99):
					if($row['voucher_id']==21):?>
						<tr data-href="<?php echo $this->button(4,$row['id']); ?>">
							<td><?php echo $i++; ?> </td>
							<td>
								<b><?php echo $row['voucher_no'];?>&nbsp;</b> 
								<span style="color:#666;font-size:95%;"><?php echo $row['voucher_date'];?></span>
								<span class="label label-info"><?php echo $row['voucher_type'];?> voucher</span>
								<?php echo $this->status($row['status']);?>
							</td>
							<td> <?php echo $row['voucher_amount'];?></td>
						</tr>
				    <?php 
				    endif;
				 elseif($user==$row['author']):
					if($row['voucher_id']==21):?>
						<tr data-href="<?php echo $this->button(4,$row['id']); ?>">
							<td><?php echo $i++; ?> </td>
							<td>
								<b><?php echo $row['voucher_no'];?>&nbsp;</b> 
								<span style="color:#666;font-size:95%;"><?php echo $row['voucher_date'];?></span>
								<span class="label label-info"><?php echo $row['voucher_type'];?> voucher</span>
								<?php echo $this->status($row['status']);?>
							</td>
							<td>
								<?php echo $row['voucher_amount'];?>
							</td>
						</tr>
				    <?php 
				    endif;
				endif;
				endforeach;?>
            </tbody>
        </table>
    </div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>

