<?php
/**
 * 
 * View -- of Store/MsaterController/subgroupAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('store/master/partial.phtml', array('active' => 'subgroup')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Name</th>
					<th>Code</th>
					<th>Item Group</th>
					<th>Prefix</th>
					<th class="no-sort">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->subgroups as $row):
				?>
						<tr>
							<td><?php echo $i++; ?> </td> 
							<td><b><?php echo $row['name']; ?></b></td> 
							<td><?php echo $row['code']; ?></td>                               
							<td><?php echo $this->groupObj->getColumn($row['item_group'],'name'); ?></td>    
							<td><?php echo $row['prefix']; ?></td>         								
							<td>
								<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('inmaster', array('action'=>'editsubgroup', 'id' => $row['id']));?>" data-target="#modal">
									<i class="ace-icon fa fa-pencil bigger-120"></i>
								</a>                                                                    
							</td>
						</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({"paging":   true,});
});
</script>
