<?php
/**
 * 
 * View -- of Realestate/GodownsizeController/addestatedtlsAction
 * 
 */
	$this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('capacity', array('action' => 'addestatedtls')); ?>"  enctype="multipart/form-data" >
	<div class="row">
		<div class="col-lg-12"> 
			<div class="widget-box">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Real Estate Storage Details
				</div>
				<div class="widget-body">
					<div class="widget-main padding-24"> 
						<div class="row">
							<div class="form-group col-lg-4">
								<label for="agreement_no" class="control-label">Location</label>
								<select class="form-control" id="location" name="location" data-placeholder="-Select-" >
									<option value=""></option>
									<?php foreach($location as $loc):?>
									<option value="<?php echo $loc['id']; ?>"> <?php echo $loc['location'];?> </option>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-4">
								<label for="storage_type" class="control-label">Storage Type</label>
								<select class="form-control" id="storage_type" name="storage_type" dataplaceholdler="~Select~">
								<option value=""></option>
									<?php foreach($storage_type as $cont):?>
										<option value="<?php echo $cont['id'];?>"> <?php echo $cont['storage_type'];?>
									<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-4">
								<label for="commodity" class="control-label"> Commodity Stored </label>
								<input type="text" class="form-control" name="commodity" id="commodity" style="text-transform: capitalize;" placeholder="Commodity Stored" required />
							</div>
						</div>
						
						<div class="row">
							<div class="form-group col-lg-4">
								<label for="capacity" class="control-label"> Capacity (in Matric Tonn) </label>
								<input class="form-control" name="capacity" id="capacity" placeholder="Capacity in Matric Tonn" required />
							</div>
							<div class="form-group col-lg-4">
								<label for="area" class="control-label">Area (in Sq.Ft)</label>
								<input type="text" class="form-control" name="area" id="area" placeholder="Area in Square Feet" required />
							</div>
							<div class="form-group col-lg-4">
								<label for="operator_name" class="control-label"> operator_name</label>
								<input type="text" class="form-control" name="operator_name" id="commodity" style="text-transform: capitalize;" placeholder="operator_name" required />
							</div>
						</div>
						
						<div class="row">
							<div class="form-group col-lg-8">
								<label for="condition" class="control-label"> Physical Condition </label>
								<textarea type="text" class="form-control" name="condition" id="condition" rows="2" placeholder="Physical Condition" ></textarea>
							</div>
						</div>
						
						<div class="row">
							<div>
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>  
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
<script type="text/javascript"> 	
    $(function() {
		$('#location').on('change', function(){
			$location_id = $(this).val(),
			//alert($location_id);
			$.post(
				"<?php echo $this->url('realestate', array('action' => 'getLeasedGodown')); ?>",
				{
					location_id: $location_id,
				},
				function(data){
					console.log(data);
					$('#storage_type').html(data.leaseditem);
					$('#storage_type').trigger('chosen:updated');
					$('form').formValidation('revalidateField','storage_type');
				},
				'json'
			);
		});
		
	}); 
	$('form select').chosen();
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				location: {
					validators: {
						notEmpty: {
							message: 'Please select location.'
						}
					}
				},
				storage_type: {
					validators: {
						notEmpty: {
							message: 'Please select Storage Type'
						}
					}
				},
				capacity: {
					validators: {
						notEmpty: {
							message: 'Please provide capacity value.'
						},
						numeric:{
							message: 'Enter a Figure Value'
						}
					}
				},
				commodity: {
					validators: {
						notEmpty: {
							message: 'Please provide commodity stored.'
						}
					}
				},
				area: {
					validators: {
						notEmpty: {
							message: 'Please provide Lessee Name.'
						},
						numeric:{
							message: 'Enter a Figure Value'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	});
</script>

