<?php // view partial.phtml 
  $restate = ($this->active == "restate")?"active":"";
 // $rents = ($this->active == "rents")?"active":"";
?>
<br/>
<ul class="nav nav-tabs padding-18" id="myTab" >
	<li class="<?php echo $restate; ?>">
		<a href="<?php echo $this->url('capacity', array('action' => 'index')); ?>">
			<i class="blue ace-icon fa fa-server bigger-120"> </i>
			<span class="hidden-xs" >Real Estate Storage</span>
		</a>
	</li>
	<!--li class="<?php //echo $rents; ?>">
		<a href="<?php //echo $this->url('realestate', array('action' => 'viewrent')); ?>">
			<i class="blue ace-icon fa fa-users bigger-120"> </i>
			<span class="hidden-xs" >Monthly Rent View</span>
		</a>
	</li-->
</ul>

