<?php
/**
 * View -- of Store/PurchaseController/editporderAction-----
 */
?>
<?php 
  foreach($this->purchase_order as $pur_order):
      extract($pur_order);
	  //print_r($pur_order); exit;
  	  $purchase_order_id = $id;
      $sel_del_location = $delivery_location;
      $sel_location = $location_id;
      $sel_group = $item_group_id;
      $sel_cost_center = $cost_center_id;
      $po_status = $status;
  endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					&nbsp;<strong><?php echo $purchase_order_no; ?> | <?php echo $supplier; ?> | <?php echo $cost_center; ?></strong>&nbsp;
					<?php $this->status($po_status);?>
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form  id="#form" method="post" action="<?php echo $this->url('inpurorder', array('action' => 'editporder', 'id' => $purchase_order_id)); ?>"  enctype="multipart/form-data" >    
						 <div class="row">	
							<div class="col-lg-3">   
								<input type="hidden" name="purchase_order_id" id="purchase_order_id" value="<?php echo $purchase_order_id; ?>">
								<input type="hidden" name="purchase_order_no" id="purchase_order_no" value="<?php echo $purchase_order_no; ?>"> 
								<div class="form-group">
									<label for="purchase_order_date" class="control-label">Purchase Order Date</label>
									<div class="date input-group" id="purchase_order_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $purchase_order_date; ?>" name="purchase_order_date" id="purchase_order_date" type="text" placeholder="PO Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="supplier" class="control-label">Supplier</label>
									<input type="text" class="form-control" name="supplier" id="supplier" value = "<?php echo $supplier;?>" placeholder="Enter supplier"/> 
								</div>
							</div>	
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="group" class="control-label">Item Group</label>
									<select id="group" name="group" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($this->groupObj->getAll() as $group):
										$selected_group = ($sel_group ==$group['id'])?"selected":"";?>
											   <option value="<?php echo $group['id'];?>"<?php echo $selected_group;?>><?php echo $group['name']; ?></option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="cost_center" class="control-label">Cost Center </label>
									<select class="form-control" name="cost_center" id="cost_center" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach($this->activities as $activity):
										$selected=($activity['id']==$sel_cost_center)?'selected':'';?>
											<option value="<?php echo $activity['id'];?>" <?php echo $selected;?>>
										   		<?php echo $activity['activity']; ?>
										   	</option>
										<?php endforeach; ?>								
									</select>
								</div>
							</div>									
						</div>
						<div class="row">
						   	<div class="col-lg-3"> 
								<div class="form-group">
									<label for="activity" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required readonly >
									  <option value=""></option>
									  <?php foreach ($regions as $region): ?>
									  	<optgroup label="<?php echo $region['region'];?>">
											<?php // retrive locations under the above region ID
												 $locations = $locationObj->get(array('l.region'=>$region['id']));
												 foreach ($locations as $location):
												 $selected = ($location['id'] == $sel_location)?"selected":"";
											?>
												<option value="<?php echo $location['id']; ?>" <?php echo  $selected; ?>>
													<?php echo $location['location']; ?>
												</option>
												<?php endforeach; ?>
									 	</optgroup>
									 <?php endforeach;  ?>									
									</select> 
								</div>
							</div>	
							<div class="col-lg-3">
								<div class="form-group">
									<label for="delivery_location" class="control-label">Delivery Location</label>
									<select id="delivery_location" name="delivery_location" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach ($regions as $region): ?>
											<optgroup label="<?php echo $region['region'];?>">
											<?php // retrive locations under the above region ID 
												$locations = $locationObj->get(array('l.region'=>$region['id']));
												foreach ($locations as $location):
											  	$selected = ($location['id'] == $sel_del_location)?"selected":"";
											?>
													<option value="<?php echo $location['id']; ?>" <?php echo $selected; ?>>
														<?php echo $location['location']; ?>
													</option>
												<?php endforeach; ?>
										  </optgroup>
									 <?php endforeach; ?>			
									</select>  
								</div> 
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="quotation_no" class="control-label">Quotation No.</label>
									<input type="text" class="form-control" value="<?php echo $quotation_no; ?>" name="quotation_no" id="quotation_no" placeholder="Quotation No."> 
								</div>
							</div> 
							<div class="col-lg-3">
								<div class="form-group">
									<label for="quotation_date" class="control-label">Quotation Date</label>
									<div class="date input-group" id="quotation_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $quotation_date; ?>" name="quotation_date" id="quotation_date" type="text" placeholder="Quotation Date" readonly>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>  
						</div>
						<div class="row">
						   <div class="col-lg-12"> 
							  <h5>Purchase Order Details</h5>
								 <div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Item</th>
												<th>UOM</th>
												<th>Quantity</th>
												<th>Rate (<?php echo $this->currency_code();?>)</th>
												<th>Amount (<?php echo $this->currency_code();?>)</th>
												<th>Remarks</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
										<?php 
										  if(sizeof($po_details) > 0 ):
											foreach ($this->po_details as $po_detail):
										?>
											<tr>
												<td>
													<div class="form-group">
													    <input type="hidden" name="details_id[]" id="details_id" value="<?php echo $po_detail['id']; ?>">
														<select id="item" name="item[]" class="form-control" data-placeholder="Select" required >
															<option value=""></option>
															<?php 
															$items =  $itemsObj->get(array('i.item_group' => $sel_group));
															foreach($items as $item):
															$selected = ($item['id']==$po_detail['item_id'])?'selected':'';
															?>
															<option value="<?php echo $item['id'];?>" <?php echo $selected;?>>
																<?php echo $item['name']?>
															</option>							
															<?php endforeach;?>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<select id="uom" name="uom[]" class="form-control" data-placeholder="Select"  required >
															<option value=""></option>
															<?php 
															$items = $this->itemsObj->get($po_detail['item_id']);
																foreach($items as $item):
																	$selected = ($item['uom']==$po_detail['uom'])?"selected":"";
																	$basic_uom = $item['uom'];
															?>
																<option value="<?php echo $item['uom']?>" <?php echo $selected;?>>
																	<?php echo $this->uomObj->getColumn($item['uom'], 'code');?>
																</option>
															<?php endforeach;?>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $po_detail['quantity']; ?>" name="quantity[]" id="quantity" quantity="<?php echo $po_detail['quantity']; ?>" required/>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="rate[]" value="<?php echo $po_detail['rate']; ?>" id="rate" rate="<?php echo $po_detail['rate']; ?>" required/>
													</div>         
												</td>
												<td>
													<div class="form-group">
														<?php $amt = $po_detail['quantity'] * $po_detail['rate'];?>
														<input type="text" class="form-control" name="amount[]" value="<?php echo number_format((float)$amt, 2, '.', '');?>" id="amount" readonly/>
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $po_detail['remarks']; ?>" name="remarks[]" id="remarks" />
													</div>
												</td>
												<td></td>											
											</tr>
											<?php 
												$poSum += $po_detail['quantity'] * $po_detail['rate'];
													endforeach;
												endif;
											?>
										</tbody>
									</table>
								</div>
							</div>
						</div>	
						<div class="row"> 
							<div class="col-lg-9"></div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="po_amount">Net Amount(<?php echo $this->currency_code();?>)</label>
									<input type="text" class="form-control tr_po_amount" name="po_amount" id="po_amount" value="<?php echo number_format($poSum, 2); ?>" readonly />
								</div>
							 </div> 
						</div>	
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
					</form>    
				</div> 
	  		</div>   
      	</div>
    </div>   
</div>	
<input type="hidden" name="po_status" id="po_status" value="<?php echo $po_status;?>" />					
<script type="text/javascript"> 
$(function() {
	$('#purchase_order_date').datepicker();
	$('#quotation_date').datepicker();
	$('#trdetails_table').inporder({
		getItem:"<?php echo $this->url("inpurorder", array("action" => "getitem"));?>",
		getUom:"<?php echo $this->url('inpurorder', array('action'=>'getitemuom'));?>",
	});
	//if($('#po_status').val() == 2){
		//$('#invoice_amount').prop('readonly', true);
	//}
    /*** Form Validation of PO ***/
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			purchase_order_date: {
				validators: {
					notEmpty: {
						message: 'Please select PO date'
					}
				}
			},
			supplier: {
				validators: {
					notEmpty: {
						message: 'Please enter supplier'
					}
				}
			},
			cost_center: {
				validators: {
					notEmpty: {
						message: 'Please select cost center'
					}
				}
			},
			location: {
				validators: {
					notEmpty: {
						message: 'Please select location'
					}
				}
			}, 
			delivery_location: {
				validators: {
					notEmpty: {
						message: 'Please select delivery location'
					}
				}
			},
			item[]: {
				validators: {
					notEmpty: {
						message: 'Please select item'
					}
				}
			},
			uom[]: {
				validators: {
					notEmpty: {
						message: 'Please select uom'
					}
				}
			},
			quantity[]: {
				validators: {
					notEmpty: {
						message: 'Please provide quantity'
					}
				}
			},
			rate[]: {
				validators: {
					notEmpty: {
						message: 'Please provide rate'
					}
				}
			},
			amount[]:{
				validators:{
					notEmpty:{
						message:'Please provide amount'
					},
				},
			},
			po_amount:{
				validators:{
					notEmpty:{
						message:'Please provide Net PO Amount',
					},
				},
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('#purchase_order_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
});    
</script>
   
