<?php
/**
 * 
 * View -- of Store/PurchaseController/indexAction
 * 
 */
 $this->headTitle($this->title);
//print_r($this->purchase_results); exit;
?>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="row">
	<div class="col-lg-12">
		<div class="row">
			<form id="#form" method="post" action="<?php echo $this->url('inpurorder'); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-2">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['month'] == '-1')?'selected':'';?>>All</option>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="group">Item Group</label>
					<select class="form-control" id="group" name="group" data-placeholder="group" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['group'] == '-1')?'selected':'';?>>All</option>
						<?php 
							$groups = $this->groupObj->getAll();
							foreach($groups as $group):
								$selected_group = ($group['id'] == $data['group'])?'selected':'';
						?>
							<option value="<?php echo $group['id']?>" <?php echo $selected_group;?>>
								<?php echo $group['name'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Purchase Order" href="<?php echo $this->url('inpurorder', array('action'=>'addporder'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add PO</span></span>
					</a>
				</div>
			</div>
		</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>PO No.</th>
                        <th>Qt no.</th>
						<th>PO Date</th>
						<th>PO Amount</th>
						<th class="no-sort no-printpdf">Action</th>						
					</tr>
				</thead>
				<tbody>
					<?php $sl=1;?>
					<?php foreach($this->purchase_results as $row):?>
						<tr data-href="<?php echo $this->url('inpurorder', array('action'=>'viewporder', 'id'=>$row['id']));?>">
							<td><?php echo $sl++;?></td>
							<td>
							 	<b><?php echo $row['purchase_order_no'];?></b>&nbsp;
								<?php echo $row['supplier'];?>&nbsp;
							 	<span class="label label-danger"> 
									<?php echo $this->groupObj->getColumn($row['item_group'],'name'); ?> &nbsp;&nbsp;&nbsp;
								</span>
								 <span class="label label-info"> 
									<?php echo $this->activitiesObj->getColumn($row['cost_center'],'activity'); ?> &nbsp;&nbsp;&nbsp;
								 </span>&nbsp;<?php $this->status($row['status']);?> 
								 <?php if($row['paid_amount'] > 0):?>
									<span class="badge badge-danger pull-right"> 
										paid  
									</span>
								<?php endif;?>
							</td>
                            <td><?php echo ($row['quotation_no']!='')?$row['quotation_no']:'--';?></td>
							<td><?php echo $row['purchase_order_date'];?></td>
							<td><?php echo $this->currency($row['total_amount']);?></td>
							<td class="action">
								<div class="btn-group">
									<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "1-".$row['id'])); ?>" title="View Activity Logs">
										<i class="ace-icon fa fa-plus bigger-120" ></i>  
							  		</a>
						  		</div>
							</td>								
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});

	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>
