<?php
/**
 * 
 * View -- of Purchase/PurchaseController/viewporder
 * 
 */
?>
<?php 
    //print_r($this->purchase_order); exit;
	foreach($this->purchase_order as $row ):
		extract($row);
	    $po_status = $status; 
	    $po_id = $id; 
	endforeach;
	foreach($this->PODObject->get(array('purchase_order' => $po_id)) as $tdrow):
		$po_total_qty += $tdrow['quantity'];
		$received_total_qty += $tdrow['received_qty'];
	endforeach;
?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<form method="post" action="<?php echo $this->url('inpurreceipt', array('action' => 'addreceipt')); ?>" >
				<div class="widget-header">
					<h5 class="widget-title lighter smaller">
						# Purchase Order Details:<strong>&nbsp;&nbsp;<?php echo $purchase_order_no; ?> | <?php echo $supplier; ?> | <?php echo $cost_center ?></strong>&nbsp;
						<?php $this->status($status);?>
					</h5>
					<input type="hidden" name="porder" id="porder" value="<?php echo $po_id;?>" />
					<div class="widget-toolbar hidden-xs">
						<?php if($status == 2):?> <!--if po qty and received qty not equal-->
							<button type="submit" class="btn btn-white btn-success btn-bold btn-xs"><i class="fa fa-step-forward"></i> Purchase Receipt </button>
						<?php endif;?>
					</div>
					<div class="widget-toolbar hidden-xs">
						<div class="btn-group">
							<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "33-".$po_id)); ?>" title="View Activity Logs">
								<i class="ace-icon fa fa-plus bigger-120" ></i>  
							</a> 
							<a class="btn btn-xs" id="print" title="Print">
								<i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
							</a>
						</div>
					</div>
				</div>
			</form>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Purchase Order no : <b class="red"><?php echo $purchase_order_no; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Supplier : <b class="red"><?php echo $supplier; ?> </b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Item Group : <b class="red"><?php echo $item_group; ?> </b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Location : <b class="red"><?php echo $location; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Quotation No : <b class="red"><?php echo $quotation_no; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										PO Amount : <b class="purple"><?php echo $total_amount; ?></b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Purchase Order Date : <b class="red"><?php echo $this->dateformat($purchase_order_date); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Cost Center : <b class="red"><?php echo $cost_center; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Delivery Location : <b class="red"><?php echo $this->locationObj->getColumn( $delivery_location, 'location'); ?> </b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Quotation Date : <b class="red"><?php echo $this->dateformat($quotation_date); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Paid Amount : <b class="blue"><?php echo $this->currency($paid_amount); ?></b>
									</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>Note: <b class="red"><?php echo $note;?> </b>
									</li>
								</ul>
							</div>
						</div>
						<div class="space-6"></div>
						<div class="row">
							<div class="col-lg-12" >
								<table class="table" style="border-top:2px solid #ddd;">
									<thead>
										<tr>
											<th>#</th>
											<th>Item</th>
											<th>UOM</th>
											<th>Quantity</th>
											<th>Rate(<?php echo $this->currency_code();?>)</th>
											<th>Amount (<?php echo $this->currency_code();?>)</th>
											<th>Remarks</th>
										</tr>
									</thead>
									<tbody>
										<?php $sl = 1; 
										    $total_amount = 0;
											foreach($this->PODObject->get(array('purchase_order' => $po_id)) as $tdrow):
													$qty = $tdrow['quantity'];
													$rate = $tdrow['rate'];
													$amt = $qty * $rate;
													$total_amount += $qty * $rate;
											?>
											<tr>
												<td><?php echo $sl++; ?></td>
												<td><?php echo $tdrow['item'];?></td>
												<td><?php echo $this->uomObj->getColumn($tdrow['uom'],'code');?></td>
												<td><?php echo $tdrow['quantity'];?></td>
												<td><?php echo $tdrow['rate'];?></td>
												<td><?php echo number_format((float)$amt, 2, '.', '');?></td>
												<td><?php echo $tdrow['remarks'];?></td>
											</tr>
										<?php endforeach;?>
										<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
											<th colspan="6"><?php echo $this->numtoWords($total_amount);?></th>
											<th colspan="2">Net Amount : 
											<?php echo $this->currency($total_amount);?></th>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-7">
						</div>
						<div class="col-lg-5" style="text-align: right">
							<?php if($po_status == '1'):?>
								<a href="<?php echo $this->url('inpurorder', array('action'=>'pendingporder', 'id'=>$po_id));?>" class="btn btn-success"> <i class="fa fa-check-square-o"></i> Send PO</a>
								<a href="<?php echo $this->url('inpurorder', array('action'=>'editporder', 'id'=>$po_id));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
							<?php endif;?>	
						</div>
					</div>
					<!-- Upload and Download file attachments -->			
					<?php   
					   echo $this->partial('partial/attachment.phtml', array('process' => '1', 'process_id'=> $po_id , 'status' => $po_status));
					?>					
				    <!-- End of attachment -->
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
</script>
