<!-- <?php
/**
 * 
 * View -- of Realestate/EstateController/addleasedAction
 * 
 */
    $this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php  //echo $this->url('realestate', array('action' => 'addleased')); ?>"  enctype="multipart/form-data" >
    <div class="row">
        <div class="col-lg-12"> 
            <div class="widget-box">
                <div class="widget-header widget-header-smaller">
                    <h4 class="widget-title blue bolder smaller"> Leased Agreement Details
                </div>
                <div class="widget-body">
                    <div class="widget-main padding-24"> 
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label for="agreement_no" class="control-label">Leased Agreement No.</label>
                                <input class="form-control" name="agreement_no" id="agreement_no" placeholder="Leased Agreement No." required >
                            </div>
                            <div class="form-group col-lg-4">
                                <label for="agreement_date" class="control-label">Agreement Date</label>
                                <div class="date input-group" id="agreement_date" data-date="today" data-date-format="yyyy-mm-dd">
                                    <input class="form-control span2" name="agreement_date" id="agreement_date" type="text" placeholder="Agreement Date" readonly required>
                                    <span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
                                </div>
                            </div>
                            <div class="form-group col-lg-4">
                                <label for="location" class="control-label">Location</label>
                                <select class="form-control" id="location" name="location" data-placeholder="-Select-" required >
                                    <option value=""></option>
                                    <?php foreach($location as $loc):?>
                                    <option value="<?php echo $loc['id']; ?>"> <?php echo $loc['location'];?> </option>
                                    <?php endforeach;?>
                                </select>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label for="leased_property" class="control-label"> Leased Property </label>
                                <select class="form-control" name="leased_property" id="leased_property" data-placeholder="-Select-" required >
                                    <option value=""></option>
                                </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label for="lessee" class="control-label"> Lessee Name</label>
                                <input type="text" class="form-control" name="lessee" id="lessee" style="text-transform: capitalize;" required />
                            </div>
                            <div class="form-group col-lg-4">
                                <label for="rent" class="control-label"> Rent (per Month) </label>
                                <input type="text" class="form-control" name="rent" id="rent" required />
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="form-group col-lg-4">
                                <label for="start_date" class="control-label">Start Date</label>
                                <div class="date input-group" id="start_date" data-date="today" data-date-format="yyyy-mm-dd">
                                    <input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" readonly required>
                                    <span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
                                </div>
                            </div>
                            <div class="form-group col-lg-4">
                                <label for="end_date" class="control-label">End Date</label>
                                <div class="date input-group" id="end_date" data-date="today" data-date-format="yyyy-mm-dd">
                                    <input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" readonly required>
                                    <span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div>
                                <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
                                <button type="button" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>  
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type="text/javascript">     
    $(function() {
        $('#location').on('change', function(){
            //$location_id = $(this).val(),
            //alert($location_id);
            $.post(
                "<?php //echo $this->url('realestate', array('action' => 'getleasedgodown')); ?>",
                {
                    location_id: $(this).val(),
                },
                function(data){
                    console.log(data);
                    $('#leased_property').html(data.leaseditem);
                    $('#leased_property').trigger('chosen:updated');
                    //$('form').formValidation('revalidateField','leased_property');
                },
                'json'
            );
        });
        
    }); 
    $('form select').chosen();  
    $('#agreement_date').datepicker();
    $('#start_date').datepicker();
    $('#end_date').datepicker();
    $('document').ready(function(){
        const fv = FormValidation.formValidation(document.getElementById('#form'), {
            fields: {
                agreement_no: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide Leased Agreement No.'
                        }
                    }
                },
                agreement_date: {
                    validators: {
                        notEmpty: {
                            message: 'Please select date.'
                        }
                    }
                },
                location: {
                    validators: {
                        notEmpty: {
                            message: 'Please select Location.'
                        }
                    }
                },
                leased_property: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide Leased Property.'
                        }
                    }
                },
                lessee: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide Lessee Name.'
                        }
                    }
                },
                rent: {
                    validators: {
                        notEmpty: {
                            message: 'Please provide Rent.'
                        },
                        numeric: {
                            message: 'The Rent in Figure Only'
                        },
                    }
                },
            },
            plugins: {
                trigger: new FormValidation.plugins.Trigger(),
                bootstrap3: new FormValidation.plugins.Bootstrap3(),
                submitButton: new FormValidation.plugins.SubmitButton(),
                defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
            },
        }).on('core.element.validated', function (e) {
            if (e.valid) {
                $('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
                $('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
            } else {
                $('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
                $('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
            }
        });

        $('#agreement_date').on('changeDate',function(){
            $('form').formValidation('revalidateField','agreement_date');
        });
        $('#start_date').on('changeDate',function(){
            $('form').formValidation('revalidateField','start_date');
        });
        $('#end_date').on('changeDate',function(){
            $('form').formValidation('revalidateField','end_date');
        });
    });
</script> -->
