<?php // view partial.phtml 
//   $leased = ($this->active == "leased")?"active":"";
//   $rents = ($this->active == "rents")?"active":"";
// ?>
// <br/>
// <ul class="nav nav-tabs padding-18" id="myTab" >
// 	<li class="<?php echo $leased; ?>">
// 		<a href="<?php echo $this->url('realestate', array('action' => 'index')); ?>">
// 			<i class="blue ace-icon fa fa-area-chart bigger-120"> </i>
// 			<span class="hidden-xs" >Leased Property</span>
// 		</a>
// 	</li>
// 	<li class="<?php echo $rents; ?>">
// 		<a href="<?php echo $this->url('realestate', array('action' => 'viewrent')); ?>">
// 			<i class="blue ace-icon fa fa-adjust bigger-120"> </i>
// 			<span class="hidden-xs" >Monthly Rent View</span>
// 		</a>
// 	</li>
// </ul>

