<!-- <?php
/*
*	 View -- of Realestate/EstateController/viewrentAction
*
*/?>
<?php echo $this->partial('realestate/estate/partial.phtml',array('active' => 'rents'));?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="row">
			<form method="post" action="<?php echo $this->url('realestate',array('action' => 'viewrent')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form><br/>	
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<?php echo $this->button(2);?>
				</div>
		</div>	
		<div class="row">
			<table class="table card-table text-nowrap" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Date</th>
						<th>Amount</th>
					</tr>
				</thead>
				<tbody>
					<?php $sl=1;?>
					<?php foreach($this->rentreceivable as $row):?>
						<tr data-href="<?php echo $this->button(4,$row['id']); ?>">
							<td><?php echo $sl++;?></td>
							<td><?php echo $row['code']; ?></td>
							<td><?php echo $row['voucher_date']; ?></td>
							<td><?php echo $this->currency($row['credit']); ?></td>
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script>		
	$("tr[data-href]").each(function(){ 
		if($(this).attr('data-href')!='#'){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).attr("data-href");
			});
		}
	});
	$('document').ready(function(){
		$('#dataTables').DataTable();
	});
</script>
 -->
