<?php 
/**
 * View -- of Administration/AssetController/assetAction
 * chophel@athang.com -- 2022
 */
	$this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(3006,3012)); ?>
<div class="card">
    <div class="card-header">
		<div class="row">
			<div class="col-lg-9">
				<form id="#form" method="POST" action="<?php echo $this->url('assets', array('action' => 'asset')); ?>" enctype="multipart/form-data" >    
					<div class="row">
						<div class="form-group col-lg-3">
							<label for="assettype" class="control-label">Asset Type</label>
							<select class="form-control" name="assettype" id="assettype" data-placeholder="Select" onChange='this.form.submit()' required>
								<option value="-1">All</option>
								<?php foreach($this->assettypeObj->getAll() as $assettype):
									$selected = ($data['typeid'] == $assettype['id'])?'selected':'';?>
								<option value="<?php echo $assettype['id'];?>"<?php echo $selected;?>>
									<?php echo $assettype['name']; ?>
								</option>
							<?php endforeach;?>
							</select>
						</div>
						<div class="form-group col-lg-3">
							<label for="region" class="control-label">Region</label>
							<select class="form-control" name="region" id="region" data-paceholder="Select">
								<option value="-1">All</option>
								<?php $regions = $this->regionObj->getAll();
								foreach ($regions as $region):?>
								<?php $selected_reg = ($data["region"]==$region['id'])? 'selected':'';?>
									<option value="<?php echo $region['id'];?>" <?php echo $selected_reg;?>>
										<?php echo $region['region']; ?>
									</option>
								<?php endforeach;?>									
							</select>
						</div> 
						<div class="form-group col-lg-3">
							<label for="location" class="contol-label">Location</label>
							<select class="form-control" name="location" id="location" data-placeholder="Select" onChange='this.form.submit()'>
								<option value="-1">All</option>
								<?php if($data["region"]>0):
									foreach($this->locationObj->get(array('region'=> $data["region"])) as $locations):
								?>
									<?php $selected_loc = ($data["location"]==$locations['id'])? 'selected':'';?>
									<option value="<?php echo $locations['id'];?>" <?php echo $selected_loc;?> >
									    <?php echo $locations['location'];?>
									</option>
								<?php endforeach;
								endif;?>							
							</select>
						</div> 
						<div class="form-group col-lg-3">
							<label for="status" class="control-label">status</label>
							<select class="form-control" name="status" id="status" data-placeholder="Select" onChange='this.form.submit()' required>
								<option value="-1">All</option>
								<?php foreach($this->statusObj->getarray([1,19,22,23]) as $sta):
									$selected = ($data['status'] == $sta['id'])?'selected':'';?>
								<option value="<?php echo $sta['id'];?>"<?php echo $selected;?>>
									<?php echo $sta['status']; ?>
								</option>
							<?php endforeach ?>
							</select>
						</div>
					</div>
				</form>
		    </div>
		     <div class="col-lg-3 ">
				<div class="space"></div>
				<div class="btn-group pull-right">
					<?php echo $this->button(2,$page);?>
				</div>
			</div> 
	    </div>
		<div class="table-responsive">
			<table class="table card-table table-vcenter text-nowrap datatable" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Assets</th>
						<th>Asset ID</th>
						<th>Location</th>
						<th>Put-in Use Date</th>
						<th>Useful life</th>
						<th>Gross Value</th>
						<th>Salvage Value</th>
						<th>Depreciable Amt</th>
						<th>Acc.Depreciation(31.12.2023)</th>
						<th>Net Value</th>
						<th>Status</th>
						<?php if($this->button(1)!=""):?>
							<th class="no-sort no-printpdf">Action</th>
						<?php endif;?>	 
					</tr>
				</thead>
				<tbody>
				<?php 
					$total_asset_value =0;
					$total_aac_dep_value =0;
					$dep=0;
					$total_salvage=0;
					$total_depreciable=0;
					$total_net_value =0;
					$total_usefullife =0;
					$i=1+(($page-1)*20); foreach ($paginator as $row):
					/*CHECK IF THE YEAR IS LEAP AND COUNT THE LEAP IN BETWEEN*/
					
					$current_year=date('Y');
					$put_in_use_year = date('Y', strtotime($row['putin_date']));
					$usefullife = $row['usefullife'];
					$end_of_life = $put_in_use_year + $usefullife;
					
					$year_of_use= $current_year - $put_in_use_year;
					$leap = 0;
					for ($year = $put_in_use_year; $year <= $end_of_life; $year++) {
						if (($year % 4 == 0 && $year % 100 != 0) || ($year % 400 == 0)) {
							$leap++;
						}
					}
					/*TOTAL USEFULLIFE IN DAYS*/ 
					$total_days_with_leap = $leap * 366;
					$regular_year = $usefullife - $leap;
					$total_days_with_regular_year = $regular_year * 365;
					$total_useful_days = $total_days_with_leap + $total_days_with_regular_year;
					
					/*TOTAL USEFULLIFE IN COMPLETED*/
					$startDate = $row['putin_date'];
					$currentDate = date("Y-m-d");
					
					/*DAY FROM USE UNTIL TODAY*/
					$timestampStartDate = strtotime($startDate);
					$timestampEndDate = strtotime($currentDate);
					if ($timestampStartDate === false || $timestampEndDate === false) {
					} else {
						$timeDifference = $timestampEndDate - $timestampStartDate;
						$daysCompletedtilltoday = floor($timeDifference / (60 * 60 * 24));
					}
					//echo '<pre>';print_r($total_useful_days);
					//echo '<pre>';print_r($daysCompletedtilltoday.'-'.'Days from the date of purchase');
					//echo '<pre>';print_r($timeDifference);
					//echo '<pre>';print_r($daysCompletedtilltoday);exit;
					
					/*DEPRECIATION AMOUNT PER DAY*/
					$actual_asset_value = $row['asset_value'];
					$salvage_value = $row['salvage'];
					// if($salvage_value > 0 && $actual_asset_value != $salvage_value){
					// 	$depreciation_per_day = ($actual_asset_value - $salvage_value) / $total_useful_days;
					// }
					//echo '<pre>';print_r($depreciation_per_day.'-'.'Daily');exit;
					//echo '<pre>';print_r($depreciation_per_day * 22 .'-'.'in 22-Days');//exit;
					/*ACCUMULATED DEPRECIATION UNTIL TODAY*/
					//$today_date = date('d', strtotime($currentDate));
					//$previous_month = $daysCompletedtilltoday - $today_date;
					//echo '<pre>';print_r($daysCompletedtilltoday);
					//echo '<pre>';print_r($previous_month);
					
					// if($daysCompletedtilltoday < $total_useful_days ){
					// 	$acc_depreciation = $depreciation_per_day * $previous_month;
					// }else{
					// 	$acc_depreciation = $actual_asset_value - $salvage_value;
					// }
					// if($row['depreciation']==1 && $usefullife >=1 ){
					// 	$depreciation_anually = ($actual_asset_value - $salvage_value) / $usefullife;
					// }else{
					// 	$depreciation_anually = 0.00;
					// }
					//echo '<pre>';print_r($acc_depreciation);//exit;
					/*CALCULATE NET AMOUNT*/
					$depreciable=$row['depreciable_amount'];
					$net_value = $row['net'];
					/*CALCULATE SUM FROM THE LIST AMOUNT*/
					$total_asset_value += $row['asset_value'];
					//$total_aac_dep_value += $acc_depreciation;
					$total_net_value += $net_value;
					$total_salvage+=$row['salvage'];
					$total_depreciable+=$depreciable;
					$total_usefullife+=$row['usefullife'];
					
					
					?>
					<tr data-href="<?php echo $this->button(4,$row['id']);?>">
						<td><?php  echo $i++; ?></td>								       
						<td class="fw-bold"><?php echo $row['name'];?></td>
						<td><?php echo $row['assetid'];?></td>
						<td><?php echo $this->locationObj->getColumn($row['location'],'location');?></td>
						<td><?php echo $row['putin_date'];?></td> 
						<td><?php echo $row['usefullife'];?></td> 
						<td class="fw-bold"><?php echo number_format($row['asset_value'],2);?></td>
						<td class="fw-bold"><?php echo number_format($row['salvage'],2);?></td>
						<td class="fw-bold"><?php echo number_format($depreciable,2);?></td>
						<td class="fw-bold"><?php echo $acc_depreciation=number_format($row['acc_depreciation'],2)?number_format($row['acc_depreciation'],2):'0.00';?></td>
						<td class="fw-bold"><?php echo number_format($net_value,2);?></td>
						<td class="fw-bold"><?php echo $this->status($row['status']);?></td>
					 <?php if($this->button(1)!=""):?>
							<td><?php echo ($row['status']==1)?$this->button(1, $row['id']):'';?></td>
						<?php endif;?> 
					</tr>
				<?php $dep+=$row['acc_depreciation']; endforeach;?>
					<tr>
						<td></td>								       
						<td></td>
						<td></td>
						<td></td>
						<td></td>			
						<td class="fw-bold"><?php echo number_format($total_usefullife,2);?></td>			
						<td class="fw-bold"><?php echo number_format($total_asset_value,2);?></td>
						<td class="fw-bold"><?php echo number_format($total_salvage,2);?></td>
						<td class="fw-bold"><?php echo number_format($total_depreciable,2);?></td>
						<td class="fw-bold"><?php echo number_format($dep,2);?></td>
						<td class="fw-bold"><?php echo number_format($total_net_value,2);?></td>
						<td class="fw-bold"></td>
						<td class="fw-bold"></td> 
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
	$("#region").change(function() { 
			$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
				var newdata ="<option value='-1'>All</option>"+data
				$('#location').html( newdata );
				$("#location").trigger('chosen:updated');
			});
	    });
	$("tr[data-href]").each(function(){ 
		if($(this).attr('data-href')!='#'){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).attr("data-href");
			});
		}
	});
	$('#dataTables').DataTable({
		"paging":   true,
		//"pageLength": 50, // Set the number of rows per page to 50
	});
});
</script>