<?php
/**
 * 
 * View -- of Accounts/TransactionController/viewtransactionAction
 * 
 */
?>
<?php 
	foreach($assets as $row ):
		extract($row);
		//$bank_ref_type_id = $row['bank_ref_type'];//
	endforeach;
?>
<div class="space"></div>
<div class="col-lg-12">
	<div class="widget-box transparent">
		<div class="widget-header widget-header-large">
			<h5 class="widget-title grey lighter">
				<i class="ace-icon fa fa-file-text-o green"></i>
				<b><?php echo $name;?> | <?php echo $this->status($status);?></b>
			</h5>
		</div>
		<div class="widget-body">
			<div class="widget-main padding-24">
				<div id="report-print">
					<div class="row" id="convert-tb0">
						<div class="col-lg-9" id="convert-tb1">
							<ul class="list-unstyled spaced">
							    <li>
									<i class="ace-icon fa fa-caret-left blue"></i><b>Asset ID :</b> <?php echo $assetid; ?>
								</li>
							    <li>
									<i class="ace-icon fa fa-caret-left blue"></i><b>Custodian :</b> <?php echo $this->employeeObj->getColumn($row['custodian'],'full_name');?> 
								</li>
							</ul>
						</div>
						<div class="col-lg-3" id="convert-tb3">
							<ul class="list-unstyled spaced">
							    <li>
									<i class="ace-icon fa fa-caret-left blue"></i><b>Region : </b> <?php echo $region; ?>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-left blue"></i><b>Location : </b><?php echo $location;?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
					    <div class="col-lg-12">
							<table class="table table-striped table-bordered table-condensed">	
								<thead>
									<th style="font-size:14px">Asset Type</th>
									<th style="font-size:14px">Asset Value</th>
									<th style="font-size:14px">Salvage</th>
									<th style="font-size:14px">Put In Use</th>
									<th style="font-size:14px">Useful Life</th>
									<!-- <th style="font-size:14px">Depreciation(Per Year)</th> -->
									
								</thead>
								<tbody>
									<tr>
										<td style="font-size:13px"><?php echo $this->assettypeObj->getColumn($row['asset_type'],'name');?></td>
										<td style="font-size:13px"><?php echo $row['asset_value'];?></td>
										<td style="font-size:13px"><?php echo $row['salvage'];?></td>
										<td style="font-size:13px; text-align:right"><?php echo $row['purchase_date'];?></td>
										<td style="font-size:13px; text-align:right"><?php echo $row['usefullife'];?></td>
										<!-- <td style="font-size:13px; text-align:right"><?php echo $row['depreciation_amount'];?></td> -->
									</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-3">
							<div class="space"></div>
							<div class="btn-group">
								<?php if($status==1){
								echo $this->button(3,$id);}?>
							</div>
						</div>
						<div class="col-lg-6 pull-right">
						    <?php 
							foreach ($assethistory as $asthisrow):
								if (is_array($asthisrow) && !empty($asthisrow) && isset($asthisrow['his_custodian']) && isset($asthisrow['created'])):?>
									<div class="timeline-container">
										<div class="timeline-label">
											<span class="label label-success arrowed-in-right label-lg">
												<b><?php $dateTime = new DateTime($asthisrow['created']);
													$day = $dateTime->format('d'); // Day with leading zeros (01 to 31)
													$month = $dateTime->format('m'); // Month with leading zeros (01 to 12)
													$year = $dateTime->format('Y'); // Four-digit year (e.g., 2024)?>
												</b>
												Transfered on <?php echo $day.'/'.$month.'/'.$year;?>
											</span>
										</div>
										<div class="timeline-items">
											<div class="timeline-item clearfix">
												<div class="timeline-info">
													<i class="timeline-indicator ace-icon fa fa-leaf btn btn-success no-hover"></i>
												</div>
												<div class="widget-box transparent">
													<div class="widget-header widget-header-small">
														<h5 class="widget-title smaller"><i>from </i><strong><?php echo $this->employeeObj->getColumn($asthisrow['his_custodian'], 'full_name').' '.'</strong><i>Location</i>'.' <strong>'.$this->locationObj->getColumn($asthisrow['his_location'], 'location'); ?></strong></h5>
														<span class="widget-toolbar no-border">
															<i class="ace-icon fa fa-clock-o bigger-110"></i>
															<?php 
															    $dateTime = new DateTime($asthisrow['created']);
															    $time = $dateTime->format('h:i:s A');
																echo $time;?>
														</span>
														<span class="widget-toolbar">
															<a href="#" data-action="collapse">
																<i class="ace-icon fa fa-chevron-up"></i>
															</a>
														</span>
													</div>
													<div class="widget-body">
														<div class="widget-main">
															by <?php echo $this->userObj->getColumn($asthisrow['author'],'name');?>
														</div>
													</div>
												</div>
											</div>
										</div><!-- /.timeline-items -->
									</div><!-- /.timeline-container -->
									<?php 
								endif;
						    endforeach;?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script type="text/javascript">
	$('#print').genpdfinvoice3({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
</script>
