<?php
/**
 * 
 * View -- of Fleet/MsaterController/fuelAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('sales/post/partial.phtml', array('active' => 'postboxnumber')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Region</th>
					<th>Location</th>
					<th>Post Box Number</th>
					<th>Size</th>
					<th>status</th>
					<th class="no-sort">Action</th>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->pos as $row):
				?>
						<tr>
							<td><?php echo $i++; ?> </td> 
							<td><?php echo $this->regionObj->getColumn($row['region'],'region'); ?></td> 
							<td><?php echo $this->locationObj->getColumn($row['location'],'location'); ?></td> 
							<td><?php echo $row['po_number']; ?></td>                               
							<td><?php echo $this->posizeObj->getColumn($row['po_size'],'post_box_size'); ?></td>     
							 <td><?php echo $this->status($row['status']) ?></td>						
							<td><?php echo $this->button(1,$row['id'])?>                                                               
							</td>
						</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable();
});
</script>

