
<style>
  .highlighted-row {
    background-color: #daf0d3; /* Set your desired background color here */
  }
  
  
</style>
<?php
/**
 * 
 * View -- of Accounts/TransactionController/viewtransactionAction
 * 
 */
?>
	
<?php 
	foreach($this->postboxs as $row ):
		extract($row);
	endforeach;
//if($row['service'] != 7 AND $row['service'] != 12):?>
<div class="space"></div>
<div class="col-lg-12">

	<div class="widget-box transparent">
		<div class="widget-header widget-header-large">
			<h5 class="widget-title grey lighter">
			<i class="ace-icon fa fa-file-text-o fa-2x blue"></i>
			
			</h5>
			<div class="widget-toolbar hidden-xs">
				<?php //echo $this->button(2,$id);?>
			</div>
		</div>
		<div class="widget-body">
			<div class="widget-main padding-24">
				<div id="report-print">
				
                <div class="col-auto ms-auto no-print">
                    <div class="btn-list">
                        <span data-bs-toggle='tooltip' data-bs-placement='top' title='PDF Print'>
                            <a class='btn btn-primary btn-sm' id="print" style="border-radius:5px;">
                            <i class="fa fa-light fa-print"></i> PDF</a></span>
                    </div>
                
            

					<div class="row" id="convert-tb0">
						<div class="col-lg-9" id="convert-tb1">
						<h5 class="widget-title grey lighter">
							<i class="ace-icon fa fa-plane fa-2x purple"></i>
							<b>From Address</b>
						</h5>
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"><b></i>Name : </b> <?php echo $name;?>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-right blue"><b></i>post-box no. : </b> <?php echo $postbox_no;?>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-right blue"><b></i>post_box_size : </b> <?php echo $post_box_size;?>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-right blue"><b></i>renewal year: </b> <?php echo $renewal_year;?>
								</li>
                                <li>
									<i class="ace-icon fa fa-caret-right blue"><b></i>renewal amount: </b> <?php echo $renewal_amount;?>
								</li>
							</ul>
						</div>
						

<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>




// function onClick(element) {
//   document.getElementById("modal01").style.display = "block";
// }
  // Add the 'highlighted-row' class to odd rows using JavaScript
  var rows = document.querySelectorAll('tbody tr');
  for (var i = 0; i < rows.length; i++) {
    if (i % 2 === 0) {
      rows[i].classList.add('highlighted-row');
    }
  }
</script>