<?php

/**
 * View -- of Hr/MasterController/apptypeAction
 */
$this->headTitle($this->title);
?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2); ?>
		</div>
	</div>
	<div class="table-responsive">
		<table class="table card-table text-nowrap" id="dataTables">
			<thead>
				<tr>
					<th>#</th>
					<th>Post Box No</th>
					<th>Registration Year</th>
					<th>Name</th>
					<th>Status</th>
					<th class="no-sort no-printpdf">Action</th>
				</tr>
			</thead>
			<tbody>
				
				<?php
				$i = 1;
				foreach ($postboxs as $postboxs): ?>
					<tr  data-href="<?php echo $this->url('postbox', array('action' => 'viewrenew', 'id' => $postboxs['id'])); ?>">
						<td><?php echo $i++; ?></td>
						<td><?php echo $postboxs['postbox_no'] ?></td>
						<td><?php echo $postboxs['registration_date'] ?></td>
						<td><?php echo $postboxs['name'] ?></td>
						<td><?php echo $this->status($postboxs['status']); ?></td>
						<td class="action">
							<!-- <div class="btn-group">
								<a class="btn btn-xs btn-primary" href="<?php echo $this->url('postbox', array('action' => 'viewreg', 'id' => $postboxs['id'])); ?>" title="View">
								<i class="fa fa-eye"></i>
								</a>
							</div> -->
						</td>
					</tr>
				<?php endforeach; ?>
				
			</tbody>
			
		</table>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content"></div>
	</div>
</div>
<script>
$('document').ready(function () {
	$('#dataTables').DataTable({ "paging": true });

	// Handle row click event
	$(".clickable-row").click(function() {
		window.location = $(this).data("href");
	});
});
</script>
