<?php
/**
 * 
 * View -- of Purchase/PurchaseController/viewporder
 * 
 */
?>
<?php 

	foreach($this->postboxs as $postboxs ):
		extract($postboxs);
endforeach;
?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<form method="post" action="<?php echo $this->url('postbox', array('action' => 'viewreg')); ?>" >
				<div class="widget-header">
					<h5 class="widget-title lighter smaller">
						# View Postbox registration: 
						
					</h5>  

					<div class="widget-toolbar hidden-xs">
						<div class="btn-group">
							<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "29-".$id)); ?>" title="View Activity Logs">
								<i class="ace-icon fa fa-plus bigger-120" ></i>  
							</a> 
							<a class="btn btn-xs" id="print" title="Print">
								<i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
							</a>
						</div>
					</div>
				</div>
                
				<div class="widget-body">
					<div class="widget-main padding-12">
						<div id="report-print">
                            
                           
							<div class="row" id="convert-tb0">
								<div class="col-lg-8" id="convert-tb1">
									<ul class="list-unstyled spaced">
										<li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b>Region: <?php echo $this->regionObj->getcolumn($region, 'region');?></b>&nbsp;
										</li>
										
										<li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b>Location :  </b>
											<?php echo $this->locationObj->getColumn($location,'location'); ?>
										</li>
										<li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b>PostBox_No : </b><?php echo $postbox_no; ?>
										</li>
										<li>
											<i class="ace-icon fa fa-caret-right blue"></i>
                                            <b>Registration date: <?php echo $this->dateformat($registration_date); ?> 

										</li>
                                        <li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b> Name : </b> <?php echo $name; ?>
										</li>
                                        <li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b> CID : </b> <?php echo $cid; ?>
										</li>
                                        <li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b> Mobile Number : </b> <?php echo $mobile; ?>
										</li>
									</ul>
								</div>
								<div class="col-lg-4" id="convert-tb2">
									<ul class="list-unstyled spaced">
                                   
                                        <li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b> Telephone : </b> <?php echo $tphone; ?>
										</li>
                                        <li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b> Email : </b> <?php echo $email; ?>
										</li>
										<li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b>Name of organisation : </b><?php echo $organizationName; ?> 
										</li>
										<li>
											<i class="ace-icon fa fa-caret-right blue"></i>
											<b>Building_no : </b><?php echo $buildingNo; ?> 
										</li>
										
									
							
			</form>
		</div>
	</div>
</div>
<script type="text/javascript">
	
	$('#cm_btn').on('click',function(){
		window.document.location = "<?php echo $this->url('pol', array('action' => 'addpol'));?>";
	});
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
</script>
