<?php
/**
 * 
 * View -- of Purchase/PurchaseController/editpreceiptAction
 * 
 */
 $this->headTitle($this->title);
?>
<?php 
  foreach($this->purchase_receipt as $pur_receipt):
	  extract($pur_receipt);
	  $pr_id = $id;
	  $sel_activity = $cost_center_id;
	  $sel_group = $item_group_id;
	  $sel_location = $location_id;
  endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-pencil"></i>&nbsp;&nbsp;&nbsp; Edit PRN : &nbsp;<strong><?php echo $purchase_receipt_no; ?> | <?php echo $supplier; ?> | <?php echo $activity ?>|<?php echo $item_group; ?></strong>&nbsp;
					<?php $this->status($status);?>
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<form id="#form" method="post" action="<?php echo $this->url('inpurreceipt', array('action' => 'editreceipt', 'id' => $pr_id)); ?>"  enctype="multipart/form-data" >    
						 <div class="row">	
						 <input type="hidden" name="id" id="id" value="<?php echo $pr_id; ?>">
						 <input type="hidden" name="purchase_receipt_no" id="purchase_receipt_no" value="<?php echo $purchase_receipt_no; ?>"> 
							<div class="col-lg-3">    
								<div class="form-group">
									<label for="purchase_receipt_date" class="control-label">Purchase Receipt Date</label>
									<div class="date input-group" id="purchase_receipt_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $purchase_receipt_date; ?>" name="purchase_receipt_date" id="purchase_receipt_date" type="text" placeholder="PRN Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>	
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="activity" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required>
									    <option value=""></option>
									    <?php foreach ($regions as $region): ?>
										<optgroup label="<?php echo $region['region'];?>">
											<?php  
												$locations = $locationObj->get(array('l.region'=>$region['id']));
												 foreach ($locations as $location):
												 $selected = ($location['id'] == $sel_location)?"selected":"";
											?>
											 <option value="<?php echo $location['id']; ?>" <?php echo $selected;?>>
												<?php echo $location['location']; ?>
											 </option>
											<?php 
											 endforeach;
											?>
									    </optgroup>
									    <?php endforeach;  ?>									
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="item_group" class="control-label">Item Group</label>
									<select id="item_group" name="item_group" class="form-control" data-placeholder="Select" readonly="readonly" required>
										<option value=""></option>
										<?php foreach ($this->groupObj->getAll() as $group):
										    $slted = ($group['id'] == $item_group_id)?"selected":"";?>
											<option value="<?php echo $group['id'];?>"<?php echo $slted;?>><?php echo $group['name']; ?></option>
										<?php endforeach; ?>								
									</select> 
								</div>
							</div>
							<div class="col-lg-3"> 
								<div class="form-group">
									<label for="cost_center" class="control-label">Cost Center</label>
									<select class="form-control" name="cost_center" id="cost_center" data-placeholder="Select" readonly="readonly" required>
										<option value=""></option>
									<?php foreach($this->activities as $activity):
										$selected=($activity['id']==$activity_id)?'selected':'';?>
											<option value="<?php echo $activity['id'];?>" <?php echo $selected;?>>
										   		<?php echo $activity['activity']; ?>
										   	</option>
										<?php endforeach; ?>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
						    <div class="col-lg-3"> 
								<div class="form-group">
									<label for="supplier" class="control-label">Supplier</label>
									<input type="text" class="form-control" name="supplier" id="supplier" value ="<?php echo $supplier?>" placeholder="Enter supplier"/> 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="custom_declaration" class="control-label">Custom Declaration</label>
									<input type="text" class="form-control" value="<?php echo $custom_declaration; ?>" name="custom_declaration" id="custom_declaration" placeholder="Custom Declaration"> 
								</div>
							</div> 
							<div class="col-lg-3">
								<div class="form-group">
									<label for="challan_no" class="control-label">Challan No.</label>
									<input type="text" class="form-control" value="<?php echo $challan_no;?>" name="challan_no" id="challan_no" placeholder="Challan no." > 
								</div>
							</div>
							<div class="col-lg-3">
								<div class="form-group">
									<label for="invoice_no" class="control-label">Invoice No.</label>
									<input type="text" class="form-control" value="<?php echo $invoice_no;?>" name="invoice_no" id="invoice_no" placeholder="Invoice no." > 
								</div>
							</div>	     				
						</div>
						<div class = "row">
						    <div class="col-lg-3">
								<div class="form-group">
									<label for="challan_date" class="control-label">Challan Date</label>
									<div class="date input-group" id="challan_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" value="<?php echo $challan_date;?>" name="challan_date" id="challan_date" type="text" placeholder="Challan Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
						    <div class="col-lg-3">
								<div class="form-group">
									<label for="purchase_order_no" class="control-label">Purchase order No.</label>
									<select class="form-control" name="purchase_order_no" id="purchase_order_no" data-placeholder="Select" readonly>
										<option value=""></option>
										<option value="<?php echo $purchase_order;?>" selected="selected">
											<?php echo $this->pur_ordersObj->getColumn($purchase_order, 'purchase_order_no');?>
										</option>	
									</select> 
								</div>
							</div> 
						</div>
						<div class="row">
						   <div class="col-lg-12"> 
							  <h5>Purchase Receipt Details</h5>
								 <div>
									<table id="trdetails_table" class="table small-padding">
										<thead>
											<tr>
												<th>Item</th>
												<th>UOM</th>
												<th>PO Qty</th>
												<th>Qty Rate</th>
												<th>Challan Qty</th>
												<th>Damage Qty</th>
												<th>Shortage Qty</th>
												<th>Accepted Qty</th>
												<th>Sound Qty</th>
												<th></th>
											</tr>
										</thead>
										<tbody>
										<?php 
										$i = 1;
										foreach ($this->pr_details as $pr_detail):?>
											<tr>
												<td>
													<div class="form-group">
														<select id="item" name="item[]" class="form-control" data-placeholder="Select" >
															<option value=""></option>		
															<?php
															$items = $this->itemObj->getItem($purchase_order);
															 foreach ($items as $item):
																$selected = ($item['id']==$pr_detail['item_id'])?"selected":"";
															  ?>
																 <option value="<?php echo $item['id']; ?>" <?php echo $selected;?>>
																	<?php echo $item['code']; ?>
																 </option>
															 <?php endforeach; ?>															
														</select>
														<input type="hidden" name="details_id[]" id="details_id" value="<?php echo $pr_detail['id'];?>">
														<input type="hidden" name="po_details_id[]" id="po_details_id" value="<?php echo $pr_detail['po_details_id']; ?>"/>
													</div>
												</td>
												<td>
												    <div class="form-group">
														<select class="form-control" name="uom[]" id="uom" data-placeholder="Select" required>
														    <?php
															    $unit = $this->itemObj->getColumn($pr_detail['item_id'], 'uom');
																$unit_code = $this->uomObj->getColumn($unit, 'code');
																$selected_unit = ($unit==$pr_detail['uom_id'])?"selected":"";
															?>	
																<option value="<?php echo $unit; ?>" <?php echo $selected_unit;?>>
																	<?php echo $unit_code;?>
																</option>
														</select>
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="po_qty[]" id="po_qty" value="<?php echo $this->po_detailsObj->getColumn($pr_detail['po_details_id'],'quantity');?>" readonly />
													    <input type="hidden" class="form-control" name="amount[]" id="amount" value="0.00" />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" name="rate[]" id="rate" value="<?php echo number_format($pr_detail['rate'], 2, '.', '');?>" readonly />
													</div>
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['challan_qauntity'];?>" name="challan_qty[]" id="challan_qty" required />
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['demage_quantity']; ?>" name="damage_qty[]" id="damage_qty" >
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['shortage_quantity']; ?>" name="shortage_qty[]" id="shortage_qty" >
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['accepted_quantity'];?>" name="accept_qty[]" id="accept_qty" readonly >
													</div>         
												</td>
												<td>
													<div class="form-group">
														<input type="text" class="form-control" value="<?php echo $pr_detail['sound_quantity'];?>" name="sound_qty[]" id="sound_qty" readonly >
													</div>         
												</td>
												<td></td>
												<?php endforeach;?>
											</tr>
									   </tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="row">    
							<div class="col-lg-12">
								<div class="col-lg-6"></div>
								<?php
								foreach($this->pur_details as $pur_detail):
								$total_payment_amt += $pur_detail['amount'];
								endforeach;?>
								<div class="form-group col-lg-3">
									<label for="net_po_amount" class="control-label">Net PO Amount</label>
									<input type="text" class="form-control" name="net_po_amount" id="net_po_amount" value="<?php echo $total_payment_amt;?>" readonly required>
								</div>
								<div class="form-group col-lg-3">
									<label for="payable_amount" class="control-label">Payable Amount</label>
									<input type="text" class="form-control" name="payable_amount" id="payable_amount" value="<?php echo $payment_amt;?>" readonly required>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"><?php echo $note;?></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('inpurreceipt', array('action' => 'viewreceipt', 'id'=> $pr_id));?>'" ><i class="fa fa-times"></i> Cancel </button> 					
							</div>
						</div>
					</form>     
				</div>
	        </div>   
        </div>
    </div>   
</div>	
<script type="text/javascript">
$(function() {
	$('form select').chosen({ allow_single_deselect:true});
	$('#purchase_receipt_date').datepicker();
	$('#challan_date').datepicker();
	$('#purchase_receipt_date').on('changeDate',function(){
	  $('form').formValidation('revalidateField', $(this).attr('id'));
	});

	$('#challan_date').on('changeDate',function(){
	  $('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#trdetails_table').inreceipt({
		getpodetail:"<?php echo $this->url('inpurreceipt', array('action'=>'getpodetail'));?>",
	});
});
/******** formValidation *************/
const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			prn_date: {
				validators: {
					notEmpty: {
						message: 'Please select voucher date'
					}
				}
			},

			location: {
				validators: {
					notEmpty: {
						message: 'Please select location'
					}
				}
			},
			activity: {
				validators: {
					notEmpty: {
						message: 'Please select activity'
					}
				}
			},
			supplier: {
				validators: {
					notEmpty: {
						message: 'Please select supplier'
					}
				}
			},
			challan_no: {
				validators: {
					notEmpty: {
						message: 'Please provide challan no.'
					}
				}
			},  
			challan_date:{
				validators: {
					notEmpty:{
						message: 'Please select challan date'
					},
				}
			}, 
			po_no:{
				validators: {
					notEmpty:{
						message: 'Please select PO No.'
					},
				}
			},      
			item[]:{
				validators: {
					notEmpty:{
						message: 'Please select item'
					},
				}
			},  
			uom[]:{
				validators: {
					notEmpty:{
						message: 'Please select uom'
					},
				}
			}, 
			po_qty[]:{
				validators: {
					notEmpty:{
						message: 'Please provide PO Qty'
					},
				}
			},  
			challan_qty[]:{
				validators: {
					notEmpty:{
						message: 'Please provide challan_qty'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
</script>