<?php
/**
 * View -- of Store/ReceiptController/indexAction
 */
 $this->headTitle($this->title);
?>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="row">
	<div class="col-lg-12">
		<div class="row">
			<form method="post" action="<?php echo $this->url('inpurreceipt'); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-2">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['month'] == '-1')?'selected':'';?>>All</option>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="item_group">Item Group</label>
					<select class="form-control" id="item_group" name="item_group" data-placeholder="cost center" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['item_group'] == '-1')?'selected':'';?>>All</option>
						<?php 
							$groups = $this->groupObj->getAll();
							foreach($groups as $group):
								$selected_group = ($group['id'] == $data['item_group'])?'selected':'';
						?>
							<option value="<?php echo $group['id']?>" <?php echo $selected_group;?>>
								<?php echo $group['code'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Purchase Receipt" href="<?php echo $this->url('inpurreceipt', array('action'=>'addreceipt'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add PR</span></span>
					</a>
				</div>
			</div>
		</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>PRN No.</th>
						<th>PRN Date</th>
						<th>PRN Amount</th>
						<th>Challan No.</th>
						<th>PO No.</th>
						<th class="no-sort no-printpdf">Actions</th>
					</tr>
				</thead>
				<tbody>
					<?php $sl = 1;?>
					<?php foreach($this->receipts_results as $row):?>
						<tr class="tr-clickable" data-href="<?php echo $this->url('inpurreceipt', array('action'=>'viewreceipt', 'id'=>$row['id']));?>">
							<td><?php echo $sl++;?></td>
							<td>
								<b><?php echo $row['purchase_receipt_no'];?></b>&nbsp;&nbsp;&nbsp;
								<i>
									<?php echo $row['supplier'];?>&nbsp;
									<span class="label label-danger"> 
										<?php echo $this->groupObj->getColumn($row['item_group'],'name'); ?> &nbsp;&nbsp;&nbsp;
									</span>
									 <span class="label label-info"> 
										<?php echo $this->activityObj->getColumn($row['cost_center'],'activity'); ?> &nbsp;&nbsp;&nbsp;
									 </span>
								</i>
								&nbsp;<?php $this->status($row['status']);?>
								<?php if($row['payment_status'] == 1):?>
									<span class="badge badge-danger pull-right"> 
										paid  
									</span>
								<?php endif;?>
							</td>
							<td><?php echo $row['purchase_receipt_date'];?></td>
							<td><?php echo $row['payment_amt'];?></td>
							<td><?php echo $row['challan_no'];?></td>
							<td><?php echo $this->poObj->getColumn($row['purchase_order'],'purchase_order_no')?></td>
							<td class="action">
								<div class="btn-group">
									<a data-toggle="modal" data-target = "#modal" class="btn btn-xs btn-danger" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "2-".$row['id'])); ?>" title="View Activity Logs">
										<i class="ace-icon fa fa-plus bigger-120" ></i>  
							  		</a>
							  	</div>
							</td>	
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
	$('document').ready(function(){
		$('#dataTables').DataTable({"paging":   true,});
	});
</script>
