<?php
/**
 *  
 * View -- of Sales/MasterController/creditceilingAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('/sales/master/partial.phtml', array('active' => 'creditceiling')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
		<table class="table table-striped table-bordered table-hover" id="dataTables" >
			<thead>
				<tr>
					<th>#</th>	
					<th>Customer</th>							
					<th>Credit Ceiling</th>
					<?php if($this->button(1)!=""):?>
						<th class="no-sort no-printpdf">Action</th>
					<?php endif;?>
				</tr>
			</thead>
			<tbody>
				<?php
					$i = 1; 
					foreach ($this->creditceilings as $creditceiling):
						$ceiling_id = $creditceiling['id'];?>
					<tr>
						<td><?php echo $i++;?></td>
						<td><b><?php echo $creditceiling['name'];?></b></td>
						<td>
							<?php $checked = ($creditceiling['credit_ceiling'] == 0 || $creditceiling['credit_ceiling'] == "")? '':'checked';?>
							<div class="checkbox">
								<label>
									<input name="form-field-checkbox" data-id="<?php echo $creditceiling['id'];?>" type="checkbox" class="ace" <?php echo $checked;?> />
									<span class="lbl"></span>
								</label>
							</div>
						</td>
						<?php echo $this->button(1, $creditceiling['id']);?>
					</tr>
				<?php endforeach;?>
			</tbody>
		</table>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
$('input[type=checkbox]').each(function(){
	$(this).bind('change',function(){
		var element = $(this);
		var data_id = element.attr('data-id');
		var data_check = (element.prop('checked'))? 1:0;
		//alert(data_check);
		$.post("<?php echo $this->url('slmaster', array('action'=>'updateceiling'));?>",{id:data_id, check:data_check}, function(data){
			//console.log(data);
			if(data !=1){
				if(data_check ==1){
					element.removeAttr('checked');
				}else{
					element.attr('checked');
				}
			}else{
				if(data_check ==1){
					element.attr('checked');
				}else{
					element.removeAttr('checked');
				}
			}
		});
	});
});
</script>

