<?php
/**
 * 
 * View -- of Sales/MasterController/schemetypeAction
 * 
 */
$this->headTitle($this->title);
?>
<?php echo $this->partial('sales/master/partial.phtml', array('active' => 'creditauthoritys')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Authority</th>
						<th>Approval Limit</th>
						<th>Condition</th>
						<th>Remarks</th>
						<?php if($this->button(1)!=""):?>
							<th class="no-sort no-printpdf">Action</th>
						<?php endif;?>
					</tr>
				</thead>
				<tbody>
					<?php
						$i = 1; 
						foreach ($this->creditauthoritys as $creditauthority):
							$condition = $creditauthority['condition'];
					?>
							<tr>
								<td><?php echo $i++; ?> </td>
								<td><?php echo $creditauthority['authority'];?></td>
								<b><?php if($condition == '1'):?>
										<td><?php echo "<= ".$creditauthority['approval_limit'];?> </td>
										<td><?php echo "Less than equal";?></td><?php
									else:?>
										<td><?php echo ">".$creditauthority['approval_limit'];?></td>
										<td><?php echo "More than";?></td>
									<?php endif;?></b>	
								<td><?php echo $creditauthority['remark'];?></td>
								<td><?php echo $this->button(1, $creditauthority['id']);?></td>
							</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
