<?php
/**
 * 
 * View -- of Sales/MasterController/schemetypeAction
 * 
 */
$this->headTitle($this->title);
?>
<?php echo $this->partial('sales/master/partial.phtml', array('active' => 'schemetypes')); ?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
			<?php echo $this->button(2);?>
		</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Scheme Type</th>
						<th>Description</th>
						<th>Type</th>
						<?php if($this->button(1)!=""):?>
							<th class="no-sort no-printpdf">Action</th>
						<?php endif;?>
					</tr>
				</thead>
				<tbody>
					<?php
						$i = 1; 
						foreach ($this->schemetypes as $schemetype):
					?>
							<tr>
								<td><?php echo $i++; ?> </td>
								<td><b><?php echo $schemetype['scheme_type'];?></b></td>
								<td><b><?php echo $schemetype['description'];?></b></td>
								<td><b><?php if($schemetype['type']=='0'):
									echo "Actual Qty";
									else: echo "Rate"; endif;?></b></td>
								<?php echo $this->button(1, $schemetype['id']);?>
							</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#dataTables').genpdftable({
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>
