<?php
/**
 * 
 * View -- of Sales/MasterController/schemetypeAction
 * 
 */
$this->headTitle($this->title);
?>
<?php echo $this->partial('sales/master/partial.phtml', array('active' => 'schemetypes')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Scheme Type</th>
						<th>Description</th>
						<th>Type</th>
						<?php if($this->button(1)!=""):?>
							<th class="no-sort no-printpdf">Action</th>
						<?php endif;?>
					</tr>
				</thead>
				<tbody>
					<?php
						$i = 1; 
						foreach ($this->schemetypes as $schemetype):
					?>
							<tr>
								<td><?php echo $i++; ?> </td>
								<td><b><?php echo $schemetype['scheme_type'];?></b></td>
								<td><b><?php echo $schemetype['description'];?></b></td>
								<td><b><?php if($schemetype['type']=='0'):
									echo "Actual Qty";
									elseif($schemetype['type'] == 1):
									echo "Rate";
									else:
									echo "Actual Slab";
									endif;?></b></td>
								<td><?php echo $this->button(1, $schemetype['id']);?></td>
							</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
