<?php
/**
 * View -- of Purchase/PaymentController/indexAction
 */
$this->headTitle($this->title);
?>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="card">
	<div class="card-header">
		<div class="row">
			<form method="post" action="<?php echo $this->url('billing'); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Supplier Payment" href="<?php echo $this->url('billing', array('action'=>'addbill'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Bill</span></span>
					</a>
				</div>
			</div>
		</div>
		<div class="row">
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Payment No.</th>
						<th>Payment Date</th>
						<th>Payment Amount(<?php //echo $this->currency_code();?>)</th>
						<th class="no-sort no-printpdf">Action</th>
					</tr>
				</thead>
				<tbody>
					<?php $sl = 1;?>
					<?php foreach($this->payments as $row):?>
					
						<tr data-href="<?php echo $this->url('billing', array('action'=>'viewbilling', 'id'=>$row['id']));?>">
							<td><?php echo $sl++;?></td>
							<td>
								<b><?php echo $row['bill_no'];?></b> &nbsp;&nbsp;&nbsp;
								<i>	 
									<?php  echo $this->partyObj->getColumn($row['supplier'],'name');   ?> &nbsp;&nbsp;&nbsp;
									
								</i>        
								&nbsp;<?php $this->status($row['status']);?>
							</td>
							<td><?php echo $row['billing_date'];?></td>
							<td><?php echo $row['net_amount']; ?></td>
							<td class="action">
								<div class="btn-group">
									<?php echo $this->button(1,$row['id']); if($userID==1 || $userID==121):?>
										<a href="<?php echo $this->url('billing',array('action'=>'deletebill','id'=>$row['id']))?>" class="btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
										<?php endif;?>
						  		</div>
							</td>									
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>	
 $('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
