<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"> <i class="fa fa-asterisk"></i> Action </h4>
</div>  <!-- /modal-header -->

<div class="modal-body">
	<div class="panel panel-default">
		<div class="panel-body">      
		<?php   
		    $variables = explode('-', $this->id);
			$applicationID = $variables['0'];
			$action = $variables['1'];
			if($action == '1') { $button = "Send Bill"; $label = "info"; }elseif($action=="2"){ $button = "Check Bill"; $label="success"; }
			elseif($action=="3"){ $button = "Approve Bill"; $label="success"; }
			elseif($action=="4"){ $button = "Cancel Bill"; $label="danger"; }
			?>
	    <form id="#form" method="post" action="<?php echo $this->url('billing', array('action' => 'processbill')); ?>">	
		<input type="hidden" value="<?php echo $action; ?>" name="action">
		<input type="hidden" value="<?php echo $applicationID; ?>" name="bill_id">
		<div class="form-group">
			<label for="remarks" class="control-label">Remarks</label>
			<textarea class="form-control" rows="3" name="remarks" required>
			</textarea>
		</div>
		<div class="form-group">
		   <input type="submit" value="<?php echo $button; ?>" class="btn btn-<?php echo $label;?>">
		</div>
	    </form>
	  </div>
	</div>	
</div>
<script>
$('#reporting_date').datepicker();
$('document').ready(function(){
	$('form select').chosen({ allow_single_deselect: true });
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			remarks: {
				validators: {
					notEmpty: {
						message: 'Please provide remarks.'
					}
				}
			},
			routing: {
				validators: {
					notEmpty: {
						message: 'Please select person to route.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
