<?php
/**
 * 
 * View -- of Purchase/PurchaseController/viewporder
 * 
 */
?>
<?php foreach($payment as $sup_pay):
		extract($sup_pay);
		$payment_id = $id;
		$pay_status = $status;
		$pay_author = $author;
		//echo "<pre>";print_r($sup_pay);exit;
     endforeach;?>
<style>
	.mytable tr th,.mytable tr td {
		padding:5px;
	}
</style>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					#Payment Detail:<strong> &nbsp;&nbsp;<?php echo $bill_no; ?> </strong>&nbsp;
					<?php $this->status($status);?>
				</h5>
				<div class="widget-toolbar hidden-xs">
					<a style='cursor:pointer' id="print">
						<i class="ace-icon fa fa-file-pdf-o red"></i>
					</a>
				</div>	
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Bill No : <b class="red"><?php echo $bill_no; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Location : <b class="red"><?php echo $this->locationObj->getColumn($location,'location'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Supplier : <b class="red"> <?php echo $this->partyObj->getColumn($supplier,'name'); ?></b>
									</li>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Reference No : <b class="red"><?php echo $ref_no;?> </b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Billing Date : <b class="red"><?php echo $billing_date; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Purchase Receipt No : <b class="red"><?php echo $this->prObj->getColumn($prn_no,'prn_no');?> </b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Net amount : <b class="red"><?php echo $net_amount;?> </b>
									
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>Note: <b class="red"><?php echo $note;?> </b>
									</li>
								</ul>
							</div>
						</div>
						<div class="space-6"></div>
						<div class="row">
							<div class="col-lg-12" >
								<table class="table" style="border-top:2px solid #ddd;">
									<thead>
										<tr>
											<th>Receipt Amount</th>
											<th>Discount</th>
											<th>Net Amount</th>
										
										</tr>
									</thead>
									<tbody>
										<tr>
											<td><?php echo $receipt_amt;?></td>
											<td><?php echo $discount?></td>
											<td><?php echo $net_amount?></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-3">
							<label class="control-label" for="freight_party">Freight Party: </label>
							<input class="form-control" name="freight_party" id="freight_party" value="<?php if($freight_party==-1){echo "";}else{echo $this->partyObj->getColumn($freight_party,'name');}?>" readonly>
						</div>
						<div class="col-lg-3">
							<label class="control-label" for="freight">Amount: </label>
							<input class="form-control" name="freight" id="freight" value="<?php echo $freight;?>" readonly>
						</div>
						<div class="col-lg-3">
							<label class="control-label" for="freight_ref">Reference No: </label>
							<input class="form-control" name="freight_ref" id="freight_ref" value="<?php echo $freight_ref;?>" readonly>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-3">
							<label class="control-label" for="tax_party">Tax Party: </label>
							<input class="form-control" name="tax_party" id="tax_party" value="<?php if($tax_party==-1){echo "";}else{echo $this->partyObj->getColumn($tax_party,'name');}?>" readonly>
						</div>
						<div class="col-lg-3">
							<label class="control-label" for="tax">Amount: </label>
							<input class="form-control" name="tax" id="tax" value="<?php echo $tax;?>" readonly>
						</div>
						<div class="col-lg-3">
							<label class="control-label" for="tax_ref">Reference No: </label>
							<input class="form-control" name="tax_ref" id="tax_ref" value="<?php echo $tax_ref;?>" readonly>
						</div>
					</div>
					<br><br>
					<div class="row">
						<div class="col-lg-6"></div>
						<div class="col-lg-3">
							<label class="control-label" for="gross">Total: </label>
							<input class="form-control" name="gross" id="gross" value="<?php echo $total;?>" readonly>
						</div>
					</div>
					<br>
					<div class="row">
						<div class="col-lg-12" style="text-align: right">		
							<?php $role = $this->userTable->getColumn($userID,'role');?>
							<?php if($status == '2' &&  $user_locs == $location && $role==2):?>
									<a href="<?php echo $this->url('billing', array('action'=>'editbill', 'id'=>$id));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
									<a data-toggle="modal" data-target="#modal" href="<?php echo $this->url('billing', array('action'=>'processbill', 'id'=>$id.'-1'));?>" class="btn btn-success">
									  <i class="fa fa-check-square-o"></i> Send Bill
									</a>
							<?php endif;?>
						</div>	
						<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
							<div class="modal-dialog">
								<div class="modal-content"> </div>
							</div>
						</div>						
					</div>	
					 <!-- Upload and Download file attachments -->			
					 <?php   
					   echo $this->partial('partial/attachment.phtml', array('process' => '703', 'process_id'=> $bill_no , 'status' => $status));
					?>					
				    <!-- End of attachment -->
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	/*$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});*/
</script>
