<?php
/**
* 
* View -- of Accounts/ChartaccountController/editheadAction
* 
*/
?>
<?php 
  foreach($this->head as $head):
    extract($head);
  endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('chartaccount', array('action' => 'edithead', 'id' => $id)); ?>"  enctype="multipart/form-data" >                              
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Head</h4>
	</div>  <!-- /modal-header -->    
	<div class="modal-body">  
		<div class="panel panel-default">                       
			<div class="panel-body">
			    <div class="row">
					<div class="col-lg-12"> 
						<div class="form-group">
							<label for="code" class="control-label">Code</label>
							<input type="text" class="form-control" name="code" id="code" value="<?php echo $code;?>" size="30" required > 
						</div>  

						<div class="form-group">
							<label for="name" class="control-label">Name</label>
							<input type="text" class="form-control" name="name" id="name" value="<?php echo $name;?>" size="30" required > 
						</div>  

						<div class="form-group">
							<label for="group" class="control-label">Group</label>
							<select id="group" name="group" class="form-control" data-placeholder="Group" required >
								<option value=""></option>
								<?php 
								foreach ($this->group as $group):
									$selected = ($group_id==$group['id'])?"selected":"";
								?>
									<option value="<?php echo $group['id'];?>" <?php echo $selected;?>>
									<?php echo $group['name']; ?>
									</option>
								<?php 
								endforeach;
								?>
							</select>
						</div>
						<div class="form-group">
							<label for="head_type" class="control-label">Head Type</label>
							<select id="head_type" name="head_type" class="form-control" data-placeholder="Head Type" required >
								<option value=""></option>
								<?php 
								foreach ($this->headtype as $headtype):
									$selected = ($headtype_id==$headtype['id'])?"selected":"";
								?>
									<option value="<?php echo $headtype['id'];?>" <?php echo $selected;?>>
										<?php echo $headtype['head_type']; ?>
									</option>
								<?php 
								endforeach;
								?>
							</select>
						</div>
					</div>
				</div>
		    </div>  
	    </div>   
	</div>                        
	<div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
	</div> 
</form> 
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			code: {
				validators: {
					notEmpty: {
						message: 'Please provide code.'
					}
				}
			},
			name: {
				validators: {
					notEmpty: {
						message: 'Please provide Name .'
					}
				}
			},
			group: {
				validators: {
					notEmpty: {
						message: 'Please select Group.'
					}
				}
			},
			headtype: {
				validators: {
					notEmpty: {
						message: 'Please select Head Type.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>