<?php
/**
 * 
 * View -- of Accounts/ChartaccountController/editheadtypeAction
 * 
 */
?>
<?php 
    foreach($this->headtype as $headtype):
        extract($headtype);        
    endforeach;
?>

<form id="#form" method="post" action="<?php echo $this->url('chartaccount', array('action' => 'editheadtype', 'id' => $id)); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Head type</h4>
    </div>  <!-- /modal-header -->
    
    <div class="modal-body">       
      <div class="panel panel-default">                       
        <div class="panel-body"> 
			<div class="row">
				<div class="col-lg-12"> 
					<div class="form-group">
						<label for="head_type" class="control-label">Head Type</label>
						<input type="text" class="form-control" name="head_type" id="head_type" value="<?php echo $head_type;?>" size="30" required > 
					</div>
					<div class="form-group">
						<label for="group" class="control-label">Group</label>
						<select class="form-control" name="group" id="group" data-placeholder="Select Group" required>
							<option value=""></option>
							<?php foreach ($this->groups as $groupRow): ?>
								<option value="<?php echo $groupRow['id']; ?>" <?php echo ($group == $groupRow['id']) ? 'selected' : ''; ?>><?php echo $this->escapeHtml($groupRow['name']); ?></option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>    
			</div>           
        </div>
      </div>
    </div>
  </div> <!-- /modal-body -->    
  <div class="modal-footer">
      <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
      <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
  </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			group: {
				validators: {
					notEmpty: {
						message: 'Please select Group.'
					}
				}
			},
			head_type: {
				validators: {
					notEmpty: {
						message: 'Please provide Head Type.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
</script>