<?php
	/**
	 * Add Bank Reconcilation
	**/
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-plus"></i>&nbsp;Bank Reconcilation &nbsp;&nbsp;
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form method="post" action="<?php echo $this->url('report', array('action' => 'addreconcilation')); ?>"  enctype="multipart/form-data" >    
						<div class="row">
							<div class="form-group col-lg-3">
								<label for="Head" class="control-label">Bank | Head</label>
								<select id="head" name="head" class="form-control" data-placeholder="Select" required>
									<option value=""></option>	
									<?php foreach($this->headObj->get(array('ht.id' =>11)) as $headRow): ?>
									  <option value="<?php echo $headRow['id'];?>"><?php echo $headRow['name']; ?></option>	
									<?php endforeach;  	?>
								</select> 
							</div> 							
						</div>					
						<div class="space-12"></div>
						<div id="row">
					         <div id="subheadlist"></div>	
					    </div>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12">
							   <button type="submit" class="btn btn-success" onClick="return confirm('Are you sure')"><i class="fa fa-save"></i> &nbsp; Reconcile</button>
							</div>
						</div>	
					</form>    
				</div> 
			</div>   
      	</div>
    </div>   
</div>	
<script type="text/javascript">  		
$("#head").change(function() {  
    var param = $(this).val(); 
    var subheadlist = $("#subheadlist");

    subheadlist.empty(); // Clear existing options before loading new ones

    subheadlist.load("<?php echo $this->url('report', array('action' => 'transactionlist')); ?>/"+ param, function() {
        subheadlist.trigger('chosen:updated');
    });
});
</script>