<?php
/**
 * 
 * View -- of Accounts/ReportController/trialbalanceAction
 * 
 */
 
//$head_id = $this->subheadObj->getColumn(30,'head');
//$group_id = $this->headObj->getColumn($head_id,'group');
//$class_id =$this->groupObj->getColumn($group_id,'class');
//echo '<pre>';print_r($class_id);exit;
?>
<?php echo $this->tabs_helper(array(684,691,685,686,687,688,689,690,699)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form data-toggle="validator" id="#form" method="post" action="<?php echo $this->url('report', array('action' => 'balancesheet')); ?>"  enctype="multipart/form-data" >    
					<div class="row"> 
                        <div class="form-group col-lg-12">
							<div class="alert alert-info">
							<strong>How to view Balance Sheet Report?</strong>
							<ol>
								<em class="text-success">
								<li>Choose the <strong>Tier</strong>,It is mendatory.</li>
								<li>Choose the <strong>Activity,Region and Location </strong>for specific parameter. By default it will take 'All'</li>
								<li><strong>Select Start Date:</strong> If there is no <strong>Transaction</strong> in the current year, then you must select the Previous year date</li>
								<li>Click <strong>Generate</strong> button</li></em>
							</ol>
							</div>
						</div>					
						<div class="form-group col-lg-2">
							<label for="tier" class="control-label">Tier</label>
							<select name="tier" id="tier" class="form-control" data-paceholder="Select">
								<option value=""></option>
								<?php 
									$st1 = ($data["tier"]==1)? 'selected':'';
									$st2 = ($data["tier"]==2)? 'selected':'';
									$st3 = ($data["tier"]==3)? 'selected':'';
									$st4 = ($data["tier"]==4)? 'selected':'';
								?>
								<option value="4" <?php echo $st4; ?> > Class </option>
								<option value="3" <?php echo $st3; ?>> Group </option>
								<option value="2" <?php echo $st2; ?>> Head </option>
								<option value="1" <?php echo $st1; ?>> Sub Head </option>
							</select>
						</div> 
						<div class="form-group col-lg-2">
							<label class="control-label" for="start_date">Start Date</label>
							<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
						<div class="form-group col-lg-2">
							<label class="control-label" for="end_date">End Date</label>
							<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div> 
						<div class="form-group col-lg-2">
							<label for="region" class="control-label">Region</label>
							<select class="form-control" name="region" id="region" data-paceholder="Select">
								<option value="-1">All</option>
								<?php foreach ($region as $reg):?>
								<?php $selected_reg = ($data["region"]==$reg['id'])? 'selected':'';?>
									<option value="<?php echo $reg['id'];?>" <?php echo $selected_reg;?>>
										<?php echo $reg['region']; ?>
									</option>
								<?php endforeach;?>									
							</select>
						</div>
						<div class="form-group col-lg-2">
							<label for="location" class="contol-label">Location</label>
							<select class="form-control" name="location" id="location" data-placeholder="Select" >
								<option value="-1">All</option>
								<?php if($data["region"]>0):
									foreach($this->locationObj->get(array('region'=> $data["region"])) as $locations):
								?>
									<?php $selected_loc = ($data["location"]==$locations['id'])? 'selected':'';?>
									<option value="<?php echo $locations['id'];?>" <?php echo $selected_loc;?> ><?php echo $locations['location'];?></option>
								<?php endforeach;
								endif;?>							
							</select>
						</div> 
					</div> 
					<div class="row">
						<div class="col-lg-12">
							<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
						</div>
					</div>			
				</form>
			</div>
		</div>
	</div>
</div>
<div class="hr hr-dotted"></div>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">	
		<div class="clearfix">
			<label> <i class="red fa fa-tags"></i> Activity: </label>  <span><?php echo $act = ($data["activity"] == -1)? "All Activities": $this->activityObj->getColumn($data["activity"], 'activity');?></span>
			<label>  <i class="blue fa fa-globe"></i> Region: </label> <span><?php echo $loc = ($data["region"] == -1)? "All Regions": $this->regionObj->getColumn($data["region"], 'region');?></span>
			<label>  <i class="orange fa fa-map-marker"></i> Location: </label> <span><?php echo $loc = ($data["location"] == -1)? "All Locations": $this->locationObj->getColumn($data["location"], 'location');?></span>
		</div>
		<div>
			<table class="table table-bordered table-striped table-condensed" id = "dataTables">
				<thead>
					<tr>
						<th rowspan="2">Particulars</th>
						<th> Present Year</th>
						<th> Previous Year </th>
					</tr>
					<?php if($data['tier'] > 0):
					?>
					<tr>
						<th> <?php echo "From"." ".$data['start_date']." "."to"." ".$data['end_date'];?> </th>
						<th> <?php $prevoius_start_year = date('y', strtotime($data['start_date'])) - 1;
						$prevoius_start_month = date('m', strtotime($data['start_date']));
						$prevoius_start_day = date('d', strtotime($data['start_date']));
						$pre_end_year = date('y', strtotime($data['end_date'])) - 1;
						$pre_end_month = date('m', strtotime($data['end_date']));
						$pre_end_day = date('d', strtotime($data['end_date']));
						$pre_starting_date = date('Y-m-d', strtotime($prevoius_start_year.'-'.$prevoius_start_month.'-'.$prevoius_start_day));
						$pre_ending_date = date('Y-m-d', strtotime($pre_end_year.'-'.$pre_end_month.'-'.$pre_end_day));
						echo "From"." ".$pre_starting_date." "."to"." ".$pre_ending_date;?> </th>
					</tr>
					<?php else: ?>
					<tr>
						<th> <?php echo "No Peroid Found";?></th>
						<th> <?php echo "No Peroid Found";?></th>
					</tr>
					<?php endif; ?>
				</thead>
				<tbody id="trial_balance">
					<?php if($data['tier'] <= 4):
					    $pre_starting_date='';
					    $pre_ending_date = '';
						foreach($this->classObj->getBalanceSheetClass($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date']) as $classrow): //class 
							$grand_pres_total = array();
							$grand_prev_total = array();?>
							<?php if($data['tier'] <= 4):?>
								<tr class="classrow">
									<td class="text-danger"><strong><?php echo $classrow['name'];?> </strong></td>
							<?php endif;?>
									<?php 
										$pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresBSCLASS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $classrow['id'], 4);	
										$prev_closing_balance = $this->transactiondetailObj->getClosingBalanceforPrevBS($data['activity'],$data['region'],$data['location'],$pre_starting_date,$pre_ending_date, $classrow['id'], 4);	
										$pres_closing_balance = ($pres_closing_balance < 0)? -$pres_closing_balance:$pres_closing_balance;
										$prev_closing_balance = ($prev_closing_balance < 0)? -$prev_closing_balance:$prev_closing_balance;
										$grand_pres_total[] = $pres_closing_balance;
										$grand_prev_total[] = $prev_closing_balance;
									?>
									<td></td>							
									<td></td>							
							<?php if($data['tier'] <= 4):?>
							    </tr>
							<?php endif;?>
								<?php 
								if($data['tier'] <= 3):
									foreach($this->groupObj->getTransactionGroupforBS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], array('class'=>$classrow['id'])) as $grouprow): 
										/*Finding Class(implement the asset liabilities formulae)*/
										#$head_id = $this->subheadObj->getColumn($subheadrow['id'],'head');
										#$group_id = $this->headObj->getColumn($headrow['id'],'group');
										$class_id =$this->groupObj->getColumn($grouprow['id'],'class');?>													
										<tr class="grouprow">
											<td class="text-success"><strong><?php echo $grouprow['name'];?></strong></td>
											<?php 
												$pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresBS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $grouprow['id'],$class_id,3);	
												$prev_closing_balance = $this->transactiondetailObj->getClosingBalanceforPrevBS($data['activity'],$data['region'],$data['location'],$pre_starting_date,$pre_ending_date, $grouprow['id'],$class_id, 3);	
												//$pres_closing_balance = ($pres_closing_balance < 0)? -$pres_closing_balance:$pres_closing_balance;
												//$prev_closing_balance = ($prev_closing_balance < 0)? -$prev_closing_balance:$prev_closing_balance;
											?>	
												<td class="text-success" style ="text-align:right"><strong><?php echo number_format($pres_closing_balance,2,'.',',');?></strong></td>
												<td class="text-success" style ="text-align:right"><strong><?php echo number_format($prev_closing_balance,2,'.',',');?></strong></td>
										</tr>
										<?php 
										if($data['tier'] <= 2):
											//foreach($this->headformatObj->get(array('group'=>$grouprow['id'])) as $htype):
											foreach($this->headObj->getTransactionHeadforBS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], array('group'=>$grouprow['id'])) as $headrow): 
											/*Finding Class(implement the asset liabilities formulae)*/
											#$head_id = $this->subheadObj->getColumn($subheadrow['id'],'head');
											$group_id = $this->headObj->getColumn($headrow['id'],'group');
											$class_id =$this->groupObj->getColumn($group_id,'class');?>													
												<?php 
												//if($data['tier'] == 2)://?>
												<tr class="headrow">
													<td class="text-secondary"><strong><?php echo $this->headObj->getColumn($headrow['id'],'name');?></strong></td>
													<?php 
														$pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresBS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $headrow['id'],$class_id, 2);
														$prev_closing_balance = $this->transactiondetailObj->getClosingBalanceforPrevBS($data['activity'],$data['region'],$data['location'],$pre_starting_date,$pre_ending_date, $headrow['id'], 2);
														//$pres_closing_balance = ($pres_closing_balance < 0)? -$pres_closing_balance:$pres_closing_balance;	
														//$prev_closing_balance = ($prev_closing_balance < 0)? -$prev_closing_balance:$prev_closing_balance;	
													?>	
														<td style ="text-align:right"><strong><?php echo number_format($pres_closing_balance,2,'.',',');?></strong></td>
														<td style ="text-align:right"><strong><?php echo number_format($prev_closing_balance,2,'.',',');?></strong></td>
												</tr>
												<?php 
												if($data['tier'] <= 1):
													foreach($this->subheadObj->getTransactionSubheadforBS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], array('head'=>$headrow['id'])) as $subheadrow): 
														/*Finding Class(implement the asset liabilities formulae)*/
														$head_id = $this->subheadObj->getColumn($subheadrow['id'],'head');
														$group_id = $this->headObj->getColumn($head_id,'group');
		                                                $class_id =$this->groupObj->getColumn($group_id,'class');?>															
														<tr class="subheadrow">
															<td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $subheadrow['code'].'-'.$subheadrow['name'];?></td>
															<?php 
																$pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresBS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $subheadrow['id'],$class_id,$data['tier']);	
																$prev_closing_balance = $this->transactiondetailObj->getClosingBalanceforPrevBS($data['activity'],$data['region'],$data['location'],$pre_starting_date,$pre_ending_date, $subheadrow['id'], 1);	
																//$pres_closing_balance = ($pres_closing_balance < 0)? -$pres_closing_balance:$pres_closing_balance;
																//$prev_closing_balance = ($prev_closing_balance < 0)? -$prev_closing_balance:$prev_closing_balance;
														?>	
															<td style ="text-align:right"><?php echo number_format($pres_closing_balance,2,'.',',');?></td>
															<td style ="text-align:right"><?php echo number_format($prev_closing_balance,2,'.',',');?></td>
														</tr>											
													<?php 
													endforeach;
												endif;
											endforeach;
										endif; 
									endforeach;
								endif; ?>
								<tr class="classrow">
										<td><strong> Total <?php echo $classrow['name'];?>: </strong></td>
									<?php foreach($grand_pres_total as $total):foreach($grand_prev_total as $total1):?>
										<td style ="text-align:right"><strong><?php echo number_format($total,3,'.',',');?></strong></td>
										<td style ="text-align:right"><strong><?php echo number_format($total1,2,'.',',');?></strong></td>
									<?php endforeach; endforeach; ?>
								</tr>
						<?php endforeach;
					endif;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$("#region").change(function() { 
		$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
			var newdata ="<option value='-1'>All</option>"+data
			$('#location').html( newdata );
			$("#location").trigger('chosen:updated');
		});
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				'tier': {
					validators: {
						notEmpty: {
							message: 'Please select tier'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
	var title_table = 'Profit Loss Statement Report: ' +' from '+$('input#start_date').val()+' to '+$('input#end_date').val();
	$('#dataTables').DataTable({
		"paging":   false,
	});
});
		
</script>
