<?php
/**
 * 
 * Index -- of Closing Balance
 * 
 */
	$this->headTitle($this->title);
?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<div class="widget-body">
					<div class="widget-main padding-24">
						<form method="post" class="form-group" action="<?php echo $this->url('report', array('action' => 'costprofit')); ?>">
							<div class="row">
								<div class="form-group col-lg-2">
									<label for="tier" class="control-label">Tier</label>
									<select name="tier" id="tier" class="form-control" data-paceholder="Select">
										<option value=""></option>
										<?php 
											$st1 = ($data["tier"]==1)? 'selected':'';
											$st2 = ($data["tier"]==2)? 'selected':'';
											$st3 = ($data["tier"]==3)? 'selected':'';
											$st4 = ($data["tier"]==4)? 'selected':'';
											$total_income_accumulated=0;
											$total_expense_accumulated=0;
											$tax1=0;$tax2=0;
										?>
										<option value="4" <?php echo $st4; ?>> Class </option>
										<option value="3" <?php echo $st3; ?>> Group </option>
										<option value="2" <?php echo $st2; ?>> Head </option>
										<option value="1" <?php echo $st1; ?>> Sub Head </option>
									</select>
								</div>  
								<div class="form-group col-lg-2">
									<label class="control-label" for="start_date">Start Date</label>
									<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
								<div class="form-group col-lg-2">
									<label class="control-label" for="end_date">End Date</label>
									<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
								<div class="form-group col-lg-2">
									<label for="region" class="control-label">Region</label>
									<select class="form-control" name="region" id="region" data-paceholder="Select" onchange="this.form.submit()">
										<option value="-1">All</option>
										<?php foreach ($this->regionObj->getAll() as $region):?>
										<?php $selected_reg = ($data["region"]==$region['id'])? 'selected':'';?>
											<option value="<?php echo $region['id'];?>" <?php echo $selected_reg;?>>
												<?php echo $region['region']; ?>
											</option>
										<?php endforeach;?>									
									</select>
								</div>
								<div class="form-group col-lg-2">
									<label for="location" class="contol-label">Location</label>
									<select class="form-control" name="location" id="location" data-placeholder="Select" onchange="this.form.submit()">
										<option value="-1">All</option>
										<?php if($data["region"]>0):
											foreach($this->locationObj->get(array('region'=> $data["region"])) as $locations):
										?>
											<?php $selected_loc = ($data["location"]==$locations['id'])? 'selected':'';?>
											<option value="<?php echo $locations['id'];?>" <?php echo $selected_loc;?> ><?php echo $locations['location'];?></option>
										<?php endforeach;
										endif;?>							
									</select>
								</div> 
								<div class="row">
									<div class="col-lg-12">
										<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
									</div>
								</div>
							</div>
						</form>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12">
								<table class="table table-striped table-bordered table-hover" id="dataTables">
									<thead>
										<tr>
											<th rowspan="2">Particulars</th>
											<th>Debit(DR)</th>
											<th>Credit(CR)</th>
										</tr>
									</thead>
									<tbody>
									<?php 
									if($data['tier'] <= 4):
										foreach($this->classObj->get(array('id'=>array(3,4))) as $class): 
											$total_pres_expenditure = array();
											$total_pres_income = array();?>
											<tr class="grouprow">
												<td class=""><?php echo $this->classObj->getColumn($class['id'],'code');?></td>
												<?php
													$suminclass= $this->tdetailsObj->sumbyclass($class['id'],$data['start_date'],$data['end_date'],$data['location'],$data['region'],'`debit`','`credit`');
													foreach($suminclass as $sumc);
														$total_debit= $sumc['debit'];
														$total_credit= $sumc['credit'];?>
												<td style ="text-align:right"><?php echo number_format($total_debit,2,'.',',');?></td>
                                                <td style ="text-align:right"><?php echo number_format($total_credit,2,'.',',');?></td>													
											</tr>
											<?php 
											if($data['tier'] <= 3):
												foreach($this->groupObj->get(array('class'=>$class['id'])) as $group):?>
													<tr class="grouprow">
														<td class="text-danger">&nbsp;<?php echo $this->groupObj->getColumn($group['id'],'code');?></td>
														<?php 
														$sumingroup= $this->tdetailsObj->sumbygroup($group['id'],$data['start_date'],$data['end_date'],$data['location'],$data['region'],'`debit`','`credit`');
														foreach($sumingroup as $sumg);
															$total_debit= $sumg['debit'];
															$total_credit= $sumg['credit'];?>	
														<td style ="text-align:right"><?php echo number_format($total_debit,2,'.',',');?></td>
														<td style ="text-align:right"><?php echo number_format($total_credit,2,'.',',');?></td>
													</tr>
													<?php
													if($data['tier'] <= 2):
														foreach($this->headObj->get(array('group'=>$group['id'])) as $head):?>
															<tr class="headrow">
																<td class="text-success">&nbsp;&nbsp;<?php echo $this->headObj->getColumn($head['id'],'code');?></td>
																<?php 
																$suminhead= $this->tdetailsObj->sumbyhead($head['id'],$data['start_date'],$data['end_date'],$data['location'],$data['region'],'`debit`','`credit`');
																foreach($suminhead as $sumh);
																	$total_debit= $sumh['debit'];
																	$total_credit= $sumh['credit'];?>	
																<td style ="text-align:right"><?php echo number_format($total_debit,2,'.',',');?></td>
																<td style ="text-align:right"><?php echo number_format($total_credit,2,'.',',');?></td>
															</tr>
															<?php 
															if($data['tier'] <= 1):
																foreach($this->subheadObj->get(array('head'=>$head['id'])) as $subhead):?>
																	<tr class="subheadrow">
																		<td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $subhead['code'];?></td>
																		<?php 
																		foreach($this->tdetailsObj->getsubheadbased($subhead['id'],$data['start_date'],$data['end_date'],$data['location'],$data['region'],'`debit`','`credit`') as $trans);
																			$total_debit= $trans['debit'];
																		    $total_credit= $trans['credit'];?>	
																		<td style ="text-align:right"><?php echo number_format($total_debit,2,'.',',');?></td>
																		<td style ="text-align:right"><?php echo number_format($total_credit,2,'.',',');?></td>
																	</tr>			
																<?php 
															   endforeach;
															endif;
														endforeach;
													endif; 
												endforeach;
											endif;
										endforeach;
									endif; ?>
									<?php
									$total_income=0;
									$total_expense=0;?>
									<tr class="blue classrow">
										<td>Gross Profit/Loss</td>
										<?php
											
										?>
											<td style ="text-align:right"><?php //echo number_format(($pl),2,'.',',');}?></td>
									</tr>
									<tr class="red classrow">
										<td> Taxable ( 30% ) </td>
										<?php 
										?>
											<td style ="text-align:right"><?php //echo number_format($tax1,2,'.',',');}?></td>
										<?php 
										//endif;?>
									 </tr>
									 <tr class="green classrow">
										<td>Net Profit/Loss</td>
										<?php 
											?>
											<td style ="text-align:right" ><?php //echo number_format(($total_income - $total_expense - $tax1),2,'.',',');}?></td>
										</tr>
									</tbody>
								</table>	
							</div>
						</div>
					</div>
				</div>
		    </div>
		</div>
	</div>
</div>
<script>
$(function(){
    $('#start_date').datepicker();
    $('#end_date').datepicker();
	$('#dataTables').DataTable({
		"paging":   false,
	});
	$("#region").change(function() { 
		$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
			var newdata ="<option value='-1'>All</option>"+data
			$('#location').html( newdata );
			$("#location").trigger('chosen:updated');
		});
	});
});
</script>
