<?php
/**
 * View -- of Report/AccountsreportController/annextureAction
 */
   $this->headTitle($this->title);
?>
<?php echo $this->tabs_helper(array(684,691,685,686,687,688,689,690,699)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form method="post" action="<?php echo $this->url('report', array('action' => 'tdsreport')); ?>"  enctype="multipart/form-data" >    
					<div class="row">
						<div class="form-group col-lg-2">
							<label class="control-label" for="start_date">Start Date</label>
							<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
						<div class="form-group col-lg-2">
							<label class="control-label" for="end_date">End Date</label>
							<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div></br>
						<div class="col-lg-4"> 
							<div class="form-group">
								<label>
									<?php 
										$percent2_checked = ($sub_head == '2132') ? 'checked' : ''; 
										$percent3_checked = ($sub_head == '2118') ? 'checked' : ''; 
										$percent5_checked = ($sub_head == '2119') ? 'checked' : ''; 
										$stlechecked = ($sub_head == '1') ? 'checked' : ''; 
										$stlecheckedst = ($sub_head == '2') ? 'checked' : '';
										$pbvi = ($sub_head == '3') ? 'checked' : '';
										$catds = ($sub_head == '2135') ? 'checked' : '';
									?>
									<input name="sub_head" id="sub_head" type="radio" value="2132" class="ace" <?php echo $percent2_checked;?> />
									<span class="lbl"> 2% TDS</span>
								</label>
								<label>
									<input name="sub_head" id="sub_head" type="radio" value="2118" class="ace" <?php echo $percent3_checked;?> />
									<span class="lbl"> 3% TDS</span>
								</label>
								<label>
									<input name="sub_head" id="sub_head" type="radio" value="2119" class="ace" <?php echo $percent5_checked;?> />
									<span class="lbl"> 5% TDS</span>
								</label>
								<label>
									<input name="sub_head" id="sub_head" type="radio" value="1" class="ace" <?php echo $stlechecked;?> />
									<span class="lbl">LE</span>
								</label>
								<label>
									<input name="sub_head" id="sub_head" type="radio" value="2" class="ace" <?php echo $stlecheckedst;?> />
									<span class="lbl">ST</span>
								</label>
								<label>
									<input name="sub_head" id="sub_head" type="radio" value="3" class="ace" <?php echo $pbvi;?> />
									<span class="lbl">PBVI</span>
								</label>
								<label>
									<input name="sub_head" id="sub_head" type="radio" value="2135" class="ace" <?php echo $catds;?> />
									<span class="lbl">CA-TDS</span>
								</label>
							</div> 
						</div>
						<div class="col-lg-2">
							<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
						</div>
					</div>	
				</form>
				<div class="hr hr-dotted"></div>
				<div class="row col-lg-12">
					<label><i class="green fa fa-calendar"></i> <strong>Date : </strong></label><span><?php echo (!isset($data['start_date']))?'-select-':$data['start_date'].' to '.$data['end_date'];?></span>
				</div>
				<div class="row col-lg-12">
					<div class="clearfix">
					    <input type="hidden" name="sub_head" id="sub_head" value="<?php echo $data['subhead']?>">
						<input type="hidden" name="st_date" id="st_date" value="<?php echo $data['start_date']?>">
						<input type="hidden" name="ed_date" id="ed_date" value="<?php echo $data['end_date'];?>">
					</div>
				</div>
				<div class="row">	
					<div class="col-lg-12">	
					    <?php if($data['subhead']=='2132'):?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">	
							<thead>
								<tr>
									<th style="text-align:left" rowspan="2">TPN</th>
									<th style="text-align:left" rowspan="2">Name of Contractor</th>
									<th style="text-align:left" rowspan="2">Description of work</th>
									<th style="text-align:left" rowspan="2">Bill</th>
									<th style="text-align:left" rowspan="2">Transaction Date</th>
									<th style="text-align:left" rowspan="2">Transaction Amount</th>
									<th colspan = "2" style="text-align:center">Amount Withheld</th>
								</tr>
								<tr>
									<th>Rate of Tax(2%)</th>
									<th>TDS</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_credit=0;
								foreach ($this->transactiondetailObj->getTDS($data) as $row):
								$subhead='';
								$transd=$this->transactiondetailObj->get(array('transaction'=>$row['transaction']));
								$voucher_amt=$this->transactionObj->getColumn($row['transaction'],'voucher_amount');
								$total_credit+=$row['credit'];
								foreach($transd as $shi):
								if($shi['debit']>0 && $row['credit']>0){
									$subhead =$shi['sub_head_name'];
									$subheadID =$shi['sub_head_id'];
								}
								
								//---------------CONTINUE FROM HERE-GET TPN FROM PARTY
								$partyid=$this->subheadObj->getColumn($subheadID,'ref_id');
								$tpn=$this->partyObj->getColumn($partyid,'tpn');
								$partyRole=$this->partyObj->getColumn($partyid,'role');
								endforeach;
								//echo '<pre>';print_r($transd);exit;//
								//echo '<pre>';print_r($subhead);exit;?>							
								<tr>
									<td><?php echo $tpn;?></td>
									<td><?php echo $subhead;?></td>
									<td><?php echo $this->partyroleObj->getColumn($partyRole,'role');?></td>
									<td style="text-align:right"><?php //echo number_format((float)$row['credit'], 2, '.', ',');?></td>
									<td style="text-align:left"><?php echo $row['voucher_dates'];?></td>
									<td class = "primary" style="text-align:right"><?php echo number_format((float)$voucher_amt, 2, '.', ',');?></td>
									<td class = "red" style="text-align:right"><?php echo $row['sub_head'];?></td>
									<td class = "green" style="text-align:right"><?php echo $row['credit'];?></td>
								</tr>							
							<?php endforeach;?>
						    	<tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo $total_credit;?></td>
								</tr>	
							</tbody>
						</table>
						<?php elseif($data['subhead']=='2118'):?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">
							<thead>
								<tr>
									<th style="text-align:left" rowspan="2">TPN</th>
									<th style="text-align:left" rowspan="2">Name of Contractor</th>
									<th style="text-align:left" rowspan="2">Description of work</th>
									<th style="text-align:left" rowspan="2">Bill</th>
									<th style="text-align:left" rowspan="2">Transaction Date</th>
									<th style="text-align:left" rowspan="2">Transaction Amount</th>
									<th colspan = "2" style="text-align:center">Amount Withheld</th>
								</tr>
								<tr>
									<th>Rate of Tax(3%)</th>
									<th>TDS</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_credit=0;
								foreach ($this->transactiondetailObj->getTDS($data) as $row):
								$subhead='';
								$transd=$this->transactiondetailObj->get(array('transaction'=>$row['transaction']));
								$voucher_amt=$this->transactionObj->getColumn($row['transaction'],'voucher_amount');
								$total_credit+=$row['credit'];
								foreach($transd as $shi):
								if($shi['debit']>0 && $row['credit']>0){
									$subhead =$shi['sub_head_name'];
									$subheadID =$shi['sub_head_id'];
								}
								//---------------CONTINUE FROM HERE-GET TPN FROM PARTY
								$partyid=$this->subheadObj->getColumn($subheadID,'ref_id');
								$tpn=$this->partyObj->getColumn($partyid,'tpn');
								$partyRole=$this->partyObj->getColumn($partyid,'role');
								endforeach;?>							
								<tr>
									<td><?php echo $tpn;?></td>
									<td><?php echo $subhead;?></td>
									<td><?php echo $this->partyroleObj->getColumn($partyRole,'role');?></td>
									<td style="text-align:right"><?php //echo number_format((float)$row['credit'], 2, '.', ',');?></td>
									<td style="text-align:left"><?php echo $row['transaction'];?></td>
									<td class = "primary" style="text-align:right"><?php echo number_format((float)$voucher_amt, 2, '.', ',');?></td>
									<td class = "red" style="text-align:right"><?php echo $row['sub_head'];?></td>
									<td class = "green" style="text-align:right"><?php echo $row['credit'];?></td>
								</tr>							
							<?php endforeach;?>
							    <tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo $total_credit;?></td>
								</tr>	
							</tbody>
						</table>
						<?php elseif($data['subhead']=='2119'):?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">	
							<thead>
								<tr>
									<th style="text-align:left" rowspan="2">TPN</th>
									<th style="text-align:left" rowspan="2">Name of Contractor</th>
									<th style="text-align:left" rowspan="2">Description of work</th>
									<th style="text-align:left" rowspan="2">Location</th>
									<th style="text-align:left" rowspan="2">Bill</th>
									<th style="text-align:left" rowspan="2">Transaction Date</th>
									<th style="text-align:left" rowspan="2">Transaction Amount</th>
									<th colspan = "2" style="text-align:center">Amount Withheld</th>
								</tr>
								<tr>
									<th>Rate of Tax</th>
									<th>TDS</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_credit=0;
								foreach ($this->transactiondetailObj->getTDS($data) as $row):
								$subhead='';
								$transd=$this->transactiondetailObj->get(array('transaction'=>$row['transaction']));
								$voucher_amt=$this->transactionObj->getColumn($row['transaction'],'voucher_amount');
								$total_credit+=$row['credit'];
								foreach($transd as $shi):
								if($shi['debit']>0 && $row['credit']>0){
									$subhead =$shi['sub_head_name'];
									$subheadID =$shi['sub_head_id'];
								}
								
								//---------------CONTINUE FROM HERE-GET TPN FROM PARTY
								$partyid=$this->subheadObj->getColumn($subheadID,'ref_id');
								$tpn=$this->partyObj->getColumn($partyid,'tpn');
								$partyRole=$this->partyObj->getColumn($partyid,'role');
								$location=$this->partyObj->getColumn($partyid,'location');
								//echo '<pre>';print_r($type);
								endforeach;?>							
								<tr>
									<td><?php echo $tpn;?></td>
									<td><?php echo $subhead;?></td>
									<td><?php echo $this->partyroleObj->getColumn($partyRole,'role');?></td>
									<td style="text-align:right"><?php echo $this->locationObj->getColumn($location,'location');?></td>
									<td style="text-align:right"><?php //echo number_format((float)$row['credit'], 2, '.', ',');?></td>
									<td style="text-align:left"><?php echo $row['voucher_dates'];?></td>
									<td class = "primary" style="text-align:right"><?php echo number_format((float)$voucher_amt, 2, '.', ',');?></td>
									<td class = "red" style="text-align:right"><?php echo $row['sub_head'];?></td>
									<td class = "green" style="text-align:right"><?php echo $row['credit'];?></td>
								</tr>								
							<?php endforeach;//exit;?>
							    <tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo $total_credit;?></td>
								</tr>	
							</tbody>
						</table>
						<?php elseif($data['subhead']=='1'):?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">	
							<thead>
								<tr>
									<th style="text-align:left">Name of Employee</th>
									<th style="text-align:left">TPN</th>
									<th style="text-align:left">Leave Encashment</th>
									<th style="text-align:left">TDS on LE</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_credit=0;
								foreach ($this->leObj->getEMPTDS($data) as $row):
								$total_credit+=$row['deduction'];
								$tpns=$this->tpnObj->get(['employee'=>$row['employee']]);
								foreach($tpns as $empT);//?>							
								<tr>
									<td><?php echo $this->employeeObj->getColumn($row['employee'],'full_name');?></td>
									<td><?php echo $empT['tpn'];?></td>
									<td class = "" style="text-align:right"><?php echo number_format((float)$row['basic'], 2, '.', ',');?></td>
									<td class = "" style="text-align:right"><?php echo $row['deduction'];?></td>
									
								</tr>								
							<?php endforeach;//exit;?>
							    <tr>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo $total_credit;?></td>
								</tr>	
							</tbody>
						</table>
						<?php elseif($data['subhead']=='2'):?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">	
							<thead>
								<tr>
									<th style="text-align:left">Name of Employee</th>
									<th style="text-align:left">TPN</th>
									<th style="text-align:left">Sitting Fees</th>
									<th style="text-align:left">@2% of sitting</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_credit=0;
								foreach ($this->sittinObj->getSTTDS($data) as $row):
								$total_credit+=$row['deduction'];
								$tpns=$this->tpnObj->get(['employee'=>$row['employee']]);
								foreach($tpns as $empT);?>							
								<tr>
									<td><?php echo $this->employeeObj->getColumn($row['employee'],'full_name');?></td>
									<td><?php echo $empT['tpn'];?></td>
									<td class = "" style="text-align:right"><?php echo number_format((float)$row['amount'], 2, '.', ',');?></td>
									<td class = "" style="text-align:right"><?php echo $row['deduction'];?></td>
									
								</tr>								
							<?php endforeach;//exit;?>
							    <tr>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo $total_credit;?></td>
								</tr>	
							</tbody>
						</table>
						<?php elseif($data['subhead']=='2135'):?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">	
							<thead>
								<tr>
									<th style="text-align:left" >Name of Contractor</th>
									<th style="text-align:left" >Description of work</th>
									<th style="text-align:left" >Bill</th>
									<th style="text-align:left" >Transaction Date</th>
									<th style="text-align:left" >Transaction Amount</th>
									<th style="text-align:left" >TDS Amount</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_debit=0;
								foreach ($this->transactiondetailObj->getTDSALL($data) as $row):
								$subhead='';
								$subheadID='';
								$transd=$this->transactiondetailObj->get(array('transaction'=>$row['transaction']));
								$voucher_amt=$this->transactionObj->getColumn($row['transaction'],'voucher_amount');
								$total_debit+=$row['debit'];
								foreach($transd as $shi):
								//echo '<pre>';print_r($row);
								if($shi['credit']>0){
									$subhead =$shi['sub_head_name'];
									$subheadID =$shi['sub_head_id'];
								}
								
								//---------------CONTINUE FROM HERE-GET TPN FROM PARTY
								$partyid=$this->subheadObj->getColumn($subheadID,'ref_id');
								//$tpn=$this->partyObj->getColumn($partyid,'tpn');
								$partyRole=$this->partyObj->getColumn($partyid,'role');
								//echo '<pre>';print_r($type);
								endforeach;?>							
								<tr>
									<td><?php echo $subhead;?></td>
									<td><?php echo $this->partyroleObj->getColumn($partyRole,'role');?></td>
									<td style="text-align:right"><?php //echo number_format((float)$row['credit'], 2, '.', ',');?></td>
									<td style="text-align:left"><?php echo $row['voucher_dates'];?></td>
									<td class = "primary" style="text-align:right"><?php echo number_format((float)$voucher_amt, 2, '.', ',');?></td>
									<td class = "green" style="text-align:right"><?php echo $row['debit'];?></td>
								</tr>								
							<?php endforeach;//exit;?>
							    <tr>
									<td></td>
									<td></td>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo $total_debit;?></td>
								</tr>	
							</tbody>
						</table>
						<?php else:?>
						<table class="table table-striped table-bordered table-hover" id="dataTables">	
							<thead>
								<tr>
									<th style="text-align:left">Name of Employee</th>
									<th style="text-align:left">TPN</th>
									<th style="text-align:left">Gross</th>
									<th style="text-align:left">TDS</th>
								</tr>
							</thead>
							<tbody>	
							<?php 
							    $total_credit=0;
								foreach ($this->pbviObj->getBonusTDS($data) as $row):
								$total_credit+=$row['deduction'];
								$tpns=$this->tpnObj->get(['employee'=>$row['employee']]);
								foreach($tpns as $empT);?>							
								<tr>
									<td><?php echo $this->employeeObj->getColumn($row['employee'],'full_name');?></td>
									<td><?php echo $empT['tpn'];?></td>
									<td class = "" style="text-align:right"><?php echo number_format((float)$row['amount'], 2, '.', ',');?></td>
									<td class = "" style="text-align:right"><?php echo $row['deduction'];?></td>
									
								</tr>								
							<?php endforeach;//exit;?>
							    <tr>
									<td></td>
									<td></td>
									<td style="text-align:right">Total</td>
									<td style="text-align:right"><?php echo number_format((float)$total_credit, 2, '.', ',');?></td>
								</tr>	
							</tbody>
						</table>
						<?php endif;?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function(){
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'sub_head': {
				validators: {
					notEmpty: {
						message: 'Please select Sub Head'
					}
				}
			},
			'start_date': {
				validators: {
					notEmpty: {
						message: 'Please select start date'
					}
				}
			},
			'end_date': {
				validators: {
					notEmpty: {
						message: 'Please select end date'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
	$('form select').chosen().change(function () {
		fv.revalidateField($(this).attr('name'));
	});
});
	
</script>


