<?php
/**
 * View -- of Report/AccountsreportController/plsAction
 */
	$this->headTitle($this->title);
?>
<?php
	$grand_debit = 0;
	$grand_credit = 0;
	//echo '<pre>';print_r($data); exit;
	//print_r($options); exit;
?>
<?php echo $this->tabs_helper(array(684,691,685,686,687,688,689,690,699)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form id="#form" method="post" action="<?php echo $this->url('report', array('action' => 'trialbalance')); ?>"  enctype="multipart/form-data" >    
					<div class="row">   
						<div class="form-group col-lg-2">
							<label for="tier" class="control-label">Tier</label>
							<select name="tier" id="tier" class="form-control" data-paceholder="Select">
								<option value=""></option>
								<?php 
									$st1 = ($data["tier"]==1)? 'selected':'';
									$st2 = ($data["tier"]==2)? 'selected':'';
									$st3 = ($data["tier"]==3)? 'selected':'';
									$st4 = ($data["tier"]==4)? 'selected':'';
									$closing_balance='';
									$grand_pres_total_income=0;
									$grand_pres_total_expenditure=0;
									$total_debit_trail=0;
									$total_credit_trail=0;
									$pl=0;
								?>
								<option value="4" <?php echo $st4; ?> > Class </option>
								<option value="3" <?php echo $st3; ?>> Group </option>
								<option value="2" <?php echo $st2; ?>> Head </option>
								<option value="1" <?php echo $st1; ?>> Sub Head </option>
							</select>
						</div>
						<div class="form-group col-lg-2">
							<label for="region" class="control-label">Region</label>
							<select class="form-control" name="region" id="region" data-paceholder="Select">
								<option value="-1">All</option>
								<?php foreach ($region as $reg):?>
								<?php $selected_reg = ($data["region"]==$reg['id'])? 'selected':'';?>
									<option value="<?php echo $reg['id'];?>" <?php echo $selected_reg;?>>
										<?php echo $reg['region']; ?>
									</option>
								<?php endforeach;?>									
							</select>
						</div>
						<div class="form-group col-lg-2">
							<label for="location" class="contol-label">Location</label>
							<select class="form-control" name="location" id="location" data-placeholder="Select" >
								<option value="-1">All</option>
								<?php if($data["region"]>0):
									foreach($this->locationObj->get(array('region'=> $data["region"])) as $locations):
								?>
									<?php $selected_loc = ($data["location"]==$locations['id'])? 'selected':'';?>
									<option value="<?php echo $locations['id'];?>" <?php echo $selected_loc;?> >
									    <?php echo $locations['location'];?>
									</option>
								<?php endforeach;
								endif;?>							
							</select>
						</div> 
						<div class="form-group col-lg-2">
							<label class="control-label" for="start_date">Start Date</label>
							<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
						<div class="form-group col-lg-2">
							<label class="control-label" for="end_date">End Date</label>
							<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
						<div class="col-lg-12">
							<button type = "submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
						</div>
					</div>			
				</form>
				<div class="clearfix">
					<label> <i class="red fa fa-tags"></i> Activity: </label>  <span><?php echo $act = ($data["activity"] == -1)? "All Activities": $this->activityObj->getColumn($data["activity"], 'activity');?></span>
					<label>  <i class="blue fa fa-globe"></i> Region: </label> <span><?php echo $loc = ($data["region"] == -1)? "All Regions": $this->regionObj->getColumn($data["region"], 'region');?></span>
					<label>  <i class="orange fa fa-map-marker"></i> Location: </label> <span><?php echo $loc = ($data["location"] == -1)? "All Locations": $this->locationObj->getColumn($data["location"], 'location');?></span>
				</div>
				<div class="row col-lg-12">
					<div class="clearfix">
						<input type="hidden" name="start_date" id="start_date" value="<?php echo $data["start_date"]?>">
						<input type="hidden" name="end_date" id="end_date" value="<?php echo $data["end_date"]?>">
					</div>
				</div>
				<div class="row col-lg-12">	
					<table class="table table-condensed table-bordered" id="dataTables">
						<thead>
							<tr>
								<th>Particulars</th>
								<th>Opening Balance</th>
								<th></th>
								<th>Debit</th>
								<th>Credit</th>
								<th>Closing Balance</th>
								<th></th>
							</tr>
						</thead>
						<tbody id="trial_balance">
							<?php   
							$total_pres_expenditure = array();
							$total_pres_income = array();?>
							<?php  
							if($data['tier'] <= 4):
								foreach($this->classObj->getTransactionClass($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date']) as $classrow): //class 
									/*PL ACCOUNT ADJUSTMENT IN TRIAL BALANCE*/
									$pres_closing_balance = $this->transactiondetailObj->getClosingBalanceforPresPLS($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $classrow['id'], 4);
									$pres_closing_balance = ($pres_closing_balance < 0)? -$pres_closing_balance:$pres_closing_balance;
									if($classrow['id'] == 3):
										$total_pres_income[] = $pres_closing_balance;
									elseif($classrow['id'] == 4):
										$total_pres_expenditure[] = $pres_closing_balance;
									endif;
									$total_debit = $this->transactiondetailObj->getSumbyClass($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'debit', $classrow['id']);
									$total_credit = $this->transactiondetailObj->getSumbyClass($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'credit', $classrow['id']);
									
									if($classrow['id'] == '1' || $classrow['id'] == '2'): /* (==) Asset & Liabilities AND (!=) Income & Expense */
									$opening_balance = $this->transactiondetailObj->getOpeningBalance($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $classrow['id'], 4);
									else:
									$opening_balance =0;
									endif;
									if($classrow['id'] == '1' || $classrow['id'] == '2'): /* (==) Asset & Liabilities AND (!=) Income & Expense */
									$closing_balance = $this->transactiondetailObj->getClosingBalanceAL($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $classrow['id'], 4);	
									else:
									$closing_balance = $this->transactiondetailObj->getClosingBalanceIE($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $classrow['id'], 4);	
									endif;
									if($opening_balance == '' || $opening_balance == '0'):
										$cr_or_dr_ob = "";
									else:
										$cr_or_dr_ob = ($opening_balance < 0)? "Cr":"Dr";
									endif;
									if($opening_balance < 0):
										$opening_balance = -$opening_balance;
									endif;
									if($closing_balance == '' || $closing_balance == '0'):
										$cr_or_dr_cb = "";
									else:
										$cr_or_dr_cb = ($closing_balance < 0)? "Cr":"Dr";
									endif;
									if($closing_balance < 0):
										$closing_balance = -$closing_balance;
									endif;
									$grand_debit += $total_debit;
									//echo $grand_debit;
									$grand_credit += $total_credit;?>		
									<?php if(($opening_balance!=0) || ($closing_balance!=0)):?>	
										<tr class="warning">
											<td class=""><?php echo $classrow['name'];?></td>
											<td style="text-align:right"><?php echo number_format((float)$opening_balance, 2, '.', ',');?></td>
											<td><?php echo $cr_or_dr_ob;//echo $this->decimal($opening_cr);?></td>
											<td style="text-align:right"><?php echo number_format((float)$total_debit, 2, '.', ',');?></td>
											<td style="text-align:right"><?php echo number_format((float)$total_credit, 2, '.', ',');?></td>
											<td style="text-align:right"><?php echo number_format((float)$closing_balance, 2, '.', ',');?></td>
											<td><?php echo $cr_or_dr_cb;//echo $this->decimal($closing_cr); ?></td>
										</tr>
									<?php endif;?>
									<?php 
									if($data['tier'] <= 3):
										foreach($this->groupObj->getTransactionGroup($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], array('class'=>$classrow['id'])) as $grouprow): //group 
											
											$total_debit = $this->transactiondetailObj->getSumbyGroup($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'debit', $grouprow['id']);
											$total_credit = $this->transactiondetailObj->getSumbyGroup($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'credit', $grouprow['id']);
											
											if($grouprow['class'] == '1' || $grouprow['class'] == '2'): /* (==) Asset & Liabilities AND (!=) Income & Expense */
											$opening_balance = $this->transactiondetailObj->getOpeningBalance($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $grouprow['id'], 3);
											else:
											$opening_balance = 0;
											endif;
											
											if($grouprow['class'] == '1' || $grouprow['class'] == '2'): /* (==) Asset & Liabilities AND (!=) Income & Expense */
											$closing_balance = $this->transactiondetailObj->getClosingBalanceAL($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $grouprow['id'], 3);	
											else:
											$closing_balance = $this->transactiondetailObj->getClosingBalanceIE($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $grouprow['id'], 3);	
											endif;
											if($opening_balance == '' || $opening_balance == '0'):
												$cr_or_dr_ob = "";
											else:
												$cr_or_dr_ob = ($opening_balance < 0)? "Cr":"Dr";
											endif;
											if($opening_balance < 0):
												$opening_balance = -$opening_balance;
											endif;
											if($closing_balance == '' || $closing_balance == '0'):
												$cr_or_dr_cb = "";
											else:
												$cr_or_dr_cb = ($closing_balance < 0)? "Cr":"Dr";
											endif;
											if($closing_balance < 0):
												$closing_balance = -$closing_balance;
											endif;?>			
											<?php 
											if(($opening_balance!=0) || ($closing_balance!=0)):?>										
												<tr class="info">
													<td>&nbsp;&nbsp;&nbsp;<?php echo $grouprow['name'];?></td>
													<td style="text-align:right"><?php echo number_format((float)$opening_balance, 2, '.', ',');?></td>
													<td><?php echo $cr_or_dr_ob;//echo $this->decimal($opening_cr);?></td>
													<td style="text-align:right"><?php echo number_format((float)$total_debit, 2, '.', ',');?></td>
													<td style="text-align:right"><?php echo number_format((float)$total_credit, 2, '.', ',');?></td>
													<td style="text-align:right"><?php echo number_format((float)$closing_balance, 2, '.', ',');?></td>
													<td><?php echo $cr_or_dr_cb;//echo $this->decimal($closing_cr); ?></td>
												</tr>
											<?php 
											endif;?>
											<?php
											if($data['tier'] <= 2):
												//foreach($this->headformatObj->get(array('group'=>$grouprow['id'])) as $htype):
													foreach($this->headObj->getTransactionHead($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'],array('group'=>$grouprow['id'])) as $headrow): // head
														// head
														$total_debit = $this->transactiondetailObj->getSumbyHead($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'debit', $headrow['id']);
														$total_credit = $this->transactiondetailObj->getSumbyHead($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'credit', $headrow['id']);
													    //echo '<pre>';print_r( $headrow);//exit;
														$class_id = $this->groupObj->getColumn(array('id'=>$headrow['group'],'class'=>array(1,2)),'class');
														
														if($class_id == '1' || $class_id == '2'):
															$opening_balance = $this->transactiondetailObj->getOpeningBalance($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $headrow['id'], 2);
														else:
															$opening_balance = 0;
														endif;
														
														if($class_id == '1' || $class_id == '2'):
														$closing_balance = $this->transactiondetailObj->getClosingBalanceAL($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $headrow['id'], 2);	
														else:
															$closing_balance = $this->transactiondetailObj->getClosingBalanceIE($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $headrow['id'], 2);	
														endif;
														if($opening_balance == '' || $opening_balance == '0'):
															$cr_or_dr_ob = "";
														else:
															$cr_or_dr_ob = ($opening_balance < 0)? "Cr":"Dr";
														endif;
														
														if($opening_balance < 0):
															$opening_balance = -$opening_balance;
														endif;
														//$opening_cr = ($opening_balance < 0)? -$opening_balance:'0';
														//$opening_dr = ($opening_balance > 0)? $opening_balance:'0';
														
														if($closing_balance == '' || $closing_balance == '0'):
															$cr_or_dr_cb = "";
														else:
															$cr_or_dr_cb = ($closing_balance < 0)? "Cr":"Dr";
														endif;
														
														if($closing_balance < 0):
															$closing_balance = -$closing_balance;
														endif;?>			
														<?php 
															if(($opening_balance!=0) || ($closing_balance!=0)):?>										
																<tr class="success">
																	<td class="">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->headObj->getColumn($headrow['id'],'code');?></td>
																	<td style="text-align:right"><?php echo number_format((float)$opening_balance, 2, '.', ',');?></td>
																	<td><?php echo $cr_or_dr_ob;//echo $this->decimal($opening_cr);?></td>
																	<td style="text-align:right"><?php echo number_format((float)$total_debit, 2, '.', ',');?></td>
																	<td style="text-align:right"><?php echo number_format((float)$total_credit, 2, '.', ',');?></td>
																	<td style="text-align:right"><?php echo number_format((float)$closing_balance, 2, '.', ',');?></td>
																	<td><?php echo $cr_or_dr_cb;//echo $this->decimal($closing_cr); ?></td>
																</tr>
															<?php  
															endif;
													//endforeach;//break;?>
													<?php 
													if($data['tier'] <= 1):
														foreach($this->subheadObj->getTransactionSubhead($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], array('head'=>$headrow['id'])) as $subheadrow): // subhead
															$total_debit = $this->transactiondetailObj->getSumbySubhead($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'debit', $subheadrow['id']);
															$total_credit = $this->transactiondetailObj->getSumbySubhead($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], 'credit', $subheadrow['id']);
															$head_id = $this->headObj->getColumn(array('id'=>$subheadrow['head']),'id'); 
															for($i=1;$i<is_array($head_id) && sizeof($head_id);$i++)://updated sizeof in php7.4
																$class_id = $this->groupObj->getColumn(array('id'=>$head_id,'class'=>array('1','2')),'class');
															endfor;
															if($class_id == '1' || $class_id == '2'):
																$opening_balance = $this->transactiondetailObj->getOpeningBalance($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $subheadrow['id'], 1);
															else:
																$opening_balance = 0;
															endif;
															
															if($class_id == '1' || $class_id == '2'):
																$closing_balance = $this->transactiondetailObj->getClosingBalanceAL($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $subheadrow['id'], 1);	
															else:
																$closing_balance = $this->transactiondetailObj->getClosingBalanceIE($data['activity'],$data['region'],$data['location'],$data['start_date'],$data['end_date'], $subheadrow['id'], 1);	
															endif;
															if($opening_balance == '' || $opening_balance == '0'):
																$cr_or_dr_ob = "";
															else:
																$cr_or_dr_ob = ($opening_balance < 0)? "Cr":"Dr";
															endif;
															if($opening_balance < 0):
																$opening_balance = -$opening_balance;
															endif;
															if($closing_balance == '' || $closing_balance == '0'):
																$cr_or_dr_cb = "";
															else:
																$cr_or_dr_cb = ($closing_balance < 0)? "Cr":"Dr";
															endif;
															if($closing_balance < 0):
																$closing_balance = -$closing_balance;
															endif;?>
															<?php if(($opening_balance!=0) || ($closing_balance!=0)):?>													
																<tr class="subheadrow">
																	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $subheadrow['code'].'-'.$subheadrow['name'];?></td>
																	<td style="text-align:right"><?php echo number_format((float)$opening_balance, 2, '.', ',');?></td>
																	<td><?php echo $cr_or_dr_ob;//echo $this->decimal($opening_cr);?></td>
																	<td style="text-align:right"><?php echo number_format((float)$total_debit, 2, '.', ',');?></td>
																	<td style="text-align:right"><?php echo number_format((float)$total_credit, 2, '.', ',');?></td>
																	<td style="text-align:right"><?php echo number_format((float)$closing_balance, 2, '.', ',');?></td>
																	<td><?php echo $cr_or_dr_cb;//echo $this->decimal($closing_cr); ?></td>
																</tr>		
															<?php endif;?>										
														<?php 
														endforeach;
													endif;
											    endforeach;
											endif;
										endforeach;//exit;
									endif; ?>
									<?php
									$grand_pres_total=0;
									if($classrow['id'] == 3):
										$grand_pres_total_income = $total_pres_income;
									elseif($classrow['id'] == 4):
										$grand_pres_total_expenditure = $total_pres_expenditure;
									endif;
									?>
									<?php if (is_array($grand_pres_total) || is_object($grand_pres_total)):
										foreach($grand_pres_total as $total):foreach($grand_prev_total as $total1):?>
									<?php endforeach; endforeach;endif; ?>
									<?php if(is_array($grand_pres_total_income) && $grand_pres_total_income!=null){
										foreach($grand_pres_total_income as $grand_pres_total_income):
										endforeach;}?>
									<?php if(is_array($grand_pres_total_expenditure) && count($grand_pres_total_expenditure)){
										foreach($grand_pres_total_expenditure as $grand_pres_total_expenditure):
										endforeach;}?>
								<?php 
								endforeach;
							endif;?>
							
							<?php 
							if($data['tier'] > 0):
								$pl=$grand_pres_total_income - $grand_pres_total_expenditure;
								//echo $pl;
								if($pl>0):
								//$total_credit_trail=$grand_debit + $pl;
								else:
								//$total_credit_trail=$grand_credit - $pl;
								endif;?>
							<?php 
							endif;?>
							<tr class="dark">
								<td>Grand Total</td>
								<td></td>
								<td></td>
								<td style="text-align:right"><?php echo number_format((float)$grand_debit, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format((float)$grand_credit, 2, '.', ',');?></td>
								<td></td>
								<td></td>
							</tr>
					    </tbody>
				    </table>
				</div>
			</div>
	    </div>
	</div>
</div>
<script>
	$(function(){
		$("#region").change(function() { 
			$.post( "<?php echo $this->url('ajresponse', array('action' => 'getlocation')); ?>/"+ $("#region").val(), function( data ) {
				var newdata ="<option value='-1'>All</option>"+data
				$('#location').html( newdata );
				$("#location").trigger('chosen:updated');
			});
	    });
	    $('#start_date').datepicker();
		$('#end_date').datepicker();
		$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});

		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				'tier': {
					validators: {
						notEmpty: {
							message: 'Please select tier'
						}
					}
				},
				'activity' : {
					validators: {
						notEmpty: {
							message: 'Please select activity'
						}
					}
				},
				'region' : {
					validators: {
						notEmpty: {
							message: 'Please select region'
						}
					}
				},
				'location' : {
					validators: {
						notEmpty: {
							message: 'Please select location'
						}
					}
				},
				'start_date': {
					validators: {
						notEmpty: {
							message: 'Please select start date'
						}
					}
				},
				'end_date': {
					validators: {
						notEmpty: {
							message: 'Please select end date'
						}
					}
				},
			},
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
			}
		});
		$('form select').chosen().change(function () {
			fv.revalidateField($(this).attr('name'));
		});
		
		var title_table = 'Trial Balance Report: ' +' from '+$('input#start_date').val()+' to '+$('input#end_date').val();
		$('#dataTables').DataTable({
			"paging":   false,
		});
		
	});
</script>
