<?php
/**
 * chophel@athang.com 
 * View -- of Report/AccountsreportController/vouchercheckAction
 */
	$this->headTitle($this->title);
?>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$start = $time;
	extract($data);
?>
<?php echo $this->tabs_helper(array(684,691,685,686,687,688,689,690,699)); ?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-12">
				<form data-toggle="validator" method="post" action="<?php echo $this->url('report', array('action' => 'vouchercheck')); ?>"  enctype="multipart/form-data" >    
					<div class="row">
						<div class="form-group col-lg-2">
							<input type ="hidden" id = "loc" name = "loc" value = "<?php echo ($data["location"] == -1 || !isset($data['location']))? "All Locations": $this->locationObj->getColumn($data["location"], 'location');?>">
							<input type="hidden" name="st_date" id="st_date" value="<?php echo $data['start_date']?>">
							<input type="hidden" name="ed_date" id="ed_date" value="<?php echo $data['end_date'];?>">
							<label for="location" class="control-label">Location</label>
							<select id="location" name="location" class="form-control" data-placeholder="Select" required>
								<option value="-1">All</option>
								<?php foreach($this->locationObj->getAll() as $locations):
								    $selected = ($data['location'] == $locations['id'])?"selected":"";?>
									<option value="<?php echo $locations['id'];?>" <?php echo $selected;?>>
										<?php echo $locations['location'];?>
									</option>
								<?php endforeach;?>
							</select> 
						</div>
						<div class="form-group col-lg-2">
							<label for="vouchertype" class="control-label">Voucher Type</label>
							<select id="vouchertype" name="vouchertype" class="form-control" data-placeholder="Select" required>
								<option value="-1">All</option>
								<?php foreach($this->journalObj->getAll() as $journals):
								$selected = ($data['journal'] == $journals['id'])?"selected":"";?>
									<option value="<?php echo $journals['id'];?>" <?php echo $selected;?>>
										<?php echo $journals['journal'];?>
									</option>
								<?php endforeach;?>
							</select> 
						</div>
						<div class="form-group col-lg-3">
							<label class="control-label" for="start_date">Start Date</label>
							<div class="date input-group" id="start_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
						<div class="form-group col-lg-3">
							<label class="control-label" for="end_date">End Date</label>
							<div class="date input-group" id="end_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
						<div class="col-lg-2">
							<div class="space-10"></div>
							<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
						</div>
					</div>	
				</form>
			</div>
		</div>
	</div>
</div>
<div class="hr hr-dotted"></div>
<div class="space-6"></div> 
	<div class ="row">
		<div class="col-lg-12">
			<div>
				<table class="table table-striped table-condensed table-bordered table-hover" id="dataTables">	
					<thead>
						<tr>
							<th>Voucher Date</th>
							<th>Vouchers</th>
							<th>Voucher Type</th>
							<th>Debit(Dr)</th>
							<th>Credit(Cr)</th>
						</tr>
					</thead>
					<tbody>	
					<?php
						$i = 1;
						$grand_debit = 0;
						$grand_credit = 0;
						foreach($this->transactionObj->getVoucherChecking($data) as $transaction):
							$sum_debit  = number_format((float)$transaction['sum_debit'], 2, '.', ',');
							$sum_credit = number_format((float)$transaction['sum_credit'], 2, '.', ',');
							if($sum_debit !=$sum_credit):
								if($data['location'] == '-1'):?>	
									<tr>
										<td><?php echo $transaction['voucher_date'];?></td>
										<td><a target="_blank" href="<?php echo $this->url('transaction', array('action'=>'viewtransaction', 'id'=>$transaction['id']));?>"><?php echo $transaction['voucher_no']; ?></a></td>
										<td><?php echo $this->journalObj->getColumn($transaction['voucher_type'],'journal'); ?></td>
										<td style="text-align:right"><?php echo $sum_debit; ?></td>
										<td style="text-align:right"><?php echo $sum_credit; ?></td>							
									</tr>
								<?php else:
									$loc_array = explode(',',$transaction['location_concat']);
									if(in_array($data['location'],$loc_array)):?>
										<tr>
											<td><?php echo $transaction['voucher_date'];?></td>
											<td><a target="_blank" href="<?php echo $this->url('transaction', array('action'=>'viewdetails', 'id'=>$transaction['id']));?>"><?php echo $transaction['voucher_no']; ?></a></td>
											<td><?php echo $this->journalObj->getColumn($transaction['voucher_type'],'journal'); ?></td>
											<td style="text-align:right"><?php echo $sum_debit; ?></td>
											<td style="text-align:right"><?php echo $sum_credit; ?></td>							
										</tr>
									<?php endif;
								endif;?>
							<?php else:?>
								<tr>
									<td><?php echo $transaction['voucher_date'];?></td>
									<td><a target="_blank" href="<?php echo $this->url('transaction', array('action'=>'viewdetails', 'id'=>$transaction['id']));?>"><?php echo $transaction['voucher_no']; ?></a></td>
									<td><?php echo $this->journalObj->getColumn($transaction['voucher_type'],'journal'); ?></td>
									<td style="text-align:right"><?php echo $sum_debit; ?></td>
									<td style="text-align:right"><?php echo $sum_credit; ?></td>							
								</tr>
							<?php endif;
						endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>	
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$finish = $time;
	$total_time = round(($finish - $start), 4);
	echo "<p class='pull-right'>Voucher Check Report generated in ".$total_time." seconds.</p>";
?>	
<script type="text/javascript">
$(function(){	
	$('#start_date').datepicker();
	$('#end_date').datepicker();
	$('#start_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	$('#end_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	var title_table = $('#loc').val()+' from '+$('input#st_date').val()+' to '+$('input#ed_date').val();
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
