<?php
/**
 * View -- of Accounts/AdvancesalaryController/viewadvancesalaryAction
 */
   $this->headTitle($this->title);
?>
<?php 
	foreach($this->advsalary as $advsal):
		extract($advsal);
		$name='';
		$advance_id = $id;
	endforeach;
?>
<div class="col-lg-12">
	<div class="widget-box transparent">
		<div class="widget-header widget-header-large">
			<h3 class="widget-title grey lighter">
				<i class="ace-icon fa fa-money green"></i>
				Advance Salary Details of <?php echo $full_name;?> | <?php echo $this->payheadObj->getColumn($pay_head,'code');?>
			</h3>
			<div class="widget-toolbar hidden-xs">
				<div class="btn-group">
					<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "26-".$advance_id)); ?>" title="View Activity Logs">
						<i class="ace-icon fa fa-plus bigger-120" ></i>  
					</a> 
					<a class="btn btn-xs" id="print" title="Print">
						<i class="ace-icon fa fa-file-pdf-o bigger-120"></i>
					</a>
				</div>
			</div>
		</div>
		<div class="widget-body">
			<div class="widget-main padding-24">
				<div id="report-print">
					<div class="row" id="convert-tb0">
						<div class="col-lg-6" id="convert-tb1">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Name: <b class="red"><?php echo $full_name.'&nbsp;('.$emp_id.')'; ?></b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Position Title: <b class="red"><?php echo $designation.'&nbsp;('.$type_code.')'; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Region:	<b class="red"><?php echo $region;?> </b>
								</li>
							</ul>
						</div>
						<div class="col-lg-6" id="convert-tb2">
							<ul class="list-unstyled spaced pull-right">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Cid No: <b class="red"><?php echo $cid; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Activity: <b class="red"><?php echo $activity; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Location: <b class="red"><?php echo $location?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="hr dotted"></div>
					<div class="row" id="convert-tb0">
						<div class="col-lg-6" id="convert-tb1">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-calendar blue"></i>Initail Date: <b class="red"><?php echo $this->dateformat($initial_date); ?> </b>
								</li>
								<li>
									<?php //echo $initial_date;?>
									<i class="ace-icon fa fa-caret-right blue"></i>Received Amount: <b class="red"><?php $received_amt = $this->payrollObj->getSumYearMonth(array('pr.employee' => $employee,'pd.pay_head' => $pay_head),date_create_from_format('Y-m-d', $initial_date)); echo $this->currency($received_amt);?> </b>
								</li>
							</ul>
						</div>
						<div class="col-lg-6" id="convert-tb2">
							<ul class="list-unstyled spaced pull-right">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Payhead: <b class="red"><?php echo $this->payheadObj->getColumn($pay_head,'head_type'); ?> </b>
								</li>
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Balance Amount: <b class="red"><?php $balance_amt = $total_amount - $received_amt;echo $this->currency($balance_amt); ?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
						<table class="table table-striped table-bordered table-condensed">	
							<thead>
								<th>#</th>
								<th>Advance Deduction Type</th>
								<th>Avail Date</th>
								<th>End Date</th>
								<th>Amount(<?php //echo $this->currency_code();?>)</th>
								<th>Monthly Deduction</th>
								<th>Status</th>
								<th class="no-sort no-printpdf">Duration Left</th>
								<th class="no-sort no-printpdf">Action</th>
							</thead>
							<tbody>
								<?php $sl = 1;
									foreach($this->advsal_details as $tdrow):?>
									<tr>
										<td><?php echo $sl++;?></td>
										<td><?php echo $this->adv_ded_typeObj->getColumn($tdrow['advance_ded_type'],'advance_ded_type');?></td>
										<td><?php echo $tdrow['avail_date'];?></td>
										<td><?php echo $tdrow['end_date'];?></td>
										<td><?php echo $tdrow['amount'];?></td>
										<td><?php echo $tdrow['monthly_deduction'];?></td>
										<td><?php echo $this->status($tdrow['status']);?></td>
										<td class="action">
											<?php 
												$date1 = date('Y-m-d');
												$date2 = $tdrow['end_date'];

												$ts1 = strtotime($date1);
												$ts2 = strtotime($date2);

												$year1 = date('Y', $ts1);
												$year2 = date('Y', $ts2);

												$month1 = date('m', $ts1);
												$month2 = date('m', $ts2);

												$diff = (($year2 - $year1) * 12) + ($month2 - $month1);
												$diff = $diff + 1;
												if($diff >0){
													echo $diff;
												}else{
											?>
												<span class="label label-warning">Expired</span>
											<?php } ?>
										</td>
										<td class="action">
											<div class="btn-group">
												<?php if($tdrow['status'] == 2):?>
												<a class="btn btn-xs btn-success" href="<?php echo $this->url('advancesalary', array('action' => 'receivedadvsal', 'id' => $tdrow['id'])); ?>" title="Fully Received">
													<i class="ace-icon fa fa-check bigger-120" ></i>  
												</a>
												<?php else:?>
													<a class="btn btn-xs btn-success disabled" href="#" title="Fully Received">
														<i class="ace-icon fa fa-check bigger-120" ></i>  
													</a>
												<?php endif;?>
											</div>
										</td>
									</tr>
								<?php endforeach;?>
								<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
									<th colspan="4"><i class="pull-right">GRAND Total Amount:</i></th>
									<th><?php echo $this->currency($total_amount);?></th>
									<th><?php echo $this->currency($total_deduction);?></th>
									<th colspan="3"></th>
								</tr>
							</tbody>
						</table>
					</div>
					<div class="row">
						<div class="col-lg-3">
							<label> Prepared by: <?php echo $this->userObj->getColumn($author,'name');?></label>
						</div>
						<div class="col-lg-6">&nbsp;</div>
						<div class="col-lg-3">
							<?php $param = $employee.'-'.$pay_head;?>
							<a href="<?php echo $this->url('advancesalary', array('action'=>'addadvancesalary', 'id'=>$param));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
							<a href="<?php echo $this->url('advancesalary', array('action'=>'commitadvsalary', 'id'=>$advance_id));?>" class="btn btn-success"> <i class="fa fa-check"></i> Add To Payroll </a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"L",//L =landscape, P = potrait
	});
</script>