<?php
/**
 * 
 * Index -- of Closing Balance
 * 
 */
	$this->headTitle($this->title);
?>
<div class="row">
	<div class="space-12"></div>
	<div class="col-xs-12">
		<div class="widget-box transparent">
			<div class="widget-header widget-header-large">
				<h3 class="widget-title grey lighter">
					<i class="ace-icon fa fa-file-text-o green"></i>
					Opening Balance of Year <?php echo $this->selected_year;?>
				</h3>
				<?php if($this->button(3)!=""):?>
					<div class="widget-toolbar no-border">
						<form method="post" action="<?php echo $this->url('closing');?>">
							<?php 
							if($this->selected_year >= date('Y') || $this->closingbalanceObj->isPresent(array('year'=>$this->selected_year))):
								$disabled = "disabled";
							else:
							?>
								<input type="hidden" name="year" id="year" value="<?php echo $this->selected_year;?>"/>
								<input type="hidden" name="task" id="task" value="1"/>
							<?php endif;?>
						</form>
					</div>
				<?php endif;?>
				<div class="widget-toolbar hidden-xs">
					<a href="#" id="print-cltable">
						<i class="ace-icon fa fa-file-pdf-o fa-lg red"></i>
					</a>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main padding-24">
					<div class="row">
						<div class="col-lg-12">
							<form method="post" class="form-horizontal" action="<?php echo $this->url('closing');?>">
								<label for="module" class="control-label col-lg-1">Year</label>
								<div class="col-lg-2">
									<select id="year" name="year" class="form-control" data-placeholder="Select" onchange="this.form.submit()">
										<?php 
										for($year = date('Y'); $year >= $this->min_year; $year--):
										?>
											<?php $selected = ($year == $this->selected_year)?"selected":"";?>
											<option value="<?php echo $year;?>" <?php echo $selected;?>>
												<?php echo $year;?> 
											</option>
										<?php endfor; ?>
									</select>
								</div>
								<label for="group" class="control-label col-lg-1">Group</label>
								<div class="col-lg-2">
									<select class="form-control" id="group" name="group" data-placeholder="Select"  required >
										<option value=""></option>
										<?php 
										foreach ($this->groupObj->getAll() as $row):
											$selected=($group==$row['id'])?"selected":"";
										?>
											<option value="<?php echo $row['id'];?>"<?php echo $selected;?>>
												<?php echo $row['name'];?>
											</option>
										<?php
										endforeach;
										?>
									</select>
								</div> 
								<label for="head" class="control-label col-lg-1">Head</label>
								<div class="col-lg-2">
									<select class="form-control chosen-widget" id="head" name="head" data-placeholder="Select" required >
										<option value="<?php echo $head;?>"><?php if ($head == '-1') {echo "All";} else {echo $this->headObj->getColumn($head, 'name');}?></option>
									</select>
								</div> 
								<div class="col-lg-2">
									<button type="submit" class="btn btn-sm btn-success pull-right"><i class="fa fa-gear"></i> Generate </button>
								</div>
							</form>
						</div>
					</div>
					<div class="space-12"></div>
					<div class="row">
						<div class="col-lg-12">
							<table class="table table-striped table-bordered table-hover" id="dataTables">
								<thead>
									<tr>
										<th>#</th>
										<th>Subhead</th>
										<th>Head</th>
										<th>Location</th>
										<th>Reference</th>
										<th>Closing_SDR</th>
										<th>Closing_DR</th>
										<th>Closing_CR</th>
									</tr>
								</thead>
								<tbody>
									<?php
									$i = 1;
									$total_closing_cr =0;
									$total_closing_dr =0;
									if($this->closingbalanceObj->isPresent(array('year' => $this->selected_year))):
										foreach($this->closingbalanceObj->getfromgroup($this->selected_year,$head,$group) as $row):
										    $total_closing_cr += $row['closing_cr'];
											$total_closing_dr += $row['closing_dr'];?>
											<tr>
												<td><?php echo $i++;?></td>
												<td><?php echo $row['sh_code'].'-'.$row['sh_name'];?></td>
												<td><strong><?php echo $this->headObj->getColumn($row['head'],'code');?></strong></td>
												<td><?php echo $location=($row['location']=='-1')?'All':$this->locationObj->getColumn($row['location'],'location') ?></td>
												<td><?php echo $row['reference'];?></td>
												<td><?php echo $row['closing_sdr'];?></td>
												<td><?php echo $row['closing_dr'];?></td>
												<td><?php echo $row['closing_cr'];?></td>
											</tr>
										<?php endforeach;?>	
											
									<?php 
									else:
										$filter = array(
											'start_date' => date('Y-m-d',strtotime('10-01-'.$this->selected_year)),
											'end_date' => date('Y-m-t',strtotime('01-12-'.$this->selected_year)),
											'activity' => -1,
											'region' => -1,
											'location' => -1,
										);
										foreach($this->subheadObj->getAll() as $rows):
										    //$total_cr += $row['asset_value'];
											$closing_balance = $this->transactiondetailObj->getClosingBalanceAL($filter['start_date'],$filter['end_date'],$filter['activity'],$filter['region'],$filter['location'], $rows['id'], 1);
											$closing_cr = ($closing_balance < 0)? -$closing_balance:'0';
											$closing_dr = ($closing_balance > 0)? $closing_balance:'0';
											
									      if(($closing_dr>0)||($closing_cr>0)):?>
											<tr>
												<td><?php echo $i++; ?> </td>
												<td><?php echo $rows['name'];?></td>
												<td><?php echo $this->currency($closing_dr);?></td>
												<td><?php echo $this->currency($closing_cr);?></td>
											</tr>
										<?php endif; endforeach;?>
									<?php endif; ?>	
                                        <tr>
											<td>Total</td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td><?php echo $this->currency($total_closing_dr);?></td>
											<td><?php echo $this->currency($total_closing_cr);?></td>
										</tr>	  								
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script>
$(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$('#group').on('change',function(){
		//alert($('#group').val());
		$.post(
			'<?php echo $this->url('closing', array('action' => 'gethead')); ?>',
			{
				group: $(this).val(),
			},
			function(data){
				console.log(data);	
				$('#head').html(data.head);	
				$("#head").trigger("chosen:updated");			
			},
			'json'
		);
	});
});
</script>
