<?php
/**
 * View -- of Administration/MasterController/addactivity
 * chophel@athang.com
 */
?>
<?php 
	foreach($this->trans as $row );
	$actionRoute = isset($this->actionRoute) ? $this->actionRoute : 'deletejournal';
?>
    <form id="#form" method="post" action="<?php echo $this->url('transaction', array('action' => $actionRoute,'id'=>$row['id'])); ?>" enctype="multipart/form-data">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title"> <i class="ace-icon fa fa-plus-square-o"></i> <?php echo $this->title; ?></h4>
        </div>     
        <div class="modal-body">    
            <div class="panel panel-default">                       
                <div class="panel-body">
                    
                        <i class="ace-icon fa fa-ban fa-2x red"></i>
                        <b>Warning!: Are you sure to revoke this voucher?</b>
                        <h5 class="widget-title grey lighter">
                    </h5>
                </div>
            </div>
        </div>    
        <div class="modal-footer">
            <button type="submit" class="btn btn-danger"><i class="fa fa-check"></i> Revoke Voucher </button>
            <button type="button" class="btn btn-success" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
        </div>  
    </form>  
