<?php
/**
* add claims----Sales/Controller/addclaim
*/
	$this->headTitle($this->title);
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i>&nbsp;&nbsp;New Claims
				</h5>
			</div><!-- end of widget-header -->
			<div class="widget-body">
				<div class="widget-main">
					<form method="post" action="<?php echo $this->url('claim', array('action' => 'addclaim')); ?>"  enctype="multipart/form-data" >    <div class="row">
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="claim_type" class="control-label">Claim Type</label>
									<select id="claim_type" name="claim_type" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
										<?php foreach ($this->claimtypeObj->getAll() as $claimtype):?>
											<option value="<?php echo $claimtype['id'];?>">
												<?php echo $claimtype['claim_type']; ?>
											</option>
										<?php endforeach; ?>
									</select> 
								</div>	
							</div>		
							<div class="col-lg-4">    
								<div class="form-group">
									<label for="claim_date" class="control-label">Claim Date</label>
									<div class="date input-group" id="claim_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="claim_date" id="claim_date" type="text" placeholder="Claim Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
							</div>
							<div class="col-lg-4"> 
								<div class="form-group">
									<label for="location" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
								<?php foreach ($this->locationObj->getAll() as $location):?>
											<option value="<?php echo $location['id'];?>">
												<?php echo $location['location']; ?>
											</option>
										<?php endforeach; ?>
									</select> 
								</div>	
							</div>
						</div>
						<div class="row">
							<div class="col-lg-4">
								<div class="form-group">
									<label for="activity" class="control-label"> Activity</label>
									<select id="activity" name="activity" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach($activities as $activity):?>
											<option value="<?php echo $activity['id'];?>">
												<?php echo $activity['activity'];?>
											</option>
										<?php endforeach;?>
									</select>
								</div>	
							</div>
							<div class="col-lg-4">
								<div class="form-group">
									<label for="supplier" class="control-label">Supplier</label>
									<select id="supplier" name="supplier" class="form-control" data-placeholder="Select" required>
										<option value=""></option>
										<?php foreach($suppliers as $supplier):?>
											<option value="<?php echo $supplier['id'];?>">
												<?php echo $supplier['code'];?>
											</option>
										<?php endforeach;?>
									</select>
								</div>
							</div>
							<div class="col-lg-4">
								<div class="form-group">
									<label for="sub_head" class="control-label">Sub Head</label>
									<select id="sub_head" name="sub_head" class="form-control" data-placeholder="Select" required>
										<option value=""></option>	
									</select> 
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-4">
								<div class="form-group">
									<label for="amount" class="control-label">Amount</label>
									<input type="text" class="form-control" name="amount" id="amount" placeholder="Enter Amount" required/>
								</div>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<a class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </a>  					
							</div>
						</div>
					</form>	
				</div><!-- widget widget-main -->
			</div>  <!-- widget widget-body -->   
		</div> <!-- widget widget-box --> 
	</div><!-- col-lg-12 -->
</div><!-- row -->

<script type="text/javascript"> 
	$('#supplier').change(function(){
		$('#sub_head').load("<?php echo $this->url('claim', array('action'=>'getshbysupplier'));?>/"+$(this).val(),function(){
			$('#sub_head').trigger('chosen:updated');
		});
	});
	
    $(function() {
		$('#claim_date').datepicker();
		$('#claim_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
	    //formValidation
		$('form').formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid',
				fields: {
					'claim_date': {
					 	validators: {
							notEmpty: {
								message: 'Please select claim date'
						  	}
					  	}
				  	},
					'claim_type': {
						validators: {
							notEmpty: {
								message: 'Please select claim type'
							}
						}
					}, 
					'location': {
						validators: {
							notEmpty: {
								message: 'Please select location'
							}
						}
					}, 
					'activity': {
						validators: {
							notEmpty: {
								message: 'Please select activity'
							}
						}
					}, 
					'supplier': {
						validators: {
							notEmpty: {
								message: 'Please select supplier'
							}
						}
					}, 
					'sub_head': {
						validators: {
							notEmpty: {
								message: 'Please select sub_head'
							}
						}
					}, 
					'amount': {
						validators: {
							notEmpty: {
								message: 'Please enter amount'
							}
						}
					}, 
				}
				}).on('success.field.fv', function(e, data) {
				  if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
						data.fv.disableSubmitButtons(true);
			      }
		});
	});  
</script>
