<?php
/**
 * 
 * addreturn claim ---Sales/ClaimController/addreturnclaimAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('claim', array('action' => 'addreturnclaim')); ?>"  enctype="multipart/form-data" >                 
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><i class="fa fa-asterisk"></i>Add Return Claim</h4>
    </div><!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="row">
					<div class="col-lg-12">
						<h5>Claim Amount Left :
						<?php echo "<i>".$left_clreturn."</i></h5>";?>
					</div>
					<div class="col-lg-6">
						<div class="form-group">
							<input type="hidden" class="form-control" name="left_clreturn" id="left_clreturn" value="<?php echo $left_clreturn;?>" >
							<label  for="ref_no" class="control-label">Ref No</label>
							<input type="text" class="form-control" name="ref_no" id="ref_no" placeholder = "Enter Ref NO" />
							<input type="hidden" class="form-control" name="claim_id" id="claim_id" value="<?php echo $claim_id;?>" />
						</div>
					</div>
					<div class="col-lg-6">
						<div class="form-group">
							<label for="return_date" class="control-label">Claim Return Date</label>
							<div class="date input-group" id="return_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
								<input class="form-control span2" name="return_date" id="return_date" type="text" placeholder="Return Date" readonly required>
								<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
							</div>
						</div>
					</div>
				</div>	
				<div class="row">
					<div class="col-lg-6">
						<div class="form-group">
							<label  for="amount" class="control-label">Amount</label>
							<input type="text" class="form-control" name="amount" id="amount" placeholder =" Enter claim return Amount" />
						</div>
					</div>
					<div class="col-lg-6">
						<div class="form-group">
							<label  for="note" class="control-label">Remarks</label>
							<input type="text" class="form-control" name="note" id="note" placeholder="Enter Remarks"/>
						</div>
					</div>
				</div>
			</div>
		</div>                    
    </div><!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div><!-- /modal-footer -->
</form>
<script type="text/javascript">
$('select').chosen({ allow_single_deselect: true });		
$('document').ready(function(){
	$('#amount').on('change',function(){
		if($.isNumeric($(this).val())){
			var left_clreturn = parseFloat($('#left_clreturn').val());
			//alert(left_clreturn);
			if($(this).val() <= left_clreturn){
				$amount = $(this).val();
				$('#amount').val(parseFloat($amount).toFixed(2));			
			}else{				
				$amount = "0.00";					
				$('#amount').val(parseFloat($amount).toFixed(2));	
				alert('Enter again, Claim return amount left is ' + left_clreturn + '.');
			}
		}
	});
	$('#return_date').datepicker();
	$('#return_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			ref_no: {
				validators: {
					notEmpty: {
						message: 'Please enter Ref No.'
					}
				}
			},
			return_date: {
				validators: {
					notEmpty: {
						message: 'Please Select return date.'
					}
				}
			},
			amount: {
				validators: {
					notEmpty: {
						message: 'Please enter amount.'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>

