<?php
/**
 * View -- of Sales/ClaimController/viewclaim
 */
?>
<?php 
	foreach($this->claims as $claim):
		extract($claim);
	    $cl_status = $status;
	    $cl_id = $id;
	    $cl_amount = $amount;
	endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					# Schemes:<strong>&nbsp;&nbsp;<?php echo $claim_no; ?> | <?php echo $claimtypeObj->getColumn($claim['claim_type'], 'claim_type'); ?> | <?php echo $activityObj->getColumn($claim['activity'], 'activity');?>&nbsp;<?php
						 $status_list  = $this->statusObj->get($status); 
						 foreach ($status_list as $status):
							 extract($status);
						 endforeach;
					 ?>
					<span class="label label-<?php echo $label;?>">
						&nbsp; <?php echo $status; ?> &nbsp;
					</span> </strong>
				</h5>
				<div class="widget-toolbar hidden-xs">
					<a style='cursor:pointer' id="print">
						<i class="ace-icon fa fa-file-pdf-o red"></i>
					</a>
				</div>	
			</div>
			<div class="widget-body">
				<div class="widget-main padding-12">
					<div id="report-print">
						<div class="row" id="convert-tb0">
							<div class="col-lg-8" id="convert-tb1">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Claim No : <b class="red"><?php echo $claim_no; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Claim Type : <b class="red"><?php echo $claimtypeObj->getColumn($claim['claim_type'], 'claim_type');?>	</b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Claim Date : <b class="red"><?php echo $claim_date; ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Amount : <b class="red"><?php echo $cl_amount; ?></b>
									</li>
									<li>
									<i class="ace-icon fa fa-caret-right blue"></i>
										Transaction Voucher No. : <b class="red"><a target="_blank" href="<?php echo $this->url('transaction', array('action'=>'viewtransaction', 'id' => $transaction));?>"><?php echo $this->transactionObj->getColumn(array('id' => $transaction),'voucher_no');?> </a> </b>
									</li>
								</ul>
							</div>
							<div class="col-lg-4" id="convert-tb2">
								<ul class="list-unstyled spaced">
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Location : <b class="red"><?php echo $locationObj->getColumn($claim['location'], 'location');?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Activity: <b class="red"><?php echo $activityObj->getColumn($claim['activity'], 'activity');?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Supplier : <b class="red"><?php echo $supplierObj->getColumn($claim['supplier'], 'name'); ?></b>
									</li>
									<li>
										<i class="ace-icon fa fa-caret-right blue"></i>
										Sub Head : <b class="red"><?php echo $subheadObj->getColumn($claim['sub_head'], 'name'); ?></b>
									</li>
								</ul>
							</div>
						</div>
						<div class="space-12"></div>
						<?php if($cl_status >= 3):?>
						<div class="row">
							<div class="col-lg-12">
								<h5>Return Claims</h5>
								<div class="table-responsive">
									<table class="table">
										<thead>
											<tr>
												<th>#</th>
												<th>Ref No</th>
												<th>Return Date</th>
												<th>Amount</th>
												<th>Remarks</th>
												<th>Status</th>
												<th class="no-sort">Action</th>
											</tr>
										</thead>
										<tbody>
										<?php $i = 1; $tot_amt = 0;
										if(sizeof($claimreturns)>0):
											foreach($claimreturns as $claimreturn):
												$return_cl_id = $claimreturn['id'];
												$rcl_status=$claimreturn['status'];?>
												<tr>
													<td><?php echo $i++;?></td>
													<td><?php echo $claimreturn['ref_no'];?></td>
													<td><?php echo $claimreturn['return_date'];?></td>
													<td><?php echo $claimreturn['amount'];
														$tot_amt += $claimreturn['amount'];?></td>
													<td><?php echo $claimreturn['note'];?></td>
													<td>
													<?php
														$status_list  = $this->statusObj->get($rcl_status); 
														foreach ($status_list as $rc_status):
															 extract($rc_status);
														endforeach;
													?>
														<span class="label label-<?php echo $label;?>">
															&nbsp; <?php echo $status; ?> &nbsp;
														</span> 
													</td>
													<td>
														<?php if($rcl_status < 3):?>
															<a class="btn btn-xs btn-info" data-toggle="modal" data-tooltip="tooltip" title="Edit Return Claims" href="<?php echo $this->url('claim', array('action'=>'editreturnclaim', 'id' => $return_cl_id));?>" data-target="#modal">
															<i class="ace-icon fa fa-pencil bigger-120"></i>
															</a>
															<a class="btn btn-xs btn-danger" data-tooltip="tooltip" title="Delete Return Claims"href="<?php echo $this->url('claim', array('action'=>'deletereturnclaim', 'id' => $return_cl_id));?>">
															<i class="ace-icon fa fa-trash-o fa-lg"></i>
															</a>
															<a class="btn btn-xs btn-success"  data-tooltip="tooltip" title="Commit Return Claims" href="<?php echo $this->url('claim', array('action'=>'commitreturnclaim', 'id' => $return_cl_id));?>">
															<i class="ace-icon fa fa-check-square-o fa-lg"></i>
															</a>
														<?php else:
															echo "---";
														endif;?>	
													</td>
												</tr>
											<?php endforeach;?>
											<tr>
												<td colspan="2" align = "right"><strong>Amount Left : </strong></td>
												<td><strong><?php echo $this->currency($cl_amount - $tot_amt);?></strong></td>
												<td colspan="2" align="right"><strong>Total Amount Received : </strong></td>
												<td><strong><?php echo $this->currency($tot_amt);?></strong></td>
												<td></td>
											</tr>
										<?php else:?>
											<tr>
												<td colspan="7">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;No Data found in this table, Return Claims not added!</td>
											</tr> 
										<?php endif;?>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					<?php endif;?>	
					</div>							
					<div class="row">
						<div class="col-lg-12" style="text-align: right">
							<?php if($cl_status == '1' || $cl_status == '2'):?>
								<a href="<?php echo $this->url('claim', array('action'=>'editclaim', 'id'=>$cl_id));?>" class="btn btn-info"> <i class="fa fa-pencil"></i> Edit </a>
								<a href="<?php echo $this->url('claim', array('action'=>'bookingclaim', 'id'=>$cl_id));?>" class="btn btn-success"> <i class="fa fa-check-square-o"></i>Book Claims</a>
							<?php endif;?>
							<?php if($cl_amount == $tot_amt && $cl_status != '5'):?>
								<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" href="<?php echo $this->url('claim', array('action' => 'receivereturnclaim','id'=>$cl_id));?>" >
									<span class="green"><i class="fa fa-close"></i> <span class="hidden-sm hidden-xs">&nbsp;Receive All</span></span>
								</a>
							<?php elseif($cl_status != '1' && $cl_status != '2' && $cl_status != '5'):?>
								<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-toggle="modal" data-target="#modal" data-placement="top" title="Add Claim" href="<?php echo $this->url('claim', array('action' => 'addreturnclaim','id'=>$cl_id));?>" >
									<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add R Claims</span></span>
								</a>
							<?php endif;?>	
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<?php echo "<strong><i>&nbsp;Notes:&nbsp;</strong>".$note."</i>";?>
						</div>
					</div>
					<div class="space-12"></div>
					<!-- Upload and Download file attachments -->			
					<?php   
					   echo $this->partial('partial/attachment.phtml', array('process' => '16', 'process_id'=> $cl_id , 'status' => $cl_status));
					?>					
				    <!-- End of attachment -->
				</div>
			</div>
		</div>
	</div>
</div>
<!-- for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script type="text/javascript">
	$('#print').genpdfinvoice({
		content: '#report-print',
		src:"<?php echo $this->url('pdfxls', array('action' => 'pdf'));?>",
		orentation:"P",//L =landscape, P = potrait
	});
</script>
