<?php
/**
 * 
 * View -- of Purchase/PurchaseController/indexAction
 * 
 */
 $this->headTitle($this->title);
?>
<?php echo $this->partial('sales/pos/partial.phtml', array('active' => 'receipt')); ?>
<div class="space-12"></div>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="row">
	<div class="col-lg-12">
		<div class="row">
			<form method="post" action="<?php echo $this->url('sales',array('action'=>'receipt')); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-3">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-3">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Credit Receipt" href="<?php echo $this->url('sales', array('action'=>'addreceipt'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add Credit Receipt</span></span>
					</a>
				</div>
			</div>
		</div>
		
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Receipt No.</th>
						<th>Location</th>
						<th>Receipt Date</th>
						<th>Received Amount</th>
						<th class="no-sort no-printpdf">Action</th>						
					</tr>
				</thead>
				<tbody>
					<?php $sl=1;?>
					<?php foreach($this->results as $row): ?>						 
						<tr data-href="<?php echo $this->url('sales', array('action'=>'viewreceipt', 'id'=>$row['id']));?>">
							<td><?php echo $sl++;?></td>
							<td>
							 	<b><?php echo $row['receipt_no'];?></b> &nbsp;&nbsp;&nbsp;							 
								<span style="font-size:12px">
									 <i>
										 <span class="label label-info"> 
											<?php echo $row['customer'];?> &nbsp;&nbsp;&nbsp;
										 </span>
									</i>        
									 &nbsp;
									 <?php $this->status($row['status']);?>
								</span>									     
							</td>
							<td><?php echo $row['location_name']; ?></td>
							<td><?php echo $row['receipt_date'];?></td>
							<td><?php echo $this->currency($row['amount']);?></td>
							<td class="action">
								<div class="btn-group">
									<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "19-".$row['id'])); ?>" title="View Activity Logs">
										<i class="ace-icon fa fa-plus bigger-120" ></i>  
							  		</a>
						  		</div>
							</td>								
						</tr>					
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
</script>
