<?php
/**
 * View -- of Sales/SalesController/salesAction
 */
	$this->headTitle($this->title);	
?>
<?php echo $this->partial('sales/pos/partial.phtml', array('active' => 'slbooking')); ?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller"> 
					<i class="fa fa-"></i> <?php echo $this->title; ?>
				</h5>
			</div>
			<div class="widget-body">
				<div class="widget-main">
				 <div class="alert alert-info fade in">  
				    * <b>When you submit End of Session</b>
				     <ol>
				       <li>It books all the sales(Cash and Credit) in to Finance Module</li>
				       <li>Schemes Provided by the suppliers are also booked into Finance Module</li>
				     </ol>
				 </div>
				 <div class="alert alert-warning fade in">  
				    * <b>Note : </b>
				     <ol>
				       <li class="red"> Please select 'Food and Essential Commodities Department' for Agency and Food Grain and 'Agricultural Marketing and Services Department' for RNR Sales.
				       Henceforth, these sales must book separately in finance module.</li>
				     </ol>
				 </div>
					<form id="#form" method="post" action="<?php echo $this->url('sales', array('action' => 'slbooking')); ?>"  enctype="multipart/form-data" >    
						<div class="row">
						    <div class="col-lg-3"> 
								<div class="form-group">
									<label for="department" class="control-label">Select Department</label>
									<select id="department" name="department" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
										<?php 
											foreach($this->departments as $department):
										?>
											<?php $selected = ($department['id'] == 1)?"selected":"";?>
											<option value="<?php echo $department['id'];?>" <?php echo $selected; ?>>
												<?php echo $department['department'];?>
											</option>
										<?php endforeach;?>										 
									</select> 
								</div>
							</div>
						    <div class="col-lg-3"> 
								<div class="form-group">
									<label for="location" class="control-label">Location</label>
									<select id="location" name="location" class="form-control" data-placeholder="Select" required>
									  <option value=""></option>
										<?php 
											foreach($admin_locs as $admin_loc):
										?>
											<?php $selected = ($admin_loc['id'] == $user_location)?"selected":"";?>
											<option value="<?php echo $admin_loc['id'];?>" <?php echo $selected; ?>>
												<?php echo $admin_loc['location'];?>
											</option>
										<?php endforeach;?>										 
									</select> 
								</div>
							</div>		
							 <div class="col-lg-3">
						        <div class="form-group">
									<label for="eos_date" class="control-label">End of Session Date </label>
									<div class="date input-group" id="eos_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="eos_date" id="eos_date" type="text" placeholder="End of Session Date" readonly required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
								</div>
						    </div>			           						 
							<div class="col-lg-3"> 
							  <div class="form-group"> <br>
							    <input type="hidden" name="task" value="1">
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> End Of Session </button>
							  </div>
							</div>
						  </div>
			        </form>				
			 </div> 
		   </div>
		</div>
	</div>
</div>
<script type="text/javascript">
$(function() {
	$('#eos_date').datepicker();
	$('#eos_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	//formValidation
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'eos_date': {
				validators: {
					notEmpty: {
						message: 'Please provide the date for EOS'
					}
				}
			},
			'location': {
				validators: {
					notEmpty: {
						message: 'Please Select a location'
					}
				}
			},
			'department': {
				validators: {
					notEmpty: {
						message: 'Please Select a department'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});	
</script>
