<?php
/**
 * View -- of Sales/SalesController/salesAction
 */
	$this->headTitle($this->title);	
	$flag = "1"; $flag1 = "1";
?>
<div class="space"></div>
<div class="col-lg-12">
	<div class="widget-box transparent">		
		<div class="widget-body">
			<div class="widget-main padding-24">
				<form id="#form" method="post" action="<?php echo $this->url('sales', array('action' => 'slbooking')); ?>"  enctype="multipart/form-data" >    
        		  <?php if($location > 0 && !empty($this->eos_date)){  
        		          $location_name = $this->locationObj->getColumn($location,'location'); 
        		          
        		      	  //select all sales base on location, eos_date, status-3, credit and group by activity
        	    	 /*    SELECT *FROM sl_sales s INNER JOIN sl_sales_dtls sd ON s.sales_no = sd.`sales` INNER JOIN st_items i ON sd.`item` = i.`id` WHERE s.`sales_date`='2015-09-09' AND s.location='14' AND i.`activity` = '2';  */
        	    	      // cash Sales booking
        	    	    ?>  
        	    	    <input type="hidden" name="location" value="<?php echo $location; ?>">
        	    	    <input type="hidden" name="eos_date" value="<?php echo $this->eos_date; ?>">
        	    	    
            			<h3 class="widget-title grey lighter">
            				<i class="ace-icon fa fa-file-text-o green"></i>
            				Cash Sales | <?php echo $location_name; ?> | <?php echo $this->eos_date; ?> 
            			</h3>
            			            		
        	    	    <div class="row">
    						<table class="table table-striped table-bordered table-condensed">	
    							<thead>    							
    								<th>Activity</th>
    								<th>Head Name</th>
    								<th>Sub Head Account</th>    			
    								<th>Amount Dr(<?php echo $this->currency_code();?>)</th>
    								<th>Amount Cr(<?php echo $this->currency_code();?>)</th>
    							</thead>
    							<tbody>
                	    	    <?php 
                	    	    $cashSalesAmt = 0;
                	    	    $total_credit = 0;
                	    	    $total_debit = 0;
                	    	    $countSales = 0;
                	    	    foreach ($this->activities as $activity):
                	    	       $condition = array('i.activity' => $activity['id'], 's.location' =>$location, 's.sales_date' => $this->eos_date, 's.credit'=>0, 's.transaction'=>0, 's.status'=>3);
                	    	       $saleDetails = $this->salesDtlObj->getByActivity($condition);
                	    	      
                	    	       if(sizeof($saleDetails)):
                	    	           $activityAmt = 0;
                	    	           $schemeAmt = 0;
                	    	           $totalSchemeAmt = 0;
                	    	           $schemeArray = array();
                	    	           $salesIDArray = array();
                	    	           foreach ($saleDetails as $salesDtl):
                                           //echo"<pre>";  print_r($salesDtl);
                	    	               $countSales++; 
                                           $activityAmt  = $activityAmt + ($salesDtl['rate'] * $salesDtl['quantity']);                                     
                                           if($salesDtl['scheme_dtls'] > 0):
                                               // Scheme Discount
                                               if($salesDtl['free_item'] == 0 && $salesDtl['discount_qty'] != 0){
                                               	  $schemeAmt = $salesDtl['discount_qty'];
                                               	  $activityAmt = $activityAmt - $schemeAmt;
                                               }                                               
                		                       elseif($salesDtl['free_item'] > 0){
                                               	//Free Item Scheme
                                               	  $itemValuation = $this->itemObj->getColumn($salesDtl['free_item'],"valuation");
                                               	  $batch = $this->batchObj->getMax($column='id', $where = array('item'=>$salesDtl['free_item']));
                                               	  $batchUom = $this->batchObj->getColumn($batch,$column='uom');
                                               	  if($itemValuation == "1"){
                                               	  	  //moving average - get the price from moving_item table
                                               	  	  $selling_price = $this->movingItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'location'=>$location), "selling_price");
                                               	  	  if($batchUom == $salesDtl['free_item_uom']) {
                                               	  	  	$schemeAmt = $selling_price * $salesDtl['discount_qty'];
                                               	  	  }
                                               	  	  else{
                                               	  	  	$uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
                                               	  	  	if ($uomConversion > 0){
                                               	  	  	    $schemeAmt = $uomConversion * $salesDtl['discount_qty'] * $selling_price ;
                                               	  	  	}
                                               	  	  	else{
                                               	  	  		$schemeAmt = 0;
                                               	  	  	}
                                               	  	  }
                                               	  	 }
                                               	  else{
                                               	  	  //FIFO - get the price from batch table                                               	  	  
                                               	  	  $selling_price = $this->batchDtlsObj->getColumn(array('batch'=>$batch, 'location'=>$location), 'selling_price');
                                               	  	  if($batchUom == $salesDtl['free_item_uom']) {                                               	  	                                                     
                                                        $schemeAmt = $selling_price * $salesDtl['discount_qty'];
                                                      }
                                                      else{
                                                         $uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
                                                         if ($uomConversion > 0){
                                                            $schemeAmt = $uomConversion * $salesDtl['discount_qty'] * $selling_price ; 
                                                          }
                                                          else{
                                                          	 $schemeAmt = 0;
                                                          }
                                                      }                                               	  	  
                                                    }
                                               // 	$schemeAmt = $salesDtl['discount_qty']; // amt of free items
                                               } 
                                               $totalSchemeAmt = $totalSchemeAmt + $schemeAmt;                                               
                                               $schemeArray[$salesDtl['id']] = $schemeAmt;
                                            endif; 
                                        
                                            if(!in_array($salesDtl['sales_id'], $salesIDArray)){
                                            	  array_push($salesIDArray, $salesDtl['sales_id']);
                                            }
                                       endforeach;                                       
                                       for ($i = 0; $i < sizeof($salesIDArray);$i++):
                                           ?>
                                            <input type="hidden" name="sales_id[]" value="<?php echo $salesIDArray[$i];?>">
                                           <?php 
                                       endfor;
                                       $debit = $activityAmt;
                                       $credit = $activityAmt + $totalSchemeAmt;
                                       ?>
                                          <tr>
                                             <td>
                                               <?php echo $activity['activity']; ?>
                                               <input type="hidden" name="activity[]" value="<?php echo $activity['id'];?>">
                                             </td> 
                                             <?php 
                                                $cashAccDtls = $this->cashAccObj->get(array('ca.location'=>$location)); 
                                                foreach ($cashAccDtls as $cashAccDtl);
                                                $cashAccID = $cashAccDtl['id'];
                                                $subHeadDtls = $this->subHeadObj->get(array('sh.type'=>'6','sh.ref_id'=>$cashAccID));
                                                 if(sizeof($subHeadDtls) == 0) { $flag = "0"; }	
												foreach ($subHeadDtls as $subHeadDtl);                                                
                                             ?>                                        
                                             <td>
                                                <?php echo $subHeadDtl['head']; ?>
                                                 <input type="hidden" name="head[]" value="<?php echo $subHeadDtl['head_id'];?>">
                                             </td>
                                             <td><?php echo $subHeadDtl['code']; ?>
                                                 <input type="hidden" name="subhead[]" value="<?php echo $subHeadDtl['id'];?>">
                                             </td>
                                             <td><?php echo $debit; ?>
                                                 <input type="hidden" name="debit[]" value="<?php echo $debit;?>">
                                             </td>
                                             <td>&nbsp;
                                                 <input type="hidden" name="credit[]" value="0">
                                             </td>                                       
                                           </tr>                                           
                                           <tr>
                                             <td><?php echo $activity['activity']; ?>
                                               <input type="hidden" name="activity[]" value="<?php echo $activity['id'];?>"></td>   
                                             <?php
                                              $incomeheadDtls = $this->incomeHeadObj->get(array('activity'=>$activity['id'],'credit_sales'=>'0')); 
                                              foreach ($incomeheadDtls as $incomeheadDtl);
                                              $subHeadDtls2 = $this->subHeadObj->get(array('sh.type'=>'7','sh.ref_id'=>$incomeheadDtl['id']));
											   if(sizeof($subHeadDtls2) == 0) { $flag = "0"; }		
											 foreach ($subHeadDtls2 as $subHeadDtl2);
                                              ?>                                      
                                             <td>
                                                <?php echo $subHeadDtl2['head']; ?>
                                                 <input type="hidden" name="head[]" value="<?php echo $subHeadDtl2['head_id'];?>">
                                             </td>
                                             <td><?php echo $subHeadDtl2['code']; ?>
                                                 <input type="hidden" name="subhead[]" value="<?php echo $subHeadDtl2['id'];?>">
                                             </td>
                                             <td>&nbsp;
                                                 <input type="hidden" name="debit[]" value="0">
                                             </td>
                                             <td><?php echo $credit; ?>
                                                 <input type="hidden" name="credit[]" value="<?php echo $credit; ?>">
                                             </td>                                                                             
                                        </tr>
                                        <?php 
                                         $schemeAmount = 0;
                                            if(sizeof($schemeArray) > 0):
                                             foreach ($schemeArray as $key=>$schemeDtl):
                            	    	        $saleDetail_id = $key;
                            	    	        $schemeDetailAmt = $schemeDtl;
                            	    	        $schemeAmount = $schemeAmount + $schemeDetailAmt;
                            	    	        ?>
                            	    	        <tr>
                                                     <td><?php echo $activity['activity']; ?>
                                                      <input type="hidden" name="activity[]" value="<?php echo $activity['id'];?>"></td>   
                                                     <?php
                                                      $schemedtl_id = $this->salesDtlObj->getColumn($saleDetail_id,'scheme_dtls');
                                                      $scheme_id = $this->schemeDtlObj->getColumn($schemedtl_id, 'scheme');
                                                      $schemeResults = $this->schemeObj->get($scheme_id);
                                                      foreach ($schemeResults as $result);
                                                      $subHeadDtls3 = $this->subHeadObj->get($result['sub_head']);
													  if(sizeof($subHeadDtls3) == 0) { $flag = "0"; }
                                                      foreach ($subHeadDtls3 as $subHeadDtl3);                                             
                                                      ?>                                      
                                                     <td><?php echo $subHeadDtl3['head']; ?>
                                                        <input type="hidden" name="head[]" value="<?php echo $subHeadDtl3['head_id'];?>">
                                                     </td>
                                                     <td><?php echo $subHeadDtl3['code']; ?>
                                                       <input type="hidden" name="subhead[]" value="<?php echo $subHeadDtl3['id'];?>">
                                                     </td>
                                                     <td><?php echo $schemeDetailAmt; ?>
                                                      <input type="hidden" name="debit[]" value="<?php echo $schemeDetailAmt; ?>"></td>
                                                     <td>&nbsp;
                                                      <input type="hidden" name="credit[]" value="0"></td>                                       
                                                    </tr>
                            	    	        <?php 
                            	    	    endforeach; 
                            	    	   endif;               	    	 
                                       $total_credit = $total_credit + $credit;
                                       $total_debit = $total_debit + $debit + $schemeAmount; 
                                   endif; 
                	    	    endforeach;
                	    	    $voucher_amount = $total_credit; 
                	    	    if($countSales == 0){ ?>
	                               <tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
	                               <th colspan="5"> * No Cash Sales to book</th>
	                               </tr>
	                            <?php 
	                            }
	                            else{
                	    	   ?>
                	    	   
                    	    	    <tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
    									<th colspan="2"><?php echo $this->numtoWords($voucher_amount);?>
    									 <input type="hidden" name="voucher_amount" value="<?php echo $voucher_amount;?>">
    									</th>
    									<th>TOTAL:</th>
    									<th><?php echo $total_debit;?></th>
    									<th><?php echo $total_credit;?></th>
    								</tr>
    						<?php } ?>
        	    	            </tbody> 
        	    	          </table>
        	    	      </div>
        	    	      
        	    	     <!-- Booking of Credit Sales --> 
        	    	    <h3 class="widget-title grey lighter">
            				<i class="ace-icon fa fa-file-text-o green"></i>
            				Credit Sales | <?php echo $location_name; ?> | <?php echo $this->eos_date; ?>
            			</h3>
            			            		
        	    	    <div class="row">
    						<table class="table table-striped table-bordered table-condensed">	
    							<thead>    							
    								<th>Activity</th>
    								<th>Head Name</th>
    								<th>Sub Head Account</th>    			
    								<th>Amount Dr(<?php echo $this->currency_code();?>)</th>
    								<th>Amount Cr(<?php echo $this->currency_code();?>)</th>
    							</thead>
    							<tbody>
        	    	      <?php 
                        //credit sales Booking
        	    	      $cashSalesAmt1 = 0;
        	    	      $total_credit1 = 0;
        	    	      $total_debit1 = 0;
        	    	      $countCredit = 0;
        	    	     foreach ($activities as $activity):
        	    	         //echo "<pre>";print_r($activity);
        	    	       $condition = array('i.activity' => $activity['id'], 's.location' => $location, 's.sales_date' => $this->eos_date, 's.credit'=>1, 's.transaction'=>0, 's.status'=>3);
        	    	       $saleDetails = $this->salesDtlObj->getByActivity($condition);
                           if(sizeof($saleDetails)):
                               $activityAmt1 = 0;                              
                               $totalSchemeAmt1 = 0;
                               $schemeArray1 = array();
                               $salesIDArray1 = array();
                               $debitAmt = 0;
                               foreach ($saleDetails as $salesDtl):
                                //  echo"<pre>";  print_r($salesDtl);                                             
                                   $schemeAmt1 = 0;
                                   $debitAmt = 0;
                                   $countCredit++;
                                   $activityAmt1  = $activityAmt1 + ($salesDtl['rate'] * $salesDtl['quantity']); 
                                   $debitAmt = ($salesDtl['rate'] * $salesDtl['quantity']);                                    
                                   if($salesDtl['scheme_dtls'] > 0):
                                       // Scheme Discount
                                       if($salesDtl['free_item'] == 0 && $salesDtl['discount_qty'] != 0){                                       	
                                       	  $schemeAmt1 = $salesDtl['discount_qty'];
                                       	  $debitAmt = $debitAmt  - $schemeAmt1;
                                       	  $activityAmt1 = $activityAmt1 - $schemeAmt1;
                                       }                                               
                                       elseif($salesDtl['free_item'] > 0){
                                       	//Free Item Scheme
                                       	$itemValuation = $this->itemObj->getColumn($salesDtl['free_item'],"valuation");
                                        $batch = $this->batchObj->getMax($column='id', $where = array('item'=>$salesDtl['free_item']));
                                        $batchUom = $this->batchObj->getColumn($batch,$column='uom');
                                        if($itemValuation == "1"){
                                        	//moving average - get the price from moving_item table
                                        	$selling_price = $this->movingItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'location'=>$location), "selling_price");
                                        	if($batchUom == $salesDtl['free_item_uom']) {
                                        		$schemeAmt1 = $selling_price * $salesDtl['discount_qty'];
                                        	}
                                        	else{
                                        		$uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
                                        		if ($uomConversion > 0){
                                        			$schemeAmt1 = $uomConversion * $salesDtl['discount_qty'] * $selling_price ;
                                        		}
                                        		else{
                                        			$schemeAmt1 = 0;
                                        		}
                                        	}
                                        }
                                        else{
                                        	//FIFO - get the price from batch table
                                        	$selling_price = $this->batchDtlsObj->getColumn(array('batch'=>$batch, 'location'=>$location), 'selling_price');
                                        	if($batchUom == $salesDtl['free_item_uom']) {
                                        		$schemeAmt1 = $selling_price * $salesDtl['discount_qty'];
                                        	}
                                        	else{
                                        		$uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
                                        		if ($uomConversion > 0){
                                        			$schemeAmt1 = $uomConversion * $salesDtl['discount_qty'] * $selling_price ;
                                        		}
                                        		else{
                                        			$schemeAmt1 = 0;
                                        		}
                                        	}
                                        }
                                       // 	$schemeAmt = $salesDtl['discount_qty']; // amt of free items
                                       }
                                       $totalSchemeAmt1 = $totalSchemeAmt1 + $schemeAmt1;
                                       $schemeArray1[$salesDtl['id']] = $schemeAmt1;
                                    endif;  
                                    
                                    if(!in_array($salesDtl['sales_id'], $salesIDArray1)){
                                    	array_push($salesIDArray1, $salesDtl['sales_id']);
                                    }
                                    ?>
                                    <tr>
                                    <td><?php echo $activity['activity']; ?>
                                      <input type="hidden" name="activity1[]" value="<?php echo $activity['id']; ?>">
                                    </td>
                                    <?php                                   
                                   $subHeadDtls = $this->subHeadObj->get(array('sh.type'=>'2','sh.ref_id'=>$salesDtl['customer'],'sh.head'=>'207'));
								   if(sizeof($subHeadDtls) == 0) { $flag1 = "0"; }	
                                   foreach ($subHeadDtls as $subHeadDtl);                                                
                                    ?>                                        
                                    <td><?php echo $subHeadDtl['head']; ?>
                                       <input type="hidden" name="head1[]" value="<?php echo $subHeadDtl['head_id'];?>">
                                    </td>
                                    <td><?php echo $subHeadDtl['code']; ?>
                                    <input type="hidden" name="subhead1[]" value="<?php echo $subHeadDtl['id']; ?>">
                                    </td>
                                    <td><?php echo $debitAmt; ?>
                                      <input type="hidden" name="debit1[]" value="<?php echo $debitAmt; ?>">
                                    </td>
                                    <td>&nbsp;
                                       <input type="hidden" name="credit1[]" value="0">
                                    </td>                                       
                                  </tr>
                              <?php                                                                                 
                               endforeach;                               
                               for ($i = 0; $i < sizeof($salesIDArray1);$i++):
                               ?>
                                   <input type="hidden" name="sales_id1[]" value="<?php echo $salesIDArray1[$i];?>">
                                  <?php 
                               endfor;                           
                               $debit1 = $activityAmt1;
                               $credit1 = $activityAmt1 + $totalSchemeAmt1;                               
                               ?>                                                         
                              <tr>
                                <td><?php echo $activity['activity']; ?>
                                <input type="hidden" name="activity1[]" value="<?php echo $activity['id']; ?>"></td>   
                                <?php
                                 $incomeheadDtls = $this->incomeHeadObj->get(array('activity'=>$activity['id'],'credit_sales'=>'1')); 
                                 foreach ($incomeheadDtls as $incomeheadDtl);
                                 $subHeadDtls2 = $this->subHeadObj->get(array('sh.type'=>'7','sh.ref_id'=>$incomeheadDtl['id']));
								 if(sizeof($subHeadDtls2) == 0) { $flag1 = "0"; }
                                 foreach ($subHeadDtls2 as $subHeadDtl2);
                                 ?>                                      
                               <td><?php echo $subHeadDtl2['head']; ?>
                               <input type="hidden" name="head1[]" value="<?php echo $subHeadDtl2['head_id'];?>">
                               </td>
                                <td><?php echo $subHeadDtl2['code']; ?>
                                <input type="hidden" name="subhead1[]" value="<?php echo $subHeadDtl2['id']; ?>">
                                </td>
                                <td>&nbsp;
                                <input type="hidden" name="debit1[]" value="0"></td>
                                <td><?php echo $credit1; ?>
                                 <input type="hidden" name="credit1[]" value="<?php echo $credit1; ?>"></td>                                       
                           </tr>
                            <?php 
                               $schemeAmount1 = 0;                             
                               if(sizeof($schemeArray1) > 0):
                                foreach ($schemeArray1 as $key1=>$schemeDtl1):
               	    	        $saleDetail_id1 = $key1;
               	    	        $schemeDetailAmt1 = $schemeDtl1;
               	    	        $schemeAmount1 = $schemeAmount1 + $schemeDetailAmt1;
               	    	        ?>
               	    	        <tr>
                                    <td><?php echo $activity['activity']; ?>
                                    <input type="hidden" name="activity1[]" value="<?php echo $activity['id']; ?>">
                                    </td>   
                                    <?php
                                     $schemedtl_id1 = $this->salesDtlObj->getColumn($saleDetail_id1,'scheme_dtls');
                                     $scheme_id1 = $this->schemeDtlObj->getColumn($schemedtl_id1, 'scheme');
                                     $schemeResults1 = $this->schemeObj->get($scheme_id1);
                                     foreach ($schemeResults1 as $result1);
                                     $subHeadDtls3 = $this->subHeadObj->get($result1['sub_head']);
									 if(sizeof($subHeadDtls3) == 0) { $flag1 = "0"; }
                                     foreach ($subHeadDtls3 as $subHeadDtl3);                                             
                                     ?>                                      
                                    <td><?php echo $subHeadDtl3['head']; ?>
                                    <input type="hidden" name="head1[]" value="<?php echo $subHeadDtl3['head_id'];?>">
                                    </td>
                                    <td><?php echo $subHeadDtl3['code']; ?>
                                       <input type="hidden" name="subhead1[]" value="<?php echo $subHeadDtl3['id']; ?>">
                                    </td>
                                    <td><?php echo $schemeDetailAmt1; ?>
                                     <input type="hidden" name="debit1[]" value="<?php echo $schemeDetailAmt1; ?>"></td>
                                    <td>&nbsp;
                                       <input type="hidden" name="credit1[]" value="0">
                                    </td>                                       
                                  </tr>
               	    	        <?php 
               	    	    endforeach; 
               	    	   endif;               	    	 
                              $total_credit1 = $total_credit1 + $credit1;
                              $total_debit1 = $total_debit1 + $debit1 + $schemeAmount1; 
                           endif; 
        	    	    endforeach;
        	    	    $voucher_amount1 = $total_credit1;
        	    	    if($countCredit == 0){ ?>
                           <tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
                           <th colspan="5"> * No Credit Sales to book</th>
                           </tr>
                        <?php 
                        }
                        else{
        	    	    ?>
        	    	      <tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
    									<th colspan="2"><?php echo $this->numtoWords($voucher_amount1);?>
    									<input type="hidden" name="voucher_amount1" value="<?php echo $voucher_amount1;?>">
    									</th>
    									<th>TOTAL:</th>
    									<th><?php echo $total_debit1;?></th>
    									<th><?php echo $total_credit1;?></th>
    								</tr>
    				 <?php } ?>
        	    	            </tbody> 
        	    	          </table>
        	    	      </div>
        	    	      <?php $salesCount = $countSales + $countCredit; ?>
        	    	      <div id="row">
							<div class="col-lg-8">
							  <div class="alert alert-success fade in">  
            				    * <b>When you click on commit button</b>
            				     <ol>
            				       <li>All the sales(Cash and Credit) and schemes for the selected date will be booked in Finance</li>
            				     </ol>
            				 </div>
							</div>
							<div class="col-lg-4"> 
							<?php 
							
								$salesCount = $countSales + $countCredit;
								$fslocations = $this->fslocationObj->get(array('l.id' =>$location,'l.location_type'=>'8'));
								foreach($fslocations as $row);
								if($salesCount > 0 || $location == $row['id']) : 
								    //echo $flag; echo "</br>";echo $flag1; exit;
									 if(($flag == "1" && $flag1 == "1") || $location == $row['id']){ ?>
									 
									  <div class="form-group">
										<input type="hidden" name="task" value="2">
										<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Commit </button>
										<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('sales');?>'" ><i class="fa fa-times"></i> Cancel </button>
									  </div>
									<?php
									}else{
										?>
										<div class="alert alert-danger fade in">  
										  *<b>Booking is not possible rite now as Ledger and Sub-Ledger are not mapped properly</b>									
										</div>
										<?php								
									}
									?>
								<?php else: ?>
									<div class="alert alert-warning fade in">  
										* <b>No Sales to commit End of Session</b>  
									 </div>
								<?php endif; ?>
								</div>
							
							
        	    	      </div>
        	    	<?php } ?>
			            </form>				
			 </div> 
		   </div>
		</div>
	</div>

<script type="text/javascript">
$(function() {
	$('#eos_date').datepicker();
	$('#eos_date').on('changeDate',function(){
		$('form').formValidation('revalidateField', $(this).attr('id'));
	});
	//formValidation
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'eos_date': {
				validators: {
					notEmpty: {
						message: 'Please provide the date for EOS'
					}
				}
			},
			'location': {
				validators: {
					notEmpty: {
						message: 'Please Select a location'
					}
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});	
});	
</script>
