<?php
/**
 * View -- of Sales/SalesController/salesAction
 */
	$this->headTitle($this->title);
?>
<?php foreach($slbooking as $slbooking):
		extract($slbooking);
		endforeach;
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget-box transparent">
			<div class="widget-body">
				<div class="widget-main padding-24">
					<div class="row">
					  <?php foreach ($this->slbooking as $slbooking);
							if($slbooking['cash_voucher_id'] > 0):
						?>
							<h3 class="widget-title grey">
								Cash Sales | <?php echo $this->transactionObj->getColumn($cash_voucher_id,'voucher_no');?> 
							</h3>
							<div class="space-6"></div>
							<div class="row">
								<table class="table table-striped table-bordered table-condensed">	
									<thead>    							
										<th>Activity</th>
										<th>Head Name</th>
										<th>Sub Head Account</th>    			
										<th>Amount Dr(<?php echo $this->currency_code();?>)</th>
										<th>Amount Cr(<?php echo $this->currency_code();?>)</th>
									</thead>
									<tbody>
									<?php 
									$cashSalesAmt = 0;
									$total_credit = 0;
									$total_debit = 0;
									
									foreach ($this->activities as $activity):
									   $condition = array('i.activity' => $activity['id'], 's.location' => $location, 's.sales_date' => $eos_date, 's.credit'=>0, 's.transaction'=>$slbooking['cash_voucher_id']);
									   $saleDetails = $this->salesDtlObj->getByActivity($condition);
										if(sizeof($saleDetails)):
										   $activityAmt = 0;
										   $schemeAmt = 0;
										   $totalSchemeAmt = 0;
										   $schemeArray = array();
										   $salesIDArray = array();
										   foreach ($saleDetails as $salesDtl):
											   //echo"<pre>";  print_r($salesDtl);
											   $activityAmt  = $activityAmt + ($salesDtl['rate'] * $salesDtl['quantity']);                                     
											   if($salesDtl['scheme_dtls'] > 0):
												   // Scheme Discount
												   if($salesDtl['free_item'] == 0 && $salesDtl['discount_qty'] != 0){
													  $schemeAmt = $salesDtl['discount_qty'];
													  $activityAmt = $activityAmt - $schemeAmt;
												   }                                               
												   elseif($salesDtl['free_item'] > 0){
													//Free Item Scheme
													  $itemValuation = $this->itemObj->getColumn($salesDtl['free_item'],"valuation");
													  $batch = $this->batchObj->getMax($column='id', $where = array('item'=>$salesDtl['free_item']));
													  $batchUom = $this->batchObj->getColumn($batch,$column='uom');
													  if($itemValuation == "1"){
														  //moving average - get the price from moving_item table
														  $selling_price = $this->movingItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'location'=>$this->location), "selling_price");
														  if($batchUom == $salesDtl['free_item_uom']) {
															$schemeAmt = $selling_price * $salesDtl['discount_qty'];
														  }
														  else{
															$uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
															if ($uomConversion > 0){
																$schemeAmt = $uomConversion * $salesDtl['discount_qty'] * $selling_price ;
															}
															else{
																$schemeAmt = 0;
															}
														  }
														 }
													  else{
														  //FIFO - get the price from batch table                                               	  	  
														  $selling_price = $this->batchDtlsObj->getColumn(array('batch'=>$batch, 'location'=>$this->location), 'selling_price');
														  if($batchUom == $salesDtl['free_item_uom']) {                                               	  	                                                     
															$schemeAmt = $selling_price * $salesDtl['discount_qty'];
														  }
														  else{
															 $uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
															 if ($uomConversion > 0){
																$schemeAmt = $uomConversion * $salesDtl['discount_qty'] * $selling_price ; 
															  }
															  else{
																 $schemeAmt = 0;
															  }
														  }                                               	  	  
														}
												   // 	$schemeAmt = $salesDtl['discount_qty']; // amt of free items
												   } 
												   $totalSchemeAmt = $totalSchemeAmt + $schemeAmt;                                               
												   $schemeArray[$salesDtl['id']] = $schemeAmt;
												endif;
										   endforeach;                                       
										   $debit = $activityAmt;
										   $credit = $activityAmt + $totalSchemeAmt;
										   ?>
											<tr>
												<td><?php echo $activity['activity']; ?></td> 
												<?php 
													$cashAccDtls = $this->cashAccObj->get(array('ca.location'=>$location)); 
													foreach ($cashAccDtls as $cashAccDtl);
													$cashAccID = $cashAccDtl['id'];
													$subHeadDtls = $this->subHeadObj->get(array('sh.type'=>'6','sh.ref_id'=>$cashAccID));
													 if(sizeof($subHeadDtls) == 0) { $flag = "0"; }	
													foreach ($subHeadDtls as $subHeadDtl);                                                
												?>                                        
												<td><?php echo $subHeadDtl['head']; ?></td>
												<td><?php echo $subHeadDtl['code']; ?></td>
												<td><?php echo number_format($debit, 2, '.', ',');?></td>
												<td></td>                                       
											</tr>                                           
											<tr>
												<td><?php echo $activity['activity']; ?></td>   
												<?php
												$incomeheadDtls = $this->incomeHeadObj->get(array('activity'=>$activity['id'],'credit_sales'=>'0')); 
												foreach ($incomeheadDtls as $incomeheadDtl);
												$subHeadDtls2 = $this->subHeadObj->get(array('sh.type'=>'7','sh.ref_id'=>$incomeheadDtl['id']));
												if(sizeof($subHeadDtls2) == 0) { $flag = "0"; }		
												foreach ($subHeadDtls2 as $subHeadDtl2);
												?>                                      
												<td><?php echo $subHeadDtl2['head']; ?></td>
												<td><?php echo $subHeadDtl2['code']; ?></td>
												<td></td>
												<td><?php echo number_format($credit, 2, '.', ','); ?></td>                                                                             
											</tr>
											<?php 
											 $schemeAmount = 0;
												if(sizeof($schemeArray) > 0):
												foreach ($schemeArray as $key=>$schemeDtl):
													$saleDetail_id = $key;
													$schemeDetailAmt = $schemeDtl;
													$schemeAmount = $schemeAmount + $schemeDetailAmt;
													?>
													<tr>
														 <td><?php echo $activity['activity']; ?></td> 
														 <?php
														  $schemedtl_id = $this->salesDtlObj->getColumn($saleDetail_id,'scheme_dtls');
														  $scheme_id = $this->schemeDtlObj->getColumn($schemedtl_id, 'scheme');
														  $schemeResults = $this->schemeObj->get($scheme_id);
														  foreach ($schemeResults as $result);
														  $subHeadDtls3 = $this->subHeadObj->get($result['sub_head']);
														  foreach ($subHeadDtls3 as $subHeadDtl3);                                             
														  ?>                                      
														 <td><?php echo $subHeadDtl3['head']; ?></td>
														 <td><?php echo $subHeadDtl3['code']; ?></td>
														 <td><?php echo number_format($schemeDetailAmt, 2, '.', ',');?></td>
														 <td></td>                                       
													</tr>
													<?php 
												endforeach; 
												endif;               	    	 
											$total_credit = $total_credit + $credit;
											$total_debit = $total_debit + $debit + $schemeAmount; 
										endif;  
									endforeach;
									$voucher_amount = $total_credit; 
									?>
									<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
										<th colspan="2"><?php echo $this->numtoWords($voucher_amount);?></th>
										<th>TOTAL:</th>
										<th><?php echo number_format($total_debit, 2, '.', ',');?></th>
										<th><?php echo number_format($total_credit, 2, '.', ',');?></th>
									</tr>
									</tbody> 
								</table>
							</div>
							<?php endif;?>
							  
							 <!-- Booking of Credit Sales --> 
						<?php 	if($slbooking['credit_voucher_id'] > 0): ?>
							<h3 class="widget-title grey">
								Credit Sales | <?php echo $this->transactionObj->getColumn($credit_voucher_id,'voucher_no');?>
							</h3>
							<div class="space-6"></div>					
							<div class="row">
								<table class="table table-striped table-bordered table-condensed">	
									<thead>    							
										<th>Activity</th>
										<th>Head Name</th>
										<th>Sub Head Account</th>    			
										<th>Amount Dr(<?php echo $this->currency_code();?>)</th>
										<th>Amount Cr(<?php echo $this->currency_code();?>)</th>
									</thead>
									<tbody>
									  <?php 
									//credit sales Booking
									  $cashSalesAmt1 = 0;
									  $total_credit1 = 0;
									  $total_debit1 = 0;
									 
									foreach ($activities as $activity):
									   $condition = array('i.activity' => $activity['id'], 's.location' => $location, 's.sales_date' => $eos_date, 's.credit'=>1, 's.transaction'=>$slbooking['credit_voucher_id']);
									   $saleDetails = $this->salesDtlObj->getByActivity($condition);
									   if(sizeof($saleDetails)):
										   $activityAmt1 = 0;                              
										   $totalSchemeAmt1 = 0;
										   $schemeArray1 = array();
										   $salesIDArray1 = array();
										   $debitAmt = 0;
										   foreach ($saleDetails as $salesDtl):
											//  echo"<pre>";  print_r($salesDtl);                                             
											   $schemeAmt1 = 0;
											   $debitAmt = 0;
											   $activityAmt1  = $activityAmt1 + ($salesDtl['rate'] * $salesDtl['quantity']); 
											   $debitAmt = ($salesDtl['rate'] * $salesDtl['quantity']);                                    
											   if($salesDtl['scheme_dtls'] > 0):
												   // Scheme Discount
												   if($salesDtl['free_item'] == 0 && $salesDtl['discount_qty'] != 0){                                       	
													  $schemeAmt1 = $salesDtl['discount_qty'];
													  $debitAmt = $debitAmt  - $schemeAmt1;
													  $activityAmt1 = $activityAmt1 - $schemeAmt1;
												   }                                               
												   elseif($salesDtl['free_item'] > 0){
													//Free Item Scheme
													$itemValuation = $this->itemObj->getColumn($salesDtl['free_item'],"valuation");
													$batch = $this->batchObj->getMax($column='id', $where = array('item'=>$salesDtl['free_item']));
													$batchUom = $this->batchObj->getColumn($batch,$column='uom');
													if($itemValuation == "1"){
														//moving average - get the price from moving_item table
														$selling_price = $this->movingItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'location'=>$this->location), "selling_price");
														if($batchUom == $salesDtl['free_item_uom']) {
															$schemeAmt1 = $selling_price * $salesDtl['discount_qty'];
														}
														else{
															$uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
															if ($uomConversion > 0){
																$schemeAmt1 = $uomConversion * $salesDtl['discount_qty'] * $selling_price ;
															}
															else{
																$schemeAmt1 = 0;
															}
														}
													}
													else{
														//FIFO - get the price from batch table
														$selling_price = $this->batchDtlsObj->getColumn(array('batch'=>$batch, 'location'=>$this->location), 'selling_price');
														if($batchUom == $salesDtl['free_item_uom']) {
															$schemeAmt1 = $selling_price * $salesDtl['discount_qty'];
														}
														else{
															$uomConversion = $this->uomItemObj->getColumn(array('item'=>$salesDtl['free_item'], 'uom'=>$salesDtl['free_item_uom']), 'conversion');
															if ($uomConversion > 0){
																$schemeAmt1 = $uomConversion * $salesDtl['discount_qty'] * $selling_price ;
															}
															else{
																$schemeAmt1 = 0;
															}
														}
													}
												   // 	$schemeAmt = $salesDtl['discount_qty']; // amt of free items
												   }
												   $totalSchemeAmt1 = $totalSchemeAmt1 + $schemeAmt1;
												   $schemeArray1[$salesDtl['id']] = $schemeAmt1;
												endif;?>
										<tr>
											<td><?php echo $activity['activity']; ?></td>
											<?php                                   
										   $subHeadDtls = $this->subHeadObj->get(array('sh.type'=>'2','sh.ref_id'=>$salesDtl['customer'],'sh.head'=>'207'));
										  foreach ($subHeadDtls as $subHeadDtl);                                                
											?>                                        
											<td><?php echo $subHeadDtl['head']; ?></td>
											<td><?php echo $subHeadDtl['code']; ?></td>
											<td><?php echo number_format($debitAmt, 2, '.', ',');?></td>
											<td></td>                                       
										</tr>
										  <?php                                                                                 
										   endforeach;                               
										   $debit1 = $activityAmt1;
										   $credit1 = $activityAmt1 + $totalSchemeAmt1;                               
										   ?>                                                         
										<tr>
											<td><?php echo $activity['activity']; ?></td>   
											<?php
											 $incomeheadDtls = $this->incomeHeadObj->get(array('activity'=>$activity['id'],'credit_sales'=>'1')); 
											 foreach ($incomeheadDtls as $incomeheadDtl);
											 $subHeadDtls2 = $this->subHeadObj->get(array('sh.type'=>'7','sh.ref_id'=>$incomeheadDtl['id']));
											 if(sizeof($subHeadDtls2) == 0) { $flag1 = "0"; }
											 foreach ($subHeadDtls2 as $subHeadDtl2);
											 ?>                                      
										   <td><?php echo $subHeadDtl2['head']; ?></td>
											<td><?php echo $subHeadDtl2['code']; ?></td>
											<td></td>
											<td><?php echo number_format($credit1, 2, '.', ',');?></td>                                       
										</tr>
										<?php 
										$schemeAmount1 = 0;                             
										if(sizeof($schemeArray1) > 0):
											foreach ($schemeArray1 as $key1=>$schemeDtl1):
											$saleDetail_id1 = $key1;
											$schemeDetailAmt1 = $schemeDtl1;
											$schemeAmount1 = $schemeAmount1 + $schemeDetailAmt1;
										?>
										<tr>
											<td><?php echo $activity['activity']; ?></td>   
											<?php
											 $schemedtl_id1 = $this->salesDtlObj->getColumn($saleDetail_id1,'scheme_dtls');
											 $scheme_id1 = $this->schemeDtlObj->getColumn($schemedtl_id1, 'scheme');
											 $schemeResults1 = $this->schemeObj->get($scheme_id1);
											 foreach ($schemeResults1 as $result1);
											 $subHeadDtls3 = $this->subHeadObj->get($result1['sub_head']);
											 if(sizeof($subHeadDtls3) == 0) { $flag1 = "0"; }
											 foreach ($subHeadDtls3 as $subHeadDtl3);                                             
											 ?>                                      
											<td><?php echo $subHeadDtl3['head']; ?></td>
											<td><?php echo $subHeadDtl3['code']; ?></td>
											<td><?php echo number_format($schemeAmount1, 2, '.', ',');?></td>
											<td></td>                                       
										</tr>
										<?php 
											endforeach; 
										endif;               	    	 
										$total_credit1 = $total_credit1 + $credit1;
										$total_debit1 = $total_debit1 + $debit1 + $schemeAmount1; 
										endif; 
									endforeach;
										$voucher_amount1 = $total_credit1;
										?>
										<tr style="border-top:2px solid #ddd;border-bottom:2px solid #ddd;">
											<th colspan="2"><?php echo $this->numtoWords($voucher_amount1);?></th>
											<th>TOTAL:</th>
											<th><?php echo number_format($total_debit1, 2, '.', ',');?></th>
											<th><?php echo number_format($total_credit1, 2, '.', ',');?></th>
										</tr>
									</tbody> 
								</table>
							</div>
							<?php endif; ?>
					</div> 
					<div class="space-6"></div>
					<div class="row">
						<label> Prepared by: <?php echo $this->userObj->getColumn($author,'name');?></label>
					</div> 
				</div> 
			</div>
		</div>
	</div>
</div>