<?php
/**
 * 
 * View -- of Stock/MasterController/edituomAction
 * 
 */
?>
<?php 
    foreach($this->classes as $class):
        extract($class);        
    endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('ftmaster', array('action' => 'editvehicleclass', 'id' => $id)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Vehicle class</h4>
    </div>  <!-- /modal-header -->
    
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body"> 
				<div class="form-group">
					<label for="class" class="control-label">Transport Class </label>
					<input type="text" class="form-control" name="class" id="class" value="<?php echo $transport_class;?>" size="30" required> 
				</div>
				<div class="form-group">
					<label for="prefix" class="control-label">Prefix</label>
					<input type="text" class="form-control" name="prefix" id="prefix" value="<?php echo $prefix;?>" size="30" required> 
				</div>
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<input type="text" class="form-control" name="description" id="description" value="<?php echo $description;?>" size="30" required> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			fuel: {
				validators: {
					notEmpty: {
						message: 'Edit class'
					},
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Edit Description'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>

