<?php
/**
 * View -- of Purchase/SupplierController/addsupplierinvAction
 */
$this->headTitle($this->title);
?>
<?php 
	/*if(sizeof($pur_receipts)>0):
		foreach($pur_receipts as $pur_receipt):
			extract($pur_receipt);
		endforeach;
	endif;
	$po_costing = $this->poObj->getColumn($purchase_order,'costing');*/
?>
<div class="row">
	<div class="col-lg-12">
		<div class="widget widget-box">
			<div class="widget-header">
				<h5 class="widget-title lighter smaller">
					<i class="fa fa-asterisk"></i>&nbsp;&nbsp;New Supplier Invoice
					<div class="widget-toolbar hidden-xs">
						<!-- Button trigger modal -->
						<a data-toggle="modal" class="btn btn-white btn-primary btn-bold btn-xs" href="<?php echo $this->url('supplier', array('action' => 'getpreceipt')); ?>" data-target="#modal">
							&nbsp;<i class="fa fa-share"></i>&nbsp;From Purchase Receipt&nbsp;
						</a>
					</div>
                </h5>
			</div>
			<!--for modal -->
			<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content"> </div>
				</div>
			</div>
			<div class="widget-body">
				<div class="widget-main">
					<?php //if(sizeof($pur_receipts)==0):?>
						<div class="row">
							<div class="col-lg-12">
								<div class="alert alert-block alert-info">
									<div class="row">
										<div class="col-lg-9">
											<i class="ace-icon fa fa-check blue"></i>
											Please Select the <strong class="blue"> Purchase Receipt </strong> (PRN) to create New Supplier Invoice.
										</div>
										<div class="col-lg-3">
											<!-- Button trigger modal -->
											<a data-toggle="modal" class="btn btn-primary" href="<?php echo $this->url('supplier', array('action' => 'getpreceipt')); ?>" data-target="#modal">
												<i class="fa fa-share"></i> &nbsp;Get Purchase Receipt
											</a>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="space-12"></div>
					<?php //endif;?>
					<form id="#form" method="post" action="<?php echo $this->url('supplier', array('action' => 'addsupplierinv')); ?>"  enctype="multipart/form-data" >
                    	<input type="hidden" value="<?php echo $po_costing;?>" name="po_costing" id="po_costing"/>
						<div class="row">	
							<div class="form-group col-lg-3">
								<label for="location" class="control-label">Location</label>
								<select class="form-control" id="location" name="location" data-placeholder="Select" required>
									<option value=""></option>
								  	<?php foreach ($regions as $region): ?>
									<optgroup label="<?php echo $region['region'];?>">
										<?php  
											// retrive locations under the above region ID
											$locations = $locationObj->get(array('region'=>$region['id']));
											foreach ($locations as $location):
											$selected = ($location['id']==$location_id)?'selected':'';
										?>
										<option value="<?php echo $location['id']; ?>" <?php echo $selected;?>>
											<?php echo $location['location']; ?>
										</option>
										<?php endforeach; ?>
								    </optgroup>
									<?php endforeach;  ?>									
								</select> 
							</div>	
							<div class="form-group col-lg-3">
								<label for="activity" class="control-label">Activity</label>
								<select id="activity" name="activity" class="form-control" data-placeholder="Select" required>
									<option value=""></option>
									<?php foreach ($this->activities as $activity):
										$selected = ($activity['id'] == $activity_id)?'selected':'';
									?>
								        <option value="<?php echo $activity['id'];?>" <?php echo $selected;?>>
								       		<?php echo $activity['activity']; ?>
								       	</option>
									<?php endforeach; ?>								
								</select> 
							</div>
							<div class="form-group col-lg-3">
								<label for="supplier" class="control-label">Supplier</label>
								<select id="supplier" name="supplier" class="form-control" data-placeholder="Select" required>
									<option value=""></option>	
									<?php foreach ($this->suppliers as $supplier): 
										$selected = ($supplier[id] == $supplier_id)?'selected':'';	
									?>
									    <option value="<?php echo $supplier['id'];?>" <?php echo $selected; ?>>
									    	<?php echo $supplier['name']; ?>
									    </option>
									<?php endforeach; ?>								
								</select> 
							</div>	
							<div class="form-group col-lg-3">
								<label for="inv_defn" class="control-label">Invoice Defination</label>
								<select id="inv_defn" name="inv_defn" class="form-control" data-placeholder="Select" >
									<option value="-1">None</option>
									<?php foreach($inv_definations as $inv_def):?>
										<option value="<?php echo $inv_def['id']; ?>">
											<?php echo $inv_def['defination'];?>
										</option>
									<?php endforeach;?>	
								</select> 
							</div>
						</div>
						<div class="row">		        
							<div class="form-group col-lg-3">
								<label for="quotation_no" class="control-label">Invoice No.</label>
								<input type="text" class="form-control" name="invoice_no" id="invoice_no" value="<?php //echo $challan_no; ?>" required> 
							</div>
						    <div class="form-group col-lg-3">
								<label for="inv_date" class="control-label">Invoice Date</label>
								<div class="date input-group" id="inv_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="inv_date" id="inv_date" type="text" value="<?php //echo $challan_date; ?>" placeholder="Invoice Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
						    <?php /*<div class="form-group col-lg-3">
								<label for="inv_due_date" class="control-label">Due Date</label>
								<div class="date input-group" id="inv_due_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
									<input class="form-control span2" name="inv_due_date" id="inv_due_date" type="text" placeholder="Due Date" readonly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>*/?>   
						    <div class="form-group col-lg-3">
								<label for="inv_record_date" class="control-label">Recording Date</label>
								<div class="date input-group" id="inv_record_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" readonly >
									<input class="form-control span2" name="inv_record_date" id="inv_record_date" value="<?php //echo $prn_date;?>" type="text" placeholder="Recording Date"  ReadOnly required>
									<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
								</div>
							</div>
							<div class="form-group col-lg-3">
								<label for="purchase_receipt" class="control-label">Purchase Receipt</label>
								<select class="form-control" name="purchase_receipt" id="purchase_receipt" data-placeholder="Select" readonly />
									<option value=""></option>
										<?php foreach ($this->pur_receipts as $pur_receipt):?>
											   <option value="<?php echo $pur_receipt['id'];?>"><?php echo $pur_receipt['prn_no']; ?></option>
										<?php endforeach; ?>	
								</select>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12"> 
						    <h5>Supplier Invoice Details</h5>
								<input type="hidden" value="1" name="uom_task" id="uom_task" />
								<table id="trdetails_table" class="table small-padding">
									<thead>
										<tr id="template_tr">
											<th>Item</th>
											<th>UOM</th>
											<th>Quantity</th>
											<th>Rate(<?php //echo $this->currency_code();?>)</th>
											<th>Amount(<?php //echo $this->currency_code();?>)</th>
											<th>MRP</th>
										</tr>
									</thead>
									<tbody>
									<?php 
									//if(sizeof($pr_details) > 0):
										//$i = 1; 
										//foreach($pr_details as $pr_detail):?>
										<!--tr>
											<td>
												<div class="form-group">
													<select class="form-control" name="item[]" id="item" data-placeholder="Select" required>
														<option value="<?php //echo $pr_detail['item_id'];?>" selected="selected">
															<?php //echo $pr_detail['item'];?>	
														</option>
													</select>
													<input type="hidden" value="<?php echo $pr_detail['id'];?>" name="prn_details_id[]" id="prn_details_id" />
												</div>
											</td>
											<td>
												<div class="form-group">
													<select class="form-control" name="uom[]" id="uom" data-placeholder="Select" required>
														<?php 
													/*	$selected_item = $this->itemObj->get($pr_detail['item_id']);
															foreach($selected_item as $item):
																$selected = ($item['uom']==$pr_detail['uom_id'])?"selected":"";
														?>
															<option value="<?php echo $item['uom']?>" <?php echo $selected;?> >
																<?php echo $this->uomObj->getColumn($item['uom'], 'code');?>
															</option>
														<?php endforeach;?>
														<?php   
															$itemuoms = $this->itemuomObj->get(array('ui.item' => $pr_detail['item_id']));
															foreach($itemuoms as $uom):
																$selected = ($uom['uom']==$pr_detail['uom_id'])?"selected":"";*/
														?>
															<option value="<?php //echo $uom['uom'];?>" <?php echo $selected;?> >
																<?php //echo $uom['uom_code'];?>
															</option>
														<?php //endforeach;?>
													</select>
												</div>
											</td>
											<td>
												<div class="form-group">
													<input type="text" class="form-control" name="quantity[]" id="quantity" value="<?php echo $pr_detail['sound_qty'];?>"  required/>
												</div>
											</td>
											<td>
												<div class="form-group">
													<?php 
													/*	if($pr_detail['po_details_id'] > 0){
															$po_details = $this->po_detailsObj->get($pr_detail['po_details_id']);
														}else{
															$po_details = $this->po_detailsObj->get(array('purchase_order' => $purchase_order, 'item' =>$pr_detail['item_id']));
														}
														foreach($po_details as $po_detail);
														$basic_uom = $this->itemObj->getColumn($pr_detail['item_id'],'uom');
														$po_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$pr_detail['item_id'], 'uom'=>$po_detail['uom_id']),'conversion');
														$pr_uom_conversion = $this->itemuomObj->getColumn(array('item'=>$pr_detail['item_id'], 'uom'=>$pr_detail['uom_id']),'conversion');
														
														$po_basic_rate = ($basic_uom == $po_detail['uom_id'])?$po_detail['rate']: $po_detail['rate'] / $po_uom_conversion;
														$po_rate = ($basic_uom == $pr_detail['uom_id'])?$po_basic_rate: $po_basic_rate * $pr_uom_conversion;*/
													?>
													<input type="text" class="form-control" name="rate[]" value="<?php //echo $po_rate;?>" id="rate" required/>
												</div>         
											</td>
											<td>
												<div class="form-group">
													<?php
														//$amount = $pr_detail['sound_qty'] * $po_rate;
													?>
													<input type="text" class="form-control" name="amount[]" id="amount" value="<?php //echo $amount;?>" readonly required/>
												</div>         
											</td>	
											<td>
												<div class="form-group">
													<input type="text" class="form-control" name="mrp[]" id="mrp" value="0.00"/>
												</div>
											</td>									
										</tr-->
										<?php 
										//	endforeach;
										//else:
										?>
										<tr>
											<td>
												<div class="form-group">
													<select class="form-control" name="item[]" id="item" data-placeholder="Select">
														<option value=""></option>
														<?php foreach ($this->item as $items):?>
															<option value="<?php echo $items['id'];?>"><?php echo $items['name']; ?></option>
														<?php endforeach; ?>	
													</select>
												</div>
											</td>
											<td>
												<div class="form-group">
													<select class="form-control" name="uom[]" id="uom" data-placeholder="Select">
														<option value=""></option>
													</select>
												</div>
											</td>
											<td>
												<div class="form-group">
													<input type="text" class="form-control" name="quantity[]" id="quantity" placeholder="Qty"/>
												</div>
											</td>
											<td>
												<div class="form-group">
													<input type="text" class="form-control" name="rate[]" value="0.00" id="rate"/>
												</div>         
											</td>
											<td>
												<div class="form-group">
													<input type="text" class="form-control" name="amount[]" value="0.00" id="amount" readonly/>
												</div>         
											</td>	
											<td>
												<div class="form-group">
													<input type="text" class="form-control" name="mrp[]" id="mrp" value="0.00"/>
												</div>
											</td>										
										</tr>
										<?php //endif;?>
									</tbody>
								</table>
					   		</div>
						</div>
						
						<div class="row">
						    <div class="col-lg-12">
		    					<div class="col-lg-9"></div>
		    					<div class="form-group col-lg-3">
									<label for="purchase_amount" class="control-label">Purchase Amount</label>
									<input type="text" class="form-control" name="purchase_amount" id="purchase_amount"  value="0.00" required >
								</div>
							</div>															
						</div>	
						
						<div class="row">    
							<div class="col-lg-12">
								<div class="col-lg-3"></div>
								<div class="form-group col-lg-2">
									<label for="freight_charge" class="control-label">Freight Charges</label>
									<input type="text" class="form-control" name="freight_charge" id="freight_charge"  value="0.00" >
								</div>
								<div class="form-group col-lg-2">
									<label for="net_inv_amount" class="control-label">Net Invoice Amount</label>
									<input type="text" class="form-control" name="net_inv_amount" id="net_inv_amount" value="0.00" readonly required>
								</div>
								<div class="form-group col-lg-2">
									<label for="deduction_amount" class="control-label">Deduction Amount</label>
									<input type="text" class="form-control" name="deduction_amount" id="deduction_amount"  value="0.00" >
								</div> 
								<div class="form-group col-lg-3">
									<label for="payable_amount" class="control-label">Payable Amount</label>
									<input type="text" class="form-control" name="payable_amount" id="payable_amount"  value="0.00" readonly required>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<label class="control-label" for="note">Note: </label>
								<textarea class="form-control" name="note" id="note"></textarea>
							</div>
						</div>
						<div class="space-12"></div>
						<div class="row"> 	
							<div class="col-lg-9"> 
								<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
								<button type="button" class="btn btn-warning" onclick="javascript:history.back();" ><i class="fa fa-times"></i> Cancel </button> 					
				        	</div>
				        </div>
			  		</form>
				</div> <!-- widget-main -->
			</div> <!-- widget-body -->  
		</div><!-- widget-box -->
	</div><!-- col-lg-12 -->
</div><!-- row -->
<script type="text/javascript">
$(function() {
	/**** Date Picker ****/
	$('#inv_date').datepicker();
	$('#inv_record_date').datepicker();
	$('#inv_due_date').datepicker();
	$('#inv_date').on('changeDate',function(){
		$('form').formValidation('revalidateField','inv_date');
	});
	$('#inv_record_date').on('changeDate',function(){
		$('form').formValidation('revalidateField','inv_record_date');
	});
	$('#inv_due_date').on('changeDate',function(){
		$('form').formValidation('revalidateField','inv_due_date');
	});
	/**** Append Invoice Defination Fields ****/
	$("#inv_defn").change(function() { 	
		$('th.inv_fields').remove();
		$('td.inv_fields').remove();	
		$.post("<?php echo $this->url('supplier', array('action' => 'getinvdeffields')); ?>/"+$('#inv_defn').val(), function(data) {
			var thead = $(data).find('th');
			$('thead tr').append(thead);
			$('tbody tr').each(function(){
				var tbody = $(data).clone();
				var id = $(this).attr('id');
				tbody.find('td :input').each(function(){
					var old_id = $(this).attr('id');
					$(this).attr('id', old_id+id);
				});
				$(this).append(tbody.find('td'));
			});
		});
    });
	$('#trdetails_table').supplierinvoice({
		getUomChange:"<?php echo $this->url('supplier',array('action'=>'getuomchange'));?>",
	});
});	
//form validation
const fv = FormValidation.formValidation(document.getElementById('#form'), {
    fields: {
        'location': {
            validators: {
                notEmpty: {
                    message: 'Please select location'
                }
            }
        },
        'activity': {
            validators: {
                notEmpty: {
                    message: 'Please select activity'
                }
            }
        },
        'supplier': {
            validators: {
                notEmpty: {
                    message: 'Please select supplier'
                }
            }
        }, 
        /*'inv_defn': {
            validators: {
                notEmpty: {
                    message: 'Please select invoice defination.'
                }
            }
        }, */
        'invoice_no': {
            validators: {
                notEmpty: {
                    message: 'Please enter invoice no'
                }
            }
        },
        'inv_date': {
            validators: {
                notEmpty: {
                    message: 'Please select invoice date'
                }
            }
        },
        /*'inv_due_date': {
            validators: {
                notEmpty: {
                    message: 'Please select invoice due date'
                }
            }
        },*/
        'inv_record_date': {
            validators: {
                notEmpty: {
                    message: 'Please select invoice record date'
                }
            }
        }, 
        'purchase_amount': {
            validators: {
                notEmpty: {
                    message: 'Please enter purchase amount'
                }
            }
        }, 
        'net_inv_amount': {
            validators: {
                notEmpty: {
                    message: 'Please enter net invoice amount'
                }
            }
        },  
        'payable_amount': {
            validators: {
                notEmpty: {
                    message: 'Please enter payable amount'
                }
            }
        }, 
        'item[]':{
            validators: {
                notEmpty: {
                    message: 'Please select item'
                },
            },
        },
        'uom[]':{
            validators: {
                notEmpty: {
                    message: 'Please select uom'
                },
            },
        },
        'quantity[]':{
            validators: {
                notEmpty: {
                    message: 'Please provide quantity'
                },
            },
        },
        'rate[]':{
        	validators: {
                notEmpty: {
                    message: 'Please provide rate'
                },
            },
        },
        'amount[]':{
        	validators: {
                notEmpty: {
                    message: 'Please provide amount'
                },
            },
        },
    },
	plugins: {
		trigger: new FormValidation.plugins.Trigger(),
		bootstrap3: new FormValidation.plugins.Bootstrap3(),
		submitButton: new FormValidation.plugins.SubmitButton(),
		defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
	},
}).on('core.element.validated', function (e) {
	if (e.valid) {
		$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
		$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
	} else {
		$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
		$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
	}
});
</script>
   
