<?php
/**
 * View -- of Purchase/InvoiceController/indexAction
 */
$this->headTitle($this->title);
?>
<?php $minYear = date('Y', strtotime($minYear)); ?> 
<div class="card">
	<div class="card-header">
		<div class="row">
			<form method="post" action="<?php echo $this->url('supplier'); ?>"  enctype="multipart/form-data" >
				<div class="form-group col-lg-2">
					<label class="control-label" for="year">Year</label>
					<select class="form-control" id="year" name="year" data-placeholder="Select" onchange='this.form.submit()'>
						<option value=""></option>
						<?php 
							for($year=date('Y');$year>=$minYear;$year--):
								$selected = ($year == $data['year'])?"selected":"";
						?>
							<option value="<?php echo $year;?>" <?php echo $selected;?> >
								<?php echo $year;?> 
							</option>
						<?php endfor; ?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="month">Month</label>
					<select class="form-control" id="month" name="month" data-placeholder="Select" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['month'] == '-1')?'selected':'';?>>All</option>
						<?php for($month=1; $month<=12; $month++):?>
							<?php $selected = ($month == $data['month'])?'selected':'';?>
							<option value="<?php echo $month;?>" <?php echo $selected; ?>>
								<?php echo DateTime::createFromFormat('!m', $month)->format('F');?>
							</option> 
						<?php endfor;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="activity">Activity</label>
					<select class="form-control" id="activity" name="activity" data-placeholder="Activity" onchange='this.form.submit()'>
						<option value="-1" <?php echo ($data['activity'] == '-1')?'selected':'';?>>All</option>
						<?php 
							$activites = $this->activityObj->getAll();
							foreach($activites as $act):
								$selected_act = ($act['id'] == $data['activity'])?'selected':'';
						?>
							<option value="<?php echo $act['id']?>" <?php echo $selected_act;?>>
								<?php echo $act['activity'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
			</form>
			<div class="col-lg-6">
				<div class="clearfix">
					<div class="pull-right tableTools-container"></div>
					<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-tooltip="tooltip" data-placement="top" title="Add New Supplier Invoice" href="<?php echo $this->url('supplier', array('action'=>'addsupplierinv'));?>" >
						<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add</span></span>
					</a>
				</div>
			</div>
		</div>
		<div>
			<table class="table table-striped table-bordered table-hover" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Invoice No.</th>
						<th>Invoice Date</th>
						<th>Payable Amount(<?php //echo $this->currency_code();?>)</th>
						<th>Purchase Receipt</th>
						<th class="no-sort no-printpdf">Action</th>
					</tr>
				</thead>
				<tbody>
					<?php $sl = 1;?>
					<?php foreach($this->sup_inv as $row):?>
						<tr data-href="<?php echo $this->url('supplier', array('action'=>'viewsupplierinv', 'id'=>$row['id']));?>">
							<td><?php echo $sl++;?></td>
							<td>
								 <b><?php echo $row['invoice_no'];?></b> &nbsp;&nbsp;&nbsp;
								 <i>
									<?php echo $this->partyObj->getColumn($row['supplier'],'name');   ?> &nbsp;&nbsp;&nbsp;
									<span class="label label-info"> 
										<?php echo $this->activityObj->getColumn($row['activity'],'activity'); ?> &nbsp;&nbsp;&nbsp;
									</span>
								</i>        
								&nbsp;<?php $this->status($row['status']);?>
                                                                <?php if($row['costing'] == 1):?>
									<span class="badge badge-danger pull-right"> 
										C
									</span>
								<?php endif;?>
							</td>
							<td><?php echo $row['inv_date'];?></td>	
							<td><?php echo $row['payable_amount'];?></td>
							<td><?php echo $this->purchase_receiptObj->getColumn($row['purchase_receipt'],'prn_no');?></td>
							<td class="action">
								<div class="btn-group">
									<a class="btn btn-xs btn-danger" data-toggle="modal" data-target="#modal" href="<?php echo $this->url('acl', array('action' => 'activitylog', 'id' => "3-".$row['id'])); ?>" title="View Activity Logs">
										<i class="ace-icon fa fa-plus bigger-120" ></i>  
							  		</a>
						  		</div>
							</td>	
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
		</div>
	</div>
</div>
<script>
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
	$("tr[data-href]").each(function(){
		$(this).find('td').not('td.action').each(function(){
			$(this).css('cursor','pointer');
			$(this).bind('click',function() {
				window.document.location = $(this).closest('tr').attr("data-href");
			});
		});
	});
});
</script>