<?php 
/**
 * chophel@athang.com -- 2022
 * View -- of Acl/AclController/permissionAction
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('realestate/estatereport/partial.phtml',array('active' => 'buildingreport'));?>
<div class="card">
	<div class="card-header">
		<div class="row">
			<div class="col-lg-9">
				<form method="POST">    
					<div class="row">
					<div class="form-group col-lg-4">
							<label for="region" class="control-label">Region</label>
							<select id="region" name="region" class="form-control" data-placeholder="Select" onchange='this.form.submit()' >
								<option value="-1" <?php echo ($data['region'] == '-1')?'selected':'';?>>All</option>
								<?php foreach($this->regionObj->get(array('status'=>'1')) as $region):?>
									<option value="<?php echo $region['id']?>"<?php echo ($region['id']==$data['region'])?'selected':'';?>>
										<?php echo $region['region'];?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div class="form-group col-lg-4">
							<label for="location" class="control-label">Location</label>
							<select id="location" name="location" class="form-control" data-placeholder="Select" onchange='this.form.submit()' >
								<option value="-1" <?php echo ($data['location'] == '-1')?'selected':'';?>>All</option>
								<?php foreach($this->locationObj->get(array('region'=>$data['region'])) as $location):?>
									<option value="<?php echo $location['id']?>"<?php echo ($location['id']==$data['location'])?'selected':'';?>>
										<?php echo $location['location'];?></option>
								<?php endforeach;?>
							</select>
						</div>
						<div class="form-group col-lg-4">
    						<label for="block" class="control-label">Block</label>
							<select id="block" name="block" class="form-control" data-placeholder="Select" onchange='this.form.submit()'>
								<option value="-1" <?php echo ($data['block'] == '-1') ? 'selected' : ''; ?>>All</option>
								<?php foreach($this->blockObj->get(array('id'=>[6,7])) as $blocks):?>
									<option value="<?php echo $blocks['id']?>"<?php echo ($blocks['id']==$data['block'])?'selected':'';?>>
										<?php echo $blocks['name'];?></option>
								<?php endforeach;?>
							</select>
						</div>
					</div>
				</form>
			</div>		
		</div>
	</div>
	<div class="table-responsive">
		<table class="table table-striped table-bordered table-hover" id="dataTables">
			<thead>
			<tr>
			<th>#</th>
			        <th>Region</th>
					<th>Location</th>
					<th>Block</th>
					<th>Building name</th>
					<th>Building ID</th>
					<th>Plot.No</th>
					<th>Thram No</th>
					<th>Custodian</th>
					<th>Total Floor</th>
				</tr>
			</thead>
			<tbody>
			<?php 
				$i=1;
				foreach ($building as $rows):?>				
				<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $this->regionObj->getColumn($rows['region'], 'region'); ?></td>
						<td><?php echo $this->locationObj->getColumn($rows['location'], 'location'); ?></td>
						<td><strong><?php echo $this->blockObj->getColumn($rows['block'],'name'); ?></strong></td>
						<td><?php echo $rows['name']; ?></td>
						<td><?php echo $rows['building_id']; ?></td>
						<td><?php echo $rows['plot_no']; ?></td>
						<td><?php echo $rows['thram_no']; ?></td>
						<td><?php echo $this->empObj->getColumn($rows['custodian'],'full_name'); ?></td>
						<td><?php echo $rows['tot_floor']; ?></td>
					
				    </tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script>
$('document').ready(function(){
		$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>