
<?php
/**
 *
 * View -- of Hr/BuildingController/addbuildingAction
 *
 */
$this->headTitle($this->title);
foreach($tenant as $tenants):extract($tenants);endforeach;
?>

<form id="#form" method="post" action="<?php echo $this->url('building', array('action' => 'edittenant','id'=>$id)); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
	  <div class="row">
		<div class="col-lg-12">
			<div class="widget-box">
				<div class="widget-header widget-header-smaller">
					<h4 class="widget-title blue bolder smaller"> Edit Tenants Information
				</div>
				<div class="widget-body">
					<div class="widget-main padding-24">
					    <div class="row">
						<input type="hidden" class="form-control" name="flat_id" id="flat_id" value="<?php echo $flat;?>" />
						<input type="hidden" class="form-control" name="rent" id="rent" value="<?php echo $rent;?>" />
						<input type="hidden" class="form-control" name="building" id="building" value="<?php echo $building;?>" />
						<div class="form-group col-lg-4">
								<label for="tenants" class="control-label">Lesse name </label>
								<select name="tenants" id="tenants" >
								<option value=""></option>
								<?php foreach($party as $partys):?>
								<option value="<?php echo $partys['id'];?>" <?php echo ($lesse_name==$partys['id'])?'selected':'';?>>
								<?php echo $partys['name']." ". '(' . $partys['code'] . ')';?>
								</option>
								<?php endforeach;?>
								</select>
							</div>
							<div class="form-group col-lg-4">
								<label for="cid" class="control-label">CID No.</label>
								<input type="text" class="form-control" name="cid" id="cid" value="<?php echo $cid;?>" />
							</div>
							<div class="form-group col-lg-4">
								<label for="contact" class="control-label">Contact No.</label>
								<input type="text" class="form-control" name="contact" id="contact" value="<?php echo $contact;?>" />
							</div>
							<br><br><br><br><br><br><br>
						<div class="form-group col-lg-4">
								<label for="agreement_date" class="control-label">Agrement_date</label>
								<div class="date input-group" id="agreement_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="agreement_date" id="agreement_date" type="text" placeholder="End Date" value="<?php echo $agreement_date;?>"  required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
							</div>
					
						<div class="form-group col-lg-4">
								<label for="start_date" class="control-label">Start_date</label>
								    <div class="date input-group" id="start_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $start_date;?>"  required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
							</div>	
						<div class="form-group col-lg-4">
								<label for="end_date" class="control-label">End_date</label>
								<div class="date input-group" id="end_date" data-date="<?php echo date('Y-m-d');?>" data-date-format="yyyy-mm-dd" >
										<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $end_date;?>" required>
										<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
									</div>
							</div>
							<br><br><br><br><br><br><br>
							<div class="form-group col-lg-4">
								<label for="status" class="control-label">Status </label>
								<select name="status" id="status" >
								<option value=""></option>
								<?php foreach($statu as $stu):?>
								<option value="<?php echo $stu['id'];?>" <?php echo ($status==$stu['id'])?'selected':'';?>>
								<?php echo $stu['status'];?>
								</option>
								<?php endforeach;?>
								</select>
							</div>
							
							<div class="form-group col-lg-4">       
								<label for="remarks" class="control-label"> Remarks</label>
								<textarea id='remarks' name='remarks' rows='3' cols='65'></textarea>
							</div>

							</div>
									<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
									<button type="button" class="btn btn-warning" onclick="javascript:history.back();"><i class="fa fa-times"></i> Cancel </button>
					</div>
				</div>
			</div>
		</div>


</form>

<script type="text/javascript">
    $(function() {
	$('#agreement_date').datepicker();
	$('#start_date').datepicker();
	$('#end_date').datepicker();
		$('#location').on('change', function(){
			$location_id = $(this).val(),
			//alert($location_id);
			$.post(
				"<?php echo $this->url('realestate', array('action' => 'getLeasedGodown')); ?>",
				{
					location_id: $location_id,
				},
				function(data){
					console.log(data);
					$('#storage_type').html(data.leaseditem);
					$('#storage_type').trigger('chosen:updated');
					$('form').formValidation('revalidateField','storage_type');
				},
				'json'
			);
		});


	});
	$('form select').chosen();
	$('document').ready(function(){
		const fv = FormValidation.formValidation(document.getElementById('#form'), {
			fields: {
				tenants: {
					validators: {
						notEmpty: {
							message: 'Please select tenants.'
						}
					}
				},
				contact: {
					validators: {
						notEmpty: {
							message: 'Please provide contact.'
						}
					}
				},
				rent: {
					validators: {
						notEmpty: {
							message: 'Please provide Asset id.'
						},
						numeric:{
							message: 'Enter a Figure Value'
						}
					}
				},
				flat_status: {
					validators: {
						notEmpty: {
							message: 'Please provide flat_status.'
						}
					}
				},
				agrement_date: {
					validators: {
						notEmpty: {
							message: 'Please provide agrement_date.'
						},
						numeric:{
							message: 'Enter a Figure Value'
						}
					}
				},
				end_date: {
					validators: {
						notEmpty: {
							message: 'Please provide end_date.'
						},
						numeric:{
							message: 'Enter a Figure Value'
						}
					}
				},
				start_date: {
					validators: {
						notEmpty: {
							message: 'Please provide start_date.'
						},
						numeric:{
							message: 'Enter a Figure Value'
						}
					}
				},
			
			plugins: {
				trigger: new FormValidation.plugins.Trigger(),
				bootstrap3: new FormValidation.plugins.Bootstrap3(),
				submitButton: new FormValidation.plugins.SubmitButton(),
				defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
			},
		}
		}).on('core.element.validated', function (e) {
			if (e.valid) {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
			} else {
				$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
				$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-i                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               nvalid');
			}
		});
	});

	
	
</script>
