<?php
/**
 * 
 * View -- of Stock/MasterController/addchargetaxAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'addchargetax')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Charge Tax</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="charge_tax" class="control-label">Charge Tax</label>
					<input type="text" class="form-control" name="charge_tax" id="charge_tax" size="30" required>
				</div>
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<input type="text" class="form-control" name="description" id="description" size="30" required> 
				</div>
				<div class="form-group">
					<label for="percentage" class="control-label">Percentage</label>
					<div class="radio">
						<label>
							<input class="ace"type="radio" name="percentage" id="percentage" value="yes" checked/>
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="percentage" id="percentage" value="no"/>
							<span class="lbl"> No </span>
						</label>
					</div> 
				</div>
				<div class="form-group">
					<label for="value" class="control-label">Value</label>
					<input type="text" class="form-control" name="value" id="value" size="30"> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
	$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			charge_tax: {
				validators: {
					notEmpty: {
						message: 'Please provide charge tax.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide charge description.'
					},
				}
			},
			percentage: {
				validators: {
					notEmpty: {
						message: 'Please select percentage.'
					},
				}
			},
			value: {
				validators: {
					notEmpty: {
						message: 'Please provide value.'
					},
				}
			},
		}
		plugins: { 
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>