<?php
/**
 * Add Invoice Field 
 */
?>
<?php foreach($inv_definations as $inv_defination):
	extract($inv_defination);
	$inv_def_id = $id;
endforeach;?>
<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'addinvfield')); ?>" enctype="multipart/form-data" >
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h4 class="modal-title"> <i class="fa fa-asterisk"></i><?php echo $title; ?>&nbsp;<b><?php echo $defination;?></b></h4>
</div>     
    <div class="modal-body">    
		<div class="panel panel-default">                       
			<div class="panel-body">
				<input type="hidden" name="inv_def" id="inv_def" value="<?php echo $inv_def_id;?>" />
				<input type="hidden" name="supplier_id" id="supplier_id" value="<?php echo $supplier;?>" />
				<div class="form-group">
					<label for="inv_def_fields" class="control-label">Type</label>
					<select class="form-control" id="inv_def_fields" name="inv_def_fields" data-placeholder="Select" required>
                        <option value=""></option>
        				<?php foreach($inv_def_fields as $inv_def_field):?>
        					<option value="<?php echo $inv_def_field['id'];?>">
        						<?php echo $inv_def_field['def_field'];?>
        					</option>
        				<?php endforeach;?>
        	        </select>
				</div>
				
				<div class="form-group">
					<label for="order_no" class="control-label">Order No.</label>
					<?php 
						$maxOrderNo = $this->inv_def_detailObj->getMax('order_by', array('inv_def' => $inv_def_id))
					?>
					<input type="text" class="form-control" name="order_no" id="order_no" value="<?php echo $maxOrderNo+1;?>" required readonly />
				</div>
				
            </div>
        </div>
    </div>    
    <div class="modal-footer">
		<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
		<button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	$('form select').chosen({allow_single_deselect:true});
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			item_code: {
				validators: {
					notEmpty: {
						message: 'please select invoice field.'
					}
				}
			}
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>