<?php
/**
 * Add new invoice defination for a supplier
 */
 $this->headTitle($this->title);
?>
<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'addinvdef'));?>" enctype="multipart/form-data">
	<div class="row">
		<div class="col-lg-12">
			<div class="widget widget-box">
				<div class="widget-header">
					<h5 class="widget-title lighter smaller">
						<i class="fa fa-asterisk"></i>&nbsp;&nbsp;New Invoice Defination<?php echo $selected_supplier; ?>
					</h5>
				</div><!-- end of widget-header -->
				<div class="widget-body">
					<div class="widget-main">
						<div class="row">
							<div class="col-lg-6">
								<div class="form-group">
									<label class="control-label" for="supplier">Supplier</label>
									<select class="form-control" name="supplier" id="supplier" data-placeholder="Select" required>
										<option value=""></option>
										<?php 
											foreach($suppliers as $supplier):
												$selected = ($supplier['id']==$selected_supplier)?"selected":"";
										?>
											<option value="<?php echo $supplier['id']?>" <?php echo $selected;?>>
												<?php echo $supplier['name'];?>
											</option>
										<?php endforeach;?>
									</select>  
								</div>
							</div>
							<div class="col-lg-6">
								<div class="form-group">
									<label class="control-label" for="defination">Invoice Defination</label>
									<input type="text" class="form-control" name="defination" id="defination" required/>  
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<table class="table table-striped table-hover table-condensed" id="">
									<thead>
										<tr>
											<th>#</th>
											<th>Field</th>
											<th>Description</th>
											<th class="no-sort center">Select</th>
										</tr>
									</thead>
									<tbody>
									<?php $i=1; 
									foreach($inv_def_fields as $inv_def):?>
										<tr>
											<td><?php echo $i++;?></td>
											<td><strong><?php echo $inv_def['def_field'];?></strong></td>
											<td><?php echo $inv_def['description'];?></td>
											<td>
												<input type="checkbox" class="form-control center" name="status[]" id="status_<?php echo $i;?>" value="<?php echo $inv_def['id'];?>" />
											</td>
										</tr>
									<?php endforeach;?>
									</tbody>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save</button>
					<button type="button" class="btn btn-warning" onclick="window.location.href='<?php echo $this->url('stmaster', array('action'=>'supinvoice', 'id'=>$selected_supplier));?>'" ><i class="fa fa-times"></i> Cancel </button>
				</div>
			</div>
		</div><!-- end of col-lg-12 -->
	</div><!-- end of row -->
</form>

<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			'supplier': {
				validators: {
					notEmpty: {
						message: 'please select supplier.'
					},
				}
			},
			'defination': {
				validators: {
					notEmpty: {
						message: 'please provide invoice defination.'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>								
