<?php
/**
 * 
 * View -- of Stock/MasterController/adduomAction
 * 
 */
?>
<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'adduom')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-asterisk"></i> New Unit of Measurement</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body">   
				<div class="form-group">
					<label for="uomtype" class="control-label">UOM Type</label>
					<select class="form-control" style="width:100%" data-placeholder="Select" name="uomtype" id="uomtype" required >
						<option></option>
						<?php foreach($this->uomtypeTable-> getAll() as $uomtype):?>
						    <option value="<?php echo $uomtype['id'];?>"><?php echo $uomtype['description'];?></option>
						<?php endforeach;?>				
					</select>				
				</div>
				<div class="form-group">
					<label for="code" class="control-label">Code</label>
					<input type="text" class="form-control" name="code" id="code" size="30" placeholder="Code" required/> 
				</div>
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<input type="text" class="form-control" name="description" id="description" size="30" placeholder="Description" required> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	$('select').chosen({ allow_single_deselect: true });
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			uomtype: {
				validators: {
					notEmpty: {
						message: 'Please select UOM type.'
					}
				}
			},
			code: {
				validators: {
					notEmpty: {
						message: 'Please provide code for item group'
					},
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide discription for item group'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>