<?php
/**
 * 
 * View -- of Accounts/TransactionController/viewtransactionAction
 * 
 */
?>
<?php 
	foreach($this->conagreementrow as $row ):
		extract($row);
	endforeach;
?>
<div class="col-lg-12">
	<div class="widget-box">
		<div class="widget-header">
			<h5 class="widget-title lighter smaller">
				# Contractor Agreement :<strong>&nbsp;&nbsp;<?php echo $agreement_no; ?>
			</h5>
			<div class="widget-toolbar hidden-xs">
				<a style='cursor:pointer' id="print">
					<i class="ace-icon fa fa-file-pdf-o red"></i>
				</a>
			</div>
		</div>
		<div class="widget-body">
			<div class="widget-main padding-24">
				<div id="report-print">
					<div class="row" id="convert-tb0">
						<div class="col-lg-6" id="convert-tb1">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Document Type : <b class="red"><?php echo "Contractor Agreement"; ?></b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Agreement No. : <b class="red"><?php echo $agreement_no; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Agreement Date : <b class="red"><?php echo $agreement_date; ?> </b>
								</li>
								
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Activity : <b class="red">
									<?php $act = $activity;
										switch($act){
											case 1: echo "Agency"; break;
											case 2: echo "Food Grains"; break;
											case 3: echo "Both Agency & Food Grains";
											case 4: echo "RNR Marketing"; break;
											} ?> </b>
								</li>
							</ul>
						</div>
						<div class="col-lg-6" id="convert-tb2">
							<ul class="list-unstyled spaced pull-right">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Contractor : <b class="red"><?php echo $contractor; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Location : <b class="red"><?php echo $location; ?> </b>
								</li>

								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Start Date :	<b class="red"><?php echo $from_date;?> </b>
								</li>
								
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>End Date : <b class="red"><?php echo $to_date; ?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<ul class="list-unstyled spaced">
								<li>
									<i class="ace-icon fa fa-caret-right blue"></i>Naration: <b class="red"><?php echo $remark;?> </b>
								</li>
							</ul>
						</div>
					</div>
					<div class="row">
						<table class="table table-striped table-bordered table-condensed">	
							<thead>
								<th>Work Type</th>
								<th>Charges</th>
								<th>Remarks</th>
							</thead>
							<tbody>
								<?php foreach($this->conagreementdtl as $tdrow): ?>
									<tr>
										<td><?php echo $tdrow['work_type'];?></td>
										<td><?php echo $tdrow['charge'];?></td>
										<td><?php echo $tdrow['remark'];?></td>
									</tr>
								<?php endforeach;?>
							</tbody>
						</table>
					</div>
					<br/>
					<div class="row">
						<div class="col-lg-3">
							<label> Prepared by: <?php echo $this->userObj->getColumn($author,'name');?></label>
							<br/><br/>
						</div>
					</div>
					<div class="row" id="convert-tb0">
						<div class="col-lg-6" id="convert-tb1"></div>
						<div class="col-lg-6" id="convert-tb2">
							<ul class="list-unstyled spaced pull-right">
								<li>
									<label> Authorized Signatory </label>
								</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
