<?php
/**
 * 
 * View -- of Stock/MsaterController/costingheadAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/master/partial.phtml', array('active' => 'costinghead')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<table class="table table-bordered table-striped table-hover" id="dataTables">
		<thead>
			<tr>
				<th>#</th>
				<th>Costing Head</th>
				<th>Description</th>
				<th>Display Sum</th>
				<th class="no-sort">Action</th>
			</tr>
		</thead>
		<tbody>
			<?php
				$i = 1; 
				foreach ($this->costingHeads as $head):
			?>
					<tr>
						<td><?php echo $i++; ?> </td> 
						<td><?php echo $head['costing_head']; ?></td> 
						<td><?php echo $head['description']; ?></td> 
						<td><?php echo ($head['display_sum'] == "0")?"No":"Yes"; ?></td>								
						<td>
							<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('stmaster', array('action'=>'editcostinghead', 'id' => $head['id']));?>" data-target="#modal">
								<i class="ace-icon fa fa-pencil bigger-120"></i>
							</a>                                                                    
						</td>
					</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
