<?php
/**
 * 
 * View -- of Stock/MasterController/edituomtypeAction
 * 
 */
?>
<?php 
    foreach($this->uomtypes as $uomtype):
        extract($uomtype);        
    endforeach;
?>

<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'edituomtype', 'id' => $id)); ?>"  enctype="multipart/form-data" >                  
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil-square-o"></i> Edit Unit of Measurement</h4>
    </div>  <!-- /modal-header -->
    
    <div class="modal-body">       
		<div class="panel panel-default">                       
			<div class="panel-body"> 
				<div class="form-group">
					<label for="uomtype">Unit Of Measurement Type</label>
					<input type="text" class="form-control" name="uomtype" id="uomtype" value="<?php echo $uom_type;?>" size="30" required/> 
				</div>
				<div class="form-group">
					<label for="description">Description</label>
					<input type="text" class="form-control" name="description" id="description" value="<?php echo $description;?>" size="30" required/> 
				</div>
			</div>
		</div>
	</div> <!-- /modal-body -->    
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>
</form>
<script>
$('document').ready(function(){
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			uomtype: {
				validators: {
					notEmpty: {
						message: 'Please select uom type.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide description for item group.'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>
