<?php
/**
 * 
 * View -- of Stock/MasterController/editchargetaxAction
 * 
 */
?>
<?php 
foreach($charge_taxs as $chargetax):
	extract($chargetax);
endforeach;
?>
<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'editchargetax')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil"></i> Edit Charge Tax</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body"> 
			<!-- sending hidden id of chargetax -->
			<input type="hidden" name="charge_tax_id" id="charge_tax_id" value="<?php echo $id;?>" />  
				<div class="form-group">
					<label for="charge_tax" class="control-label">Charge Tax</label>
					<input type="text" class="form-control" name="charge_tax" id="charge_tax" value="<?php echo $charge_tax;?>" size="30" required>
				</div>
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<input type="text" class="form-control" name="description" id="description" value="<?php echo $description;?>" size="30" required> 
				</div>
				<div class="form-group">
					<label for="percentage" class="control-label">Percentage</label>
					<div class="radio">
					<?php 
						$checked1 = ($percentage =="1")?"checked":"";
						$checked2 = ($percentage =="0")?"checked":"";
					?>
						<label>
							<input class="ace"type="radio" name="percentage" id="percentage" value="1" <?php echo $checked1;?>/>
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="percentage" id="percentage" value="0" <?php echo $checked2;?>/>
							<span class="lbl"> No </span>
						</label>
					</div> 
				</div>
				<div class="form-group">
					<label for="value" class="control-label">Value</label>
					<input type="text" class="form-control" name="value" id="value" value="<?php echo $value;?>" size="30"> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	//$('select').chosen({ allow_single_deselect: true });
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			charge_tax: {
				validators: {
					notEmpty: {
						message: 'Please provide charge tax.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide charge description.'
					},
				}
			},
			percentage: {
				validators: {
					notEmpty: {
						message: 'Please select percentage.'
					},
				}
			},
			value: {
				validators: {
					notEmpty: {
						message: 'Please provide value.'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>