<?php
/**
 * 
 * View -- of Stock/MasterController/editcostingheadAction
 * 
 */
?>
<?php
	foreach($costing_heads as $costinghead):
		extract($costinghead);
	endforeach; 
?>
<form id="#form" method="post" action="<?php echo $this->url('stmaster', array('action' => 'editcostinghead')); ?>"  enctype="multipart/form-data" >
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"> <i class="fa fa-pencil"></i> Edit Costing Head</h4>
    </div>  <!-- /modal-header -->
    <div class="modal-body">
		<div class="panel panel-default">                       
			<div class="panel-body"> 
			<!-- sending hidden id of chargetax -->
			<input type="hidden" name="costing_head_id" id="costing_head_id" value="<?php echo $id;?>" />  
				<div class="form-group">
					<label for="costing_head" class="control-label">Costing Head</label>
					<input type="text" class="form-control" name="costing_head" id="costing_head" value ="<?php echo $costing_head;?>" size="30" required>
				</div>
				<div class="form-group">
					<label for="description" class="control-label">Description</label>
					<input type="text" class="form-control" name="description" id="description" value="<?php echo $description;?>" size="30" required> 
				</div>
				<div class="form-group">
					<label for="percentage" class="control-label">Display Sum In Costing Sheet</label>
					<div class="radio">
						<?php 
							$checked1 = ($display_sum == "1")?"checked":"";
							 $checked2 = ($display_sum == "0")?"checked":"";
						?>
						<label>
							<input class="ace"type="radio" name="display_sum" id="display_sum" value="1" <?php echo $checked1;?>/>
							<span class="lbl"> Yes </span>
						</label>
						<label>
							<input class="ace" type="radio" name="display_sum" id="display_sum" value="0" <?php echo $checked2;?>/>
							<span class="lbl"> No </span>
						</label>
					</div> 
				</div>
			</div>
		</div>
    </div> <!-- /modal-body -->
    <div class="modal-footer">
        <button type="submit" class="btn btn-success"><i class="fa fa-check"></i> Save </button>
        <button type="button" class="btn btn-warning" data-dismiss="modal" ><i class="fa fa-times"></i> Cancel </button> 
    </div>  
</form>
<script>
$('document').ready(function(){
	//$('select').chosen({ allow_single_deselect: true });
	const fv = FormValidation.formValidation(document.getElementById('#form'), {
		fields: {
			costing_head: {
				validators: {
					notEmpty: {
						message: 'Please provide costing head.'
					}
				}
			},
			description: {
				validators: {
					notEmpty: {
						message: 'Please provide costing head description.'
					},
				}
			},
		},
		plugins: {
			trigger: new FormValidation.plugins.Trigger(),
			bootstrap3: new FormValidation.plugins.Bootstrap3(),
			submitButton: new FormValidation.plugins.SubmitButton(),
			defaultSubmit: new FormValidation.plugins.DefaultSubmit(),
		},
	}).on('core.element.validated', function (e) {
		if (e.valid) {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-invalid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-valid');
		} else {
			$('div#'+ e.field.replace('[]','') +'_chosen').removeClass('is-valid');
			$('div#'+ e.field.replace('[]','') +'_chosen').addClass('is-invalid');
		}
	});
});
</script>