<?php
/**
 * Add new invoice defination field
 */
?>
<?php echo $this->partial("stock/master/partial.phtml", array('active' => 'invdeffield'));?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
			<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold" data-toggle="modal" data-target="#modal" data-tooltip="tooltip" data-placement="top" title="Add New Invoice Def Field" href="<?php echo $this->url('stmaster', array('action' => 'addinvdeffield'));?>" >
				<span class="red"><i class="fa fa-plus"></i> <span class="hidden-sm hidden-xs">&nbsp;Add</span></span>
			</a>
		</div>
		<div>
			<table class="table table-bordered table-hover table-stripted" id="dataTables">
				<thead>
					<tr>
						<th>#</th>
						<th>Defination Field</th>
						<th>Description</th>
						<th class="no-sort no-printpdf">Action</th>
					</tr>
				</thead>
				<tbody>
				<?php $i = 1; 
				foreach($inv_def_fields as $inv_def_field):?>
					<tr>
						<td><?php echo $i++;?></td>
						<td><strong><?php echo $inv_def_field['def_field']; ?></strong></td>
						<td><?php echo $inv_def_field['description']; ?></td>
						<td>
							<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('stmaster', array('action'=>'editinvdeffield', 'id' => $inv_def_field['id']));?>" data-target="#modal">
								<i class="ace-icon fa fa-pencil bigger-120"></i>
							</a>                                                            
						</td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
