<?php
/**
 * 
 * View -- of Stock/MsaterController/scalarAction
 * 
 */
	$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/master/partial.phtml', array('active' => 'scalar')); ?>
<div class="card">
	<div class="card-header">
		<div class="btn-group pull-right">
			<?php echo $this->button(2);?>
		</div>
	</div>
	<i class="blue">*Conversion value is to be Multiplied.</i>
	<table class="table table-bordered table-striped table-hover" id="dataTables">
		<thead>
			<tr>
				<th>#</th>
				<th>From UOM</th>
				<th>To UOM</th>
				<th>Conversion</th>
				<th class="no-sort">Action</th>
			</tr>
		</thead>
		<tbody>
			<?php
				$i = 1; 
				foreach ($this->scalars as $scalar):
				$from = $this->uomObj->select(array('id'=>$scalar['from_uom']))->current()->code;
				$to = $this->uomObj->select(array('id'=>$scalar['to_uom']))->current()->code;
			?>
					<tr>
						<td><?php echo $i++; ?> </td>
						<td><?php echo $from; ?></td> 
						<td><?php echo $to; ?></td>  
						<td><?php echo $scalar['conversion'];?></td>                             
						<td>
							<a class="btn btn-xs btn-info" data-toggle="modal" href="<?php echo $this->url('stmaster', array('action'=>'editscalar', 'id' => $scalar['id']));?>" data-target="#modal">
								<i class="ace-icon fa fa-pencil bigger-120"></i>
							</a>                                                                    
						</td>
					</tr>
			<?php endforeach;?>
		</tbody>
	</table>
</div>
<!--for modal -->
<div id="modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content"> </div>
    </div>
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
