<?php
/**
 * View -- of Stock/MsaterController/tripAction
 */
$this->headTitle($this->title);
?>
<?php echo $this->partial('stock/master/partial.phtml', array('active' => 'trip')); ?>
<div class="space-12"></div>
<div class="row">
	<div class="col-lg-12">
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
			<a class="red pull-right DTTT_button btn btn-white btn-info btn-bold"  data-tooltip="tooltip" data-placement="top" title="Add New Trip" href="<?php echo $this->url('stmaster', array('action' => 'addtrip'));?>" >
				<span class="red"><i class="fa fa-plus"></i> 
				<span class="hidden-sm hidden-xs">&nbsp;Manage Trip</span></span>
			</a>
		</div>
		<div>
		<?php  $result = $this->locationsObj->get(array('lt.sales' => '1')); ?>
                    
		   <table class="table table-bordered table-striped table-hover" id="dataTables">
		      <thead>
			 <tr>
			    <th>#</th>
			    <th>Location</th>
			    <?php foreach($result as $row): ?>
          			    <th><?php echo $row['location']; ?></th>
                            <?php endforeach; ?>
			  </tr>
		     </thead>
		     <tbody>
		          <?php 
			   $sl = 1;
			  foreach($result as $row1): ?>
		            <tr> 
			       <td><?php echo $sl++; ?></td>
			       <td><?php echo $row1['location']; ?> </td>
                                 <?php  foreach($result as $row2): ?>
				         <?php 
					    $tripDtls = $this->tripObj->get(array('source_location'=>$row1['id'], 'destination_location'=>$row2['id'])); 			  
					    if(sizeof($tripDtls) == 0){ 
					       $tripDtls = $this->tripObj->get(array('source_location'=>$row2['id'], 'destination_location'=>$row1['id'])); 			  
					    }
					    if(sizeof($tripDtls) > 0) {
					       foreach($tripDtls as $dtl):
					           ?> <td>
						   Plain(KM):<?php echo $dtl['plain_distance']; ?>, Plain Rate:<?php echo $dtl['plain_rate'].","; ?>
						   Hill(KM):<?php echo $dtl['hill_distance']; ?>, Hill Rate:<?php echo $dtl['hill_rate'].","; ?><br />
						   Stops: <?php echo $dtl['hop']; ?>
						   </td><?php
					       endforeach;
					    } else{
					    ?><td>0</td><?php
					    }
					 ?>
				 <?php  endforeach; ?>
			    </tr>
			  <?php endforeach; ?>
		      </tbody>
		   </table> 		 
		</div>	   
	</div>	
</div>
<script type="text/javascript">
$('document').ready(function(){
	$('#dataTables').DataTable({
		"paging":   true,
	});
});
</script>
