<?php
/**
 * View -- of Report/StockreconcilreportController/eosreconcileAction
 */
	$this->headTitle($this->title);
?>
<style>
	tr.group,
	tr.group:hover {
		background-color: #ddd !important;
		font: 15px "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}
</style>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$start = $time;
?>
<div class="row">
	<div class="col-lg-12">
		<form method="post" action="<?php echo $this->url('stockreconcilreport', array('action' => 'eosreconcile')); ?>"  enctype="multipart/form-data" >    
			<div class="row">
				<div class="form-group col-lg-2">
					<label class="control-label" for="location">Location</label>
					<input type="hidden" name="location_name" id="location_name" value="<?php echo $this->locationObj->getColumn($data['location'],'location');?>" >
					<select class="form-control" name="location" id="location" data-placeholder="select" >
						<option value="-1">All</option>
						<?php foreach($regions as $region):?>
							<optgroup label="<?php echo $region['region'];?>">
							<?php  
								$locations = $locationObj->get(array('region'=>$region['id'],'location_type'=>array(1,2,7,8)));
								foreach ($locations as $location):
									$selected_loc = ($location['id']==$data['location'])?"selected":"";
							?>
								<option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
									<?php echo $location['location']; ?>
								</option>
							<?php endforeach;?>
							</optgroup>
						<?php endforeach;  ?>									
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="start_date">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="end_date">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="col-lg-2">
					<div class="space-8"></div>
					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>Refresh</button>
				</div>
			</div>
		</form>
		<div class="hr hr-dotted"></div>
		<div class="space-4"></div>
		<div>
			<table class="table table-striped table-condensed table-bordered table-hover" id="example">
				<thead>
					<tr>
				        <th>#</th>
					    <th>EOS No.</th>
					    <th>EOS Date</th>
					    <th>Location</th>
					    <th>Cash Voucher</th>
					    <th>Cash Voucher Amt</th>
					    <th>Cash Sales Amt</th>
					    <th>Credit Voucher</th>
					    <th>Credit Voucher Amt</th>
					    <th>Credit Sales Amt</th>
					</tr>
				</thead>
				<tbody>
					<?php 
					    $sl = 1;
					    $bookings = $this->bookingObj->getBooking($data);
					    foreach($bookings as $booking):
					        $cash_voucher_amount = ($booking['cash_voucher_id']==NULL)?'0':$this->transactionObj->getColumn($booking['cash_voucher_id'],'voucher_amount');
					        $cash_sales_amount = $this->salesObj->getBooking($booking['eos_date'],$booking['location'],'0');
				            $credit_voucher_amount = ($booking['credit_voucher_id']==NULL)?'0':$this->transactionObj->getColumn($booking['credit_voucher_id'],'voucher_amount');
				            $credit_sales_amount = $this->salesObj->getBooking($booking['eos_date'],$booking['location'],'1');
				            
				            $cash_voucher_amount = number_format($cash_voucher_amount,'2','.',',');
				            $cash_sales_amount = number_format($cash_sales_amount,'2','.',',');
				            $credit_voucher_amount = number_format($credit_voucher_amount,'2','.',',');
				            $credit_sales_amount = number_format($credit_sales_amount,'2','.',',');
					?>
					<tr>
					    <td><?php echo $sl++;?></td>
					    <td><?php echo $booking['eos_voucher'];?></td>
					    <td><?php echo $booking['eos_date'];?></td>
					    <td><?php echo $this->locationObj->getColumn($booking['location'],'location');?></td>
					    
					    <td style="text-align:right" class="<?php echo ($cash_voucher_amount == $cash_sales_amount)?'green':'red';?>"><?php echo ($booking['cash_voucher_id']==NULL)?'-':$this->transactionObj->getColumn($booking['cash_voucher_id'],'voucher_no');?></td>
					    <td style="text-align:right" class="<?php echo ($cash_voucher_amount == $cash_sales_amount)?'green':'red';?>"><?php echo $cash_voucher_amount; ?></td>
					    <td style="text-align:right" class="<?php echo ($cash_voucher_amount == $cash_sales_amount)?'green':'red';?>"><?php echo $cash_sales_amount;?></td>
					    
					    <td style="text-align:right" class="<?php echo ($credit_voucher_amount == $credit_sales_amount)?'green':'red';?>"><?php echo ($booking['credit_voucher_id']==NULL)?'-':$this->transactionObj->getColumn($booking['credit_voucher_id'],'voucher_no');?></td>
					    <td style="text-align:right" class="<?php echo ($credit_voucher_amount == $credit_sales_amount)?'green':'red';?>"><?php echo $credit_voucher_amount;?></td>
					    <td style="text-align:right" class="<?php echo ($credit_voucher_amount == $credit_sales_amount)?'green':'red';?>"><?php echo $credit_sales_amount;?></td>
					</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$finish = $time;
	$total_time = round(($finish - $start), 4);
	echo "<p class='pull-right'>Sales Reconciliation generated in ".$total_time." seconds.</p>";
?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#start_date').datepicker();
		$('#end_date').datepicker();
		$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		
		/*** Form Validation ***/
		$('form').formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid',
				fields: {
					'location': {
					 	validators: {
							notEmpty: {
								message: 'Please select location'
						  	}
					  	}
				  	},
					'start_date': {
						validators: {
							notEmpty: {
								message: 'Please select start date'
							},
						}
					},
					'end_date': {
						validators: {
							notEmpty: {
								message: 'Please select end date'
							}
						},
					},
				}
			}).on('success.field.fv', function(e, data) {
				if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
					data.fv.disableSubmitButtons(true);
			}
		});
		
		var title_table = $('#location_name').val()+'('+$('#activity_name').val()+') from '+$('input#start_date').val()+' to '+$('input#end_date').val();
		
			$('#example').DataTable( {
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				columnDefs: [ {
					visible: false
				} ],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true
			} );
	} );
</script>