<?php
/**
 * View -- of Report/StockreconcilreportController/salesreconcileAction
 */
	$this->headTitle($this->title);
?>
<style>
	tr.group,
	tr.group:hover {
		background-color: #ddd !important;
		font: 15px "Open Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
	}
</style>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$start = $time;
?>
<div class="row">
	<div class="col-lg-12">
		<form method="post" action="<?php echo $this->url('stockreconcilreport', array('action' => 'salesreconcile')); ?>"  enctype="multipart/form-data" >    
			<div class="row">
				<div class="form-group col-lg-2">
					<label class="control-label" for="location">Location</label>
					<input type="hidden" name="location_name" id="location_name" value="<?php echo $this->locationObj->getColumn($data['location'],'location');?>" >
					<select class="form-control" name="location" id="location" data-placeholder="select" >
						<option value="-1">All</option>
						<?php foreach($regions as $region):?>
							<optgroup label="<?php echo $region['region'];?>">
							<?php  
								$locations = $locationObj->get(array('region'=>$region['id'],'location_type'=>array(1,2,7,8)));
								foreach ($locations as $location):
									$selected_loc = ($location['id']==$data['location'])?"selected":"";
							?>
								<option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
									<?php echo $location['location']; ?>
								</option>
							<?php endforeach;?>
							</optgroup>
						<?php endforeach;  ?>									
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="activity">Activity</label>
					<input type="hidden" name="activity_name" id="activity_name" value="<?php echo $this->activityObj->getColumn($data['activity'],'activity');?>" >
					<select class="form-control" name="activity" id="activity" data-placeholder="select" >
						<option value=""></option>
						<?php 
							$activities = $this->activityObj->getAll();
							foreach($activities as $activity):
							$selected_act = ($activity['id']==$data['activity'])?"selected":"";
						?>
							<option value="<?php echo $activity['id'];?>" <?php echo $selected_act;?>>
								<?php echo $activity['activity'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="start_date">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="end_date">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="item">Stock Item</label>
					<select class="form-control" name="item" id="item" data-placeholder="select" >
						<option value="-1" <?php echo ($data['item'] == '-1')?'selected':'';?>>All</option>
						<?php foreach($stock_items as $stock_item):
							$selected_item = ($stock_item['item_id'] == $data['item'])?'selected':'';
						?>
							<option value="<?php echo $stock_item['item_id'];?>" <?php echo $selected_item;?> >
								<?php echo $stock_item['code'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="col-lg-2">
					<div class="space-8"></div>
					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>Refresh</button>
				</div>
			</div>
		</form>
		<div class="hr hr-dotted"></div>
		<div class="space-4"></div>
		<div>
			<table class="table table-striped table-condensed table-bordered table-hover" id="example">
				<thead>
					<tr>
						<th>Item</th>
						<?php if($data['activity'] == '1' || $data['activity'] == 7): ?>
						<th>Batch</th>
						<th>Supplier</th>
						<?php endif;?>
						<th>ELC</th>
						<th>SP</th>
						<th>Credit Qty</th>
						<th>Credit Value</th>
						<th>Credit Sales</th>
						<th>Cash Qty</th>
						<th>Cash Value</th>
						<th>Cash Sales</th>
						
					</tr>
				</thead>
				<tbody>
					<?php 
					if($data['activity'] == 1 || $data['activity'] == 7):
						$sale_list = $this->salesObj->filterSMBatch($data['start_date'],$data['end_date'],$data['location'],array('i.activity'=>$data['activity'],'s.status'=>3),'s.sales_date','s.location',$array,$data['item']);
						
						$total_credit = 0;
						$total_credit_value = 0;
						$total_reconcile_credit_value = 0;
						$total_cash = 0;
						$total_cash_value = 0;
						$total_reconcile_cash_value = 0;
						foreach($sale_list as $list):
							$batches = $this->batchObj->fetchSMBatchDetails($list['id']);
							foreach($batches as $batch);
							
							if($data['location'] != '-1'):
								$batch_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$data['location']),'landed_cost');
								//$batch_elc = $batch['landed_cost'];
								$batch_elc = $batch_elc/$batch['unit_uom'];
								$batch_sp = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$data['location']),'selling_price');
								
							else:
								$total_elc = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'landed_cost');
								$total_no = $this->batch_dtlsObj->getCount(array('batch'=>$batch['id']));
								$batch_elc = $total_elc/$total_no;
								$batch_elc = $batch_elc/$batch['unit_uom'];
								
								$total_sp = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'selling_price');
								$batch_sp = $total_sp/$total_no;
								
							endif;
							
							//Sales Table
							$credit = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							$cash = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							
							//Sales Reconciliation
							$reconcile_credit_value = $this->salesObj->reconcileSUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location');
							$reconcile_cash_value = $this->salesObj->reconcileSUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location');
							
							if($cash == 0 && $credit== 0):
						?>
						<?php else:
								$credit_value = $credit * $batch_sp;
								$credit_value = number_format($credit_value, 2, '.', '');
								$total_credit_value += $credit_value;
								
								$cash_value = $cash * $batch_sp;
								$cash_value = number_format($cash_value, 2, '.', '');
								$total_cash_value += $cash_value;
								
								$reconcile_credit_value = number_format($reconcile_credit_value, 2, '.', '');
								$total_reconcile_credit_value += $reconcile_credit_value;
								$reconcile_cash_value = number_format($reconcile_cash_value, 2, '.', '');
								$total_reconcile_cash_value += $reconcile_cash_value;
						?>
							<tr class="<?php echo ($reconcile_credit_value != $credit_value || $reconcile_cash_value != $cash_value)?'danger':'';?>">
								<td><?php echo $batch['code'];?></td>
								<?php if($data['activity'] == '1' || $data['activity'] == '7'): ?>
								<td><?php echo $batch['batch'];?></td>
								<td><?php echo $this->partyObj->getColumn($batch['supplier'],'code');?></td>
								<?php endif;?>
								
								<td style="text-align:right"><?php echo number_format($batch_elc, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format($batch_sp, 2, '.', ',');?></td>
								
								<td style="text-align:right">
									<?php $total_credit += $credit;
										echo ($credit != '' && $credit != 0)?number_format($credit, 2, '.', ','):'-';?>
								</td>
								<td class="green" style="text-align:right"> 
									<?php 
										
										echo number_format($credit_value, 2, '.', ',');?>
								</td>
								<td class="blue" style="text-align:right">
									<?php 
										echo ($reconcile_credit_value != '' && $reconcile_credit_value != 0)?number_format($reconcile_credit_value, 2, '.', ','):'0.00';
									?>
								</td>
								<td style="text-align:right">
									<?php $total_cash += $cash;
										echo ($cash != '' && $cash != 0)?number_format($cash, 2, '.', ','):'-';?>
								</td>
								<td class="green" style="text-align:right"> 
									<?php 
										echo number_format($cash_value, 2, '.', ',');?>
								</td>
								<td class="blue" style="text-align:right">
									<?php 
										echo ($reconcile_cash_value != '' && $reconcile_cash_value != 0)?number_format($reconcile_cash_value, 2, '.', ','):'0.00';
									?>
								</td>
							</tr>
					<?php 
							endif;
						endforeach;
					else:
						$items = $this->batchObj->fetchSMDistinctItems(array('i.activity'=>$data['activity'], 'i.valuation'=>1, 'b.status' => 3),$data['item']);
						$total_credit = 0;
						$total_credit_value = 0;
						$total_reconcile_credit_value = 0;
						$total_cash = 0;
						$total_cash_value = 0;
						$total_reconcile_cash_value = 0;
						foreach($items as $item):
							if($data['location'] != '-1'):
								$spbatches = $this->movingitemspObj->getBatchRow(array('item' => $item['item_id']),'sp_effect_date',$data['start_date'],$data['end_date']);
								if(sizeof($spbatches)==0){
									$spbatches = $this->movingitemspObj->getBatchByDate(array('m.item' => $item['item_id']),$data['start_date']);
								}
								$moving_elc_sum = 0;
								$moving_sp_sum = 0;
								$moving_count = 0;
								foreach($spbatches as $spbatch):
									$batch_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$spbatch['batch'],'location'=>$data['location']),'landed_cost');
									$unit_uom = $this->batchObj->getColumn($spbatch['batch'],'unit_uom');
									$batch_elc = $batch_elc/$unit_uom;
									$moving_elc_sum += $batch_elc;
									$moving_count += 1;
									
									$batch_sp = $this->batch_dtlsObj->getColumn(array('batch'=>$spbatch['batch'],'location'=>$data['location']),'selling_price');
									$moving_sp_sum += $batch_sp;
								endforeach;
								$dated = date('Y-m-d');
								$moving_elc = $moving_elc_sum/$moving_count;
								$moving_sp = $moving_sp_sum/$moving_count;
							else:
								$spbatches = $this->movingitemspObj->getBatchByDate(array('m.item' => $item['item_id']),$data['start_date']);
								foreach($spbatches as $spbatch);
								
								$unit_uom = $this->batchObj->getColumn($spbatch['batch'],'unit_uom');
								$total_elc = $this->batch_dtlsObj->getSUM(array('batch'=>$spbatch['batch']),'landed_cost');
								$total_no = $this->batch_dtlsObj->getCount(array('batch'=>$spbatch['batch']));
								$moving_elc = $total_elc/$total_no;
								$moving_elc = $moving_elc/$unit_uom;
								
								$total_sp = $this->batch_dtlsObj->getSUM(array('batch'=>$spbatch['batch']),'selling_price');
								$moving_sp = $total_sp/$total_no;
							endif;
							//Sales Table
							$credit = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							$cash = $this->salesObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
							
							
							//Sales Reconciliation
							$reconcile_credit_value = $this->salesObj->reconcileSUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'credit'=>1,'s.status'=>3),'s.sales_date','s.location');
							$reconcile_cash_value = $this->salesObj->reconcileSUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'credit'=>0,'s.status'=>3),'s.sales_date','s.location');
							
							if($cash == 0 && $credit== 0):
						?>
						<?php else:
						        $credit_value = $credit * $moving_sp;
								$credit_value = number_format($credit_value, 2, '.', '');
								$total_credit_value += $credit_value;
								
								$cash_value = $cash * $moving_sp;
								$cash_value = number_format($cash_value, 2, '.', '');
								$total_cash_value += $cash_value;
								
								$reconcile_credit_value = number_format($reconcile_credit_value, 2, '.', '');
								$total_reconcile_credit_value += $reconcile_credit_value;
								$reconcile_cash_value = number_format($reconcile_cash_value, 2, '.', '');
								$total_reconcile_cash_value += $reconcile_cash_value;
							?>
							<tr class="<?php echo ($reconcile_credit_value != $credit_value || $reconcile_cash_value != $cash_value)?'danger':'';?>">
								<td><?php echo $item['code'];?></td>
								<?php if($data['activity'] == '1' || $data['activity'] == '7'): ?>
								<td><?php echo 'NA';?></td>
								<td><?php echo $this->partyObj->getColumn($item['supplier'],'code');?></td>
								<?php endif;?>
								
								<td style="text-align:right"><?php echo number_format($moving_elc, 2, '.', ',');?></td>
								<td style="text-align:right"><?php echo number_format($moving_sp, 2, '.', ',');?></td>
								
								<td style="text-align:right">
									<?php $total_credit += $credit;
										echo ($credit != '' && $credit != 0)?number_format($credit, 2, '.', ','):'-';?>
								</td>
								<td class="green" style="text-align:right"> 
									<?php 
										
										echo number_format($credit_value, 2, '.', ',');?>
								</td>
								<td class="blue" style="text-align:right">
									<?php 
										echo ($reconcile_credit_value != '' && $reconcile_credit_value != 0)?number_format($reconcile_credit_value, 2, '.', ','):'0.00';
									?>
								</td>
								<td style="text-align:right">
									<?php $total_cash += $cash;
										echo ($cash != '' && $cash != 0)?number_format($cash, 2, '.', ','):'-';?>
								</td>
								<td class="green" style="text-align:right"> 
									<?php 
										echo number_format($cash_value, 2, '.', ',');?>
								</td>
								<td class="blue" style="text-align:right">
									<?php 
										echo ($reconcile_cash_value != '' && $reconcile_cash_value != 0)?number_format($reconcile_cash_value, 2, '.', ','):'0.00';
									?>
								</td>
							</tr>
						<?php 
								endif;
						endforeach;
					endif;	
					?>
				</tbody>
				<tfoot>
					<tr>
						<?php
							$total_credit = number_format($total_credit, 2, '.', ',');
							$total_credit_value = number_format($total_credit_value, 2, '.', ',');
							$total_reconcile_credit_value = number_format($total_reconcile_credit_value, 2, '.', ',');
							$total_cash = number_format($total_cash, 2, '.', ',');
							$total_cash_value = number_format($total_cash_value, 2, '.', ',');
							$total_reconcile_cash_value = number_format($total_reconcile_cash_value, 2, '.', ',');
						?>
						<th>Total</th>
						<?php if($data['activity'] == '1' || $data['activity'] == 7): ?>
						<th>-</th>
						<th>-</th>
						<?php endif;?>
						<th>-</th>
						<th>-</th>
						<th style="text-align:right"><?php echo $total_credit;?></th>
						<th class="<?php echo ($total_credit_value != $total_reconcile_credit_value)?'danger':'green';?>" style="text-align:right"><?php echo $total_credit_value;?></th>
						<th class="<?php echo ($total_credit_value != $total_reconcile_credit_value)?'danger':'blue';?>" style="text-align:right"><?php echo $total_reconcile_credit_value;?></th>
						<th style="text-align:right"><?php echo $total_cash;?></th>
						<th class="<?php echo ($total_cash_value != $total_reconcile_cash_value)?'danger':'green';?>" style="text-align:right"><?php echo $total_cash_value;?></th>
						<th class="<?php echo ($total_cash_value != $total_reconcile_cash_value)?'danger':'blue';?>" style="text-align:right"><?php echo $total_reconcile_cash_value;?></th>
						
					</tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
<?php
	$time = microtime();
	$time = explode(' ', $time);
	$time = $time[1] + $time[0];
	$finish = $time;
	$total_time = round(($finish - $start), 4);
	echo "<p class='pull-right'>Sales Reconciliation generated in ".$total_time." seconds.</p>";
?>
<script type="text/javascript">
	$(document).ready(function() {
		$('#start_date').datepicker();
		$('#end_date').datepicker();
		$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		
		$('#activity').on('change', function(){
			$.post(
				"<?php echo $this->url("stockreport", array("action" => "getitemactivity"));?>",
				{
					activity: $(this).val(),
				},
				function(data){
					//console.log(data);
					$('#item').html(data.item);
					$('#item option:selected').removeAttr('selected');
					$('item option[value='+data.selected_item+']').attr('selected', 'selected');
					$('#item').trigger('chosen:updated');
					$('form').formValidation('revalidateField', $('#item').attr('id'));
				},
				'json'
			);
		});
		/*** Form Validation ***/
		$('form').formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid',
				fields: {
					'location': {
					 	validators: {
							notEmpty: {
								message: 'Please select location'
						  	}
					  	}
				  	},
					'activity': {
						validators: {
							notEmpty: {
								message: 'Please select activity'
							}
						}
					},
					'start_date': {
						validators: {
							notEmpty: {
								message: 'Please select start date'
							},
						}
					},
					'end_date': {
						validators: {
							notEmpty: {
								message: 'Please select end date'
							}
						},
					},
					'item': {
						validators: {
							notEmpty: {
								message: 'Please select item'
							}
						}
					},
				}
			}).on('success.field.fv', function(e, data) {
				if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
					data.fv.disableSubmitButtons(true);
			}
		});
		
		var title_table = $('#location_name').val()+'('+$('#activity_name').val()+') from '+$('input#start_date').val()+' to '+$('input#end_date').val();
		if($('#activity').val() == 1 || $('#activity').val() == 7){
			var table = $('#example').DataTable({
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				"columnDefs": [
					{ "visible": false, "targets": 2 }, 
				],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true,
				"order": [[ 2, 'asc' ],[ 0, 'asc' ],[ 1, 'asc' ]],
				"displayLength": 10,
				"drawCallback": function ( settings ) {
					var api = this.api();
					var rows = api.rows( {page:'current'} ).nodes();
					var last=null;
	 
					api.column(2, {page:'current'} ).data().each( function ( group, i ) {
						if ( last !== group ) {
							$(rows).eq( i ).before(
								'<tr class="group"><td colspan="16">'+group+'</td></tr>'
							);
	 
							last = group;
						}
					} );
				}
			} );
			
			// Order by the grouping
			$('#example tbody').on( 'click', 'tr.group', function () {
				var currentOrder = table.order()[0];
				if ( currentOrder[0] === 2 && currentOrder[1] === 'asc' ) {
					table.order( [ 2, 'desc' ] ).draw();
				}
				else {
					table.order( [ 2, 'asc' ] ).draw();
				}
			} );
		}else{
			$('#example').DataTable( {
				dom: 'Bfrtip',
				lengthMenu: [
					[ 10, 25, 50, -1 ],
					[ '10 rows', '25 rows', '50 rows', 'Show all' ]
				],
				columnDefs: [ {
					visible: false
				} ],
				buttons: [
					{
						extend: 'copy',
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-files-o"></i> Copy',
						titleAttr: 'Copy'
					},
					{
						extend: 'csv',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-text-o"></i> Csv',
						titleAttr: 'CSV'
					},
					{
						extend: 'excel',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-file-excel-o"></i> Excel',
						titleAttr: 'Excel'
					},
					{
						extend: 'pdfHtml5',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						orientation: 'landscape',
						pageSize: 'LEGAL',
						text: '<i class="fa fa-file-pdf-o"></i> Pdf',
						titleAttr: 'PDF'
					},
					{
						extend: 'print',
						title: title_table,
						exportOptions: {
							columns: ':visible'
						},
						text: '<i class="fa fa-print"></i> Print',
						titleAttr: 'Print'
					},
					'pageLength','colvis'
				],
				select:true
			} );
		}
	} );
</script>