<?php
/**
 * View -- of Stock/StockreconcilreportController/stockreconcilAction
 * 
 */
 ini_set('max_execution_time', 300); //300 seconds = 5 minutes
 $time_start = microtime(true);
	$this->headTitle($this->title);
?>
<div class="row">
	<div class="col-lg-12">
		<div class="clearfix">
			<div class="pull-right tableTools-container"></div>
		</div>
		<form method="post" action="<?php echo $this->url('stockreconcilreport', array('action' => 'stockreconcil')); ?>"  enctype="multipart/form-data" >    
			<div class="row">
				<div class="form-group col-lg-2">
					<label class="control-label" for="location">Location</label>
					<select class="form-control" name="location" id="location" data-placeholder="select" >
						<option value="-1">All</option>
						<?php foreach($regions as $region):?>
							<optgroup label="<?php echo $region['region'];?>">
							<?php  
								$locations = $locationObj->get(array('region'=>$region['id']));
								foreach ($locations as $location):
									$selected_loc = ($location['id']==$data['location'])?"selected":"";
							?>
								<option value="<?php echo $location['id']; ?>" <?php echo $selected_loc;?>>
									<?php echo $location['location']; ?>
								</option>
							<?php endforeach;?>
							</optgroup>
						<?php endforeach;  ?>									
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="activity">Activity</label>
					<input type="hidden" name="activity_name" id="activity_name" value="<?php echo $this->activityObj->getColumn($data['activity'],'activity');?>" >
					<select class="form-control" name="activity" id="activity" data-placeholder="select" >
						<option value=""></option>
						<?php 
							$activities = $this->activityObj->getAll();
							foreach($activities as $activity):
							$selected_act = ($activity['id']==$data['activity'])?"selected":"";
						?>
							<option value="<?php echo $activity['id'];?>" <?php echo $selected_act;?>>
								<?php echo $activity['activity'];?>
							</option>
						<?php endforeach;?>
					</select>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="start_date">Start Date</label>
					<div class="date input-group" id="start_date" data-date="<?php echo $data['start_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="start_date" id="start_date" type="text" placeholder="Start Date" value="<?php echo $data['start_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="form-group col-lg-2">
					<label class="control-label" for="end_date">End Date</label>
					<div class="date input-group" id="end_date" data-date="<?php echo $data['end_date'];?>" data-date-format="yyyy-mm-dd" >
						<input class="form-control span2" name="end_date" id="end_date" type="text" placeholder="End Date" value="<?php echo $data['end_date'];?>" readonly required>
						<span class="input-group-addon add-on"><i class="fa fa-calendar"></i></span>
					</div>
				</div>
				<div class="col-lg-2">
					<div class="space-8"></div>
					<button type="submit" class="btn btn-primary pull-right"><i class="fa fa-refresh"></i>Refresh</button>
				</div>
			</div>
		</form>
		<div class="hr hr-dotted"></div>
		<div class="space-6"></div>
		<div>
			<table class="table table-striped table-condensed table-bordered table-hover" id="example">
				<thead>
					<tr>
					    <!--<th>#</th>-->
						<th>Item</th>
						<?php if($data['activity'] == 1 || $data['activity']==7):?>
						<th>Batch</th>
						<?php endif;?>
						<th>OpeningBal</th>
						<th>Intransit</th>
						<th>Purchase</th>
						<th>Total Receipt</th>
						<th>TransitLoss</th>
						<th>Sales</th>
						<th>Dumped</th>
						<?php if($data['activity'] == '1' || $data['activity'] == 7): ?>
						<th>Scheme</th>
						<?php endif; ?>
						<th>Intransit</th>
						<th>Shortage</th>
						<th>Total</th>
						<th>Closing</th>
						<th>Actual_qty</th>
						<th>Stock Value</th>
					</tr>
				</thead>
				<tbody>
					<?php 
							if($data['activity'] == 1 || $data['activity']== 7): //FIFO
								if($data['location'] != '-1'):
								$lists = $this->batchObj->getLocationBI(array('d.location'=>$data['location'],'i.activity'=>$data['activity'], 'i.valuation'=>0, 'b.status' => 3),$data['item']);
								//echo "From batch=".sizeof($lists)."<br>";
								$pur_list = $this->pur_receiptObj->getDistinctIB($data['start_date'],$data['end_date'],$data['location'],array('p.status'=>3,'p.activity'=>1),'p.prn_date','p.location',$lists);
								//echo "Purchase=".sizeof($pur_list)."<br>";
								$disp_list = $this->dispatchObj->getDistinctIB($data['start_date'],$data['end_date'],$data['location'],array('d.status'=>array(2,10,3),'d.activity'=>1),'d.dispatch_date','d.from_location',$lists);
								//echo "dispatch=".sizeof($disp_list)."<br>";
								$rept_list = $this->dispatchObj->getDistinctIB($data['start_date'],$data['end_date'],$data['location'],array('d.status'=>3,'d.activity'=>1),'d.received_on','d.to_location',$lists);
								//echo "receipt=".sizeof($rept_list)."<br>";
								$tras_list = $this->dispatchObj->getDistinctIBTransit($data['end_date'],$data['location'],array('d.activity'=>1,'d.status'=>array(2,10)),'d.dispatch_date','d.to_location',$lists);
								//echo "Transit=".sizeof($tras_list)."<br>";
								$sale_list = $this->salesObj->getDistinctIB($data['start_date'],$data['end_date'],$data['location'],array('i.activity'=>1,'s.status'=>3),'s.sales_date','s.location',$lists);
								//echo "Sales=".sizeof($sale_list)."<br>";
								$sam_list = $this->samObj->getDistinctIB($data['start_date'],$data['end_date'],$data['location'],array('s.activity'=>1,'s.status'=>3),'s.sam_date','s.location',$lists);
								//echo "sam=".sizeof($sam_list)."<br>";
								$row_list = array_merge($lists,$pur_list,$disp_list,$rept_list,$tras_list,$sale_list,$sam_list);
								//echo "Merge = ".sizeof($row_list)."<br>";
								$row_unique = array_unique($row_list, SORT_REGULAR);
								//echo "Unique = ".sizeof($row_unique)."<br>"; exit;
								
								else:
									$row_unique = $this->batchObj->getDistinctItemBatch(array('i.activity'=>$data['activity'], 'i.valuation'=>0, 'b.status' => 3),$data['item']);
								endif;
								foreach($row_unique as $list):
									$batches = $this->batchObj->getDtls($list['id']);
									foreach($batches as $batch);
									/** OPENING BALANCE OF ITEMS WITH VALUATION 0 (BATCH WISE) **/
									if($data['location'] != '-1'):
										$batch_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$data['location']),'landed_cost');
										$batch_elc = $batch['landed_cost'];
										$batch_elc = $batch_elc/$batch['unit_uom'];
																	        $batch_elc = number_format($batch_elc, 2, '.', '');

										$total_qty = $this->batch_dtlsObj->getColumn(array('batch'=>$batch['id'],'location'=>$data['location']),'quantity');
									else:
										$total_elc = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'landed_cost');
										$total_no = $this->batch_dtlsObj->getCount(array('batch'=>$batch['id']));
										$batch_elc = $total_elc/$total_no;
										$batch_elc = $batch_elc/$batch['unit_uom'];
																	        $batch_elc = number_format($batch_elc, 2, '.', '');

										$total_qty = $this->batch_dtlsObj->getSUM(array('batch'=>$batch['id']),'quantity');
									endif;
									
									//Opening Stock Table
									$op_stock_openings = $this->openingObj->getSMOpeningSUM($data['start_date'],$data['location'],array('o.batch'=>$batch['batch'],'o.item'=>$batch['item']));
								    $op_purchases = $this->pur_receiptObj->getSMOpeningSUM($data['start_date'],$data['location'],array('pd.batch'=>$batch['id'],'pd.item'=>$batch['item'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
									if($data['location'] != '-1'){
										$openingDate = $this->openingdateObj->getColumn(array('location'=>$data['location']),'opening_date');
									}
									$op_dispatch = $this->dispatchObj->getSMOpeningSUM($data['start_date'],$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,10,3)),'d.dispatch_date','d.from_location','dd.basic_quantity',$openingDate);
									$op_in_receipt = $this->dispatchObj->getSMOpeningSUM($data['start_date'],$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>3),'d.received_on','d.to_location','dd.accepted_qty',$openingDate);
									
									$op_cred_cash = $this->salesObj->getSMOpeningSUM($data['start_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
									
									//op_dump = op_dump+op_shortage+$op_sales_promotion
									$op_dump = $this->samObj->getSMOpeningSUM($data['start_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>array(1,2,3,4),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
									$op_adjustment = $this->samObj->getSMOpeningSUM($data['start_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
																$op_disqty = $this->salesObj->fetchFIOpeningSUM($data['start_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'s.status'=>3,'sd.free_item' => $batch['item']),'s.sales_date','s.location','sd.discount_qty');

									$opening = $op_stock_openings + $op_purchases - $op_dispatch + $op_in_receipt + $op_converted_to + $op_adjustment - $op_converted_from - $op_cred_cash - $op_dump - $op_disqty;// - $op_shortage -$op_sales_promotion - $op_credit -  $op_cash;					
									//Purchase Receipt Table
									$purchases = $this->pur_receiptObj->getSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('pd.batch'=>$batch['id'],'pd.item'=>$batch['item'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
									
									//Dispatch Table
								    $in_transit_date = $this->dispatchObj->fetchSMTransitQtyDateSUM($data['end_date'],$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
        							$in_transit_status = $this->dispatchObj->fetchSMTransitQtyStatusSUM($data['end_date'],$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,10)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
        							$in_transit = $in_transit_date + $in_transit_status;
								$prevoius_start_year = date('Y', strtotime($data['start_date'])) - 1;
							$pre_starting_date = date('Y-m-d', strtotime($prevoius_start_year.'-12'.'-31'));
							$in_transit_date1 = $this->dispatchObj->fetchSMTransitQtyDateSUM1($pre_starting_date,$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');$in_transit_status1 = $this->dispatchObj->fetchSMTransitQtyStatusSUM1($pre_starting_date,$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(2,10)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');			$in_transit1 = $in_transit_date1 + $in_transit_status1;								    //$dispatch_shortage = $this->dispatchObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('dd.batch'=>$batch['id'],'dd.item'=>$batch['item'],'d.status'=>array(3),'d.fcb_transport'=>'1'),'d.dispatch_date','d.from_location','dd.shortage_qty');
									
									//Sales Table
									$sales = $this->salesObj->getSRQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
									
									//SAM Table
									$dump = $this->samObj->getSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>array(1,2),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
									$shortage = $this->samObj->getSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>3,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
						        	$sales_promotion = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>4,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							        $adjustment = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
									$free_item_qty = $this->salesObj->fetchFIQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.batch'=>$batch['id'],'sd.item'=>$batch['item'],'credit'=>0,'s.status'=>3,'sd.free_item' => $batch['item']),'s.sales_date','s.location','sd.discount_qty');
								
									//Transitloss Table
									$transitloss = $this->transitlossObj->getSRQtyLossSUM($data['start_date'],$data['end_date'],$data['location'],array('t.batch'=>$batch['id'],'t.item'=>$batch['item'],'d.status'=>3));
									$total_transit_loss = $dispatch_shortage + $transitloss;
									//total receipt
									$total_receipt = $opening + $purchases + $adjustment + $in_transit1;
									$total_used = $transitloss + $sales + $dump + $shortage + $sales_promotion + $free_item_qty+$in_transit;
									$closing = $total_receipt - $total_used;
									$sv = $closing * $batch_elc;
									$total_stock_value += $sv;
									$siv = $in_transit * $batch_elc;
								    $total_stock_intransit_value += $siv;
									
									if($opening == 0 && $purchases == 0 && $in_receipt == 0 && $dispatch == 0 &&$dump == 0 && $adjustment == 0 && $shortage == 0 &&$cash == 0 && $credit== 0 && $in_transit == 0 && $converted_to == 0 && $converted_from == 0 && $sales_promotion == 0 && $purchase_shortage == 0):
								?>
								<?php else:
                                                                    								    $dump = $dump + $sales_promotion;
								    $total_transit_loss = ($total_transit_loss != '' && $total_transit_loss != 0)?number_format($total_transit_loss, 2, '.', ','):'-';
									$total_receipt = ($total_receipt != '' && $total_receipt != 0)?number_format($total_receipt, 2, '.', ','):'-';
									$total_used = ($total_used != '' && $total_used != 0)?number_format($total_used, 2, '.', ','):'-';
									$opening = ($opening != '' && $opening != 0)?number_format($opening, 2, '.', ','):'-';
									$purchases = ($purchases != '' && $purchases != 0)?number_format($purchases, 2, '.', ','):'-';
									$in_transit1 = ($in_transit1 != '' && $in_transit1 != 0)?number_format($in_transit1, 2, '.', ','):'-';
									$in_transit = ($in_transit != '' && $in_transit != 0)?number_format($in_transit, 2, '.', ','):'-';
									$sales = ($sales != '' && $sales != 0)?number_format($sales, 2, '.', ','):'-';
									$free_item_qty = ($free_item_qty != '' && $free_item_qty != 0)?number_format($free_item_qty, 2, '.', ','):'-';
									$dump = ($dump != '' && $dump != 0)?number_format($dump, 2, '.', ','):'-';
									$shortage = ($shortage != '' && $shortage != 0)?number_format($shortage, 2, '.', ','):'-';
									$transitloss = ($transitloss != '' && $transitloss != 0)?number_format($transitloss, 2, '.', ','):'-';
									$total_qty = ($total_qty != '' && $total_qty != 0)?number_format($total_qty, 2, '.', ','):'-';
								
									$closing = ($closing != '' && $closing != 0)?number_format($closing, 2, '.', ','):'-';
								?>
									<tr>
										<!--<td><?php //echo $sl++; ?></td> -->
										<td><?php echo $batch['code'];?></td>
										<td><?php echo $batch['batch'];?></td>
										<td class="green" style="text-align:right">
											<?php echo $opening;?>
										</td>
										<td class="green" style="text-align:right"><?php echo $in_transit1;?></td>
										<td class="green" style="text-align:right"><?php echo $purchases;?></td>
										<td class="purple" style="text-align:right"><?php echo $total_receipt;?></td>
										<td class="red" style="text-align:right"><?php echo $total_transit_loss;?></td>
										<td class="red" style="text-align:right"><?php echo $sales;?></td>
										<td class="red" style="text-align:right"><?php echo $dump; ?></td>
										<?php if($data['activity'] == '1' || $data['activity'] == '7'): ?>
										<td class="red" style="text-align:right"><?php echo $free_item_qty;?></td>
										<?php endif;?>
										<td class="red" style="text-align:right"><?php echo $in_transit;?></td>
										<td class="red" style="text-align:right"><?php echo $shortage;?></td>
										<td class="purple" style="text-align:right"><?php echo $total_used;?></td>
										<td class="blue" style="text-align:right"><?php echo $closing;?></td>
										<td class="blue" style="text-align:right"><?php echo $total_qty;?></td>
										<td style="text-align:right">
											<?php echo number_format($sv, 2, '.', ','); ?>
										</td>
									</tr>
						
					<?php 			endif;
					
								endforeach;
							elseif($data['activity'] == 2): //Wt Moving Avg
								$items = $this->batchObj->getSMDistinctItems(array('i.activity'=>$data['activity'], 'i.valuation'=>1, 'b.status' => 3),$data['item']);								foreach($items as $item):
							        
                                                                if($data['location'] != '-1'):
							    $max_spe_date = $this->movingitemspObj->getMaxBatchdateByLocation('sp_effect_date',array('item' => $item['item_id']),$data['end_date'],$data['location']);
								$max_batch_id = $this->movingitemspObj->getMaxBatchIdByLocation('b.batch',array('item' => $item['item_id']),$max_spe_date,$data['location']);
								$spbatches = $this->movingitemspObj->getBatchRowByLocation(array('item' => $item['item_id']),$max_spe_date,$data['location']);
							else:
							    $max_spe_date = $this->movingitemspObj->getMaxBatchdateforAllLocs('sp_effect_date',array('item' => $item['item_id']),$data['end_date']);
								$max_batch_id = $this->movingitemspObj->getMaxBatchIdforAllLocs('b.batch',array('item' => $item['item_id']),$max_spe_date);
								$spbatches = $this->movingitemspObj->getBatchRow(array('item' => $item['item_id']),$max_spe_date);
							endif;
							$moving_elc_sum = 0;
							$moving_sp_sum = 0;
							$moving_count = 0;
							foreach($spbatches as $spbatch):
								$unit_uom = $this->batchObj->getColumn($spbatch['batch'],'unit_uom');
								if($data['location'] != '-1'):
									$total_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$spbatch['batch'],'location'=>$data['location']),'landed_cost');
							        $total_elc = number_format($total_elc, 2, '.', '');
									$selling_price = $this->batch_dtlsObj->getColumn(array('batch'=>$max_batch_id,'location'=>$data['location']),'selling_price');
								else:
									$total_elc = $this->batch_dtlsObj->getColumn(array('batch'=>$spbatch['batch']),'landed_cost');
						            $total_elc = number_format($total_elc, 2, '.', '');
									$selling_price = $this->batch_dtlsObj->getColumn(array('batch'=>$max_batch_id),'selling_price');
								endif;
								$moving_elc = $total_elc/$unit_uom;
								$moving_elc_sum += $moving_elc;
								$moving_count += 1;
							endforeach;
							$moving_elc = $moving_elc_sum/$moving_count;	
	                        $moving_elc = number_format($moving_elc, 2, '.', '');
							if($data['location'] != '-1'):
							    $total_qty = $this->movingObj->getSUM(array('item' => $item['item_id'],'location'=>$data['location']),'quantity');
							else:
							    $total_qty = $this->movingObj->getSUM(array('item' => $item['item_id']),'quantity');	
							endif;
								/** OPENING BALANCE OF ITEMS WITH VALUATION 0 (BATCH WISE) **/
								//Opening Stock Table
								$op_stock_openings = $this->openingObj->getSMOpeningSUM($data['start_date'],$data['location'],array('o.item'=>$item['item_id']));
								
								$op_purchases = $this->pur_receiptObj->getSMOpeningSUM($data['start_date'],$data['location'],array('pd.item'=>$item['item_id'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
if($data['location'] != '-1'){
									$openingDate = $this->openingdateObj->getColumn(array('location'=>$data['location']),'opening_date');
								}							
								$op_dispatch = $this->dispatchObj->getSMOpeningSUM($data['start_date'],$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10,3)),'d.dispatch_date','d.from_location','dd.basic_quantity',$openingDate);
								$op_in_receipt = $this->dispatchObj->getSMOpeningSUM($data['start_date'],$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>3),'d.received_on','d.to_location','dd.accepted_qty',$openingDate);
								
							    $op_converted_to = $this->itemconversionObj->getSMOpeningSUM($data['start_date'],$data['location'],array('converted_item'=>$item['item_id'],'status'=>3),'conversion_date','location','converted_basic_qty');
								$op_converted_from = $this->itemconversionObj->getSMOpeningSUM($data['start_date'],$data['location'],array('item'=>$item['item_id'],'status'=>3),'conversion_date','location','basic_qty');
								
								$op_cred_cash = $this->salesObj->getSMOpeningSUM($data['start_date'],$data['location'],array('sd.item'=>$item['item_id'],'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
								//op_dump = op_dump+op_shortage+$op_sales_promotion	
								$op_dump = $this->samObj->getSMOpeningSUM($data['start_date'],$data['location'],array('sd.item'=>$item['item_id'],'sam_type'=>array(1,2,3,4),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
								$op_adjustment = $this->samObj->getSMOpeningSUM($data['start_date'],$data['location'],array('sd.item'=>$item['item_id'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
								
								$opening = $op_stock_openings + $op_purchases + $op_adjustment - $op_dispatch + $op_in_receipt + $op_converted_to - $op_converted_from - $op_cred_cash - $op_dump; //- $op_shortage - $op_sales_promotion - $op_credit - $op_cash;
								
								//Purchase Receipt Table
								$purchases = $this->pur_receiptObj->getSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('pd.item'=>$item['item_id'],'p.status'=>3),'p.prn_date','p.location','pd.basic_sound_qty');
								//Dispatch Table
								//$in_transit2 = $this->dispatchObj->getSRIntransitQtyTwoSUM($data['start_date'],$data['end_date'],$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10)),'d.dispatch_date','d.to_location','dd.basic_quantity');
								$in_transit_date = $this->dispatchObj->fetchSMTransitQtyDateSUM($data['end_date'],$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit_status = $this->dispatchObj->fetchSMTransitQtyStatusSUM($data['end_date'],$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit = $in_transit_date + $in_transit_status;
								$prevoius_start_year = date('Y', strtotime($data['start_date'])) - 1;
							$pre_starting_date = date('Y-m-d', strtotime($prevoius_start_year.'-12'.'-31'));
							$in_transit_date1 = $this->dispatchObj->fetchSMTransitQtyDateSUM1($pre_starting_date,$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,3)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit_status1 = $this->dispatchObj->fetchSMTransitQtyStatusSUM1($pre_starting_date,$data['location'],array('dd.item'=>$item['item_id'],'d.status'=>array(2,10)),'d.dispatch_date','d.received_on','d.to_location','dd.basic_quantity');
							$in_transit1 = $in_transit_date1 + $in_transit_status1;
								//Item Conversion
    							$converted_to = $this->itemconversionObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('converted_item'=>$item['item_id'],'status'=>3),'conversion_date','location','converted_basic_qty');
    							$converted_from = $this->itemconversionObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('item'=>$item['item_id'],'status'=>3),'conversion_date','location','basic_qty');
							
								//Sales Table
								$sales = $this->salesObj->getSRQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'s.status'=>3),'s.sales_date','s.location','sd.basic_quantity');
								
								//SAM Table
								$dump = $this->samObj->getSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'sam_type'=>array(1,2),'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
								$shortage = $this->samObj->getSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'sam_type'=>3,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
								$sales_promotion = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'sam_type'=>4,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
							    $adjustment = $this->samObj->fetchSMQuantitySUM($data['start_date'],$data['end_date'],$data['location'],array('sd.item'=>$item['item_id'],'sam_type'=>5,'s.status'=>3),'s.sam_date','s.location','sd.basic_quantity');
								//Transitloss Table
								$transitloss = $this->transitlossObj->getSRQtyLossSUM($data['start_date'],$data['end_date'],$data['location'],array('t.item'=>$item['item_id'],'d.status'=>3));
							//echo $transitloss; exit;
								//Closing Balance
								//$closing = $opening + $purchases + $in_receipt + $adjustment - $dispatch + $converted_to - $converted_from - $dump - $shortage - $cash - $credit - $sales_promotion; 
								$total_receipt = $opening + $purchases + $adjustment + $converted_to +  $in_transit1;
								$total_used = $transitloss + $sales + $dump + $shortage + $in_transit +$sales_promotion + $converted_from;
								$closing =  $total_receipt - $total_used;
                                                                //echo "Opening".$opening."br";echo "purchase".$purchases."br"; echo "inrecipt".$in_receipt."br";echo "Intransit".$in_transit//;//echo "sales".$sales;echo "dump".$dump; echo "Shortage".$shortage; echo "sales P".$sales_promotion;exit;                			
$moving_elc = number_format($moving_elc, 2, '.', ',');
								$sv = $closing * $moving_elc;
								$siv = $in_transit * $moving_elc;
								$total_stock_intransit_value += $siv;
								$total_stock_value += $sv;
								
								if($opening == 0 && $purchases == 0 && $in_receipt == 0 && $dispatch == 0 &&$dump == 0 && $adjustment == 0 && $shortage == 0 &&$cash == 0 && $credit== 0 && $in_transit == 0 && $converted_to == 0 && $converted_from == 0 && $sales_promotion == 0):
								?>
								<?php else:
								$total_receipt = ($total_receipt != '' && $total_receipt != 0)?number_format($total_receipt, 2, '.', ','):'0';
								$total_used = ($total_used != '' && $total_used != 0)?number_format($total_used, 2, '.', ','):'0';
								$opening = ($opening != '' && $opening != 0)?number_format($opening, 2, '.', ','):'0';
								$purchases = ($purchases != '' && $purchases != 0)?number_format($purchases, 2, '.', ','):'0';
								$in_transit1 = ($in_transit1 != '' && $in_transit1 != 0)?number_format($in_transit1, 2, '.', ','):'0';
								$in_transit = ($in_transit != '' && $in_transit != 0)?number_format($in_transit, 2, '.', ','):'0';
								$sales = ($sales != '' && $sales != 0)?number_format($sales, 2, '.', ','):'0';
								$dump = ($dump != '' && $dump != 0)?number_format($dump, 2, '.', ','):'0';
								$shortage = ($shortage != '' && $shortage != 0)?number_format($shortage, 2, '.', ','):'0';
								$transitloss = ($transitloss != '' && $transitloss != 0)?number_format($transitloss, 2, '.', ','):'0';
								$total_qty = ($total_qty != '' && $total_qty != 0)?number_format($total_qty, 2, '.', ','):'0';
							
								$closing = ($closing != '' && $closing != 0)?number_format($closing, 2, '.', ','):'0';
					?>
								<tr>
									<!--<td><?php //echo $sl++; ?></td> -->
									<td><?php echo $item['code'];?></td>
									<td class="green" style="text-align:right">
										<?php echo $opening;?>
									</td>
									<td class="green" style="text-align:right"><?php echo $in_transit1;?></td>
									<td class="green" style="text-align:right"><?php echo $purchases;?></td>
									<td class="purple" style="text-align:right"><?php echo $total_receipt;?></td>
									<td class="red" style="text-align:right"><?php echo $transitloss;?></td>
									<td class="red" style="text-align:right"><?php echo $sales;?></td>
									<td class="red" style="text-align:right"><?php echo $dump; ?></td>
									<td class="red" style="text-align:right"><?php echo $in_transit;?></td>
									<td class="red" style="text-align:right"><?php echo $shortage;?></td>
									<td class="purple" style="text-align:right"><?php echo $total_used;?></td>
									<td class="blue" style="text-align:right"><?php echo $closing;?></td>
									<td class="blue" style="text-align:right"><?php echo $total_qty;?></td>
									<td style="text-align:right">
										<?php echo number_format($sv, 2, '.', ','); ?>
									</td>
								</tr>
					<?php 
								endif;
								endforeach;
							endif;
					?>
				</tbody>
			</table>
		</div>
		
	</div>
</div>
<?php $time_end = microtime(true);
$time = $time_end - $time_start;
echo 'Script took ',number_format($time,2,'.',''),' seconds';?>
<script type="text/javascript">
	$(function() {
		$('#start_date').datepicker();
		$('#end_date').datepicker();
		$('#start_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		$('#end_date').on('changeDate',function(){
			$('form').formValidation('revalidateField', $(this).attr('id'));
		});
		
		
		/*** Form Validation ***/
		$('form').formValidation({
				framework: 'bootstrap',
				excluded: ':disabled',
				message: 'This value is not valid',
				fields: {
					'location': {
					 	validators: {
							notEmpty: {
								message: 'Please select location'
						  	}
					  	}
				  	},
					'activity': {
						validators: {
							notEmpty: {
								message: 'Please select activity'
							}
						}
					},
					'start_date': {
						validators: {
							notEmpty: {
								message: 'Please select start date'
							}
						}
					},
					'end_date': {
						validators: {
							notEmpty: {
								message: 'Please select end date'
							}
						}
					},
				}
			}).on('success.field.fv', function(e, data) {
				if (data.fv.getInvalidFields().length > 0) {    // There is invalid field
					data.fv.disableSubmitButtons(true);
			}
		});
		
		var title_table = "Stock Reconcil "+'('+$('#activity_name').val()+') from '+$('input#start_date').val()+' to '+$('input#end_date').val();
		$('#example').append('<caption style="caption-side: bottom">Total Stock Balance Value = <?php echo $this->currency($total_stock_value);?>&nbsp;&nbsp;&nbsp;Total Stock Intransit Value = <?php echo $this->currency($total_stock_intransit_value);?></caption>');
		$('#example').DataTable( {
			dom: 'Bfrtip',
			/*buttons: [
				'copy', 'csv', 'excel', 'pdf', 'print'
			]*/
			lengthMenu: [
				[ 10, 25, 50, -1 ],
				[ '10 rows', '25 rows', '50 rows', 'Show all' ]
			],
			columnDefs: [ {
				visible: false
			} ],
			buttons: [
				{
					extend: 'copy',
					exportOptions: {
						columns: ':visible'
					},
					text: '<i class="fa fa-files-o"></i> Copy',
					titleAttr: 'Copy'
				},
				{
					extend: 'csv',
					title: title_table,
					exportOptions: {
						columns: ':visible'
					},
					text: '<i class="fa fa-file-text-o"></i> Csv',
					titleAttr: 'CSV'
				},
				{
					extend: 'excel',
					title: title_table,
					exportOptions: {
						columns: ':visible'
					},
					text: '<i class="fa fa-file-excel-o"></i> Excel',
					titleAttr: 'Excel'
				},
				{
					extend: 'pdfHtml5',
					title: title_table,
					exportOptions: {
						columns: ':visible'
					},
					orientation: 'landscape',
					pageSize: 'LEGAL',
					text: '<i class="fa fa-file-pdf-o"></i> Pdf',
					titleAttr: 'PDF'
				},
				{
					extend: 'print',
					title: title_table,
					exportOptions: {
						columns: ':visible'
					},
					text: '<i class="fa fa-print"></i> Print',
					titleAttr: 'Print'
				},
				'pageLength','colvis'
			],
			select:true
		} );
	});
</script>
